kubevirt/project-infra

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
https://github.com/kubevirt/project-infra/pull/1533 removed the slack reporter config of the periodics, the PR readds it.
/cc @dhiller 
> Re-add slack reporter config to periodics

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
People are likely spending effort on understanding why they see
failures, and we know these lanes are currently flaky.
Running the 1.21 lane will be enough to prevent regressions.
> Don't always run sig-storage flaky lanes.

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Non root lanes are failing with:
```
The cluster provider k8s-1.20-nonroot does not exist
```
See for example https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6361/pull-kubevirt-e2e-k8s-1.20-sig-compute-nonroot/1435140916326174720
> Revert "Add nonroot keyword to target (#1525)"

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
Image used in [this run](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirtci-bump-kubevirt/1435030289188392960) didn't have required tool. Pushed latest image version and used that in the job.
Successful run of bump-kubevirtci here: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirtci-bump-kubevirt/1435140650168225792
/cc @fgimenez
> Update pr-creator image for kubevirtci bump job to latest version

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The jobs build with bazel and all jobs which use bazel should use the
bootstrap image.
Further let the jobs build unnested to not have to download the builder image which saves a few gigabyte of transfer per run.
This fixes some sandboxing issues when updating to centos8: https://github.com/kubevirt/kubevirt/pull/6177#issuecomment-914349099
> Use bootstrap image for sriov and vgpu jobs

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
- github/ci/services/prometheus-stack/BUILD.bazel
- github/ci/services/prometheus-stack/hack/deploy.sh
- github/ci/services/prometheus-stack/manifests/alert-rules/common/alertmanager.yaml
- github/ci/services/prometheus-stack/manifests/alert-rules/common/general.yaml
- github/ci/services/prometheus-stack/manifests/alert-rules/common/k8s.yaml
- github/ci/services/prometheus-stack/manifests/alert-rules/common/kube-apiserver.yaml
- github/ci/services/prometheus-stack/manifests/alert-rules/common/kube-prometheus-node-alerting.yaml
- github/ci/services/prometheus-stack/manifests/alert-rules/common/kube-scheduler.yaml
- github/ci/services/prometheus-stack/manifests/alert-rules/common/kubernetes-absent.yaml
- github/ci/services/prometheus-stack/manifests/alert-rules/common/kubernetes-apps.yaml
- github/ci/services/prometheus-stack/manifests/alert-rules/common/kubernetes-resources.yaml
- github/ci/services/prometheus-stack/manifests/alert-rules/common/kubernetes-storage.yaml
- github/ci/services/prometheus-stack/manifests/alert-rules/common/kubernetes-system.yaml
- github/ci/services/prometheus-stack/manifests/alert-rules/common/node-exporter.yaml
- github/ci/services/prometheus-stack/manifests/alert-rules/common/node.yaml
- github/ci/services/prometheus-stack/manifests/alert-rules/common/prometheus-operator.yaml
- github/ci/services/prometheus-stack/manifests/alert-rules/common/prometheus.yaml
- github/ci/services/prometheus-stack/manifests/stack/common/alertmanager-config.yaml
- github/ci/services/prometheus-stack/manifests/stack/common/alertmanager.yaml
- github/ci/services/prometheus-stack/manifests/stack/common/kube-prometheus-stack.yaml
- github/ci/services/prometheus-stack/manifests/stack/production-e2e-workloads/alertmanager-storage.yaml
- github/ci/services/prometheus-stack/patches/production-e2e-workloads/alertmanager.yaml
- github/ci/services/prometheus-stack/secrets/testing/slack-config/apiURL
Changes included in the PR:
* Fix alertmanager deployment on prow-workloads
* Fix connection between prometheus and alertmanager
* Use AlertmanagerConfig CRD for configuring alertmanager, this allows us to have the slack URL defined as a proper k8s secret.
* Modify deployment jobs to decrypt the slack URL secret
* Added basic set of alert and recording rules related to alerting.
Already deployed and tested on ibm-prow-jobs and prow-workloads clusters. 
> Enable alertmanager and add rules

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.41.yaml
Some of the bazel cache entries related to 0.41 jobs are missing, we get errors like https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5971/pull-kubevirt-e2e-k8s-1.18-0.41/1435874708988891136#1:build-log.txt%3A238. 
I've temporarily disable the cache for 1.18-0.41 lane and the build process works fine here https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5971/pull-kubevirt-e2e-k8s-1.18-0.41/1435985550992478208
These are all the cache miss failures we are getting https://search.ci.kubevirt.io/?search=IOException%3A+null&maxAge=48h&context=1&type=build-log&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job The underlying issue will be fixed when we reset the bazel cache in prow-workloads cluster. For the time being …
> Temporariy disable bazel cache for 0.41 lanes

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.41.yaml
More 0.41 lanes are giving missing bazel cache entries errors https://prow.ci.kubevirt.io/pr-history/?org=kubevirt&repo=kubevirt&pr=5971. I have already applied the changes in this PR and the builds are looking ok now in https://github.com/kubevirt/kubevirt/pull/5971, the PR will persist this changes until we reset bazel cache in prow-workloads.
/cc @dhiller
> Disable bazel cache on more 0.41 jobs

- github/ci/prow-deploy/kustom/components/greenhouse/base/resources/deployment.yaml
- github/ci/prow-deploy/kustom/components/greenhouse/hostpath/kustomization.yaml
- github/ci/prow-deploy/kustom/components/greenhouse/hostpath/patches/JsonRFC6902/deployment.yaml
- github/ci/prow-deploy/kustom/components/greenhouse/pv/resources/pvc.yaml
When alerts were enabled we started getting an alert about an estimation of bazel's disk being filled within 4 days. Turns out that because of how bazel handles the cache, writing and evicting entries, this is normal behavior and the alert would be flapping forever, triggering when new entries are written and resolving when old entries are evicted.
To prevent that behavior in this PR:
* the configuration of bazel in ibm-prow-jobs is aligned to what we have in prow-workloads, leaving 30% of the volume to have enough room to grow and sink the cache.
* the defined PV is increased to 700Gb.
/cc @dhiller   
> Fix bazel cache on ibm-prow-jobs

- github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-periodics.yaml
We started getting alerts about one job in non-ready state, looking at the pod list it was in pending state, from the description:
```
$ kubectl describe pod -n kubevirt-prow-jobs b38e4b9b-124b-11ec-ba99-4ab30ff1269c 
......
Containers:
test:
......
Environment:
......
JOB_NAME:                        periodic-publish-kubemacpool-flakefinder-four-weekly-report
......
Events:
Type     Reason            Age                   From               Message
----     ------            ----                  ----               -------
Warning  FailedScheduling  2m17s (x73 over 67m)  default-scheduler  0/6 nodes are available: 6 node(s) didn't match Pod's node affinity/selector.
```
Looking at the job definition it doesn't have a cluster defined and it has a node selector that doesn't match any of …
> Fix kubemacpool flakefinder weekly report job

- github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
We have some people on the project which are very intested in tracking
monitoring changes for e.g. performance and scale, dashboard creation or
alerting.
This change will allow people to write `/area monitoring` to label issues and PRs.
> Add area/monitoring label to kubevirt/kubevirt

- github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/prow-exporter-deployment.yaml
We have been getting alerts about prow-exporter crashlooping and being down when prometheus tried to scrape it. Looking at the resource usage and logs all seemed to be ok, in the pod description:
```
Warning  Unhealthy  1s (x391 over 3d2h)  kubelet, 10.240.128.12  Liveness probe failed: Get "http://172.17.89.68:8081/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
``` 
This PR aims to prevent the pod from being restarted by the kubelet  by relaxing the probes settings. It also sets resources according to recent usage to get guaranteed QoS.
/cc @dhiller 
> Relax prow-exporter probes settings and set resources

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
There are some cases when the automatic bump of a new provider needs
some manual adjsutments. In that case we would like to freeze the
push to existing bump PR until we manage to fix the issues.
> Do not update existing KCI provider bump PR when hold label exists

- github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
K8s 1.22 is not supported yet in kubevirt-infra-bootstrap
> HCO: revert add lane for K8s 1.22

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
As the k8s 1.22 provider has been merged, we now make the job to run
automatically and be required to merge.
/cc @enp0s3
> Make k8s 1.22 check provision job mandatory

- robots/cmd/flakefinder/report.go
- robots/cmd/flakefinder/report_test.go
Introduces an additional report in CSV format that is written and
stored besides the original html report.
Output is like this:
```
"Test Name","Test Lane","Severity","Failed","Succeeded","Skipped","Jobs (JSON)"
"t1","a","red",4,1,2,"{BuildNumber: 1742,Severity: ""red"",PR: 4217,Job: ""testJob"",},"
"t1","b","yellow",5,2,3,
"t2","a","cyan",8,2,4,
"t2","b","blue",9,3,5,
```
**Note:** according to [RFC 4180](https://tools.ietf.org/html/rfc4180) double quotes within a double quoted field value have to be escaped with another double quote
Example output: gs://kubevirt-prow/reports/flakefinder/preview/kubevirt/kubevirt/flakefinder-2021-09-05-024h.csv
Signed-off-by: dhiller@redhat.com
/cc @fgimenez
> Add csv reporting for easier aggregation

- github/ci/services/prometheus-stack/manifests/rules/common/kubernetes-apps.yaml
On high usage time it is common for a job to wait in the queue 30min, these changes will prevent `KubePodNotReady` to trigger very frequently because of enqueued CI jobs.
/cc @dhiller 
> Increase time to trigger KubePodNotReady

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
This will fix the creation of the generated alertmanager configuration and will prevent these errors in the operator logs:
```
level=warn ts=2021-09-15T07:31:01.814978897Z caller=operator.go:897 component=alertmanageroperator msg="skipping alertmanagerconfig" error="key \"apiURL\" in secret \"slack-config\" not found" alertmanagerconfig=monitoring/kubevirtci namespace=monitoring alertmanager=prometheus-stack-kube-prom-alertmanager
```
/cc @dhiller 
> Fix slack-config secret for prometheus deployment

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
There was an error in https://github.com/kubevirt/project-infra/pull/1549 and instead of the flaky storage lanes, the compute lanes were set to not run.
/cc @rmohr 
> Always run sig-compute lanes and do not run flaky sig-storage lanes

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Adds a retest job to trigger retesting on failed kubevirtci builds as we
have for kubevirt. This will hopefully remediate the flaky check-provision checks due to docker rate limit.
Also fixes some job names.
/cc @fgimenez @jean-edouard
> Add retester for kubevirtci, fix some job names

- images/prow-deploy/Dockerfile
The main goal is shipping a more recent kubectl that allows `apply --server-side` to prevent errors like https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/1587/pull-project-infra-prow-deploy-test/1438747463094636544#1:build-log.txt%3A552 
I've also taken the opportunity to switch the base image to the latest fedora-based bootstrap, to bump the test-infra sources from which we build several tools and to add the which package required here https://github.com/kubevirt/project-infra/blob/main/hack/patch_node.sh#L15.
/cc @dhiller 
> Updated prow-deploy image

- github/ci/prow-deploy/kustom/components/docker-mirror-proxy/base/resources/deployment.yaml
- github/ci/prow-deploy/molecule/default/Dockerfile.j2
- github/ci/prow-deploy/molecule/default/molecule.yml
- github/ci/prow-deploy/tasks/deploy.yml
* Use image from https://github.com/kubevirt/project-infra/pull/1590 and update docker service start in the container to work with it
* Use `kubectl apply --server-side` to prevent errors like https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/1587/pull-project-infra-prow-deploy-test/1438747463094636544#1:build-log.txt%3A552
* Remove duplicated env value in mirror-proxy deployment (unnoticed before. now causes error)
/cc @dhiller 
> Fix prow deployment

- github/ci/prow-deploy/kustom/overlays/ibmcloud-production/kustomization.yaml
- github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/ingress-class.yaml
We no longer need to deploy the default IngressClass in ibm-prow-jobs cluster, it is deployed with different values by the managed services.
This change will fix errors like https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/post-project-infra-prow-control-plane-deployment/1438837799989022720
/cc @dhiller 
> Do not deploy default IngressClass in ibm-prow-jobs

- robots/cmd/kubevirt-job-copier/main.go
- robots/cmd/kubevirt-job-copier/main_test.go
It is required for the new periodics to copy the extra_refs field from the previous job, otherwise the job will not work.
/cc @enp0s3 @fgimenez
> Add copying for extra_refs

- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
We have no periodic for pushing the builder. So when we have an update to the builder it never makes it into quay. This PR fixes that.
> Add nightly push of the builder image for CDI

- github/ci/services/prometheus-stack/manifests/rules/production-control-plane/ci-usage-alerting.yaml
Followup of #1586, adds alerts for some of the metrics used in the CI usage dashboard https://grafana.ci.kubevirt.io/d/qFDyvVinx/ci-infrastructure-utilization?orgId=1
> Add CI usage alerts

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt.github.io/kubevirt-github-io-presubmits.yaml
Signed-off-by: Tyler Auerbeck <tauerbec@redhat.com>
@mazzystr Took an initial run at https://github.com/kubevirt/kubevirt.github.io/issues/785
This (I _think_) will add presubmit jobs to begin linting markdown files and running spell checks (in addition to the existing link checker). Please let me know if this is the appropriate place or if there is somewhere else this belongs.
> Add presubmit linting jobs for kubevirt-github-io

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Change the TARGET value for k8s-1.22 periodic for operator, which fixes this problem: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.22-operator/1440108636092239872#1:build-log.txt%3A38
/cc @fgimenez @stu-gott
> Fix 1.22 periodic for kubevirt

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Adds a new manual lane for k8s 1.22 (root) to run only the [functional tests](https://github.com/kubevirt/kubevirt/blob/280697044fcdaf163bf16b99ef4cdb6528950bb3/tests/realtime/realtime.go) for realtime use cases. This PR takes into account the changes introduced in this other [PR](https://github.com/kubevirt/kubevirt/pull/6182) (kubevirt) to the [automation/test.sh](https://github.com/kubevirt/kubevirt/blob/280697044fcdaf163bf16b99ef4cdb6528950bb3/automation/test.sh) script to tune the created cluster to support realtime VMs.
@fgimenez @vladikr @dhiller @pkliczewski can you take a look?
> Add Realtime lane (manual trigger)

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
- hack/bump-prow-job-images.sh
- hack/update-jobs-with-latest-image.sh
- images/pr-creator/Dockerfile
The script `hack/bump-prow-job-images.sh` updates a list of images that are currently hardcoded. Changes required for that to work:
* update pr-creator image by adding install of skopeo to be able to fetch latest image tags
* update `hack/update-jobs-with-latest-image.sh` to use skopeo for fetching latest image tag
Created a new periodic job `periodic-project-infra-prow-job-image-bump` that runs daily to execute that script.
Example result is here: https://github.com/kubevirt/project-infra/pull/1584/commits/6268062bb2109d9e41b9707cd798e64d6a43e38a
/cc @fgimenez
> Add new job and script that bump images used in prow job definitions

- github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner-operator/OWNERS
- github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner-operator/hostpath-provisioner-operator-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner-operator/hostpath-provisioner-operator-presubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner/hostpath-provisioner-postsubmits.yaml
- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
- github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Added support for lgtm/approve and release for hostpath-provisioner-operator
Together with https://github.com/kubevirt/hostpath-provisioner-operator/pull/132 this should enable full PROW support for the operator.
> Add hostpath-provisioner-operator repo to PROW

- github/ci/prow-deploy/kustom/components/docker-mirror-proxy/base/resources/deployment.yaml
- github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/ghproxy_deployment.yaml
We are having a issues with the docker-mirror-proxy and ghproxy deployments, the new pods are blocked in `ContainerCreating` status bc the old pods have the associated volume attached and the new one can't attach it in exclusive mode.
These changes aim to improve automation (no need to manually scale down and up the deployment to unblock de rollout) at the cost of non zero-downtime deployments. In case it is required to replace the pod it might happen that after the old pod is down and before the new pod is up the service provided by it could be unavailable.
/cc @dhiller 
> Allow one unavailable pod in several deployments

- github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner/hostpath-provisioner-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner/hostpath-provisioner-presubmits.yaml
To support migrating from travis, we can make releases using PROW and run unit tests. https://github.com/kubevirt/hostpath-provisioner/pull/74 supports removal of travis and adds release scripts called here.
> Add post submit to hostpath-provisioner and unit tests runner

- hack/bump-prow-job-images.sh
- hack/update-jobs-with-latest-image.sh
Also add non zero exit in case of empty repository.
Fixes https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-project-infra-prow-job-image-bump/1440835968474025984
/cc @fgimenez
> Exclude private and empty repos from bumping

- github/ci/prow-deploy/tasks/deploy.yml
Forces the manager of all the potential fields that might change in the future to be server-side. Will prevent errors like https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/post-project-infra-prow-control-plane-deployment/1441026775944531968#1:build-log.txt%3A181
> Add --force-conflicts to prow-deploy kubectl apply

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
- github/ci/prow-deploy/molecule/default/molecule.yml
Bumps the image used in prow-deploy tests to the version created in #1614
/cc @dhiller 
> Bump prow-deploy image

- github/ci/testgrid/README.md
Remove leftovers and point to config merger configuration and the job for pushing our config to GCS.
/cc @dhiller 
> Remove references to transfigure in testgrid doc

- github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner/hostpath-provisioner-presubmits.yaml
Switch the remaining tests to the golang container as they use it
also.
> switch remaining hpp tests to golang container

- github/ci/prow-performance-workloads/bootstrap.yml
- github/ci/prow-performance-workloads/hack/bootstrap.sh
- github/ci/prow-performance-workloads/hack/common.sh
- github/ci/prow-performance-workloads/hack/deploy.sh
- github/ci/prow-performance-workloads/inventory/prow-performance-workload/README.md
- github/ci/prow-performance-workloads/inventory/prow-performance-workload/group_vars/all/docker.yml
- github/ci/prow-performance-workloads/inventory/prow-performance-workload/group_vars/etcd.yml
- github/ci/prow-performance-workloads/inventory/prow-performance-workload/group_vars/k8s_cluster/addons.yml
- github/ci/prow-performance-workloads/inventory/prow-performance-workload/group_vars/k8s_cluster/k8s-cluster.yml
- github/ci/prow-performance-workloads/inventory/prow-performance-workload/group_vars/k8s_cluster/k8s-net-calico.yml
- github/ci/prow-performance-workloads/inventory/prow-performance-workload/group_vars/kube-proxy.yml
- github/ci/prow-performance-workloads/roles/bootstrap/tasks/main.yml
Adding the configuration files and scripts to create the Sig-Scale cluster.
The files are used to configure kubespray, and the scripts are used to create the cluster.
The new Sig-Scale cluster will be used to run performance jobs for the Continuous Performance Evaluation of the KubeVirt control plane. As detailed here: https://github.com/kubevirt/kubevirt/issues/6309
There are still two missing pieces to automate the cluster creation:
- add the needed private key in `'prowPerformance.sshKey'`
- create a new configmap `'prowPerformance.hostsYml'` with the cluster configuration
> [Sig-Scale] adding the config files to create the sig-scale cluster

- github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner-operator/hostpath-provisioner-operator-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner-operator/hostpath-provisioner-operator-presubmits.yaml
The hpp operator scripts are very similar to hpp and thus
should be using the golang container as well for testing
and releases.
> Switch hpp operator to use golang container

- github/ci/services/prometheus-stack/manifests/rules/common/kubernetes-apps.yaml
- github/ci/services/prometheus-stack/manifests/rules/production-control-plane/kubernetes-apps.yaml
- github/ci/services/prometheus-stack/manifests/rules/production-e2e-workloads/kubernetes-apps.yaml
* Creates different definitions of `KubePodNotReady` for control plane and workloads clusters.
* Sets the trigger to 90m for workloads cluster.
/cc @dhiller 
> Set KubePodNotReady alert trigger to 90m in prow-workloads

- github/ci/services/prometheus-stack/manifests/rules/common/kubernetes-apps.yaml
- github/ci/services/prometheus-stack/manifests/rules/production-control-plane/kubernetes-apps.yaml
- github/ci/services/prometheus-stack/manifests/rules/production-e2e-workloads/kubernetes-apps.yaml
Fixes errors like https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/post-project-infra-prometheus-stack-deployment/1443935838986571776
/cc @dhiller 
> Rename kubernetes-apps PrometheusRule and rule group for common and cluster use cases

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
- images/vm-image-builder/Dockerfile
Adds image to handle creation of the images defined here https://github.com/kubevirt/kubevirtci/tree/main/cluster-provision/images/vm-image-builder I've also taken the opportunity to split the jobs that currently manage bootstrap and golang images.
/cc @dhiller @jordigilh 
> Add vm-image-builder image and jobs to handle it

- github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner-operator/hostpath-provisioner-operator-presubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner/hostpath-provisioner-presubmits.yaml
They are currently marked on prow-workloads but don't require
bm at all to run. So phx-prow is better.
> Move hpp(-operator) unit tests to phx-prow cluster

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The jobs should only run for PRs against default branch: Wrong example: https://github.com/kubevirt/kubevirt/pull/6517
/cc @fgimenez @jean-edouard
> Skip release branches for 1.22 jobs

- github/ci/prow-deploy/requirements.txt
`github/ci/prow-deploy/requirements.txt` is only used for local testing during development, it should always have the same content as the one used on CI, `images/prow-deploy/requirements.txt`
> Symlink prow-deploy requirements.txt to the file used on CI

- github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml
This will be automated soon (https://github.com/kubevirt/project-infra/pull/1616/files#diff-657f2447d4813480e447b9dad795932f8dd1b9e03df940df35d5fdfb1da98344R25), for now it will fix errors like https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/publish-kubernetes-nmstate/1445309051528286208#1:build-log.txt%3A82
/cc @qinqon @dhiller 
> Bump bootstrap image used in nmstate publish job

- robots/pkg/kubevirt/cmd/copy/jobs.go
- robots/pkg/kubevirt/cmd/copy/jobs_test.go
Also add some other test cases to increase coverage in general. This is related to the previous fix for the addition of the branch selection on presubmits: https://github.com/kubevirt/project-infra/pull/1646
> Add test for copying branch rules on presubmits

- github/ci/prow-deploy/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-presubmits-master.yaml
We run e2e in OpenshiftCI only now
> NMO: Remove e2e from presubmits, clean postsubmit

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
- robots/cmd/kubevirt/README.md
- robots/pkg/kubevirt/cmd/copy/BUILD.bazel
- robots/pkg/kubevirt/cmd/copy/jobs.go
- robots/pkg/kubevirt/cmd/copy/jobs_test.go
- robots/pkg/kubevirt/cmd/remove/BUILD.bazel
- robots/pkg/kubevirt/cmd/remove/always_run.go
- robots/pkg/kubevirt/cmd/remove/jobs.go
- robots/pkg/kubevirt/cmd/remove/jobs_test.go
- robots/pkg/kubevirt/cmd/remove/remove.go
- robots/pkg/kubevirt/release/BUILD.bazel
- robots/pkg/kubevirt/release/release.go
- robots/pkg/kubevirt/release/release_test.go
Adds the automation to disable `always_run` on kubevirt sig presubmit jobs for unsupported k8s providers.
Also fixes the selection of the releases to only contain differing minor releases. The unfiltered list contains all patch release versions, while we need to consider only the latest patch version per minor version.
Finally fixes the branch name for the delete job prowjob, which was the same as the job it was copied from.
/cc @fgimenez
> Add always run disabler, fix PR branch and selection of releases for delete jobs job

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Adds a new lane for running the realtime performance tests. These tests capture the maximum CPU latency when running a VM in realtime and compare it against a given latency threshold. The test will pass if the maximum latency is below the given threshold.
@fgimenez @vladikr @acardace @pkliczewski @rmohr @dhiller
> Adds new lane for running periodic realtime perf tests

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
> add an optional presubmit e2e test on ARM64

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
For 0.34 and 0.36 where there are infrequent updates happening we need
to update the testing manifests also, otherwise the openshift-ci tests
will fail.
/cc @fgimenez
> Add postsubmit to update testing manifests

- github/ci/prow-deploy/files/orgs.yaml
This repository will eventually repolace client-go by only exporting the
API of KubeVirt which can then be usede by client-gen.
> Request an API repository for KubeVirt

- WORKSPACE
We were getting errors with gazelle as described here https://github.com/bazelbuild/bazel-gazelle/issues/1076, removing the unneeded `com_github_bazelbuild_buildtools` dep fixes them.
> Remove unneded dep from WORKSPACE

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Run `make go-build` to build the binary locally in order for the test to run
Signed-off-by: Ryan Hallisey <rhallisey@nvidia.com>
> Perfscale-audit binary is missing from the Perf periodic

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
- github/ci/prow-deploy/hack/test.sh
Requires https://github.com/kubevirt/secrets/pull/37
Changes to use an unprivileged gh token in prow-deploy tests to make sure that we don't interact with production components during their execution. Recently this PR https://github.com/kubevirt/kubevirt-velero-plugin/pull/10 was merged before the changes that would enable tide queries for its repo were deployed, probably during prow-deploy integration tests.
> Use unprivileged token for prow-deploy tests

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
- github/ci/prow-deploy/hack/test.sh
- github/ci/prow-deploy/kustom/overlays/workloads-production/kustomization.yaml
- github/ci/prow-deploy/molecule/default/vars/kubevirtci-testing.yml
- github/ci/prow-deploy/tasks/secrets.yml
Fixes errors like https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/1701/pull-project-infra-prow-deploy-test/1455871425150717952 The `GIT_ASKPASS` definition is a leftover, now that we don't mount the github token it has started causing the job to fail.
Also added code to deploy the unprivileged github token used during tests, and changed the `pull-project-infra-prow-deploy-test` to mount and use it.
/cc @rmohr @dhiller  
> Do not use GIT_ASKPASS for prow-deploy-test

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
- github/ci/prow-deploy/kustom/components/docker-mirror-proxy/base/resources/deployment.yaml
- github/ci/prow-deploy/kustom/components/docker-mirror-proxy/base/resources/service.yaml
- github/ci/prow-deploy/kustom/components/greenhouse/base/resources/deployment.yaml
- github/ci/prow-deploy/kustom/overlays/workloads-production/resources/ingress-controller.yaml
- github/ci/prow-deploy/kustom/overlays/workloads-production/resources/metrics-server.yaml
- github/ci/prow-deploy/tasks/deploy.yml
Currently we are not continuously deploying to the workloads cluster, these changes set the job to run on relevant changes and update some of the resources to be able to be deployed there. 
They also add logic in the deployment role for not using server-side apply on the workloads cluster, which runs k8s 1.19 and doesn't work well with it. In any case, server-side apply is required only for Prow control plane because of the length of the CRDs. In any case we need to update the workloads cluster k8s version, but for now these changes will allow us to keep deploying changes there.
Tested successfully here https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/post-project-infra-prow-workloads-cluster-deployment/1454002949243015168
Signed-off-by: Federico Gimenez …
> Fix workloads cluster deployment

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Last two runs
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-publish-kubevirt-flakefinder-four-weekly-report/1454108770077511680
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-publish-kubevirt-flakefinder-four-weekly-report/1451571806946201600
seem to have timed out after 3h, so we increase the timeout to 4h.
/cc @fgimenez
> periodic-publish-kubevirt-flakefinder-four-weekly-report: Increase timeout to 4h

- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits-1.34.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits-1.38.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Other than that sticking to the same subset as we have now & deploy prometheus on 2 lanes & cleanup of entries.
> Make the required switch from 1.19, 1.20 to 1.21, 1.22 in CDI

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
1.21-sig-storage and 1.22-sig-storage lanes are extremely flaky since ~4 Nov. There are some ongoing efforts to stabilize them but they haven't improved the situation so far and the merge queue has already more than 10 PRs blocked because of this https://github.com/kubevirt/kubevirt/pulls?q=is%3Apr+is%3Aopen+label%3Aapproved+label%3Algtm+-label%3Ado-not-merge%2Fhold+-label%3Aneeds-rebase The average retests to merge is above 6 and the average time to merge is above one day now.
This PR proposes to make these two lanes temporarily optional until we understand the root cause of the issue and we prepare a proper fix.
/cc @maya-r @brybacki @rmohr @dhiller 
> Make flaky sig-storage lanes optional

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
After the latest PR to stabilize sig-storage lanes was merged https://github.com/kubevirt/kubevirt/pull/6778 we did not get any more errors in the periodics from master for non-quarantined tests:
1.22-sig-storage:
1.21-sig-storage:
Also the presubmits look stable. This PR makes them required again. 
/cc @rmohr @maya-r @brybacki @dhiller 
> Make sig-storage presubmit lanes required again

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt.github.io/kubevirt-github-io-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt.github.io/kubevirt-github-io-postsubmits.yaml
- github/ci/prow-deploy/files/orgs.yaml
Part of respectful naming initiative.
https://github.com/kubevirt/kubevirt.github.io/issues/786
> Update kubevirt.github.io default branch to main

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
This PR introduces the prow jobs to configure the performance workload cluster and run kubespray to create a new k8s cluster.
> add prow jobs to configure the performance workload cluster

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Publish to kubevirt/client-go and kubevirt/api always together with the
developer build to have a working combination at hand.
> Publish staging code together with the developer release

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
The jobs using the kubespray image does not have the initialization script "/usr/local/bin/runner.sh" like the jobs using the other images. Then, this PR is removing the script "/usr/local/bin/runner.sh" of those jobs and calling "/bin/bash" directly.
> remove runner.sh script from jobs using kubespray image

- images/bootstrap/Dockerfile
The tool is useful to query remote images. Needed to determine in https://github.com/kubevirt/containerdisks to determine if images need to be updated.
> Include skopeo in the bootstrap image

- hack/manage-secrets.sh
Will fix errors like https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/post-project-infra-prow-performance-workloads-bootstrap-nodes/1460969308174684160 and in general will be useful for any job that is based on an external image (potentially without yq installed) and requires to decrypt secrets
/cc @marceloamaral @dhiller 
> Add yq for managing secrets if not present

- github/ci/testgrid/default.yaml
Standard cell width (90) view takes big amount of screen estate and not much information is available. The change switches default width to 20 (compact). 
> testgrid: width compact

- github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-periodics.yaml
- github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits-v0.20.yaml
- github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits-v0.21.yaml
- github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits-v0.26.yaml
- github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits-v0.31.yaml
- github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner-operator/hostpath-provisioner-operator-presubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner/hostpath-provisioner-presubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-tutorial/kubevirt-tutorial-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-tutorial/kubevirt-tutorial-presubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-velero-plugin/kubevirt-velero-plugin-presubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.34.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.42.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/macvtap-cni/macvtap-cni-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/macvtap-cni/macvtap-cni-presubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
- github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-periodics.yaml
- github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits-0.15.yaml
- github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits-0.31.yaml
- github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits-0.35.yaml
- github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits-0.37.yaml
phx-prow cluster is being decommissioned by EOY and the jobs running there are giving a lot of connectivity issues, we need to migrate all the jobs currently running there. The end goal is having a new separate workloads cluster, it is not yet in place but for now we have already scaled up ibm-prow-jobs cluster to handle the load. 
This PR takes care of configuring all the jobs currently running on phx-prow to run on ibm-prow-jobs, it also removes the node selector settings that are only meaningful in phx-prow.
> Move jobs scheduled on phx-prow to ibm-prow-jobs

- github/ci/prow-deploy/files/orgs.yaml
Account seems to have gotten deleted, peribolos complains on that:
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-org-github-config-updater/1461391744753995776#1:build-log.txt%3A8
> Remove fdupont-redhat from org

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
The build now executes `hack/publish-staging.sh` which needs golang.
> Ensure that go is available for the developer build pusher

- github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
* An optional presubmit job which solely builds without pushing images
* A daily periodic job which determines if new images need to be built and pushes them on demand.
> Initial set of jobs for kubevirt/containerdisks

- github/ci/prow-deploy/files/orgs.yaml
I have merged my work account (fdupont-redhat) into my personal account (fabiendupont).
https://github.com/kubevirt/project-infra/pull/1741 removed fdupont-redhat from the organization. This pull request adds fabiendupont.
And I continue to belong to the Kubevirt organization.
> Add fabiendupont to organization

- github/ci/services/prometheus-stack/secrets/production-control-plane/prometheus-stack-kube-prom-prometheus-scrape-confg/additional-scrape-configs.yaml
After https://github.com/fgimenez/ci-health has been transferred to https://github.com/kubevirt/ci-health we need to update the prometheus target to scrape metrics from that repo.
/cc @dhiller 
> Update prometheus' ci-health target

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Go is needed to build tooling for syncing staging to their target repos.
> Make go available for nightly builds

- github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
This should unblock https://github.com/kubevirt/containerdisks/pull/1 now that #1746 is merged.
> Bump the bootstrap image to get a new skopeo version

- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Will prevent tide being blocked because of gh actions errors
/cc @qinqon @dhiller 
> Ignore unknown cotexts for nmstate/kubernetes-nmstate

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
`hack/publish-staging.sh` is switching its path. If the git askpass path is not absolute, it will point to a non-existing file.
> We need an absolute askpass path due to directory switching

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
- robots/cmd/kubevirtci-bumper/README.md
- robots/cmd/kubevirtci-bumper/main.go
- robots/pkg/kubevirt/cmd/BUILD.bazel
- robots/pkg/kubevirt/cmd/check/BUILD.bazel
- robots/pkg/kubevirt/cmd/check/check.go
- robots/pkg/kubevirt/cmd/check/providers.go
- robots/pkg/kubevirtci/kubevirtci.go
- robots/pkg/kubevirtci/kubevirtci_test.go
> Drop unsupported providers

- github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
- github/ci/testgrid/hack/check.sh
Testgrid config upload is failing now https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/post-project-infra-update-testgrid-config/1461638674906091520 looks like the tests didn't catch an issue in the containerdisks repo tests.
The changes specify the tests to be executed.
> Fix testgrid tests

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Make 1.19 check-provision optional in order to be able to remove it. This check is currently failing the removal of the kubevirtci provider for 1.19 which is not in use any more.
https://github.com/kubevirt/kubevirtci/pull/712#issuecomment-977474129
/cc @rmohr @fgimenez @enp0s3
> Make 1.19 check-provision optional

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- hack/git-pr.sh
And use it for make rpm job. Because it's super annoying to always add a release note none like here: https://github.com/kubevirt/kubevirt/pull/6826
> Add -R for release-note-none

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
We still use kind-1.19-sriov on kubevirt,
let's return the lane until we fully switch to sriov-1.22,
so it will be part of the gating.
> sriov-1.19, Readd check-up-kind-1.19-sriov lane

- github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.42.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.44.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.53.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.58.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
Recent skopeo releaeses updated the OS and moved to
use more advanced syscalls, ones that are currently
filtered by docker (issue [0]).
In order to move past this issue, updating to image
using fedora 34.
[0] containers/skopeo#1501
Notes: fixes https://github.com/kubevirt/cluster-network-addons-operator/issues/1080
> cnao, unit-tests, Update unit-test lane image

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
Enables the release job backported by https://github.com/kubevirt/kubevirt/pull/6837 to run.
/cc @rmohr
/hold
> Backport kubevirt release job to release-0.36

- hack/mkpj.sh
I'm having some build errors with mkpj on f35 seemingly related to the python3 version shipped, after completely cleaning up bazel cache I get:
```
Loading: 0 packages loaded
INFO: Repository py3_deps instantiated at:
no stack (--record_rule_instantiation_callstack not enabled)
Repository rule pip_import defined at:
/home/fgimenez/.cache/bazel/_bazel_fgimenez/c0d189b08f12465ef5319973ed87a017/external/rules_python/python/pip.bzl:44:29: in <toplevel>
ERROR: An error occurred during the fetch of repository 'py3_deps':
pip_import failed:  (Traceback (most recent call last):
File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File …
```
> Add mkpj.sh script

- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
We have been getting a lot of errors downloading packages from the default golang proxy during the last weeks, like https://search.ci.kubevirt.io/?search=Error+in+fail%3A+failed+to+fetch&maxAge=336h&context=1&type=build-log&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
We are not sure if the issue is related to a connectivity issue or rate-limiting from the proxy. There is a support ticket open for more than 10 days now to determine if this is a connectivity problem on the cloud provider side, but we haven't had too much progress so far.
This PR proposes to set https://goproxy.io/ as the default proxy for all the jobs using Prow's default preset with no labels as described here https://github.com/kubernetes/test-infra/blob/master/config/jobs/README.md#job-presets If we …
> Add default preset with go proxy setting

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
Some `go mod` actions make golang now a requirement.
Fixes this issue: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/push-release-kubevirt-tag/1466160989484355584
> The release job needs golang

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
- hack/images_to_mirror.csv
- hack/mirror-images.sh
docker.io has a pull limit and we want to consume some images from quay.io. 
This PR add a postsubmit job which mirror some specific images from docker.io to quay.io. It aims to add an automated script which will work whenever you add a new image into the list. 
**Open Points**
The list of images is not clear yet.  Please add the images as comments. 
**Notes:**
As far as I see, calico is fetched from quay.io now.  https://github.com/kubevirt/kubevirtci/blob/main/cluster-provision/k8s/1.22/extra-pre-pull-images
Signed-off-by: Erkan Erol <eerol@redhat.com>
> Mirror images from docker.io to quay.io

- github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
- github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits.yaml
The kubernetes-nmstate project has remove the go installation from the
Makefile, it's still at automation but this should be part of the CI, so
we reduce infra at the project.
> knmstate: Install go 1.16

- github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml
Publish has to be called on merged to main or release branches and
Release has to be called on tagging with semVer.
> knmstate: Don't call publish on release

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
Requires https://github.com/kubevirt/kubevirtci/pull/696 to land first.
/hold
> Add bump-cdi job

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
Thanks for spotting this! Now the pr is created against the correct repo :)
Job run here: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirtci-bump-cdi/1468176156996931584
Resulting PR here: https://github.com/kubevirt/kubevirtci/pull/719
/cc @akalenyu @fgimenez
> Fix repository on kubevirtci cdi bump

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
In order to be able to develop, provision and test the new k8s-1.22-ipv6 provider,
add this job.
For now it isn't `always run`, once it is ready we will make it mandatory.
Would need this lane for developing https://github.com/kubevirt/kubevirtci/pull/721
which creates the new provider `k8s-1.22-ipv6` in a dedicated folder.
> k8s-1.22-ipv6: Add kubevirtci presubmit job

- github/ci/prow-deploy/files/jobs/kubevirt/qe-tools/qe-tools-presubmits.yaml
- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
- github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Since we disabled Travis CI we don't have any automated testing here. See https://github.com/kubevirt/qe-tools/pull/24 where we could need it.
Manual run of the job here: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_qe-tools/24/pull-qe-tools-make-test/1468170849990217728
/cc @lukas-bednar @rmohr
> Add presubmit job to test PRs on qe-tools

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.42.yaml
Align it to the cluster which runs sriov jobs for
other releases (i.e 0.41) and main branch.
We can see it hangs on the previous cluster
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6209/pull-kubevirt-e2e-kind-1.17-sriov-0.42/1468605263404601344
> sriov, release-0.42: Use prow-workloads for running jobs

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
This PR adds a new lane for testing metrics/alerts with a real Prometheus instance.
The job in this PR will consume the changes in this PR: https://github.com/kubevirt/kubevirt/pull/6933
Signed-off-by: Erkan Erol <eerol@redhat.com>
> Add sig-monitoring lane

- github/ci/prow-performance-workloads/inventory/prow-performance-workloads/group_vars/kube-proxy.yml
The default configuration in kubespray when creating a k8s cluster does not expose kube proxy metrics.
But to scrape these metrics using prometheus, we need to change the `kube_proxy_metrics_bind_address` from using localhost address to 0.0.0.0 to bind all IPv4 interfaces.
/cc @fgimenez @dhiller 
> updated the kube proxy metrics bind address to use 0.0.0.0

- github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
Needed for https://github.com/kubevirt/containerdisks/pull/9
> Bump containerdisks repo to golang 1.16

- docs/cncf-tools.md
Describes how to get access to https://servicedesk.cncf.io/ and the tools provided from there.
> Add document about CNCF tools

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
The job is very unstable when all possible tests are executed. Focus only on sig-compute to make it less flaky.
https://prow.ci.kubevirt.io/?job=periodic-kubevirt-e2e-k8s-1.20-cgroupsv2
> Reduce the scope of cgroups v2 periodic job

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Now that 1.23 provider has gotten merged we need to make the check-provision for it mandatory, otherwise we'll miss when it breaks. This would then impact the 1.23 kubevirt lanes.
> Make check-provision required for 1.23

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
In order to be able to install k8s 1.21.3 we need to bump kubespray, there are dictionaries with the digests of the images to download indexed by k8s versions like https://github.com/kubernetes-sigs/kubespray/blob/b7ae4a2cfde75b7f110c756438c77b2103cc4761/roles/download/defaults/main.yml#L191-L215 and 1.21.3 is not present in kubespray v2.15.0 (the version the jobs are currently using)
Succesful execution here https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/post-project-infra-prow-performance-workload-cluster-deployment/1463901223005458432 (using secrets from https://github.com/kubevirt/secrets/pull/41)
/cc @marceloamaral @dhiller 
> Bump kubespray in prow-performance deployment jobs.

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The PR makes cgroups v2 presubmit job mandatory instead of runnig the periodic job.
With the test scope reduced to sig-compute only the results look more stable now: https://prow.ci.kubevirt.io/?job=periodic-kubevirt-e2e-k8s-1.20-cgroupsv2
@rmohr , @fgimenez FYI. We can monitor the periodic a bit more if there are doubts about it. But I think it should be fine to have  a mandatory presubmit.
> Always run cgroups v2 presubmit job

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Depends on https://github.com/kubevirt/kubevirtci/pull/721
Added with `always_run: false`, `optional: true` until we make kubevirt support single stack ipv6.
> k8s-1.22-ipv6, network: Add kubevirt presubmit job

- github/ci/prow-deploy/files/jobs/kubernetes-sigs/cluster-api-provider-kubevirt/cluster-api-provider-kubevirt-presubmits.yaml
capik goes to golang 1.17 and will not compile with 1.16 anymore which is our current default.
> Bump capik job to golang 1.17

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Since the lane is already passing with it's current configuration,
and it is part of the kubevirtci package,
it should be marked as mandatory.
> k8s-1.22-ipv6: Make the lane mandatory

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
After observing the lane for a while and ensuring it works, we can enable reporting now.
It will be still optional but developers will be warned about the issues. After a while, it can
be mandatory as well.
https://prow.ci.kubevirt.io/?job=pull-kubevirt-e2e-k8s-1.22-sig-monitoring
Signed-off-by: Erkan Erol <eerol@redhat.com>
> Enable reporting for sig-monitoring

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
This PR sets the new Kubevirt SR-IOV lane, `kubevirt-pull-e2e-kind-1.22-sriov`, 
as voting lane instead of ` kubevirt-pull-e2e-kind-1.19-sriov`.
The new lane periodic job results show that its stable for more then two weeks:
https://testgrid.k8s.io/kubevirt-periodics#periodic-kubevirt-e2e-k8s-1.22-sriov
> Upgrade presubmits Kubevirt SR-IOV lane

- github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.65.yaml
The configuration for 0.65 was copied from the previous stable branch
instead of the current main. Due to that, some of the recent changes
were not taken. Due to a missing Go dependency, this caused a failing CI
lane.
With this patch, release 0.65 is synced with the main config.
> Update CNAO release 0.65 presumbmit based on main

- images/bootstrap/Dockerfile
This updates moby-engine and picks up moby/moby#42681 which fixes
pthread_create for glibc 2.34 or newer.
> Whitespace change to trigger rebuild of bootstrap image

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
`kubevirt check providers` fails with non zero exit code if it detects
unsupported providers. This causes a daily noise in the slack channel.
We now just stop execution if that check fails and output a message
pointing it out instead.
/cc @enp0s3 @rmohr
> Make jobs silently cancel execution to reduce slack noise

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Add a Prow job that runs a density test once a day by creating 100 VMs in the performance cluster.
The results of this work will be used as the baseline performance of KubeVirt to evaluate a possible performance regression.
> add daily job to run a density test in the performance cluster

- github/ci/prow-deploy/files/orgs.yaml
Added Brian also as a kubevirt org member. 
This PR also sets the `prow-job-taskforce` team to admin of the secrets repo, let me know wdyt
> Add Brian Carey to prow-job-taskforce team

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
As [moving it to the workloads cluster didn't fix it](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/publish-bootstrap-image/1480471070967336960), I updated the bootstrap image, worked locally.
Successful cluster run for new job config here: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/publish-bootstrap-image/1480491623212126208
> Update bootstrap image for bootstrap and golang image build

- github/ci/services/prometheus-stack/manifests/rules/production-e2e-workloads/kubernetes-apps.yaml
Large number of critical alerts were raised due to high load on clusters and pods not being ready within 1h30m.
These critical alerts resolved themselves over time as load reduced.
Increasing the time to trigger this alert to 3 hours to reduce noise. 
/cc @fgimenez @dhiller
> Increase KubePodNotReady alert timeout to 3 hours to reduce noise

- github/ci/services/prometheus-stack/BUILD.bazel
- github/ci/services/prometheus-stack/manifests/service-monitors/common/servicemonitors.yaml
After updating the prometheus stack to be deployed to the performance cluster, the prow-workloads cluster started getting alerts about some service monitors.
Although the [original code](https://github.com/kubevirt/project-infra/pull/1778/files#diff-8ac0dadb1c90800200076b5a36d0b123da3490b0ec96c52574119230d91e0f40L63) has been configured to deploy the service monitors in the `kubevirt-prow` namespace. `kubevirt-prow` prow cluster actually has the service monitors deployed in the `monitoring` namespace.
So this PR is changing all service monitor deployments to be in the `monitoring` namespace.
Also, the service monitors to extract metrics from `controller-manager`, kube-proxy` and `kube-scheduler` are not healthy. Even the old ones in the `monitoring` namespace and the new ones deployed in …
> Move prometheus stack service monitors from kubevirt-prow to monitoring namespace

- github/ci/services/prometheus-stack/manifests/stack/common/node-exporter.yaml
Upgrading node-exporter to image version v.1.3.1 due to issue seen with high context switching alert.
/cc @fgimenez @dhiller  
> Bump node-exporter to image version v1.3.1

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
kubevirt/project-infra#1616 set a new version for the prow-deploy image on the jobs, which gave the following error: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/1846/pull-project-infra-prow-deploy-test/1481666249732657152#1:build-log.txt%3A22
We reset back to the previous working version.
> Set prow-deploy image back to the tag of working version

- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
We no longer use the devmapper ln and it is causing issues with
the new builder image. Removing them from the pre-submits.
> Remove CDI devmapper link in jobs

- github/ci/services/prometheus-stack/manifests/rules/common/node-exporter-alerting.yaml
Short spikes are causing lots of alerts to fire for high context switching. 
These alerts are not causing any issues for the e2e jobs so increasing the time to reduce noise. 
/cc @dhiller @fgimenez 
> Increase alert time for high context switching to reduce noise from short spikes

- github/ci/prow-deploy/tasks/deploy.yml
See deployment failure here: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/post-project-infra-prow-control-plane-deployment/1481897605402202112#1:build-log.txt%3A148
/cc @fgimenez @brianmcarey
> Remove unsupported deck url for hmac

- github/ci/services/prometheus-stack/manifests/stack/production-control-plane/grafana.yaml
This adds the new panel, so that we can quickly see when suddenly a lot
of jobs fail at once. I.e. there were a couple of jobs failing due to
the prowjob image update, with this panel we'll see them quickly.
Arrows in screenshort mark the times when cdi jobs started failing:
/cc @brianmcarey @fgimenez
> Added new failed jobs panel to prow job load dashboard

- hack/update-jobs-with-latest-image.sh
The script doesn't filter out `latest` image tags. See https://github.com/kubevirt/project-infra/pull/1850/files#diff-642559bcaf57a97a9c127a55ec4d5f37d3c366d158c23a72c19d28056592208cR10
> Remove 'latest' tag from list of image tags

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
We now have kind-1.22-sriov which is the operational one.
> kind-1.19-sriov: Disable job autorun

- github/ci/prow-deploy/files/orgs.yaml
Tell peribolos to rename default branch of user-guide from master to main per compassionate language project
https://github.com/kubevirt/user-guide/issues/430
> Set user-guide default branch to main

- github/ci/prow-deploy/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-presubmits-master.yaml
- hack/update-jobs-with-latest-image.sh
Fixes a bug that does not take job config files with default branch name into account.
Adds a parameter to the script `hack/update-jobs-with-latest-image.sh` to select the directory for which the job configs should get bumped.
Finally bumps the node-maintenance-operator job configs.
Job instances with new image:
* [pull-node-maintenance-operator-build](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_node-maintenance-operator/172/pull-node-maintenance-operator-build/1483124046433357824)
* [pull-node-maintenance-operator-check](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_node-maintenance-operator/172/pull-node-maintenance-operator-check/1483124656822030336)
/cc @machadovilaca @slintes
> Fix prow job image bump for branch configs

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Since https://github.com/kubevirt/kubevirt/pull/6042 is merged into the main branch, it probably makes sense to enable at least one presubmit storage job for testing the functionality (i.e. hotplug disks on cgroup v2 host).
> Always run a mandatory cgroup v2 storage job

- github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
Update k8s-testimages/bootstrap image in cluster-network-addons-operator-presubmits to latest version
Jobs in kubevirt/cluster-network-addons-operator/pull/1142 are failing when building a `Dockefile` with a `centos:stream9` because of the use of an older `k8s-testimages/bootstrap` 
/cc @dhiller @RamLavi @phoracek @qinqon
Signed-off-by: João Vilaça <jvilaca@redhat.com>
> Update k8s-testimages/bootstrap image in CNAO jobs to latest version

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
add versions 1.22 and 1.23 to GCP cri-o mirror
> sync crio repos with 1.22,1.23 versions

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
According to [this article](https://stackoverflow.com/questions/49302859/gsutil-serviceexception-401-anonymous-caller-does-not-have-storage-objects-list#comment105668942_56952730) for certain operations you need to explicitly activate the service account.
Successful job run here: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirtci-mirror-crio-repository-weekly/1488099413959118848
Please note that you could further improve the gsutil operation by using the `-m` flag: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirtci-mirror-crio-repository-weekly/1488099413959118848#1:build-log.txt%3A516
/cc @rhrazdil @brianmcarey
> Fix gcloud rsync by adding explicit sa activation

- github/ci/prow-deploy/hack/deploy.sh
For the post deploy job the general env var declaration for `GIT_ASKPASS` does not work. Overwriting it in the script into an absolute path, so that it still works.
> overwrite GIT_ASKPASS declaration in script

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
To be able to run all of our migration tests, rook needs to be deployed.
> Deploy rook on the migration test job

- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Add a second proxy and ensure that go will download from the next
specified source in case of any failure.
The old value was `https://proxy.golang.org,direct`, the new value is `https://proxy.golang.org|https://goproxy.io|direct`.
This fixes an issue where the jobs sometimes gets a GOAWAY which leads
to an immediate error, since direct download is only considered if a 404
or a 410 error code is returned.
Note that there is a difference between `,` and `|` separators. If `,` is used, only in the mentioned cases above retries are happening. Details are here: https://go.dev/doc/go1.15#go-command
> Add a GOPROXY fallback if the main proxy rejects us

- github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner/hostpath-provisioner-presubmits.yaml
Add a lane that bases the HPP storage pool on ceph PVC
Optional at first so we can make necessary adjustments in the hostpath-provisioner repo.
> Add HPP ceph lane

- github/ci/prow-deploy/files/orgs.yaml
Adding @jberkus to  the kubevirt org. He does incredibly valuable community work for us.
Sponsors according to https://github.com/kubevirt/community/blob/main/membership_policy.md:
Sponsor 1: @rmohr 
Sponsor 2: @fabiand
> Add jberkus to our org

- github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-postsubmits.yaml
The CNAO repo has now a workflow_distpatch to create release PR
manually, those releases PR are branchs at origin and they don't have to
run the release job, the release job is for when those PRs get merged to
"main" or "release-x.y" branches.
> cnao: Run release only on main and "release-"

- github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/community/community-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-postsubmits.yaml
- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Adding the github credential preset for prowjobs in:
- cluster-network-addons-operator
- community
- containerized-data-importer
- csi-driver
This also includes an update to the GIT_ASKPASS environment variable to use the absolute path.
Issue #1730
> Add the github credentials preset for a selection of prowjobs

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Add a Prow job that runs a medium-scale density scaling performance test once a day by creating 200, 400, up to 600 VMIs in the performance cluster.
The results of this work will be used as the baseline performance of KubeVirt to evaluate a possible performance regression.
Also, I updated the density test to use golang images as the kubevirt build was failing because the bootstrap images don't have go.
This PR depends on kubevirt/kubevirt/pull/7060
/cc @fgimenez @rmohr @davidvossel @rthallisey
> add density scaling performance test, ranging from 200, 400, and 600 VMis

- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Job failing with file not found error when using /go/src/github.com/kubevirt/project-infra/hack/git-askpass.sh
eg. https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirtci-cluster-patchversion-updater/1489279885993054208
> Change GIT_ASKPASS env variable back to using the relative path

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Ensure that we have optional 1.21, 1.22 and 1.23 lanes for migrations. Still optional. The KUBEVIRT_E2E_FOCUS is removed. The filtering will be done in https://github.com/kubevirt/kubevirt/pull/7165.
Needed as preparation for: https://github.com/kubevirt/kubevirt/pull/7165.
> Move migration tests to a separate lane

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Add a preset for github credentials to kubevirt  presubmit, postsubmit and periodic jobs.
Issue: #1730
> Add github credentials preset for kubevirt prowjobs

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The storage backend is set in the kubevirt script if needed.
Depends on https://github.com/kubevirt/kubevirt/pull/7165
> Make migration tests required and remove setting the storage backend

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
The [periodic-kubevirtci-bump-cdi job](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirtci-bump-cdi/1491222982280876032) fails as the GIT_ASKPASS set in preset-github-credentials is not present.
The pr-creator container image is built with the GIT_ASKPASS environment variable set to /usr/local/bin/git-askpass.sh and the preset overwrites this.
https://github.com/kubevirt/project-infra/blob/b412c95c1dc971a4c1882f3eac4fa610ac3a1a8e/images/pr-creator/Dockerfile#L27
/cc @dhiller 
> Reset custom GIT_ASKPASS path in bump-cdi job after overwrite from preset

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Setting the GITHUB_TOKEN env variable as part of the github credentials preset caused issues in some jobs.
Removing GITHUB_TOKEN from the preset and adding it back to the pull-project-infra-prow-deploy-test job definition.
> Remove GITHUB_TOKEN from github preset due to issues in some jobs

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Fix for the spelling error was merged so moving the check-testgrid-config job back to being required.
> Make check-testgrid-config job required again

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
In order to prepare for removing the providers with https://github.com/kubevirt/kubevirtci/pull/747
we make those jobs optional.
> Make 1.20 check-provision jobs optional for kubevirtci

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Substitute 1.10.1 with 1.13, as we're not using 1.10.1 anywhere anyway.
> Sync version Istioctl version 1.13

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Add `kind-1.23-vgpu` lane that will replace `kind-1.19-vgpu` in future
/cc @dhiller
> Add kind-1.23-vgpu lane

- github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-periodics.yaml
The preset was added to all relevant prowjobs in the following
components:
- cluster-network-addons-operator
- containerized-data-importer
- csi-driver
- hyperconverged-cluster-operator
The preset helps to reduce some duplication in prowjob definitions
Issue: #1899
/cc @dhiller 
> Add preset for GCS credentials to subset of prowjobs

- github/ci/prow-deploy/files/orgs.yaml
Since Brian is part of the CI team, he needs access to things like
webhook configurations.
Furter make Federico a normal member since he left the CI team.
> Make Brian an owner of the kubevirt org

- github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml
The publish job push to quay.io latest but latest has to point only to code at
main branch. This change disable publish at release branches.
> knmstate: Call publish only on main

- github/ci/prow-deploy/files/jobs/kubevirt/kubectl-virt-plugin/kubectl-virt-plugin-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubectl-virt-plugin/kubectl-virt-plugin-presubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/libguestfs-appliance/libguestfs-appliance-periodics.yaml
The preset is added to the prowjobs under:
- kubevirt
- kubevirtci
- libguestfs-appliance
This preset allows for a reduction in duplication in the prowjob
definitions
Unused gcs volumes are also removed from the prowjobs in
kubectl-virt-plugin
Fixes https://github.com/kubevirt/project-infra/issues/1899
/cc @dhiller 
> Add preset for GCS credentials to remaining prowjobs

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
In order to collect stability data of the lane, make it always run and optional
1.23 lane jobs can be viewed here:
[https://prow.ci.kubevirt.io/?repo=kubevirt%2Fkubevirt&job=*-kind-1.23-vgpu](https://prow.ci.kubevirt.io/?repo=kubevirt%2Fkubevirt&job=*-kind-1.23-vgpu)
/cc @dhiller
> Make kind-1.23-vgpu lane run always

- github/ci/services/loki/manifests/common/loki.yaml
The default resource limits were too small for a large cluster which
causes the loki pod to restart
Increasing the resource limits to match what is used for prometheus
/cc @dhiller 
> Increase resource requests and limits for the Loki service

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
remove the optional flag so the lane will always run upon
monitoring code change. Also make the report visible since
not all the contributors are familiar with the Prow dashboard.
> [kubevirt-presubmits]: update the sig-monitoring job configuration

- github/ci/prow-deploy/files/jobs/kubevirt/qe-tools/qe-tools-presubmits.yaml
In order to use gingko 2.0 on qe-tools
we need go 1.16
> qe-tools: Update to go 1.16

- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner/hostpath-provisioner-presubmits.yaml
- HPP ceph lane is now mandatory (tested)
- CDI NFS lane will now deploy and test everything on NFS CSI
> Enable NFS CSI/make HPP lane mandatory

- github/ci/services/loki/secrets/production-control-plane/loki-config/loki.yaml
Enabling a two week [retention period](https://grafana.com/docs/loki/latest/operations/storage/table-manager/#retention) on the Loki Table Manager will help control the amount of storage used.
/cc @dhiller 
> Enable two week retention period for loki table manager

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
A spell check error in the kubernetes/test-infra repo is causing the check-testgrid-config job to fail constantly leading to blocked pull requests. Moving the check-testgrid-config job to optional until this spell check error is fixed.
An example of the failure:
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/1948/pull-project-infra-check-testgrid-config/1500931020109647872
/cc @dhiller
> Make check-testgrid-config not required due to spell check failure

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
We reconfigure the whole GPU when executing vgpu jobs. During that time
no other vgpu job should get scheduled to the node, so that they are not
in the way of each other.
Add a pod anti affinity which ensures that pods labeled with `vgpu:
true` are not scheduled on the same nodes at the same time.
> Ensure that vgpu jobs are not scheduled to the same nodes

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
We add a lane for running KubeVirt tests in a k8s cluster with swap enabled. This lane is currently not reporting and can only be run manually.
See kubevirt/kubevirt#7171
/cc @Barakmor1 @brianmcarey @jean-edouard
> Add kubevirt lane for k8s with swap enabled

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Single stack IPv6 support was added to kubevirt (https://github.com/kubevirt/kubevirt/pull/7158).
This PR changes the single stack IPv6 lane to be mandatory.
> Change kubevirt-e2e-k8s-1.22-ipv6-sig-network to be mandatory

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.49.yaml
Align the release-0.49 config with the main one.
- Update 1.20 lanes with 1.23.
- Update kind-1.19-vgpu lane with kind-1.23-vgpu
- Adding *-sig-compute-migrations lanes
These are necessary to backport the update of poddisruption budget api from v1beta1 to v1
Signed-off-by: fossedihelm <ffossemo@redhat.com>
> Update kubevirt-presubmits-0.49 config to 1.23

- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
- github/ci/prow-deploy/kustom/base/manifests/local/branch-protector.yaml
- github/ci/prow-deploy/kustom/base/manifests/local/cherrypicker_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/local/label-sync-kubevirt.yaml
- github/ci/prow-deploy/kustom/base/manifests/local/label-sync-nmstate.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/crier_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/deck_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/ghproxy.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/hook_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/horologium_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/needs-rebase_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/prow_controller_manager_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/prowjob-crd/prowjob_customresourcedefinition.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/sinker_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/statusreconciler_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/tide_deployment.yaml
- github/ci/prow-deploy/kustom/overlays/ibmcloud-production/kustomization.yaml
- github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/prow-exporter-deployment.yaml
- github/ci/prow-deploy/molecule/default/prepare.yml
This secret has been added to the deployment specs for prow services
such as sinker as part of the prow bump. The pods remain in pending state when this secret is not
in place.
See #1768
/cc @dhiller
> Add new secret to allow prow pods to start

- github/ci/prow-deploy/tasks/secrets.yml
The kubeconfig-build-test-infra-trusted secret was introduced in #1944 but was not included for higher environments which caused post-deploy tasks to fail. 
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/post-project-infra-prow-control-plane-deployment/1505851124660310016#1:build-log.txt%3A177
/cc @dhiller 
> Create kubeconfig-build-test-infra-trusted for higher environments

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.49.yaml
Since https://github.com/kubevirt/kubevirt/pull/6042 is not present in release 0.49, mark pull-kubevirt-e2e-k8s-1.23-sig-compute-cgroupsv2-0.49 as `always_run: false`
/cc @dhiller 
Signed-off-by: fossedihelm <ffossemo@redhat.com>
> Don't run cgroup v2 storage job

- github/ci/services/loki/manifests/common/loki.yaml
- github/ci/services/loki/manifests/common/rules.yaml
- github/ci/services/loki/secrets/production-control-plane/loki-config/loki.yaml
- github/ci/services/loki/secrets/testing/loki-config/loki.yaml
The loki alerting rules are provided as a configmap which is included in
the loki deployment and mounted under the ruler storage.
The loki configuration is updated to include ruler storage and the
alertmanager_url
See the [loki docs](https://grafana.com/docs/loki/latest/rules/) for more information on ruler configuration
This change also includes a couple of simple alert rules for grafana and ci-search
/cc @dhiller 
> Enable loki alerting rules and push them to alertmanager

- github/ci/services/prometheus-stack/manifests/stack/production-control-plane/grafana.yaml
Grafana version 8.4 provides an improved view of alerts from both
prometheus and loki
/cc @dhiller 
> Upgrade Grafana to version 8.4

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.49.yaml
In https://github.com/kubevirt/project-infra/pull/1970 has been disabled the wrong lane. Re-enable pull-kubevirt-e2e-k8s-1.23-sig-compute-cgroupsv2-0.49 and disable pull-kubevirt-e2e-k8s-1.23-sig-storage-cgroupsv2-0.49
Signed-off-by: fossedihelm <ffossemo@redhat.com>
/cc @dhiller
> Fix wrong lane disabled in release 0.49

- github/ci/services/prometheus-stack/manifests/stack/production-control-plane/grafana.yaml
Updating the grafana deployment using the RollingUpdate strategy fails due to being unable to claim a mount from existing pod
The [Recreate strategy](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#recreate-deployment) will remove the old pod before creating the updated pod.
/cc @dhiller 
> Use recreate strategy for Grafana deployment update

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.50.yaml
Release 0.50 does not contain single stack IPv6 support that was added to kubevirt here https://github.com/kubevirt/kubevirt/pull/7158
Signed-off-by: fossedihelm <ffossemo@redhat.com>
/cc @dhiller
> [release 0.50]Remove ipv6 lane as required

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
This new lane doesn't automatically run and is optional, for now.
It doesn't specify a sig to just run everything.
It uses a single node with a single replica of virt-api and virt-controller, which is a particular setup not currently tested by any lane.
I requested "only" 15GiB of memory since there's only one node, but maybe that's wrong?
> Add single-node single-replica lane

- github/ci/prow-deploy/files/jobs/kubevirt/cloud-provider-kubevirt/cloud-provider-kubevirt-presubmits.yaml
Add the presubmits file, currently include unit tests target job
> cloud-provider-kubevirt: Add presubmits file

- github/ci/services/loki/manifests/common/rules.yaml
The [alertmanager configuration](https://github.com/kubevirt/project-infra/blob/main/github/ci/services/prometheus-stack/manifests/stack/common/alertmanager-config.yaml#L58) expects a description field to pass
alerts to slack. Updating the loki alerts to have a description annotation.
/cc @dhiller 
> Use description instead of summary annotation for loki alerts

- github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Old format is deprecated and produces warnings.
See https://github.com/kubernetes/test-infra/issues/20631#issuecomment-787693609
Requires update of configcheck image: #1991
> Migrate plugin config to new format

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
We don't support 1.19 anymore with the main branch.
> Update nonroot vgpu lane to 1.23

- github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
Needed for https://github.com/kubevirt/containerdisks/pull/18
> Bump containerdisks repo to golang 1.17

- github/ci/prow-deploy/tasks/deploy.yml
- github/ci/prow-deploy/vars/ibmcloud-production/main.yml
- github/ci/prow-deploy/vars/kubevirtci-testing/secrets.yml
- github/ci/prow-deploy/vars/workloads-production/main.yml
After the deployment has happened we scale down and up again to avoid the number duplication as described in kubernetes/test-infra#25768
> Add rescaling of pushgateway deployment

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.51.yaml
Release 0.51 does not contain single stack IPv6 support that was added to
kubevirt here kubevirt/kubevirt#7158
> [Release 0.51] IPv6 lane shouldn't be required and should be optional

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
There are only 2 nodes that can run SR-IOV jobs, each at the moment
can only run a single job at a time.
Running the nonroot jobs for pre-submit is overloading what seems to be
a not yet stable CI workload.
This reverts commit eb4115da872dcdff53ad5d87bbb322990164e84f.
> Revert "Make nonroot network lane required (#1900)"

- images/bootstrap/Dockerfile
CDI uses `docker build` to build a builder, and it uses this builder
to do other builds.
Having an aarch64 builder will allow us to do native aarch64 builds,
and for that we need a fancier `docker build` like buildah (or buildx).
qemu-user-static allows us to execute non-native (e.g. aarch64)
binaries.
Part of tackling https://github.com/kubevirt/containerized-data-importer/issues/2211
> Add packages to bootstrap (to build multi-arch containers)

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
- github/ci/prow-deploy/kustom/overlays/workloads-production/kustomization.yaml
- github/ci/prow-deploy/kustom/overlays/workloads-production/resources/priority-classes.yaml
This will make the scheduler prefer sriov and vgpu jobs. But it will not
preempt them above others.
> Add priority classes for the sriov and vgpu jobs

- github/ci/prow-deploy/files/jobs/kubevirt/cloud-provider-kubevirt/cloud-provider-kubevirt-presubmits.yaml
Change Golang version to 1.17 in "pull-cloud-provider-kubevirt-unit-tests" container
> cloud-provider-kubevirt: Change Presubmit Golang version to 1.17

- github/ci/services/prometheus-stack/manifests/stack/production-control-plane/grafana.yaml
https://grafana.ci.kubevirt.io/d/acSjBD17z/prow-job-load?orgId=1&from=now-3h&to=now&var-job_name=.*&refresh=1m
/cc @EdDev @brianmcarey
> Add job_name filter to prow job load dashboard

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
To be able to build the alpine image /lib/modules and /dev need to be
mounted.
> kubevirtci, publish: Mount modules and devs

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The single-replica lane is not bound to a sig, so it needs a storage backend to run sig-storage tests.
> Add ceph to single replica lane

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
The pull-project-infra-check-testgrid-config has been failing constantly
due to an issue in the test-infra repo. An issue has been raised in the
kubernetes/test-infra repo.
The job was already marked as optional. This change stops reporting the
failures.
/cc @dhiller 
> Skip reporting on pull-project-infra-check-testgrid-config due to failures

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Adding `KUBEVIRT_STORAGE="rook-ceph-default"` actually focuses the whole lane on `storage-req` tests...
Specifying a focus of "all tests" works around that.
> single-node lane: add a "focus all" option to avoid storage-req auto-focus

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.52.yaml
Manual run of
```
config-forker -job-config .../project-infra/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml \
-output .../project-infra/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.52.yaml \
-version 0.52
```
to add configs for kubevirt/kubevirt release-0.52 branch.
/cc @enp0s3 @brianmcarey
> Fork kubevirt prow job configs for release-0.52

- github/ci/prow-deploy/files/orgs.yaml
@opokornyy
* @ksimon1 
* @0xFelix 
* https://github.com/kubevirt/tekton-tasks-operator/pull/13
* https://github.com/kubevirt/ssp-operator/pull/327
* https://github.com/kubevirt/ssp-operator/pull/328
* https://github.com/kubevirt/ssp-operator/pull/336
* https://github.com/kubevirt/common-templates/pull/431
> Add opokornyy to the org

- images/kubevirt-infra-bootstrap/Dockerfile
add podman to kubevirt-infra-bootstrap image
update base kubevirtci/bootstrap image to latest.
Update all commands to to dnf, because kubevirtci/bootstrap uses fedora 34.
In common-templates repo we changed docker command to podman https://github.com/kubevirt/common-templates/pull/431
Signed-off-by: Karel Šimon <ksimon@redhat.com>
> add podman to kubevirt-infra-bootstrap image

- github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
Run a minimal containerdisk pipeline check based on https://github.com/kubevirt/containerdisks/blob/main/pipeline.sh which will verify cirros as example workload.
> [containerdisks] Add a pipeline test presubmit job

- github/ci/services/loki/manifests/common/rules.yaml
Alertmanager is matching on the namespace label for the slack receiver
/cc @dhiller 
> Add namespace label to loki alerts

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
I think this is the missing part. We already have the inventory inside the secrets (look for `.prowWorkloads.hostsYml`). Also the key is extracted in the shellscript that this job points to.
Note: the inventory may be outdated, we should discuss next week on how to proceed.
> Fix path to bootstrap script for prow-workloads cluster

- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
We previously removed goproxy.io due to 500 errors IIRC, here we reinstate it again.
> Reinstate goproxy.io

- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Instead of each lane setting the kubernetes version, use the new scripts
that set the version. This way each lane doesn't have to be updated in
project-infra each time we want to update kubernetes version.
> Enable CDI lane scripts

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
- github/ci/testgrid/hack/check.sh
Bazel rules are no longer relevant in kubernetes/test-infra. This causes
failures in the check-testgrid-config tests due to bazel builds failing. eg. https://github.com/kubernetes/test-infra/issues/25938
This change is to run the check-testgrid-config tests using go instead of bazel.
/cc @dhiller 
> Use go to run check-testgrid-config tests

- github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-periodics.yaml
Move the containerdisk push job to the bare metal cluster and give it more memory to be able to run the cluster for verification. Finally point the job to the new pipeline script.
Requires https://github.com/kubevirt/containerdisks/pull/25 to be merged.
> Verify containerdisks before pushing

- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
- github/ci/prow-deploy/kustom/overlays/workloads-production/kustomization.yaml
- github/ci/prow-deploy/templates/quay_credentials.j2
To directly talk to the quay api an oauth token needs to be used. This token can be used for interacting with the containerdisks repo to push docs there.
> Add quay oauth token to the quay credentials secret

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
To build alpine now we are using virt-install for that the job needs
libvirt and mkisofs.
> kubevirtci: Install libvirt + genisoimage

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.52.yaml
using config-updater manually doesn't seem to work, so we try to
re-update it by adding a commit.
This is while investigating https://github.com/kubevirt/kubevirt/pull/7609
> Force change for job definitions on release-0.52

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
The build for configurator fails with go version 1.16
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/2049/pull-project-infra-check-testgrid-config/1518868129835388928
test-infra was updated to use go version 1.18
https://github.com/kubernetes/test-infra/commit/52e11cab1ea80f71e7af5f69573ffbb17b234cca
> Use go version 1.18 for check testgrid config

- github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
- github/ci/prow-deploy/kustom/base/manifests/local/branch-protector.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/crier_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/deck_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/hook_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/horologium_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/prow_controller_manager_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/sinker_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/statusreconciler_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/tide_deployment.yaml
- github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/ci-usage-exporter-deployment.yaml
- github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/prow-exporter-deployment.yaml
- github/ci/prow-deploy/kustom/overlays/kubevirtci-testing/resources/bootstrap.yaml
This is a quick interim solution to fix the 0.52 jobconfig, we still
need to provide a proper generation of configmaps per repo later on.
See here for motivation of the change: https://github.com/kubevirt/kubevirt/pull/7609
> Shard the job configs into configmaps per org

- github/ci/prow-deploy/tasks/deploy.yml
The config-bootstrapper creates required configmaps that
several deployments rely on. post deployment fails on this here:
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/post-project-infra-prow-control-plane-deployment/1519611136603852800#1:build-log.txt%3A183
> Move config bootstrapping before deployment

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The job has been failing for a few days now [1], timing out and then
failing to dump logs. The latter is being looked into by issue #7170,
this change simply increases the timeout to hopefully allow the job to
complete before ever running this logic.
[1] https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.21-sig-performance
Signed-off-by: Lee Yarwood <lyarwood@redhat.com>
> sig-performance: Increase timeout to 1h30m0s

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
https://github.com/kubevirt/kubevirt/issues/7658 identified that the sig-performance job was timing out due to ~12 VMIs becoming unschedulable due to memory pressure in the test environment. 
This PR simply increases the available k8s/KubeVirt memory in the env by ~4G to allow these final 12 VMIs to launch. A previous increase to the overall job timeout is also removed as this shouldn't be required anymore with the job typically completing in around ~30 mins prior to this issue.
> sig-performance: Increase KUBEVIRT_MEMORY_SIZE to 10G

- github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits.yaml
Add job for kubernetes-nmstate upgrade lane.
It's not required at the beginning, we can make it required later when we see it's stable.
> knmstate: add e2e upgrade lane

- github/ci/prow-deploy/tasks/deploy.yml
The [config-bootstrapper](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/config-bootstrapper) requires that relative pathes used in the
configs (i.e. plugins.yaml) MUST NOT be part of the --source-path
attribute. The [filter logic](https://github.com/kubernetes/test-infra/blob/64ee58efac4ff2dbbefefc1f9cb668748101836f/prow/plugins/updateconfig/updateconfig.go#L217-L234) otherwise throws the changes away as it
can't match them.
> Fix config-bootstrapper call

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The perf periodic job needs more memory.  Also, make the presubmit job the same memory.
fixes: https://github.com/kubevirt/kubevirt/issues/7658
> Increase periodic performance jobs mem

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
From pod monitoring, it can seen that the check-provision-k8s-* jobs use
around 12.5Gi of memory which is over the requested 8Gi. Increasing the
request to 14Gi better reflects the actual memory required.
Example check-provision-k8s-1.22:
https://grafana.ci.kubevirt.io/d/GlXkUBGiz/kubernetes-pod-overview?orgId=1&var-namespace=kubevirt-prow-jobs&var-pod=c293a885-cc95-11ec-a5bc-c24a5dc64b9c&var-container=All&var-cluster=prow-workloads&from=1651769476297&to=1651776098371
/cc @dhiller 
> Increase memory request to 14Gi for kubevirtci presubmits

- hack/mkpj.sh
When the mkpj.sh script is run and the docker daemon is not running it fails. If podman is installed, I would prefer it to use podman as it doesn't require a running daemon.
```
./hack/mkpj.sh
Using default tag: latest 
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running? 
```
/cc @dhiller 
> Use podman for mkpj.sh script if installed

- robots/cmd/flake-report-creator/cmd/jenkins.go
To avoid problems with javascript when a Content Security Policy is active we use css for popups instead.
/cc @rmohr @brianmcarey @lukas-bednar
> flake-report-creator jenkins: Use css for popup

- Makefile
- WORKSPACE
- go.mod
- go.sum
- go_third_party.bzl
- robots/cmd/flake-report-creator/cmd/BUILD.bazel
- robots/cmd/flake-report-creator/cmd/jenkins.go
We were seeing two things:
1. get latest build returned a build struct with `0` as number for latest build
2. get build failed with 504, which failed the whole process
Issue 1 was fixed by removing the call to GetLatestBuild, and using the build number that was already present in the `job.Raw.LastBuild.Number`.
Issue 2 was fixed by using a retry for the GetBuild step in case a 504 was issued.
/cc @lukas-bednar
> flakefinder: fix timeouts for jenkins build retrieval

- github/ci/prow-deploy/tasks/deploy.yml
- github/ci/prow-deploy/vars/kubevirtci-testing/secrets.yml
- github/ci/prow-deploy/vars/workloads-production/main.yml
Ansible role was updated to delete the prirority classes prior
to the launch of the deployment itself. This is because updating
the priority class that is in use will fail, thus its requried
to re-create it.
**Discalimer**
* Trivial approach (no usage of `yq`)
* Currently w/o testing via Molecule. 
> prow-deploy: delete priority classes before re-deployment

- github/ci/prow-deploy/vars/ibmcloud-production/main.yml
As was seen in the [error](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/post-project-infra-prow-control-plane-deployment/1524310295969796096#1:build-log.txt%3A188) log from postsubmit, the priority class deletion variable should be defined in all the ansible roles.
> prow-deploy: fix missing ansbile variable for deployment

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
- hack/mirror-crio.sh
An issue with the latest release of cri-o caused failures in kubevirtci
presubmits. Using the previous minor releases avoided these failures.
This change adds the previous cri-o minor releases to the kubevirtci
mirror
See https://github.com/kubevirt/kubevirtci/pull/796 for more details
> Add mirror for previous minor release of cri-o

- github/ci/prow-deploy/kustom/overlays/workloads-production/resources/place-holder.yaml
- github/ci/prow-deploy/kustom/overlays/workloads-production/resources/priority-classes.yaml
CI SR-IOV nodes are running both SR-IOV job and regular jobs.
SR-IOV jobs have a higher priority class, which isn't preemptive.
Therefore a new SR-IOV might need to wait until a regular job finishes.
This PR introduces a DaemonSet that will spin a pod, 
that reserves the resources needed for SR-IOV job.
Once a SR-IOV job is scheduled it will preempt the place holder, and run until completed.
Once it is done, the place holder will be rescheduled, saving again the resources.
This way SR-IOV jobs won't need to wait and a dedicate place holder pod will wait for them.
Since the place holder requests the same resources that the real SR-IOV job needs and has
a higher priority than regular jobs, it will not let other pods replace it, nor take those resources.
The place holder pods have anti …
> sriov: Introduce place holder DaemonSet

- github/ci/prow-deploy/kustom/overlays/workloads-production/kustomization.yaml
This PR should add the missing part for #2068, that the new place-holder DS wasn't treated by Kustomize.
> prow-deploy: add the place-holder daemonset to kustomize list

- github/ci/prow-deploy/kustom/overlays/workloads-production/resources/place-holder.yaml
- github/ci/prow-deploy/tasks/deploy.yml
Without the namespace, the anti affinity
doesn't make sure that only either
sriov or place-holder are running.
Add sriov-place-holder PC to the delete command
so when we are redeploying it will clean the previous PCs as needed.
> sriov: Add namespace to the place holder ds

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Since we have now sriov place holder,
the jobs of kubevirtci sriov should have
pc of sriov, so they can preempt the place holder,
and run instead.
Related to https://github.com/kubevirt/project-infra/pull/2068
> kubevirtci, sriov: Add missing pc

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Since we have now sriov place holder,
the jobs of sriov should have
pc of sriov, so they can preempt the place holder,
and run instead.
Remove trailing spaces.
> periodic, sriov: Add missing pc

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.34.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.36.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.37.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.38.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.39.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.40.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.41.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.42.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.43.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.44.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.45.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.46.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.47.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.48.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.49.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.50.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.51.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.52.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.53.yaml
Remote cache eviction happens too often, and since the garbage collector
is unaware of the Bazel build graph, it will delete the stale items in
a LRU manner w/o taking care about them being intermediate artifacts.
Therefore the lanes tend to fail and until the cache wipe won't
happen the job won't work.
As a short-term solution we would like to reduce the load on the
Bazel greenhouse cache deployment, thus disable its usage for the
release branches CI lanes.
> prow-deploy: disable usage of remote caching for release configs

- images/bootstrap/Dockerfile
Fedora 36 has been released so the bootstrap image should be updated.
As F36 comes with git version 2.36.1 which has strict rules around
directory ownership of git repos[1], an update to the git config to trust
repos was required. This was an issue when testing e2e jobs with phaino.
[1] https://git-scm.com/docs/git-config/2.35.2#Documentation/git-config.txt-safedirectory
/cc @dhiller 
> Update bootstrap image to Fedora 36

- github/ci/prow-deploy/files/jobs/kubevirt/secrets/secrets-presubmits.yaml
- github/ci/prow-deploy/kustom/overlays/ibmcloud-production/kustomization.yaml
- github/ci/prow-deploy/kustom/overlays/workloads-production/kustomization.yaml
- github/ci/prow-deploy/tasks/secrets.yml
- github/ci/prow-deploy/vars/kubevirtci-testing/secrets.yml
In order to access private repositories with prow we need to use an SSH
key as described here:
https://github.com/kubernetes/test-infra/blob/cab76bdbd3760143a7b45dc35cf0b4d8d43b6c77/prow/pod-utilities.md#how-to-configure
> Add ssh secret to access private repos with prow

- OWNERS_ALIASES
For kubot to work the file needs to get updated. See here:
https://github.com/kubevirt/project-infra/blob/fa9cac36250effd1709fb8790caa1b173e5bdf67/images/kubot/worker.coffee#L60-L59
/cc @brianmcarey @enp0s3 
Example: https://coreos.slack.com/archives/C01EX3K1FGE/p1652691592281729
> Update ci-maintainers for kubot

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
The previous minor releases were added to the mirror due to an issue
with the latest cri-o release. The previous minor releases have been rebuilt
and now has the same issue.
The previous minor releases were introduced here https://github.com/kubevirt/project-infra/pull/2086 but are no longer needed.
/cc @dhiller 
> Remove previous minor release of cri-o from mirror job

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.52.yaml
Since we have now sriov place holder,
the jobs of sriov should have
pc of sriov, so they can preempt the place holder,
and run instead.
Out of the releases, only 0.52 missed it,
so this PR add it manually.
> release-0.52, sriov: Add missing pc (#2096)

- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Using branch protection for private repos is a pro feature,
thus we can not use it.
/cc @brianmcarey @enp0s3
> Remove branch protection for secrets

- github/ci/services/loki/manifests/common/rules.yaml
The previous message was not clear on which application was experiencing
high levels of errors in the logs.
> Improve alert message for high percentage of errors in Grafana

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Prow jobs should use the default Go version from the kubevirtci golang
image where possible.
https://github.com/kubevirt/project-infra/blob/26ca49f8e110861cdd4aacb501e51e0e9f7ff869/images/golang/Dockerfile#L3
A successful test run of [periodic-kubevirt-e2e-k8s-1.22-sriov](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.22-sriov/1527234012848852992) was carried out using `GIMME_GO_VERSION=1.15.8`
/cc @dhiller @EdDev @oshoval 
> Remove GIMME_GO_VERSION from kind prow jobs

- hack/update-jobs-with-latest-image.sh
A valid tag is a tag that is matching our schema of
`v<reverse-date>-<short-git-sha>`.
> Narrow down image bump to only use images with valid tag

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
The 1.24 version of cri-o will be required to be present in the
kubevirtci mirror to allow for testing with the 1.24 kubernetes cluster
provider.
> Add cri-o version 1.24 to periodic mirror job for 1.24 provider

- github/ci/prow-deploy/kustom/base/manifests/local/prow-debug-rbac.yaml
- hack/generate-prow-debug-kubeconfig.sh
Creates a new serviceaccount `prow-deploy` that has readonly access prowjobs and pods. Based on that serviceaccount the script creates a new secret that is attached to the serviceaccount and can be used as a login token for `prow-deploy`. The script then generates a KUBECONFIG file with the token data of the generated secret that can be used as usual.
/cc @xpivarc @brianmcarey
> Add prow debug serviceaccount and KUBECONFIG generation script

- github/ci/prow-deploy/files/orgs.yaml
Signed-off-by: Geetika Kapoor <gkapoor@redhat.com>
@geetikakay
*@ksimon1
*@0xFelix
https://github.com/kubevirt/ssp-operator/pull/363
> Add geetikakay to the org

- github/ci/services/loki/manifests/common/rules.yaml
The alert triggers when there is a high rate of failed writes occurring
in the logs of the ci-search pods. This can occur when the persistent
volume is full but it can also occur in other scenarios.
This updates the description to better reflect the error that is occurring.
> Update ci search alert description to better reflect error

- images/bootstrap/runner.sh
If the bootstrap container fails to start the docker daemon,
currently prow jobs that require the docker daemon will continue. This
makes it difficult to identify the cause of the failure in the job. The
script should exit if it fails to start the docker daemon.
> Update runner.sh to exit when docker daemon fails to start

- github/ci/prow-deploy/files/jobs/kubevirt/bridge-marker/bridge-marker-presubmits-0.9.1.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/bridge-marker/bridge-marker-presubmits.yaml
New stable branch was created. This time it is awkwardly on a patch release due to breakage in Go version dependency introduced in 0.9.2.
> Register bridge-marker 0.9.1 to CI

- github/ci/prow-deploy/files/jobs/kubevirt/community/community-postsubmits.yaml
Failing job: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/postsubmit-community-update-kubevirt-devstats-repo-sql/1531670941363343360
Successful run using fix: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/postsubmit-community-update-kubevirt-devstats-repo-sql/1532320183941599232
> Fix: override GIT_ASKPASS to make the job work again

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
This PR adds lane to kubevirt project with a purpose to run checks
that ensures the introduced code change is aligned with kubevirt clean
code standards.
The lane executes `make lint`.
NOTE: I'm not sure we need all the labels, I have "forked" the job properties
from existing netowork-sig job.
> kubevirt: add lane used for running clean code checks

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
The `check-provision-k8s-1.24` should be required and should always run
when the kubernetes 1.24 provider becomes available in kubevirtci.
This change also moves the `check-provision-k8s-1.21 prow` job to optional in
preparation for phasing out the 1.21 provider.
/hold 
Hold can be removed once https://github.com/kubevirt/kubevirtci/pull/800 is merged.
> Set check-provision-k8s-1.24 to required to test new provider

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Add k8s-1.24-ipv6 lane
Depends on https://github.com/kubevirt/kubevirtci/pull/808
> k8s-1.24-ipv6: Add provision lane

- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
[This](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/2119/pull-project-infra-prow-deploy-test/1535142515663966208#1:build-log.txt%3A1580) should be expanded, so we add an expression for it.
> Add ansible output highlighting

- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
The [previous one](https://github.com/kubevirt/project-infra/pull/2154) was causing deck to not load. This could be reproduced
by removing the entry from the `highlight_regexes:` part of the
kubevirt-prow config configmap and rescaling the deck deployment.
> Fix highlight expression

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The lint job runs kubevirt `lint` target (`make lint`) which uses the
dockerized wrapper.
In order to run the docker service, there is a need for privileged
access.
> kubevirt/presubmits/lint: Add privileged security context

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Add periodic jobs for:
`kubevirt-e2e-k8s-1.23-sig-storage-cgroupsv2`
`kubevirt-e2e-k8s-1.23-sig-compute-cgroupsv2`
Since we now have periodic for this jobs,
no need to run it on each PR, run it only if
the relevant folder is changed.
It will save CI resources.
> cgroupsv2: Add periodics and run_if_changed

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.50.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.51.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.52.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.53.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
- github/ci/prow-deploy/kustom/overlays/workloads-production/resources/priority-classes.yaml
- github/ci/prow-deploy/tasks/deploy.yml
Currently there is only a maximum of 1 windows e2e job allowed run at a
time.
This can lead to build up of windows job queues.
Due the restriction of the 1 job at a time - there should always be one
job running if there is a queue. This is not the case at the moment as
other regualar e2e jobs can get scheduled ahead of them.
Adding a priority class for the windows jobs should ensure that there is
always one job running when there is a queue
/cc @dhiller @enp0s3 @EdDev 
> Add priority class for windows e2e jobs

- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
- github/ci/prow-deploy/kustom/base/manifests/local/branch-protector.yaml
- github/ci/prow-deploy/kustom/base/manifests/local/cherrypicker_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/local/label-sync-kubevirt.yaml
- github/ci/prow-deploy/kustom/base/manifests/local/label-sync-nmstate.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/crier_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/deck_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/ghproxy.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/hook_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/horologium_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/needs-rebase_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/prow_controller_manager_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/sinker_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/statusreconciler_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/tide_deployment.yaml
- github/ci/prow-deploy/kustom/overlays/ibmcloud-production/kustomization.yaml
- github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/prow-exporter-deployment.yaml
- github/ci/prow-deploy/molecule/default/prepare.yml
- github/ci/prow-deploy/tasks/secrets.yml
A new kubeconfig secret was added to the upstream test-infra prow
deployment definitions. The kubevirt prow services will fail to deploy
without this secret.
These changes are applied on top of the changes from - https://github.com/kubevirt/project-infra/pull/2119/
Fixes #2120 
/cc @dhiller 
> Add new kubeconfig secret required to deploy prow services 

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Since cgroups jobs are conditional,
they have implicit `optional: true` added.
Once they run they run as non required.
Make them required by setting `optional: false`.
One of the jobs had even an explicit optional field that was updated.
Add also skip_report: false, to be explicit.
> cgroups: Make lanes non optional

- robots/pkg/flakefinder/report_data.go
- robots/pkg/flakefinder/report_data_test.go
Counting the occurrences a test failed will cause tests with lower number of failures but same number of appearances to appear before tests that have higher number of failures.
Also using the ratio of #tests_failed / #tests_succeeded as a factor emphasizes tests with less failures but a high ratio far more than tests with higher number of tests.
As we want to emphasize tests that have higher failure numbers over those that have less failures, we tabularize the severity as a factor according to the relation of `#tests_failed / #tests_succeeded` .
We then multiply that value by the number of failures.
Besides that we refactor the tests using a struct to increase readability.
/cc @enp0s3 @xpivarc
> emphasize tests with higher number of failures over those with higher ratio

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
- images/golang/Dockerfile
The kubevirt builder image uses go version 1.17.8[1] - the golang image
used for testing should default to the same.
This change also includes the build of the golang image in the build-bootstrap-image presubmit as it requires a locally built bootstrap image. 
[1] https://github.com/kubevirt/kubevirt/blob/fadd752f0392a320483524aae753fe53930a6ba6/hack/builder/Dockerfile#L7
> Update golang image to use go 1.17.8

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
We need to check [the status page](https://status.coveralls.io/) before we take this back in.
> Disable coveralls reporting due to service outage

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
This reverts commit 8c9213c1f63a72a6b886f102e991c59a17f3eec5 (PR #2175)
Since the job will rebase the bump PR again and again,
it waste CI resources, and even might interrupt jobs that didn't finish yet on the bump PR.
Of course unless there are labes, and then it doesn't rebase, but sometimes it takes time until
we review, or we first want to see the jobs status.
If we had logic that in case of rebase only without actual kubevirtci change, doesn't rebase
it would be safer.
> Revert "kubevirtci kubevirt bump: Increase periodic rate (#2175)"

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Istio version 1.14.0 adds support for Kubernetes version 1.24 [1]
KubeVirt CI is currently using 1.10.0 [2] - this should be updated to 1.14.0
[1] https://istio.io/latest/docs/releases/supported-releases/#support-status-of-istio-releases
[2] https://github.com/kubevirt/kubevirtci/blob/da6af0433636565a75bbcdc39e82c8c38e5d7cab/cluster-provision/k8s/1.23/provision.sh#L21
> Add istio version 1.14.0 to the kubevirtci mirror

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Based on #2184, while setting the 1.24 sig lanes to run always, we also want to set the 1.21 sig lanes to run manually.
/cc @brianmcarey @rmohr
> Require kubevirt presubmits and 1.21 manual trigger

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Since people sometime forget to `make deps-sync`, this lane sometimes fails constantly just because of human-error. Instead, this lane should be required to ensure our dependencies are always synced.
As in [this comment](https://github.com/kubevirt/kubevirt/pull/8062#issuecomment-1176180982), the reason this lane was optional is because of a worry that this lane may be unstable since it requires access to quite some external resources. But since the lane proved itself being stable, it can be required now.
> Make pull-kubevirt-verify-go-mod lane required

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Sometimes we want to refresh kubevirtci bumps at kubevirt manually.
This lane can be used for it.
The lane doesn't check labels of the bump PR if exists, as the periodic
does.
> kubevirt: Add manual lane to bump kubevirtci at kubevirt

- github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-postsubmits.yaml
- github/ci/prow-deploy/files/orgs.yaml
- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Changes the configurations to prepare to switch default branch for kubevirt/csi-driver to main.
/hold to synchronize the change in all places
> Update configs to switch to default branch main

- images/bootstrap/Dockerfile
This is so we can merge the code in https://github.com/kubevirt/hostpath-provisioner/pull/115
(The golang image used by hostpath-provisioner presubmits is based on the bootstrap image)
> Add podman to bootstrap images

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
We use 1.24-ipv6 so the presubmit should be accordingly
> kubevirtci, single stack ipv6: Update presubmit to use 1.24

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Currently kubevirt-bot requests review from around 15 contributors on the
automated bump prow images PR [1]. It should be enough to request review
from the prow-job-taskforce for this PR and good to reduce noise for other
contributors.
[1] https://github.com/kubevirt/project-infra/pull/2213
/cc @kubevirt/prow-job-taskforce
> Update bump prow images job to request review from taskforce

- images/bootstrap/Dockerfile
This reverts commit 139f21be7fc69ee931b2c8e159158215eb528022.
The PRs needing podman specifically were re-written so docker
is supported as well, to aid the proposed plan of gradually
transitioning CI lanes to podman by having a separate
podman-only image.
> Revert "Add podman to bootstrap images (#2196)"

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
In case we run the manual job `pull-kubevirtci-bump-kubevirt` from the bump PR itself
it will update the description with just the new differences
since the previous bump if exists.
Because the changes are already there and it calculate the difference.
In case we run it from a PR of kubevirt that is not related,
It will include in the bump those commits which are not related,
since it checkouts the code of that PR.
Adding reset --hard to kubevirt main in order to avoid those.
> manual bump job: Fix Running job from within kubevirt

- github/ci/prow-deploy/files/jobs/kubernetes-sigs/cluster-api-provider-kubevirt/cluster-api-provider-kubevirt-presubmits.yaml
We are seeing some flakiness in our capk CI job that could be attributed to shared resources. I've also updated the golang version to 1.18 which matches what we are using in our containerized builds and published artifacts of capk.
> Set mem limits and golang version for capk presubmit 

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.54.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.55.yaml
Presubmits for release branches fail due to bazel cache issues.
Similar has been done for previous release versions [1]
[1] https://github.com/kubevirt/project-infra/pull/2092
/cc @enp0s3 @xpivarc 
> Remove bazel-cache from presubmits for releases 0.54 & 0.55

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
- images/bootstrap/Dockerfile
- images/golang/Dockerfile
- images/publish_multiarch_image.sh
build bootstrap image for amd64 and arm64
New Dockerfile for bootstrap has `ARG ARCH` which is not acquired in the build-bootstrap-image test, so the test would always fail.
> build multiarch bootstrap image

- github/ci/prow-deploy/files/orgs.yaml
- add Andrew Burden, remove Chris Callegari
- enable admin of katacoda-scenarios repo (needed to establish demos)
> Updates for KubeVirt community team

- hack/images_to_mirror.csv
Those images are used by kubevirtci and are still on `docker.io`.
Mirror them to quay, so we can use them without rate limits.
Once they are mirrored, we need one time to make the new repos public.
> container images: Mirror needed images to quay

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Signed-off-by: João Vilaça <jvilaca@redhat.com>
Some new monitoring tests in https://github.com/kubevirt/kubevirt/pull/8199 require migrations to be performed. This can only be achieved if the cluster has at least 2 nodes
> Use 2 nodes in pull-kubevirt-e2e-k8s-1.22-sig-monitoring

- hack/images_to_mirror.csv
- hack/mirror-images.sh
Istio is deployed with Istio operator, which can only be configured to use different registry repository
but will always use container image names: pilot, proxyv2, etc.
Therefore the images should not have the "istio-" prefix
this way the istio operator will use `quay.io/kubevirtci/pilot:v1` instead of `docker.io/istio/pilot:v1`
see https://github.com/kubevirt/kubevirtci/pull/851
Additional changes:
According https://github.com/rook/rook/issues/7213
docker.io/rook/ceph doesn't have rate limits.
We are also using its docker.io version, not the quay one.
Removing it from the mirroring list.
> mirror: Update istio images naming so we can use them with istio operator

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
The arm64 build of the bootstrap image fails[1] on the ibm-prow-jobs
cluster as it requires more resources. The job completes successfully
when it is run on the prow-workloads cluster.
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/publish-multiarch-bootstrap-image/1552545593149100032
/cc @zhlhahaha @xpivarc 
> Move multiarch bootstrap jobs to prow-workloads cluster

- github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
It would be nice to start tagging and tracking specific instancetype API
bugs under a single label, this change introduces the label.
> Add area/instancetype label

- github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
The release-blocker plugin is currently in a loop where it endlessly
removes and adds the release-plocker label.
The outcome can be observed at https://github.com/kubevirt/kubevirt/pull/8246.
> Disable the release-blocker plugin until it is fixed

- github/ci/prow-deploy/files/jobs/kubevirt/libguestfs-appliance/libguestfs-appliance-periodics.yaml
Lately, the libguestfs-appliance started failing for limited resource. Let's schedule the job at another time
> change time when the job run

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
- images/bootstrap-legacy/Dockerfile
- images/bootstrap-legacy/README.md
- images/bootstrap-legacy/create_bazel_cache_rcs.sh
- images/bootstrap-legacy/entrypoint.sh
- images/bootstrap-legacy/runner.sh
- images/golang-legacy/Dockerfile
This change creates two new images called bootstrap-legacy and
golang-legacy which are based off of the current bootstrap and golang
images. These images wiil provide projects a fallback option in the case
that the new proposed podman changes[1] cause issues in their CI lanes.
- Copy bootstrap directory to bootstrap-legacy
- Copy golang directory to golang-legacy
- Update golang-legacy Dockerfile to use bootstrap-legacy image as base
- Add presubmit job to test build of legacy images
- Add postsubmit job to publish legacy images to quay
[1] https://github.com/kubevirt/project-infra/pull/2055
/cc @xpivarc @enp0s3 
> Create bootstrap-legacy image for existing docker bootstrap prow jobs

- github/ci/prow-deploy/README.md
- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
- github/ci/prow-deploy/kustom/base/manifests/local/branch-protector.yaml
- github/ci/prow-deploy/kustom/base/manifests/local/cherrypicker_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/local/label-sync-kubevirt.yaml
- github/ci/prow-deploy/kustom/base/manifests/local/label-sync-nmstate.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/crier_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/deck_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/ghproxy.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/hook_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/horologium_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/needs-rebase_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/prow_controller_manager_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/prowjob-crd/prowjob_customresourcedefinition.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/sinker_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/statusreconciler_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/tide_deployment.yaml
- github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/crier_deployment.yaml
- github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/prow-exporter-deployment.yaml
The automated prow bump PR[1] is failing the presubmit deploy test due to the crier pod
failing to start successfully. This change includes the image bumps from that PR and the fix required for a successful deployment. 
Crier was failing to start due to an undefined flag being specified.
Removing the -gcs-workers flag allows crier to start successfully.
```
[root@instance workspace]# kubectl logs -n kubevirt-prow crier-6468d759d6-b5tv5
flag provided but not defined: -gcs-workers
```
Also small update to prow-deploy README to include the correct path to
the kubeconfig.
/cc @kubevirt/prow-job-taskforce 
[1] https://github.com/kubevirt/project-infra/pull/2119
> Remove -gcs-workers flag from crier deployment

- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Allow CDI to run fossa check, not required or automatic
for now, until we can configur the entire setup.
> Added fossa presubmit job for cdi

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
The build of the multiarch bootstrap images is hitting the current
timeout limit of 4 hours [1]. Increasing this to 5 hours to unblock changes
to the image.
An issue[2] has been opened to look at reducing the time that this job requires to complete. This PR does not fix the issue it just unblocks changes to the images. 
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/2055/build-multiarch-bootstrap-image/1559137945284251648
[2] https://github.com/kubevirt/project-infra/issues/2252
/cc @dhiller @xpivarc  @zhlhahaha 
> Update timeout for multiarch bootstrap jobs to 5 hours

- hack/flake-report-creator.sh
- robots/cmd/flake-report-creator/cmd/jenkins.go
- robots/cmd/flakefinder/report_test.go
- robots/pkg/flakefinder/report_data.go
Updates the flake-report-creator to have a new popup showing the failures per build in the upper right corner of the report. Additionally each test popup now has the number of total failures shown in braces for easier orientation.
JSON is also extended to include the failuresForJobs base data, such that it is now a map that has two keys `data` and `failuresForJobs`, where each of the values has the corresponding data. `failuresForJobs` is a map where the key is created as `{job}-{buildNumber}`.
> Update flake-report-creator to show failuresForJobs in report and json

- images/autoowners/Dockerfile
The autoowners image build fails when using golang:1.16 as builder base
image. Upgrading to golang:1.18 leads to a successful build.
Example failure: 
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/2260/rehearsal-build-autoowners-image/1559886806290272256
> Update autoowners image builder to golang 1.18

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt.github.io/kubevirt-github-io-presubmits.yaml
Adds a presubmit so we catch build failures on kubevirt.github.io in order to gate for them before merging.
/cc @brianmcarey @cwilkers
> Add presubmit for build of kubevirt.github.io

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
- images/publish_multiarch_image.sh
Building the bootstrap image using the original `publish_image.sh` script
no longer works due to missing `ARCH` arg[1].
This update allows for just building amd64 images using the
`publish_multiarch_image.sh` script.
/cc @zhlhahaha @dhiller @xpivarc 
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/publish-bootstrap-image/1561635282061627392
> Allow for only amd64 image builds in mulitarch image script

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Currently there are two of the three VGPU tests in quarantine. This
means that these do not get run as part of the presubmit vgpu lanes. A
periodic test lane will help to identify when the flakes in these tests
are fixed.
> Add periodic job for vgpu test lane

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
The version of podman in the latest bootstrap image does not have the
`--amend` flag availabe when using `podman manifest create`. This causes the
publish_multiarch_image.sh to fail [1].
This flag looks like it will be available in the next podman release[2] so
just moving these jobs back to using DinD until the flag is available
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/publish-bootstrap-image/1561665301555187712
[2] https://github.com/containers/podman/pull/15350
/cc @dhiller 
> Update multiarch publish jobs to use legacy bootstrap image

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
The 1.22-ipv6 provider was removed from the kubevirtci repo[1]
[1] https://github.com/kubevirt/kubevirtci/commit/203b112e3114966f6f87c1fabb5499711701b54c
/cc @oshoval @enp0s3 
> Remove check-provision job for 1.22-ipv6 as provider no longer exists

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Since it's using the default provider, which is 1.22 currently, we
update the periodic name.
See https://github.com/kubevirt/kubevirtci/blob/7aa6748dc9ed5db081ec44301b5cb96118a4dfa3/cluster-up/hack/common.sh#L20
> Fix periodic sysprep name to use 1.22

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Element was missing, see #2282 where yaml modification tried to remove
the part. Also see here for correct definition:
https://github.com/kubevirt/project-infra/blob/b8ddb38f5e598465347daa21abb8fb439adc9a55/github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml#L19
> Fix pod antiaffinity for check-up-kind-1.23-vgpu

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Updated all vgpu jobs podAntiAffinity to have a topologyKey value, since it's required.
Started modified periodics with added topologyKey, seems to work: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-kind-1.23-vgpu/1562838672078802944
> Add topologyKey to podAntiAffinity rules of vgpu

- github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-postsubmits.yaml
postsubmit job used very old image and failed on 
```
vendor/github.com/openshift/build-machinery-go/make/targets/golang/../../lib/golang.mk:22: *** `go` is required with minimal version "1.13.4", detected version "1.12.9". You can override this check by using `make GO_REQUIRED_MIN_VERSION:=`.  Stop.
```
https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/logs/publish-csi-driver
The image is updated so it contains newer toolbox. 
> csi-driver postsubmit: update container image

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
This periodic job is currently failing[1] as it can't find the files
required to build the multiarch bootstrap. Adding an extra ref to the
project-infra repo and setting it as the working directory.
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-publish-multiarch-bootstrap-image/1563549538193510400
> Add reference to project-infra repo for multiarch periodic

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Waiting for results when max_concurrency is 1 takes a lot of time,
increase it to 2.
> kubevirtci, presubmit: Increase max_concurrency

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt.github.io/kubevirt-github-io-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt.github.io/kubevirt-github-io-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt.github.io/kubevirt-github-io-presubmits.yaml
@dhiller I am not 100% sure that I am not losing something by taking "runner.sh" out of the equation here, but it looks like something that is only needed for bootstrap containers doing big Go builds.
> Update kubevirt.github.io jobs to use new container

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Update the kubevirtci prowjobs to use the new podman based bootstrap image. 
There is an outstanding issue with running sonobuoy on the kind based lanes that are deployed with podman so these lanes have been updated to use the legacy image for now.
> Switch kubevirtci prowjobs to use podman in container setup

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
As stated we don't currently test migration with 1.24. So therefore we bump to use 1.24 for migration from 1.22, also we bump non root from 1.23 to 1.24.
/cc @xpivarc @brianmcarey @enp0s3
> Bump migration lanes to use 1.24 provider

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
The publish-kubevirtci job is failing due to issue with cleaning up
containers[1]. This issue was not seen when using the dind setup. Updating
this job to use the legacy image until the logic is in place to
correctly cleanup the containers.
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/publish-kubevirtci/1565349289993965568
> Use legacy dind setup for publish-kubevirtci prowjob

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Jobs that use external provider dont require
29Gi memory as the ones that use KubevirtCI
> Reduce memory for external execution

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
The jobs check-provision-alpine-with-test-tooling and publish-kubevirtci
are getting stuck regularly on bm9. We add an antiaffinity until the
problem is resolved.
> Add antiaffinity rules to bm9 for publish and alpine

- images/bootstrap/Dockerfile
For the switch of kubevirt/kubevirt to bazel 5.3.0 it makes sense to start caching the version.
> Cache bazel 5.3.0 for kubevirt/kubevirt

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Pushing images using bazel fails when run from the podman bootstrap
image. It fails with a 400 bad request[1]. Updating these jobs back to
using the legacy image until issue is resolved.
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-push-nightly-build-main/1566954990545670144#1:build-log.txt%3A3
/cc @xpivarc @enp0s3 @dhiller 
> Use legacy image for jobs that push images using bazel

- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-postsubmits.yaml
Right now CDI will only use buildah as a build command if podman is also
used, but in that case we won't build multi-arch images.
Force buildah so we can get arm64 images as well.
> Build CDI builder using buildah

- images/bootstrap/runner.sh
An issue occurred when trying to push images using bazel[1]. Bazel failed
to find the registry credentials as `${HOME}/.docker/config.json` no longer
existed. This change sets a path for the podman authfile and
then symlinks it to `${HOME}/.docker/config.json` to allow the
bazel push to succeed.
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-push-nightly-build-main/1566592579221327872#1:build-log.txt%3A812
> Setup registry auth file for podman bootstrap

- github/ci/prow-deploy/files/orgs.yaml
Marcin, Radim and Quique need to be marked as OWNERS at the project since they are maintainers.
> kccm: Add more owners

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
This version of the bootstrap image includes a fix for an issue pushing
images with bazel[1].
[1] https://github.com/kubevirt/project-infra/pull/2319
> Update kubevirt periodics to use the latest podman bootstrap

- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
- github/ci/prow-deploy/kustom/base/manifests/local/branch-protector.yaml
- github/ci/prow-deploy/kustom/base/manifests/local/cherrypicker_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/local/label-sync-kubevirt.yaml
- github/ci/prow-deploy/kustom/base/manifests/local/label-sync-nmstate.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/crier_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/deck_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/ghproxy.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/hook_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/horologium_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/needs-rebase_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/prow_controller_manager_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/sinker_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/statusreconciler_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/tide_deployment.yaml
- github/ci/prow-deploy/kustom/overlays/ibmcloud-production/kustomization.yaml
- github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/prow-exporter-deployment.yaml
- github/ci/prow-deploy/molecule/default/prepare.yml
- github/ci/prow-deploy/tasks/secrets.yml
Include changes from prow autobump PR (https://github.com/kubevirt/project-infra/pull/2324)
Adds a new secret - `kubeconfig-build-rules-k8s`
> Fix prow autobump by adding new secret  kubeconfig-build-rules-k8s

- github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-presubmits.yaml
Added the new `pull-csi-driver-split-e2e-k8s-1.23` lane to the CSI Driver, in order to test split cluster.
> Add new lane to csi-driver

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
`publish-kubevirtci` was moved to use the legacy dind bootstrap due to issue with dependent containers (https://github.com/kubevirt/project-infra/pull/2312)
This issue should be resolved by https://github.com/kubevirt/kubevirtci/pull/875
> Update publish-kubevirtci to use podman in container setup

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Fix for https://github.com/kubevirt/project-infra/pull/2193.
In the above PR, this line was added to the lane definition:
```yaml
run_if_changed: ^vendor/.*|^staging/.*|go\.mod$|go\.sum$
```
As @rmohr had [pointed out](https://github.com/kubevirt/project-infra/pull/2193#discussion_r970671141), we can have one of the two: either required, or selective run. Since we want this lane to be required, we should remove the selective run option.
> Fix: make pull-kubevirt-verify-go-mod required

- robots/cmd/kubevirt-lanes-overview/BUILD.bazel
- robots/cmd/kubevirt-lanes-overview/README.md
- robots/cmd/kubevirt-lanes-overview/main.go
Adds kubevirt-lanes-overview, which creates a CSV file containing all e2e test lanes and the env settings per job, so that we can see what settings the lanes actually have.
/cc @stu-gott @fabiand @xpivarc
> Add kubevirt-lanes-overview

- github/ci/services/loki/manifests/common/rules.yaml
Adding a Loki alert  to alert when the thanos compaction is halted due to an error occuring similar to the following:
```
level=error ts=2022-09-17T09:14:25.183977714Z caller=compact.go:458 msg="critical error detected; halting" err="compaction: group 0@129772796
23947480160: block with not healthy index found /var/thanos/compact/compact/0@12977279623947480160/01FX852DEYQ9N639AH29KA46A9; Compaction level 1; Labels: map[cluster:prow-workloads prometheus:monitoring/prometheus-stack-kube-prom-prometheus prometheus_replica:prometheus-prometheus
-stack-kube-prom-prometheus-0]: 2/229719 series have an average of 1.000 out-of-order chunks: 1.000 of these are exact duplicates (in terms o
f data and time range)"
```
The retention limits are not applied if compaction is halted [1]. 
/cc @dhiller …
> Add alert for critical halting error in thanos compact

- github/ci/services/prometheus-stack/manifests/stack/production-control-plane/thanos.yaml
Increase retention period for 5 minutes resolution data to 45 days and and 180 days for 1 hour resolution.
This will give us a good overview of the infrastructure over the past 180 days.
As compaction has been halted for the past few months the previous 21 days retention limit has not been enforced.
```
level=error ts=2022-09-17T09:14:25.183977714Z caller=compact.go:458 msg="critical error detected; halting" err="compaction: group 0@129772796
23947480160: block with not healthy index found /var/thanos/compact/compact/0@12977279623947480160/01FX852DEYQ9N639AH29KA46A9; Compaction level 1; Labels: map[cluster:prow-workloads prometheus:monitoring/prometheus-stack-kube-prom-prometheus prometheus_replica:prometheus-prometheus
-stack-kube-prom-prometheus-0]: 2/229719 series have an average of …
```
> Increase retention period for lower resolution data in Thanos

- images/kubevirt-user-guide/Dockerfile
The current Dockerfile fails to build the kubevirt/user-guide project. This is a copy of kubevirt-kubevirt.github.io Dockerfile that allows to build the documentation using the current user-guide makefile.
Signed-off-by: Javier Cano Cano <jcanocan@redhat.com>
> Update kubervirt-user-guide to match kubervirt-kubevirt.github.io

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
Clusters have been failing to come up on the hco test lanes[1]. There looks to be an issue with the providers that have been published with podman which breaks scp to the nodes.
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_hyperconverged-cluster-operator/2092/pull-hyperconverged-cluster-operator-e2e-k8s-1.23/1572554341003300864
> Move publish-kubevirtci prowjob back to using dind

- github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-presubmits.yaml
Added a lane that calls the kubernetes e2e csi suite for the kubevirt csi driver
> kubernetes e2e csi test suite for csi driver

- github/ci/services/prometheus-stack/manifests/stack/production-control-plane/thanos.yaml
The thanos data bucket currently contains around 1.825TiB. 
Reducing the data retention periods to reduce storage costs.
/cc @dhiller 
> Reduce data retention for thanos data sets

- github/ci/services/prometheus-stack/manifests/stack/production-control-plane/thanos.yaml
Increasing the size of the persistent volume used by the thanos compact pod to 20GB
No space left errors have been halting the compaction process.
```
level=error ts=2022-09-26T12:55:05.816703454Z caller=compact.go:458 msg="critical error detected; halting" err="compaction: group 0@12977279623947480160: compact blocks [/var/thanos/compact/compact/0@12977279623947480160/01FCQGRHFN4C6PVPDW54D30SC3 /var/thanos/compact/compact/0@12977279623947480160/01FCQH1XER3VH9YY90R80TV3FS /var/thanos/compact/compact/0@12977279623947480160/01FCQHBTPM1ZHQV3HW1ZFFGEA9 /var/thanos/compact/compact/0@12977279623947480160/01FCQHK1YYPVQZ41GC9GST4HG9 /var/thanos/compact/compact/0@12977279623947480160/01FCQHTEKXB0BCC8Y73TDZPPBB /var/thanos/compact/compact/0@12977279623947480160/01FCQJ2KVZYC7TZ67H9B4CFY44]: 2 …
```
> Increase the size of thanos compact volume

- github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-presubmits.yaml
> Make new k8s e2e suite lane mandatory for kubevirt csi driver

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Updating to latest pr-creator is necessary, as the cached bazel version seems to get corrupt after 1 year due to bad logic: https://github.com/bazelbuild/bazel/issues/14355
This leads to failing jobs like this one: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirtci-cluster-minorversion-updater/1574742168902307840#1:build-log.txt%3A43
> Update pr-creator image to latest

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Increase interval and timeout since the jobs takes around 1h: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-org-github-config-updater/1575454462862954496
> Increase interval and timeout

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
We need to add the namespace to the service url since all prow job pods are running in `kubevirt-prow-jobs` while pushgateway service is inside `kubevirt-prow` namespace.
Successful run here: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-push-kubevirt-flakefinder-report-values/1575811694112804864
/cc @xpivarc @enp0s3 
FYI @brianmcarey
> Correct pushgateway url

- github/ci/services/prometheus-stack/manifests/stack/production-control-plane/thanos.yaml
The compact process is hitting an error due to a full disk which is causing the compaction to halt and the data retention limits not to be enforced.
Increasing the size of the PVC to 40Gi.
> Increase thanos compact PVC to 40Gi

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Since the periodic single-node lane is [failing with a timeout after 5h](https://testgrid.k8s.io/kubevirt-periodics#periodic-kubevirt-e2e-k8s-1.23-single-node&width=90) on nearly all runs, thus it doesn't add any value, we are removing it.
FYI @jean-edouard
> Remove single-node lane

- github/ci/services/prometheus-stack/manifests/stack/production-control-plane/thanos.yaml
The compaction process gets halted due to the persistent volume running out of space. Increasing the volume size to 100Gi should help this issue.
/cc @dhiller 
> Increase thanos-compact pvc to 100Gi due to out space error

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
This version is needed in order
to support kubernetes 1.25
> Mirror istioctl 1.15

- hack/images_to_mirror.csv
This version is needed in order
to support kubernetes 1.25
> Mirror istio images 1.15

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
Since the post-project-infra-mirror-images-from-docker-hub was updated to use the new podman bootstrap image, it fails trying to mount /var/lib/containers/storage/overlay due to permission issues[1]. Allowing the job to run as privileged allows the job to complete successfully.
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/post-project-infra-mirror-images-from-docker-hub/1579426531975892992
> Allow mirror images job to run privileged

- github/ci/prow-deploy/files/orgs.yaml
I'd like to use the wiki feature for the Community repo to support an events page, which will require relatively frequent updates. 
Signed-off-by: Andrew Burden <aburden@redhat.com>
> Toggling wiki to 'true' for the community repo

- github/ci/prow-deploy/files/jobs/kubevirt/libguestfs-appliance/libguestfs-appliance-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/libguestfs-appliance/libguestfs-appliance-presubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/test-benchmarks/test-benchmarks-presubmits.yaml
This change updates the libguestfs-appliance prowjobs and the test-benchmarks prowjobs to use the new podman bootstrap image. 
/cc @alicefr
> Update libguestfs-appliance prowjobs to use podman bootstrap image

- images/bootstrap/runner.sh
Timeouts waiting for the podman socket to be ready have been seen[1] when there is high load on the cluster. Increasing the wait time should help with this.
This change also removes the enabling of ip6table_nat as this looks to be not needed and just causes an error when enabling ipv6.
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/8605/pull-kubevirt-e2e-k8s-1.24-sig-network-nonroot/1581994128529428480
/cc @dhiller 
> Increase wait time for podman socket to be ready

- github/ci/services/prometheus-stack/manifests/stack/production-control-plane/thanos.yaml
From monitoring the thanos compact pod, it can be seen that the CPU[1] and memory[2] usage consistently hits the limits allowed. Increasing these limits should improve the compaction performance.
The pod is being killed due to being out of memory:
```
kubectl get pods -n monitoring | grep compact
thanos-compact-0                                         1/1     Running   22 (9m39s ago)   5d
```
```
kubectl describe pod -n monitoring thanos-compact-0 | grep Reason
Reason:    OOMKilled
```
[1]
[2]
/cc @xpivarc @dhiller @brybacki 
> Increase thanos compact cpu and memory limits

- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
This reverts commit d23fb8e6d10b56edb8815406bf5cf8fe4e910735.
An issue has been noticed with rsync failing[1] in the CDI CI when using the podman setup - switching back to dind for now.
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/2445/pull-containerized-data-importer-e2e-destructive/1581990466008649728#1:build-log.txt%3A1764
/cc @dhiller @awels 
> Revert "Update CDI prow jobs to use the podman bootrap (#2339)"

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The non-root sriov presubmit lane has been failing consistently.[1] This issue has not been seen in the periodic sriov lane which runs rootful. The issue looks to be non-root specific.
The sriov PFs are not available in the prow pod.
`FATAL: Could not find available sriov PFs on host`
Updating the non-root sriov presubmit to optional and the rootful sriov presubmit to required. This allows us to keep testing sriov without blocking unrelated PRs while investigation into non-root issue is ongoing.
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/8627/pull-kubevirt-e2e-kind-1.22-sriov-nonroot/1583370129192783872
/cc @dhiller @EdDev @oshoval
> Switch non-root sriov presubmit to optional

- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
fossa issues have been solved, we can now reliably run it against our repo.
> Make fossa lane in CDI always run and required

- images/bootstrap/Dockerfile
j2 is required to template the multus-cni e2e test manifests, which are not pushed into the multus repo.
Signed-off-by: Miguel Duarte Barroso <mdbarroso@redhat.com>
> bootstrap: add j2 to the img

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Since we are using sig-operator in k8s <= 1.24 already, let's update the
lane names to reflect reality for 1.25.
The update of the sig name for the automation will be done in a separate
PR.
NOTE: we are NOT updating the lanes for 1.24 <= to avoid losing
information in the testgrid dashboard!
/cc @enp0s3 @xpivarc
> Use correct provider name for operator lane

- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
- github/ci/prow-deploy/kustom/base/manifests/local/branch-protector.yaml
- github/ci/prow-deploy/kustom/base/manifests/local/cherrypicker_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/local/label-sync-kubevirt.yaml
- github/ci/prow-deploy/kustom/base/manifests/local/label-sync-nmstate.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/crier_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/deck_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/ghproxy.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/hook_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/horologium_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/needs-rebase_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/prow_controller_manager_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/prowjob-crd/prowjob_customresourcedefinition.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/sinker_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/statusreconciler_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/test_infra/current/tide_deployment.yaml
- github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/prow-exporter-deployment.yaml
Theres an issue[1] with sriov pods not getting the labels applied correctly. This causes a clash with sriov pods being scheduled together as the anti-affinity can no longer work correctly.
https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/8597/pull-kubevirt-e2e-kind-1.22-sriov/1584691345816031232/podinfo.json
[1] https://github.com/kubevirt/kubevirt/issues/8656
/cc @dhiller @oshoval @rmohr
> Revert prow due to issue with applying sriov labels to pods

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Since the FOSSA check has stabilized we can enable reporting for it again.
https://prow.ci.kubevirt.io/?repo=kubevirt%2Fkubevirt&job=*fossa*
/cc @brianmcarey @xpivarc @enp0s3 @acardace
> Reenable reporting for FOSSA presubmit

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Currently there are two vgpu lanes running for each PR - running just the non-root lane should be enough for this testing - similar is done for the sriov lane.
> Switch rootful vgpu lane to be optional

- github/ci/prow-deploy/files/orgs.yaml
/cc @ksimon1 
This project will hopefully eventually replace common-templates. It has been residing under my personal account for a while now and is ready to start the migration to the KubeVirt namespace.
> Add common-instancetypes repo to KubeVirt

- external-plugins/rehearse/plugin/handler/handler.go
- github/ci/prow-deploy/kustom/base/manifests/local/prow-rehearse-deployment.yaml
No changed files were being discovered as there was no diff between
`HEAD` and `main` after the PR commits were merged into the user's main
branch of their fork. 
```
err = git.MergeAndCheckout(pr.Base.Ref, string(github.MergeSquash), pr.Head.SHA)
if err != nil {
log.WithError(err).Error("Could not rebase the PR on the target branch.")
return
}
log.Infoln("Getting diff")
changedFiles, err := git.Diff("HEAD", pr.Base.Ref)
```
After the merge `HEAD` and `pr.Base.Ref` (`main`) were the same so no diff could be found. 
```
time="2022-11-01T02:16:04Z" level=info msg="Merging \"b2f0217ff25ca28dc097a33fc0e422ad195a4d59\" using the \"squash\" strategy" client=git org=zhlhahaha repo=project-infra
time="2022-11-01T02:16:04Z" level=info msg="Getting diff" …
```
> Fix rehearse plugin to rebase on target main branch

- hack/images_to_mirror.csv
Mirror kind node image v1.25.2 in order to use it in kubevirtci kind-1.25-sriov provider [1].
[1] https://github.com/kubevirt/kubevirtci/pull/893
Signed-off-by: Orel Misan <omisan@redhat.com>
> images_to_mirror: Add kind node image v1.25.2

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
[PR #839](https://github.com/kubevirt/kubevirtci/pull/893) in kubevirtci adds a `kind-1.25-sriov` provider.
Add an optional pre-submit job, in order to check kind-1.25-sriov.
Signed-off-by: Orel Misan <omisan@redhat.com>
> kubevirtci, presubmit: Add optional job to check kind-1.25-sriov

- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
An issue with rsync failures and podman was identified and the CDI prowjobs were moved back to using dind[1]. The rsync failures were caused by the rsync container not being cleaned up correctly and a fix has been created for this issue[2].
This change depends on https://github.com/kubevirt/containerized-data-importer/pull/2448 being merged
/cc @awels  @maya-r 
[1] https://github.com/kubevirt/project-infra/commit/a2e6419e36d8c3c4303585a1ea256e94d5b0a236 
[2] https://github.com/kubevirt/containerized-data-importer/pull/2448
> Update CDI prow jobs to use the podman bootrap image

- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
- github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
The tide, trigger, lgtm and approve plugins are missing config for repo kubevirt/test-benchmarks. See [prow plugin docs](https://prow.k8s.io/plugins) and [kubevirt merge automation docs](https://github.com/kubevirt/community/blob/main/docs/add-merge-automation-to-your-repository.md).
Closes #2399
/cc @alicefr @brianmcarey
> Add CI plugin config for test-benchmarks

- github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
This PR adds the `multus-dynamic-networks-controller` [e2e tests](https://github.com/maiqueb/multus-dynamic-networks-controller/blob/main/e2e/e2e_test.go) as a late to CNAO presubmits.
> cnao: add multus-dynamic-networks functests to presubmits

- github/ci/prow-deploy/files/jobs/kubevirt/test-benchmarks/test-benchmarks-presubmits.yaml
Currently, the CI results are not reported on PRs for the test-benchmarks repo.
> Set enable CI report for test-benchmarks

- hack/flake-report-creator.sh
- robots/pkg/circuitbreaker/BUILD.bazel
- robots/pkg/circuitbreaker/circuitbreaker.go
- robots/pkg/circuitbreaker/circuitbreaker_test.go
- robots/pkg/jenkins/BUILD.bazel
- robots/pkg/jenkins/builds.go
- robots/pkg/jenkins/builds_test.go
* Create a minimal circuitbreaker implementation that avoids stressing the Jenkins with requests in case the service returns 504 status indicating it is not healthy.
* To make the use case testable, create new interface BuildDataGetter for
dependency injection with default implementation. Extract method that
uses the interface while preserving the original. Use this interface for mock testing.
* Add test for parallel execution that assures that
the service is not called more often than wanted.
Note: the retry and jitter values were extended since the feedback was that the Jenkins services requires around 1-2 minutes to recover, therefore an extra minute to give it a bit more time.
TODOs:
/cc @fossedihelm @xpivarc
> Add circuit breaker to flake-report-creator

- github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-postsubmits.yaml
A new image should only be published when a change to the builder image is merged.
/cc @lyarwood @dhiller 
> Only publish common-instancetypes image when it changes

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Based on #2439 where the rest of the sig lanes always_run was disabled, we also disable operator 1.22 `always_run`.
Closes #2439
/cc @brianmcarey @enp0s3
> Disable kubevirt 1.22 always run

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
sig-performance lanes have been failing consistently[1] - this is due to
insufficient memory on the nodes to schedule the full amount of vms.
```
{
"type": "PodScheduled",
"status": "False",
"lastProbeTime": null,
"lastTransitionTime": "2022-11-08T10:23:13Z",
"reason": "Unschedulable",
"message": "0/4 nodes are available: 4 Insufficient memory."
```
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.22-sig-performance/1589920378929549312
> [sig-performance] Increase node memory and job memory request

- hack/images_to_mirror.csv
Mirror kind node image v1.23.13 in order to use it in kubevirtci kind-1.23-sriov provider [1].
[1] kubevirt/kubevirtci#897
Signed-off-by: Orel Misan <omisan@redhat.com>
> images_to_mirror: Add kind node image v1.23.13

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
https://github.com/kubevirt/kubevirtci/pull/897 adds a kind-1.23-sriov provider.
Add an optional pre-submit job, in order to check `kind-1.23-sriov`.
> kubevirtci, presubmit: Add optional job to check kind-1.23-sriov

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
There looks to be performance issues with the publish-kubevirtci job when the workloads cluster is heavily loaded
https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/logs/publish-kubevirtci
Increasing the memory request to match the regular e2e jobs should guarantee a certain level of compute resources for the job.
> Increase memory request of publish-kubevirtci job

- github/ci/prow-deploy/files/jobs/kubevirt/libguestfs-appliance/libguestfs-appliance-periodics.yaml
The https://github.com/kubevirt/libguestfs-appliance/pull/15 changed the file name from appliance to libguestfs appliance and the latest-version.txt contains also the tarball suffix.
> Update libguetfs periodics

- github/ci/prow-deploy/files/jobs/kubernetes-sigs/cluster-api-provider-kubevirt/cluster-api-provider-kubevirt-presubmits.yaml
There is an issue with some of the Dockerfiles in the capk repository that breaks podman[1].
Moving the job back to dind to unblock the CI while issue is being investigated
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubernetes-sigs_cluster-api-provider-kubevirt/208/pull-kubernetes-sigs-cluster-api-provider-kubevirt-e2e/1592088855954067456#1:build-log.txt%3A422
/cc @nunnatsa @dhiller 
> Move capk e2e prowjob back to using dind

- github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
shellcheck was recently introduced to the image [1], bump so we can start to use it in prow job.
[1] https://github.com/kubevirt/common-instancetypes/pull/10
> Bump common-instancetypes-builder

- github/ci/prow-deploy/files/jobs/kubernetes-sigs/cluster-api-provider-kubevirt/cluster-api-provider-kubevirt-presubmits.yaml
This reverts commit d86c52f5cc6677d0a055ab6fc024f1787b418dbf.
Issues with running this job under podman have been identified and should be fixed by:
https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/pull/208
/cc @dhiller @nunnatsa @qinqon
> Revert "Move capk e2e prowjob back to using dind (#2456)"

- images/bootstrap/Dockerfile
- images/bootstrap/storage.conf
An additional read-only image store will allow podman to run regularly used images such as the kubevirtci node images without having to pull them everytime. This will greatly reduce the amount of data being pulled over the network and written to the disks.
Initially the additonal image store will be empty until there is automation in place to populate and manage this image store. This update just enables the bootstrap image to use the new image store.
The storage.conf is based on the default config[1] with an update for the additional image store.
[1] https://github.com/containers/podman/blob/6c37cf332439989148e408af49afaf7c0cb6e166/vendor/github.com/containers/storage/storage.conf
/cc @dhiller  @xpivarc @rmohr 
> Add additional image store to podman conf

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.58.yaml
The sig-performance lane for the 0.58 release is seeing the same issue with insufficient memory on the nodes [1].
This backports the memory increase[2] to the 0.58 release.
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/8785/pull-kubevirt-e2e-k8s-1.22-sig-performance-0.58/1592806770189799424 
[2] https://github.com/kubevirt/project-infra/pull/2442
/cc @dhiller @lyarwood 
> Increase node memory for 0.58 performance lane

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
It seems the current timeout of one hour is a bit tight. Thus we are increasing the timeout by 30 minutes.
> Increase timeout by 30mins on sig monitoring presubmit

- github/ci/prow-deploy/files/orgs.yaml
The user's github username[1] has been updated which causes the automation to fail[2]
[1] https://github.com/iholder101
[2] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-org-github-config-updater/1593512760266723328
/cc @iholder101 @dhiller 
> Update iholder's username to iholder101

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
In order for the kubevirt-bot to request review from just the taskforce a new line is required before /cc of taskforce
/cc @kubevirt/prow-job-taskforce 
> Add newline to commit msg for bump prow jobs

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
This reverts commit 8fe75668f8088e3c3a37daba279a4e0e04a382ec.
The newline character did not result in a new line in the PR description so it did not have the desired effect[1]. Revert back to previous commit message.
/cc @dhiller 
[1] https://github.com/kubevirt/project-infra/pull/2472#issue-1456714984
> Revert "Add newline to commit msg for bump prow jobs (#2466)"

- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-postsubmits.yaml
There has been an issue with pushing CDI images since the change to podman - change back to the legacy bootstrap image and dind until issue is resolved.
/cc @awels @dhiller 
> Change CDI image postsubmits back to dind

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
This PR adds new periodic and presubmit jobs for testing Kubevirt SR-IOV tests on k8s-1.23 cluster (using the new SR-IOV kubecirtci provider kubevirt/kubevirtci#897).
And use the new jobs instead of the old ones (i.e: use pull-kubevirt-e2e-kind-1.23-sriov instead of pull-kubevirt-e2e-kind-1.22-sriov).
Note to reviewer: 
- Since only two SR-IOV jobs can runs simontanuasly its necessary to pick only SR-IOV lane (e.g: `pull-kubevirt-e2e-kind-1.23-sriov`).
- The new `kind-1.23-sriov` periodic job will start after `kind-1.22-sriov` perodic job.
We can remove it as soon as we see that the new periodic job is stable.
> Add K8s-1.23 SR-IOV lane jobs

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Following #2477, this PR enables the new `check-up-kind-1.23-sriov` job instead of the old `check-up-kind-1.22-sriov` job.
It checks that creating a SR-IOV cluster succeeds and runs Kubevirt SR-IOV tests suite with a given kubevirt/kubevirtci PR changes.
> presubmit, kubevirtci: Switch to check-up-kind-1.23-sriov

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
- robots/cmd/kubevirtci-presubmit-creator/main.go
- robots/pkg/jenkins/builds_test.go
Adds the new presubmit for the new 1.26 provider in kubevirtci.
It also adds the flag `k8s-release-semver` to the kubevirtci-presubmit-creator so we can create new presubmits for arbitrary versions. This skips the lookup for the latest kubernetes version.
/cc @Barakmor1 @brianmcarey
> Add new presubmit for kubevirtci 1.26 provider, update creator to manually create presubmits

- github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
Depends on https://github.com/kubevirt/cluster-network-addons-operator/pull/1451
So adding it as `optional`, and not `always_run` atm.
> cnao, presubmit: Add kube secondary dns lane

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
The 1.22 provider is in the process of being retired - we should not be running an extra presubmit per PR.
/cc @dhiller 
> Switch check-provision-1.22 to optional

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
- robots/pkg/kubevirt/cmd/copy/jobs.go
Creates the SIG test lanes for kubevirt/kubevirt using 1.26 k8s provider.
Also modifies the automation around `kubevirt copy jobs` to add a flag
`--k8s-release-semver flag` to manually create a copy for a not yet existing version.
/cc @brianmcarey @Barakmor1 @xpivarc 
/hold since https://github.com/kubevirt/kubevirtci/pull/907 has not yet landed in kubevirt/kubevirt
> Create 1.26 lanes for kubevirt

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Depends on https://github.com/kubevirt/kubevirtci/pull/912
> kubevirtci, presubmit: Introduce k8s-1.25-ipv6

- github/ci/prow-deploy/files/jobs/kubevirt/kubesecondarydns/kubesecondarydns-presubmits.yaml
`make create-nodeport` is already done as part of cluster-sync.
No need to do it twice.
> kubesecondarydns, presubmit: Fix e2e lane

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
This is a copy of the 1.24-psa job, with just the path and the name changed
> Add check-provision job for 1.25-fips

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
As the test both kind e2e tests and unit tests have passed. We can try to run a periodic job for them to see the stability of them.
The rehearsal-pull-kubevirt-e2e-arm64 and rehearsal-pull-kubevirt-unit-test-arm64 can be found in the following PR.
https://github.com/kubevirt/project-infra/pull/2351
> Add periodic unit tests and kind e2e tests for Arm64 Cluster

- github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
Adding labels as per https://github.com/kubevirt/kubevirt/pull/8752/files
I noticed that there is currently a `release-note-action-required` label already here.
Maybe the `kind/action-required` is not necessary if we want to continue with that, however does it make sense for consistency sake to have these labels all as `kind/` ? Both from the POV of a contributor remembering to add relevant labels to their PR and also from kubevirt-bot automation.
Signed-off-by: Andrew Burden <aburden@redhat.com>
> Adding kind/ labels to help categorise release notes

- github/ci/prow-deploy/files/jobs/kubevirt/kubesecondarydns/kubesecondarydns-presubmits.yaml
Update image, because the newer image has increased timeout waiting for podman socket.
Error here
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubesecondarydns/38/pull-kubesecondarydns-e2e-k8s/1599692018617946112
> presubmit, ksd: Update image

- github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
Also includes
* Update image
The newer image has a bigger timeout for podman socket
readiness check.
> presubmit, cnao, ksd: Make lane required

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
This PR adds a new lane `pull-kubevirt-e2e-k8s-1.24-psa-sig-network`
> kubevirt, presubmits: Add psa-sig-network lane

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
The presubmit jobs which test the building of the bootstrap container images look to be failing due to low memory.
https://github.com/kubevirt/project-infra/pull/2501
> Increase memory requests of bootstrap image build jobs

- images/bootstrap-legacy/Dockerfile
- images/bootstrap/Dockerfile
Needed for `nslookup` which is used by `KubeSecondaryDNS`.
> bootstrap files: Add bind-utils

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Currently Both pull-kubevirt-unit-test-arm64 and pull-kubevirt-e2e-arm64, this may lead to memory run out. Allocate pull-kubevirt-unit-test-arm64 jobs to Arm Cluster 2
> kubevirt, presubmits: run pull-kubevirt-unit-test-arm64 on Arm Cluster 2

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The 1.22 provider will no longer be supported soon so updating lanes to use the 1.25 kubernetes provider
@rthallisey  - this change may impact the performance metrics. 
The periodic sysprep lane (periodic-kubevirt-e2e-k8s-1.22-sysprep) is actually using the 1.25 already [1] - updating name to better reflect what is running. 
Update the sig-monitoring lane to 1.23 as there were issues with 1.24/1.25 [2]
/cc @dhiller @rthallisey 
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.22-sysprep/1595930288540618752#1:build-log.txt%3A365
[2] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/2487/rehearsal-pull-kubevirt-e2e-k8s-1.25-sig-monitoring/1600155780672131072
> Update the performance lanes to use the 1.25 provider

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
The job is failing due to a lack of resources[1] and it succeeeds locally using phaino. Increasing the memory request for the job.
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/publish-shared-images-controller-image/1600798705781313536
/cc @dhiller 
> Increase memory request/limit for publish of shared images

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
- hack/bump-prow.sh
Adds the bumping of the prow images inside the job definitions to `hack/bump-prow.sh`.
Note: also sets the job images to the currently used version.
/cc @xpivarc @enp0s3
> Add image bump for prowjobs to hack/bump-prow.sh

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
The lane is very flaky, and thus steadily blocking merges.
See: https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/check-up-kind-1.23-vgpu
> Set check-up-kind-1.23-vgpu to optional

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Since the 1.26 k8s version has been released, we let the provision check run on every PR.
> Set check provision for 1.26 to run always

- github/ci/services/prometheus-stack/manifests/stack/production-control-plane/thanos.yaml
Data retained in the thanos bucket has been greatly reduced so the data retention period for the 1hr resolution can be increased to 1 year
This will allow better visibility of trends over time.
/cc @dhiller 
> Increase thanos data retention for 1hr resolution to 1 year

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Update pathes for binaries of peribolos and commenter, since the pathes have changed when we introduced the new images, reducing in failures of a number of jobs. Examples:
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-org-github-config-updater/1601162006000308224
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-project-infra-stale/1601165277557428224
> Fix prow binary pathes

- github/ci/prow-deploy/kustom/overlays/workloads-production/kustomization.yaml
- github/ci/prow-deploy/kustom/overlays/workloads-production/resources/shared-images-controller.yaml
This daemonset is responsible for maintaining the shared image store on
each node in the workloads cluster. It will download the latest
kubevirtci node images and remove any old images that are no longer
required. The e2e jobs will mount this directory as a read only shared
image store.
/cc @enp0s3 @xpivarc 
> Add daemonset for shared images to prow-workloads cluster

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
This preset will allow the e2e jobs to access the shared image store which will include the kubevirtci node images so the jobs will no longer have to spend time downloading the images.
> Add preset for podman shared images store

- hack/update-jobs-with-latest-image.sh
Don't consider the platform based images, use the general image tags instead.
See https://github.com/kubevirt/project-infra/pull/2472/files#diff-12f4d5cb56d6eb2ad6984f4302f785e8fb92bd0aebf262c3ee4c765b42864d40R17
> Reduce length of image tag to be looked for

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Remove 1.23 migration presubmit lane, bump 1.24 (root and nonroot) to 1.25. Also bump periodic lane.
/cc @brianmcarey @fossedihelm @iholder101 @jean-edouard
> Bump sig compute migration lanes

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
https://groups.google.com/g/kubevirt-dev/c/zdgrOmJcodc/m/72-MqVwzGQAJ
The performance job has been stable for many months so I think its time to make it voting.
This job is designed to catch the following issues on a new PR:
1) Performance regression (slow phase transitions)
2) Scale regression (too many http requests)
3) control-plane mem increase
Catching these issues in an MR would allow the author to add a release note documenting a performance change.
> Make the performance job voting and running per commit

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Update PSA lanes to 1.25 and use a new way to enable PSA rather than the dedicated provider.
> Update PSA jobs and use new way to enable it

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The link for fetching the windows 2016 image seems to be broken. Until we fix it, make the lane optional.
Signed-off-by: enp0s3 <ibezukh@redhat.com>
> Temporary workaround for windows2016 lane issue

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The windows VM test images will be hosted in a private GCS bucket so these jobs will require these credentials.
/cc @dhiller @dominikholler @xpivarc 
> Add gcs credentials to windows related e2e jobs

- images/bootstrap-legacy/Dockerfile
- images/bootstrap/Dockerfile
- images/golang/Dockerfile
Fedora 37 has been released for over a month now[1] and looks stable enough
so we can update the bootstrap images to F37.
The kubevirt builder image is using golang version 1.19.2 [2] - this golang
bootstrap image should default to the same.
[1] https://fedoramagazine.org/announcing-fedora-37/
[2] https://github.com/kubevirt/kubevirt/blob/297edbe21961c7a3ef462f94f4eeead0520ec043/hack/builder/Dockerfile#L7
> Update bootstrap images to use Fedora 37

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
This was previously disabled due to being unable to access the remote vm images[1]
These images have been mirrored to a Kubevirt GCS bucket and should always be available now.
[1] https://github.com/kubevirt/project-infra/pull/2520
> Enable the windows e2e presubmit lane for all kubevirt PRs

- github/ci/prow-deploy/files/jobs/kubevirt/ansible-kubevirt-modules/ansible-kubevirt-modules-presubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
There were some jobs that use images that are built from the bootstrap
image. These images were rebuilt recently and the jobs were updated[1] so these jobs now require the
podman preset to be enabled.
[1] https://github.com/kubevirt/project-infra/pull/2531
> Update remaining jobs to use podman

- github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
This image uses podman
The old image has problems suddenly with docker
`Error: statfs /var/run/docker.sock: no such file or directory`
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_hyperconverged-cluster-operator/2198/pull-hyperconverged-cluster-operator-e2e-k8s-1.24/1610587959369666560
We need to use podman anyhow.
Previous image is based on an old image, if all is passing with the new one no need to keep it.
> hco,presubmit: Update golang bootstrap image

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The image tag of the arm64 based jobs were updated to an image that does not support arm64. This updates theses jobs to the latest bootstrap image that supports arm64.
/cc @zhlhahaha @dhiller 
> Fix bootstrap image version for arm64 workloads

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
- robots/pkg/kubevirt/cmd/remove/always_run.go
Now that the periodics for 1.26 seem to pass we want to run the presubmits on every PR.
Also disable running the 1.23 sig lanes on every PR. Add a `force` flag to the automation to skip the check for this.
/cc @brianmcarey @jean-edouard @rthallisey
> Set 1.26 lanes to run on every PR

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Since the 1.26 periodics look good, and we don't see any issues on the 1.26 presubmits either, we can make the lanes for 1.26 gating.
See testgrid dashboard here: https://testgrid.k8s.io/kubevirt-periodics
/cc @brianmcarey @rthallisey
> Set 1.26 lanes to gating

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The ARM64 based KubeVirt presubmit lanes have been reasonably stable recently[1][2]. Reporting these on the KubeVirt PRs would give valuable feedback to the contributors.
[1] https://testgrid.k8s.io/kubevirt-presubmits#pull-kubevirt-e2e-arm64 
[2] https://testgrid.k8s.io/kubevirt-presubmits#pull-kubevirt-unit-test-arm64
/cc @zhlhahaha @dhiller 
> Enable reporting on ARM64 presubmits

- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
- github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
KubeSecondaryDNS is already using a builtin github action to create the release notes based on PR titles.
In this repository we don't need to manually add another custom collectible note to the PR description,
hence remove the plugin that expects it.
> ksd: remove the release-note plugin from ksd

- images/kubevirt-user-guide/Dockerfile
In order to support https://github.com/kubevirt/user-guide/pull/633, this patch adds mkdocs-material theme to the list of packages installed to the user-guide build container.
> Install Material theme to user-guide container

- github/ci/prow-deploy/files/jobs/kubevirt/community/community-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
- hack/update-jobs-with-latest-image.sh
Updates the kubevirt builder image for jobs, since i.e. bump-kubevirt-rpms-weekly is [failing](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/bump-kubevirt-rpms-weekly/1614748255260774400) due to bazel being too old.
Also adjusts the bump-image script to work for kubevirt builder image tags.
> Update kubvirt builder image

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Using kubevirt builder as job image is a waste of resources, we use pr-creator instead.
Successful run here: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-project-infra-prow-bump/1614981981030846464
> Make prow-bump use pr-creator image

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The kubevirt fossa presubmit check is failing constantly[1]. Fossa support have been contacted about the issue.
The failing fossa presubmit is blocking merges and batch merges to the kubevirt/kubevirt repo - updating this job to be optional.
[1] https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-fossa
/cc @dhiller @EdDev @enp0s3 
> Make kubevirt fossa check optional due to failures

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
This PR includes a couple of changes to cleanup the presubmits lanes and also added periodic lanes to test rootful kubevirt. 
- [Swap rootful vgpu lane for nonroot lane](https://github.com/kubevirt/project-infra/commit/72d3a15fde22fbd30d7bf05ec4f84c6df59b9ee2)
-  [Add periodic 1.26 root test lanes](https://github.com/kubevirt/project-infra/commit/463313e781a164800ac148819b9873e2f0d3359a)
-  [Bump remaining lanes that use the 1.23 provider](https://github.com/kubevirt/project-infra/commit/d827f31ecd3c63336ee7f80cb83d144133df8d2f)
> Cleanup of 1.23 kubevirt presubmit lanes and add 1.26 periodic root lanes

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
The ARM64 e2e lane has been failing recently[1] due to kind being unable to find /var/log/audit - add an emptyDir to the job definition to stop this failing.
Test run of this config change here - https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-kind-e2e-test-ARM64/1617917479961497600
[1] https://testgrid.k8s.io/kubevirt-periodics#periodic-kubevirt-kind-e2e-test-ARM64
/cc @zhlhahaha @dhiller 
> Add /var/log/audit path to Arm64 e2e periodic lane

- github/ci/prow-deploy/files/orgs.yaml
- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
- github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
It is a proxy that provides access to VM's VNC, and uses a time limited token for authentication.
Currently the project is in my personal repository: https://github.com/akrejcir/vm-console-proxy
> Add vm-console-proxy repository to kubevirt organization

- github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-presubmits.yaml
Kubevirt csi driver presubmit lanes don't specify kubernetes version (its defined in the repo). Removing version from the presubmit lanes
> Remove k8s version from csi driver presubmits

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Since https://github.com/kubevirt/kubevirt/pull/8649 KubeVirt can run VMs as `restricted` PSA pods, we should run all the latest lanes with PSA enabled to make sure we don't break this.
Running with PSA enabled translates in testing KubeVirt in the most restrictive Kubernetes environment and thus it's only more beneficial if we run every PR against PSA lanes.
> Enable PSA on 1.26 lanes

- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Moves the project away from squash given the tendency for multiple commit PRs and squash causing a loss of a clean history in the repository.
> common-instancetypes: Switch merge_method to merge

- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Switch `merge_methods` of `kubevirt/common-templates` and `kubevirt/containerdisks` to `merge` to avoid the loss of a clean history in the repository when merging multiple commit PRs. (similar to https://github.com/kubevirt/project-infra/pull/2573)
> Switch merge_methods of kubevirt/common-templates and kubevirt/containerdisks to merge

- github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-periodics.yaml
- robots/cmd/flake-report-creator/cmd/BUILD.bazel
- robots/cmd/flake-report-creator/cmd/cmd_suite_test.go
- robots/cmd/flake-report-creator/cmd/jenkins-report-template.gohtml
- robots/cmd/flake-report-creator/cmd/jenkins.go
- robots/cmd/flake-report-creator/cmd/prow-report-template.gohtml
- robots/cmd/flake-report-creator/cmd/prow.go
- robots/cmd/flake-report-creator/cmd/prow_test.go
- robots/cmd/flakefinder/index.go
- robots/cmd/flakefinder/main.go
- robots/cmd/flakefinder/report.gohtml
- robots/cmd/flakefinder/report_test.go
- robots/pkg/flakefinder/report_data.go
- robots/pkg/flakefinder/report_data_test.go
Improve readability of test names by extracting attributes/tags and showing them as labels above the test name. Also improve readability for valued tags like `test_id:1742` by separation of attribute name and value.
Example report: https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/preview/flakefinder-2023-01-11-024h.html
/cc @brianmcarey @enp0s3
> Improve flakefinder test name layout

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
As part of the effort to make the provider robust, we need to remove the presubmit job of the legacy
standalone single stack provider.
Needed for https://github.com/kubevirt/kubevirtci/pull/954
> kubevirtci, k8s-1.26-ipv6: Remove presubmit job

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.58.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The docker image proxy is currently down on the ibm-prow-jos cluster - temporarily move the jobs that rely on this proxy to the prow-workloads cluster.
This should be changed back once the docker image proxy is back up.
/cc @dhiller 
> Temporarily move pinc jobs to prow-workloads cluster

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Since go was updated to 1.19 by #2362 yesterday we need to adjust `GIMME_GO_VERSION` for two jobs.
Examples:
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-project-infra-check-prow-jobconfigs/1620707968225906688#1:build-log.txt%3A4
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-push-kubevirt-flakefinder-report-values/1620594217694793728#1:build-log.txt%3A4
> Update kubevirt periodics job and project-infra to 1.19

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
The 1.23 provider is no longer published - these lanes should be removed.
> Remove 1.23 cgroupsv2 periodic lanes

- robots/pkg/kubevirt/cmd/get/presubmits.gohtml
Adds a new column where the env vars of the container spec are listed
/cc @xpivarc @enp0s3 @brianmcarey
> kubevirt get presubmits: add env var list

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.53.yaml
Similar change to https://github.com/kubevirt/project-infra/pull/2583
> Temporarily move 0.53 jobs to prow-workloads due to image cache issue

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
- hack/mirror-crio.sh
The CentOS Stream 8 builds for cri-o 1.24 look to be failing.
The repo only has up to 1.24.1[1] which still hits this intermittent issue[2] which is fixed in 1.24.2.
Use the CentOS 8 build as a workaround for this.
Also remove cri-o 1.23 from kubevirt mirror. 
[1] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.24/CentOS_8_Stream/x86_64/
[2] https://github.com/cri-o/cri-o/issues/5889
/cc @dhiller
> Add workaround for cri-o version 1.24

- github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
This change adds a basic func test prow job for common-instancetypes that deploys KubeVirt from HEAD, deploys common-instancetypes and then exercises the various validation code paths by creating VirtualMachines for each instance type and preference available in the environment.
Future test coverage could start these VirtualMachines and exercise the runtime VirtualMachineInstance code paths but this should be enough for now ahead of KubeVirt `v0.59.0` and common-instancetypes `v0.1.0` being cut.
> common-instancetypes: Add basic functional test coverage

- robots/pkg/kubevirt/cmd/get/periodics.gohtml
Adds the env variable settings to the overview page for the periodic jobs that is created by `kubevirt get periodics`.
Same as what commit 1d331960 does to presubmit list.
> Add container env variable output to periodics

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
Since we want the overview of kubevirt e2e jobs for [periodics](https://storage.googleapis.com/kubevirt-prow/reports/e2ejobs/kubevirt/kubevirt/periodics.html) and [presubmits](https://storage.googleapis.com/kubevirt-prow/reports/e2ejobs/kubevirt/kubevirt/presubmits.html) as up to date as possible we convert the periodic into a postsubmit.
> Convert periodic into postsubmit

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
We want to be sure that job-config-validator is not impacted from changes in the codebase, therefore we create a presubmit for it to catch this early.
Example: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-project-infra-check-prow-jobconfigs/1623352740203728896
See #2603 for a fix to the above job
> Add presubmit for job-config-validator

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.57.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.58.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.59.yaml
We agreed in the past to ignore Bazel remote cache in release configs, in order not to exhaust the cache.
During the last release cut we forgot to remove the preset, this PR fixes the situation.
Signed-off-by: enp0s3 <ibezukh@redhat.com>
> release-configs: remove usage of Bazel remote cache

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
As the 1.26 CentOS 9 provider is the provider that testing will be carried out against in kubevirt[1] - the check-provision job should be set to required.
The 1.26 CentOS 8 provider will be removed shortly so a check-provision job should not be required there. 
[1] https://github.com/kubevirt/project-infra/pull/2610
> Set check-provision-k8s-1.26-centos9 to required

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Since we want to have CentOS Stream 9 as default node OS, and PSA enabled, and this should be our only merge gate, we explicitly set the centos9 for the 1.26 default gating sig lanes, and remove the centos9 lanes entirely.
/cc @acardace @enp0s3 @fabiand @fossedihelm @phoracek @xpivarc
> Make 1.26 CentOS Stream 9 based provider default for gating 1.26 lanes, remove explicit centos9 lanes

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Add a template periodic and optional presubmit lane to help testing of AMD SEV against a single node external cluster. These jobs will be updated once tests are added to kubevirt/kubevirt
/cc @dhiller @xpivarc @vasiliy-ul 
> Add template prowjobs for testing against SEV cluster

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.59.yaml
This ports the [changes of switching](https://github.com/kubevirt/project-infra/pull/2610) to CentOS Stream 9 for the gating lanes to release branch 0.59 CI lanes.
The only difference here is that the operator-upgrade lane will have PSA disabled since 0.58 release is not PSA ready and thus upgrade on PSA enabled system can't work.
/cc @brianmcarey @enp0s3 @acardace @xpivarc @fossedihelm @phoracek @stu-gott
> release-0.59: backport switch for 1.26 gating lanes to CentOS Stream 9 with PSA enabled

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Since we don't need to run the upgrade tests without PSA (as 0.59 is
PSA ready) we merge the two lanes operator-upgrade and
operator-configuration together into one.
Also we remove the 1.26 CentOS 8 lane for sig-operator.
/cc @xpivarc @brianmcarey @fossedihelm
> Merge split operator lanes

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Testing is no longer required against the 1.26 CentOS 8 provider[1]
Updating the 1.26 periodics to use the CentOS 9 provider and remove specifice CentOS 9 periodics.
> Update 1.26 periodics to use 1.26 CentOS 9 provider

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
- robots/pkg/kubevirt/cmd/get/BUILD.bazel
- robots/pkg/kubevirt/cmd/get/periodics.go
- robots/pkg/kubevirt/cmd/get/periodics.gocsv
- robots/pkg/kubevirt/cmd/get/presubmits.go
- robots/pkg/kubevirt/cmd/get/presubmits.gocsv
Adds flag `--output-format` where allowed values are `html` and `csv`, according to the flag value an output file in that format is generated.
Also adds the support for multiple presubmit config files and modifies the postsubmit generating [presubmits.html](https://storage.googleapis.com/kubevirt-prow/reports/e2ejobs/kubevirt/kubevirt/presubmits.html) and [periodics.html](https://storage.googleapis.com/kubevirt-prow/reports/e2ejobs/kubevirt/kubevirt/periodics.html) to use files for main and release-0.59.
Screenshots (**please note the 0.59 suffixes that mark the release branch jobs**):
> Add csv output to kubevirt get

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
There have been a couple of runs where it appears that the shhuttle tunnel is no longer active. [1]
Adding `ServerAliveInterval=60` as an ssh option should help to keep the tunnel alive.
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7197/pull-kubevirt-e2e-k8s-1.26-sev/1626477337849630720#1:build-log.txt%3A1251
> Add keepalive for sshuttle tunnel in SEV lanes

- github/ci/services/ci-search/manifests/full.yaml
- github/ci/services/ci-search/patches/statefulset.yaml
These requests are causing a large number of failed authentications to bugzilla - removing for now.
> Remove bugzilla search queries from ci-search statefulset

- hack/flake-report-creator.sh
- robots/cmd/flake-report-creator/cmd/jenkins-report-template.gohtml
- robots/cmd/flakefinder/report.gohtml
Port test name layout report enhancements to report creator. Use visual label representations to make test labels more visible.
(see #2549)
> Port test name layout enhancements

- images/bootstrap/create_bazel_cache_rcs.sh
Basel --remote_http_cache has been deprecated
Update it to --remote_cache to reduce some noise in the job logs[1]
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7197/pull-kubevirt-e2e-k8s-1.26-sev/1626202588405829632#1:build-log.txt%3A218
> Update bazel remote cache flag to --remote_cache

- robots/pkg/kubevirtci/kubevirtci.go
- robots/pkg/kubevirtci/kubevirtci_test.go
Previously alternative providers such as `k8s-1.26-centos9` were being skipped by the kubevirtci bumper for minor version bumps.
This update will bump the minor versions of these alternative providers.
Fixes #2340 
> Update kubevirtci-bumper to bump minor version of alt providers

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Instead using the old k8s-x-ipv6 provider,
use the new one which supports both dual stack
and single stack.
Depends on https://github.com/kubevirt/kubevirtci/pull/954 - done.
Need to be tested with the [bump](https://github.com/kubevirt/kubevirt/pull/9375) and merge both together.
> single stack providers: Use the robust provider

- hack/test-report.sh
- robots/cmd/test-report/cmd/execution/execution.go
- robots/cmd/test-report/cmd/execution/execution_test.go
- robots/cmd/test-report/cmd/execution/ssp-config.yaml
- robots/cmd/test-report/cmd/execution/test-report.gohtml
- robots/pkg/test-report/test_report.go
Adds filtering mechanisms to the report, so that it will be easier to narrow down what we want to look at.
Three filtering options are present:
* Include tests with terms
* Exclude tests with terms
* Show only the not run tests
All of these can be applied at the same time, i.e.
> Add filtering to test-report

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Following [kubevirt/kubevirtci#973](https://github.com/kubevirt/kubevirt/pull/9388) sig-network gating lanes will run with Multus V3.
This PR adds an optional presubmit and periodic job that run the sig-network 1.26 lane with MultusV4 including the hotplug NICs tests (which depend on Multus v4).
The jobs spec sets specify the following env var`KUBEVIRT_WITH_MULTUS_V3 = false`
It makes cluster-up deploy Multus V4 with CNAO instead of Multus v3 and makes the Kubevirt test suite run the hotplug NIC tests.
The periodic job is set to run weekly at 5:00 on Sundays.
The presubmit job is optional and will run on demand by commenting `/test pull-kubevirt-e2e-k8s-1.26-sig-network-multus-v4`
> sig-network: Add optional and weekly jobs to run tests with MultusV4

- github/ci/prow-deploy/files/jobs/kubevirt/controller-lifecycle-operator-sdk/controller-lifecycle-operator-sdk-presubmits.yaml
Current kubevirtci is ancient (pulls from dockerhub!) 
Verified locally
> Bump kubevirtci on controller-lifecycle-operator-sdk-e2e

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Add k3d-sriov presubmit and periodic jobs.
Switch kubevirt presubmit kind with k3d as the gating job.
Disable gating of kubevirtci kind-1.23-sriov presubmit (k3d-sriov is gating already).
Fix name typo of kubevirt kind periodic
Kept the kind-1.23-sriov kubevirt periodic for now.
Depends on 
https://github.com/kubevirt/kubevirtci/pull/972 (need to be [bumped](https://github.com/kubevirt/kubevirt/pull/9384) as well)
https://github.com/kubevirt/kubevirt/pull/9326
> k3d-sriov: Replace kind with k3d for SR-IOV jobs

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The centos8 based k8-1.26 target was removed so the sig-monitoring presubmit lane can no longer complte successfully[1].
Update to use the centos stream 9 target
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/9392/pull-kubevirt-e2e-k8s-1.26-sig-monitoring/1638096889373003776#1:build-log.txt%3A54
> Update sig-monitoring presubmit to use k8s-1.26-centos9 target

- github/ci/prow-deploy/files/orgs.yaml
@assafad
* @orenc1 https://github.com/kubevirt/hyperconverged-cluster-operator/pull/2268#issuecomment-1448566638
* @sradco
- https://github.com/kubevirt/hyperconverged-cluster-operator/pull/2204
- https://github.com/kubevirt/hyperconverged-cluster-operator/pull/2254
- https://github.com/kubevirt/kubevirt/pull/7843
- https://github.com/kubevirt/kubevirt/pull/7569
> Add assafad to the org

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Currently we are running both k3d and kind periodics, each one twice a day.
We even run them on the same time so they might [fall](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-k3d-1.25-sriov/1638206139675971584) to schedule.
Reduce the rate, as we are running k3d on every presubmit,
in order to save resources during work hours.
Increase the delta between the two periodics in order to reduce
collisions.
Kind was changed to `"At 23:00 on Saturday”`.
K3d was changed to `“At 21:00”`.
Note:
We can even consider to remove kind periodic, 
or maybe bump it from 1.23 to 1.25 but without cpu manager
tests and config, and keep the periodic of it.
> kubevirt, periodics, SR-IOV: Reduce rate

- github/ci/prow-deploy/files/orgs.yaml
- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
- github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
- github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Also configure prow plugins to enable tide on sig-release PRs.
Add a new sig-release label.
Originated from [Slack thread](https://kubernetes.slack.com/archives/C0163DT0R8X/p1678956725745269)
/cc @acardace @aburdenthehand @fabiand @xpivarc @rthallisey
> Create sig-release repo and release-team

- images/shared-images-controller/main.go
Currently the `shared-images-controller` is failing to pull the k8s-1.26 provider image as the provider[1] was removed and is no longer published. 
Updated to temporarily handle the new provider name for 1.26 - `k8s-1.26-centos9`
Also removed the return - as if it fails to pull the first image, we still want it to continue to try to download the rest. 
[1] https://github.com/kubevirt/kubevirtci/pull/969
> Update 1.26 kubevirtci image name to match provider name

- github/ci/prow-deploy/kustom/overlays/workloads-production/resources/shared-images-controller.yaml
Updating the shared images controller daemonset to the latest `quay.io/kubevirtci/shared-images-controller:v20230323-979a45c` to consume the recent change[1] to allow for the centos stream 9 based 1.26 kubernetes provider.
[1] https://github.com/kubevirt/project-infra/pull/2659
/cc @enp0s3 @dhiller
> Bump shared images controller to the latest published image

- external-plugins/rehearse/Makefile
- external-plugins/rehearse/plugin/handler/handler.go
- external-plugins/rehearse/plugin/handler/handler_test.go
- hack/print-workspace-status-no-git-tag.sh
Add support to select jobs for rehearsal from the set of changed jobs by commenting with
/rehearse job-name-1
...
/rehearse job-name-n
Also refine command matching to allow spaces after blank /rehearse commands.
/cc @brianmcarey @xpivarc @enp0s3 @ormergi
> Add support for /rehearse <job-name>

- github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
This adds a presubmit for testing in the containerdisks repo.
> feat(containerdisks): Add presubmit test job

- github/ci/prow-deploy/files/orgs.yaml
mykaul is no longer involved with the KubeVirt community so removing from the github org
/cc @dhiller @dankenigsberg
> Remove mykaul from kubevirt org

- github/ci/prow-deploy/files/orgs.yaml
See https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-org-github-config-updater/1641324948611928064#1:build-log.txt%3A8
> Remove fromanirh from org since user doesn't exist any more

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
The k8s-1.27 provider has been merged[1] and the check-provision presubmit is passing. We should make this job required so that we can keep this provider in a ready state for when it is needed.
[1] https://github.com/kubevirt/kubevirtci/pull/988
/cc @dhiller
> Make the 1.27 check-provision presubmit required

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
This change also removes some of the presubmit lanes that are no longer needed. 
> Migrate kubevirtci check-provision jobs to new workloads cluster

- external-plugins/rehearse/plugin/handler/handler.go
- external-plugins/rehearse/plugin/handler/handler_test.go
- github/ci/prow-deploy/kustom/base/manifests/local/prow-rehearse-deployment.yaml
Makes the rehearse plugin reply with comments on a PR in response when a user uses `/rehearse`, so that user knows what actually happened after they added their comment.
In case of `/rehearse ?` a list of all jobs for which a rehearsal can be triggered is added as comment.
In all other cases a list of jobs for which a rehearsal was triggered is added as comment.
> Add responses on rehearse

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Since moving these jobs to the new workloads cluster some performance issues. Updating the check provision jobs to match the same memory requests as the e2e jobs so that resources are split evenly across the nodes.
/cc @xpivarc
> Update kubevirtci presubmit memory requests to match e2e jobs

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.59.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
The new workloads cluster is ready for the vgpu related jobs to be scheduled there.
Periodic vgpu lane run on new cluster:
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-kind-1.25-vgpu/1646787762814193664
> Move vgpu workloads to the new workloads cluster

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.49.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.50.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.51.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.52.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.53.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.54.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.55.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.56.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.57.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.58.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.59.yaml
These workloads from the main branch have been stable on the new
cluster[1] - move over the release e2e lanes to the new cluster.
[1] https://github.com/kubevirt/project-infra/pull/2681
> Move release sig-compute and sig-operator lanes to new workloads cluster

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
This change moves the lighter jobs to the managed control plane cluster and the heavier jobs to the new workloads cluster. 
/cc @dhiller
> Move project-infra prowjobs from old workloads cluster

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Since the move it is failing:
https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/pull-project-infra-prow-deploy-test
I suggest to move it back and investigate what is wrong.
/cc @brianmcarey @enp0s3
> Revert move of prow-deploy-test

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
These lanes appear to be a bit flaky on the new cluster - move back to old cluster while issue is investigated.
/cc @dhiller
> Move kubevirtci vm provider check provisions back to old cluster

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Presubmit seems to get killed due to OOM, let's increase the memory request.
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/2717/pull-project-infra-test-github-ci-services/1648694386088742912
Successful run here:
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/2717/pull-project-infra-test-github-ci-services/1648704604306673664
> Increase memory request for test-github-ci-services

- cni-plugins/sriov-passthrough-cni/README.md
- cni-plugins/sriov-passthrough-cni/plugin/sriov-passthrough-cni
Some nodes external network interfaces have SR-IOV capabilities, including the cluster network interface.
Nothing prevent the CNI from allocating such interfaces, which if they do get allocated, the node will have network disconnection.
To prevent such cases, the 'SYSTEM_RESERVED_PFS' env var is introduced to enable users specify the interfaces the CNI should not allocate.
The CNI will not allocate interfaces that specified in the 'SYSTEM_RESERVED_PFS' env var.
The 'SYSTEM_RESERVED_PFS' env var value is expected to be in the form of comma separated list: "eno1,eno2,eno3".
> sriov-passthru-cni: Enable allocation restriction of system reserved PFs

- WORKSPACE
- external-plugins/rehearse/plugin/handler/BUILD.bazel
- go_third_party.bzl
- images/shared-images-controller/BUILD.bazel
- robots/cmd/perf-report-creator/BUILD.bazel
- robots/pkg/flakefinder/BUILD.bazel
Seems like we missed some updates for bazel workspace when the latest modifications to `go.mod` got in.
> Update bazel WORKSPACE, add missing files

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Adds the presubmits and periodics for the sigs, so that they can start testing using the k8s 1.27 provider.
/cc @rthallisey @fabiand @xpivarc @enp0s3 @brianmcarey @jean-edouard
> Add presubmits and periodics for k8s 1.27

- github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
/cc @0xFelix 
/cc @ksimon1 
/cc @akrejcir 
/cc @jcanocan 
/cc @opokornyy 
/cc @codingben 
The Red Hat CNV Infra team would like to adopt the use of the help prow plugin and commands across a number of projects where we are the main contributors. More details on the plugin available here:
https://www.kubernetes.dev/docs/guide/help-wanted/
> Add the help plugin to a number of projects

- github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
This adds individual presubmit jobs for artifacts which run depending on
the changed files.
It also lowers the timeout of existing presubmits and drops unnecessary
privileges for the containerdisks repo.
Merge after #https://github.com/kubevirt/containerdisks/pull/66
> feat(virtctl): Add individual presubmit jobs for artifacts 

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
This also includes moving the windows, sig-performance and sig-monitoring lanes to the new cluster.
A successful run of a periodic sig-storage lane against the new cluster:
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.25-sig-storage/1648756366325583872
> Move sig storage e2e jobs for main branch to new cluster

- github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
Always run the cirros pipeline to have at least one pipeline job which is required to merge a PR. The optional attribute is dropped from all other pipeline jobs because it has no effect on conditional jobs.
> containerdisks: Always run cirros pipeline

- cni-plugins/sriov-passthrough-cni/README.md
- cni-plugins/sriov-passthrough-cni/plugin/sriov-passthrough-cni
Using an env var is not effective due to how the CNI is executed in k8s cluster.
Replace the `SYSTEM_RESERVED_PFS` with a file that will have the reserved system SR-IOV PF interface names.
The file can be created on the relevant nodes using MachineConfig API.
> sriov-passtru-cni: Use file instead of env var for reserved ifaces

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
In the past it was forgotten to update the bazel configurations after changes were merged. Thus we introduce a presubmit that checks whether the config files need an update.
Example run against https://github.com/kubevirt/project-infra/pull/2703 here: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/2703/pull-project-infra-test-bazel-config/1649399907032764416
> Introduce check for bazel configurations

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.49.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.50.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.51.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.52.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.53.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.54.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.55.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.56.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.57.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.58.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.59.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
The new cluster is now able to take SRIOV workloads. Move the existing SRIOV jobs to the new cluster.
Successful periodic run against the new cluster:
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-k3d-1.25-sriov/1649327589547839488
> Move SRIOV e2e prow jobs to the new cluster

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- robots/cmd/test-label-analyzer/BUILD.bazel
- robots/cmd/test-label-analyzer/Makefile
- robots/cmd/test-label-analyzer/README.md
- robots/cmd/test-label-analyzer/cmd/BUILD.bazel
- robots/cmd/test-label-analyzer/cmd/filter.go
- robots/cmd/test-label-analyzer/cmd/root.go
- robots/cmd/test-label-analyzer/cmd/stats.go
- robots/cmd/test-label-analyzer/cmd/stats.gohtml
- robots/cmd/test-label-analyzer/cmd/stats_test.go
- robots/cmd/test-label-analyzer/cmd/test_suite_test.go
- robots/cmd/test-label-analyzer/cmd/testdata/BUILD.bazel
- robots/cmd/test-label-analyzer/cmd/testdata/migration_test.go.ginkgooutline.json
- robots/cmd/test-label-analyzer/cmd/testdata/simple_test.go
- robots/cmd/test-label-analyzer/main.go
- robots/pkg/test-label-analyzer/BUILD.bazel
- robots/pkg/test-label-analyzer/config.go
- robots/pkg/test-label-analyzer/ginkgo.go
- robots/pkg/test-label-analyzer/stats.go
- robots/pkg/test-label-analyzer/stats_test.go
- robots/pkg/test-label-analyzer/test_suite_test.go
- robots/pkg/test-label-analyzer/time.go
- robots/pkg/test-label-analyzer/time_test.go
See kubevirt/project-infra#2679
This PR introduces a new cli for analysis of label data from tests inside a given code base.
Initial target is of course `kubevirt/kubevirt`, but might be useful for other [Ginkgo] V2 based projects as well.
The PR also creates a periodic job that leverages the cli to generate an html page of tests in quarantine for kubevirt/kubevirt, example output here: https://storage.googleapis.com/kubevirt-prow/reports/quarantined-tests/kubevirt/kubevirt/index.html
The cli is able to work in a more generalized style of using a test config in yaml form
```yaml
File: /tmp/analyzer-config.json                  
────────────────────────────────────────────────────────────────────
{                                                                   
"categories": [ …
```
> Test tooling: introduce test-label-analyzer cli - generate a page of quarantined tests for kubevirt/kubevirt

- github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.53.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.58.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.65.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.79.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.85.yaml
The CNAO e2e lanes for the main branch have been running ok against the new workloads cluster[1] so the release lanes can now be moved over.
[1] https://github.com/kubevirt/project-infra/pull/2697
> Move CNAO release lanes to the new workloads cluster

- WORKSPACE
- external-plugins/rehearse/plugin/handler/BUILD.bazel
- external-plugins/rehearse/plugin/handler/handler.go
- external-plugins/rehearse/plugin/handler/handler_test.go
- go.mod
- go.sum
- go_third_party.bzl
The comparison for jobs to be rehearsed was done only by the Spec field, which lead to jobs moving to another cluster not being rehearsable. This fix extends the comparison to the complete job, while also fixing a field after the jobs are loaded in order to avoid the comparison always failing.
Reviewer note: the first commit fixed an issue that when make gazelle-update-repos was called led to the fix from dependabot regarding opencontainers bump being reverted. This was done by moving the opencontainers/runc bump into a replace.
> rehearse plugin: fix comparison of jobs

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
- github/ci/prow-deploy/kustom/base/manifests/local/prow-rehearse-deployment.yaml
Instead of using the pure bazel target we override the stamping inside the Makefile to use a short version for the tag.
We also update the image for rehearse plugin to include fix from #2737
> Use make target for rehearse push

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.57.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.58.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.59.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Successful run of 1.25 network periodic:
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.25-sig-network/1653466335042080768
/cc @dhiller
> Move network kubevirt e2e lanes to the new workloads cluster

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
There are two nodes that have GPUs for vgpu testing. The anti-affinity should stop the jobs from being scheduled on the same node so the max concurrency should be increased from 1 to make use of our GPU nodes.
/cc @jean-edouard @fossedihelm @dhiller
> Increase max concurrency of vpgu e2e lane to 2

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
This reverts commit 32ccf98bb85741fb56d9dd53f2d4a3c41b7ce5e5.
There has been a significant degradation in the vgpu lane performance since this change which suggests collisions in the jobs.
https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-kind-1.25-vgpu
> Revert "Increase max concurrency of vpgu e2e lane to 2 (#2747)"

- github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
Theses jobs should be moved to the new workloads cluster as the old cluster has been reduced in size to prepare for decommissioning.
/cc @0xFelix
> Move containerdisks e2e jobs to new workloads cluster

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The `pull-kubevirt-e2e-arm64` lane appears to be very flaky recently[1] - this is causing a lot of noise for contributors on PRs and as the lane is not required lets skip reporting until the stability improves
[1] https://testgrid.kubernetes.io/kubevirt-presubmits#pull-kubevirt-e2e-arm64
/cc @zhlhahaha @dhiller
> Skip reporting on the arm64 e2e jobs due to flaky lane

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.58.yaml
The 0.58 sig network lanes are hitting DNS issues on the new cluster
Move them to the old cluster until the issue is resolved
> Move sig-network lanes for 0.58 back to old workloads cluster

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The fossa check has been failing constantly for the past couple of months so it is not adding any useful feedback to PRs - skip reporting the presubmit result until the issue is resolved.
> Skip reporting on the failing fossa presubmit check

- OWNERS
- OWNERS_ALIASES
According to the [prow documentation](https://docs.prow.k8s.io/docs/components/plugins/approve/approvers/#overview) `OWNERS` files contain either references to GitHub users or to groups of users, which are defined in `OWNERS_ALIASES`. Since we didn't reference `ci-maintainers` the group actually was not used.
This PR adds the group `ci-maintainers` from `OWNERS_ALIASES` to `reviewers` and `approvers` in `OWNERS`.
(we could argue about whether we want to add this group to approvers in order to reduce the load of reviews for ci-maintainers group)
FYI @xpivarc
> Actually use ci-maintainers alias

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
Some release prowjobs run dnf transactions which can fail due to a missing old cri-o mirror repo[1] - lets add the old mirrors back to cover these backport cases.
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/1557/pull-e2e-cnao-monitoring-k8s-release-0.79/1661383673036935168#1:build-log.txt%3A446
/cc @dhiller @phoracek
> Add older versions of cri-o to mirror for backports

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
This increases the timeout of the sig-monitoring e2e tests to 2h0m0s so the whole testsuite has enough time to finish.
Fixes CI failures in https://github.com/kubevirt/kubevirt/pull/9724
> Increase sig-monitoring e2e test timeout

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
According to testgrid the presubmit lanes should be good to go for gating. This PR enables gating for sig-operator, sig-compute, sig-network and sig-storage presubmit lanes.
See https://testgrid.k8s.io/kubevirt-presubmits#pull-kubevirt-e2e-k8s-1.27-sig-compute&width=20
/cc @rthallisey @acardace @phoracek @awels
> Make 1.27 sig lanes gating

- external-plugins/rehearse/plugin/handler/handler.go
- external-plugins/rehearse/plugin/handler/handler_test.go
Currently all rehearsal jobs that are created by the plugin are targeting the HEAD branch (usually main).
Since there are jobs that are targeting other branches, i.e. release branch jobs, we run rehearsals against the correct branch(es) when doing the rehearsal.
Closes #2783 
/cc @brianmcarey @qinqon
> rehearse-plugin: checkout branch(es) from job spec

- images/vm-image-builder/Dockerfile
- images/vm-image-builder/README.md
- images/vm-image-builder/qemu.conf
- images/vm-image-builder/start_libvirtd.sh
In order to use vm-image-builder to build multi-arch VM image and make it works in prow CICD pipeline. Some update are needed.
> vm-image-builder: update vm-image-builder

- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
This Pull Request adds a new testing lane for CDI with `local` Storage Class as default.
This non-CSI lane will allow us to keep testing the non-populator flow once https://github.com/kubevirt/containerized-data-importer/pull/2722 is merged.
> Add CDI non-CSI lane

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
The bump kubevirtci presubmit job fails to get scheduled due to this selector.
This change also moves the periodic to the control plane cluster.
/cc @dhiller
> Remove bare-metal selector as running on control-plane cluster

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
- github/ci/prow-deploy/hack/test.sh
- github/ci/prow-deploy/kustom/base/manifests/local/prow-rehearse-deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/local/release-blocker_deployment.yaml
- github/ci/prow-deploy/kustom/components/greenhouse/base/resources/deployment.yaml
- github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/ci-usage-exporter-deployment.yaml
- github/ci/prow-deploy/molecule/default/converge.yml
- github/ci/prow-deploy/molecule/default/retry-pod-status.yml
- github/ci/prow-deploy/molecule/default/smoke_tests.yml
Whenever the cluster is loaded the job [project-infra-prow-deploy-test](https://prow.ci.kubevirt.io/?type=presubmit&job=pull-project-infra-prow-deploy-test) is very flaky and fails more than half of the time. First on the prow deployment check and then, if the former passes, on the ingress deployment. Also when the job fails it doesn't even capture the artifacts that are required to debug the failures.
This PR fixes these three main issues in the prow-deploy presubmit. Besides that it increases the cpu resources.
We are seeing that if the cluster is loaded the step deploying the prow components does not get ready in time. Therefore we should use exponential backoff in order to cope with deployments taking longer.
Instead of polling pods on a constant delay we
* increase the initial delay, …
> Reduce retries, add exponential backoff

- robots/cmd/test-label-analyzer/cmd/stats.go
- robots/pkg/test-label-analyzer/stats.go
- robots/pkg/test-label-analyzer/stats_test.go
Job creating the quarantined tests html page is failing: https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/logs/periodic-kubevirt-quarantined-tests-daily-report
Adjust to the special case where there's a filename inside the blame info due to file renaming.
> Fix git blame extraction regex

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
It will run sanity check to see it pass,
run the unit tests,
and show what would happen once the PR is merged
(i.e which providers will be rebuilt and which retagged).
Depends on https://github.com/kubevirt/kubevirtci/pull/982
> provision manager: Add presubmit job

- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
This Pull Request updates the non-csi lane in CDI to make it mandatory.
> Make non-csi lane in CDI mandatory

- images/bootstrap/Dockerfile
- images/golang/Dockerfile
- Update base image for bootstrap to Fedora 38 : Fedora 38 was released a few weeks ago - update bootstrap to fedora 38 base.
- Upgrade go to version 1.19.9 in golang bootstrap : The builder image is being updated to v1.19.9[1] - this golang image used for testing should use the same version.
- This change also includes an update to bazelisk to the latest release[2]
[1] https://github.com/kubevirt/kubevirt/pull/9848
[2] https://github.com/bazelbuild/bazelisk/releases/tag/v1.17.0
> Update to Fedora 38 and go 1.19.9 in the bootstrap images

- robots/cmd/perf-report-creator/main.go
- robots/cmd/perf-report-creator/plot.go
This PR adds a flag `--since` to `weekly-graph` subcommand of perf-report-creator. 
With this subcommand even if all the data historic data exists in weekly directory 
(see [here](https://github.com/kubevirt/ci-performance-benchmarks/tree/main/weekly)) 
fixes #2816 
cc @rthallisey
> add ability to plot data after a given date

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Depends on https://github.com/kubevirt/kubevirtci/pull/1026
> presubmit, kubevirtci, vgpu: Bump to 1.27

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
When there is high disk IO on a node, we can sometimes see jobs fail due to etcd timeouts[1][2]. Update these jobs to run etcd in memory to reduce reliance on node disks.
`Error from server: error when creating "/home/prow/go/src/github.com/kubevirt/kubevirt/_out/manifests/release/kubevirt-cr.yaml": etcdserver: request timed out`
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/9848/pull-kubevirt-e2e-k8s-1.27-sig-operator/1666679307365257216#1:build-log.txt%3A2065
[2] https://search.ci.kubevirt.io/?search=etcdserver%3A+request+timed+out&maxAge=336h&context=1&type=build-log&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
/cc @dhiller @EdDev @xpivarc
> Update e2e presubmits to run etcd in memory

- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Currently getting very close to 5h limit.  Going over with some new functionality.
> Give pull-containerized-data-importer-e2e-ceph 6h to complete

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
cri-o 1.27 needs to be added to the kubevirt mirror in order to allow updating of the kubevirtci 1.27 provider
/cc @dhiller
> Add crio 1.27 to the kubevirt mirror

- github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner-operator/hostpath-provisioner-operator-presubmits.yaml
The lane was marked optional which is an oversight, it should be required.
> Make hostpath provisioner operator unit test lane required

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Hold until https://github.com/kubevirt/kubevirtci/pull/1027 get merged.
> kubevirt e2e Arm64: using kind-1.27 cluster to run e2e test on Arm64

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Once `kind-1.27-vgpu` lands on kubevirt https://github.com/kubevirt/kubevirt/pull/9893
and then need to delete the old one from kubevirtci itself.
> kubevirt, vgpu: Bump to 1.27

- github/ci/services/prometheus-stack/manifests/rules/common/node-exporter-alerting.yaml
The alerts need to get reconfigured so that they are not flapping any more, we are going to do this in a later task.
For now we are disabling them since they are creating noise which makes us not see the failing job notifications.
> Turn off flapping alerts

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Creates a job that executes the perf-report-creator robots from project-infra on a weekly basis.
This can serve as the groundwork for #2705, we could add the graph plotting etc. to the same job or create a different one.
/hold
/cc @alaypatel07 @rthallisey @xpivarc
> Create periodic job for perf-report-creator

- github/ci/services/prometheus-stack/manifests/rules/common/kubernetes-apps.yaml
- github/ci/services/prometheus-stack/manifests/rules/common/node-exporter-alerting.yaml
Disable alerts since they are flapping and creating noise:
* KubeJobCompletion
* HostUnusualDiskReadRate
* HostUnusualDiskWriteRate
> Disable flapping alerts UnusualDiskReadWrite and job

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.59.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.0.yaml
This lane was disabled in main[1] - disabling in 0.59 and 1.0 branches to unblock backports
[1] https://github.com/kubevirt/project-infra/pull/2846
/cc @dhiller @rmohr @enp0s3 @xpivarc
> Disable pull-kubevirt-apidocs for 0.59 & 1.0 branches 

- images/bootstrap/runner.sh
We should rely on podman to cleanup all of the created containers as part of the e2e tests.
`podman rm --all --force`
The above should remove all containers and we should not hit the dependent containers issue[1] that we can hit with the current cleanup.
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/9974/pull-kubevirt-e2e-k8s-1.25-sig-storage-1.0/1673289162947563520#1:build-log.txt%3A3103
[2] https://docs.podman.io/en/latest/markdown/podman-rm.1.html#all-a
/cc @enp0s3 @xpivarc
> Use --all flag when cleaning up podman containers in bootstrap pod

- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
As the e2e jobs run the builds unnested - the bazel version set in the preset should match that of the kubevirt builder image[1]
[1] https://github.com/kubevirt/kubevirt/blob/d89207bd558440af2c273870540093951a82e97c/hack/builder/Dockerfile#L6
/cc @xpivarc @enp0s3
> Update preset bazel version to match kubevirt builder image

- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
The linter lane needs to compile some go code soon, modifying the used container to be a golang container
> CDI linter lane use golang container

- github/ci/prow-deploy/files/orgs.yaml
Andrew and Lubo are helping out with releases. They need write permissions to make and edit releases.
> Give aburdenthehand and xpivarc 'write' permissions to help out with kubevirt/kubevirt releases

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Istio should run fine now with CentOS Stream 9.
> kubevirt-presubmits: Enable Istio tests to run with 1.26 CentOS Stream 9

- github/ci/services/prometheus-stack/manifests/rules/common/kubernetes-apps.yaml
Alerts `KubeJobFailed` display neither the actual job name nor the namespace that has failed, i.e. https://cloud-native.slack.com/archives/C02GACK29RV/p1688376657114679
See https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/runbook.md#alert-name-kubejobfailed
> Fix label names in rule
