kubevirt/project-infra

github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits-0.52.yaml

Add presubmit jobs for knmstate release-0.52

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt.github.io/kubevirt-github-io-presubmits.yaml

Remove linter for now

---

github/ci/prow-deploy/files/orgs.yaml

Set default branch to main for cdi-api-reference repo

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.46.yaml

Manual run of the config-forker from test-infra for 0.46

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Make the arm presubmit not run always

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Add nonroot gpu lane

---

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml

(CDI) Add optional lanes to test a transition to newer k8s providers

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

fix missing project-infra error in e2e test on ARM

---

github/ci/prow-deploy/files/orgs.yaml

Signed-off-by: João Vilaça <jvilaca@redhat.com>
Sponsors:
@maiqueb [kubevirt#6613#1](https://github.com/kubevirt/kubevirt/pull/6613#issuecomment-944114508)
@rmohr [kubevirt#6613#2](https://github.com/kubevirt/kubevirt/pull/6613#issuecomment-944118051)

Add machadovilaca as member

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

fix missing kubectl-path error

---

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-postsubmits.yaml

HCO: move post submit to prow-workloads

---

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml

/hold
waiting for kubevirt/hyperconverged-cluster-operator#1592

HCO: add presubmit test to check the test util image before merging the PR

---

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml

HCO: fix wrong image tag for quay.io/kubevirtci/bootstrap

---

github/ci/prow-deploy/files/orgs.yaml

Also, update the members for must-gather team.

add new group to allow rerun jobs in HCO

---

github/ci/prow-deploy/files/orgs.yaml

Add cwilkers to web maintainers

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.47.yaml

add presubmit job for branch release-0.47

---

github/ci/prow-deploy/files/orgs.yaml

Changes suggested in kubevirt-dev mailing list by @mazzystr 

Update to GitHub website and user-guide repos

---

github/ci/prow-deploy/files/orgs.yaml
github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml

The repo will be used for creating Dockerfiles which are officially maintained by KubeVirt.

Integrate kubevirt/containerdisks repo with prow

---

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml

remove nodeSelector leftovers

---

images/bootstrap/Dockerfile

Bump bootstrap base image

---

github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml

knmstate: fix typo

---

github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml

HCO remove the requied coverage/coveralls check, to solve a github issue

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml

Remove check-provision-k8s-1.19 as k8s-1.19 was removed

---

github/ci/prow-deploy/files/orgs.yaml

* @AlonaKaplan 
* @EdDev 
- https://github.com/kubevirt/kubevirt/pull/6766
- https://github.com/kubevirt/kubevirt/pull/6774
- https://github.com/kubevirt/kubevirt/pull/6797
- https://github.com/kubevirt/kubevirt/pull/6838
- https://github.com/kubevirt/kubevirt/pull/6856
Signed-off-by: Orel Misan <omisan@redhat.com>

Add orelmisan to the organization

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml

Rebuild golang image if bootstrap changes

---

github/ci/prow-deploy/files/jobs/kubevirt/cluster-api-provider-kubevirt/OWNERS
github/ci/prow-deploy/files/jobs/kubevirt/cluster-api-provider-kubevirt/cluster-api-provier-kubevirt-presubmits.yaml

Temporary job to demonstrate kubevirtci and kubevirt prow with capik.

Add e2e validation job for capik

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
robots/cmd/kubevirtci-presubmit-remover/BUILD.bazel
robots/cmd/kubevirtci-presubmit-remover/main.go
robots/cmd/kubevirtci-presubmit-remover/main_test.go

Also use pr-creator image for the job that adds presubmits for new
kubevirtci providers.
/cc @enp0s3

Add job to remove kubevirtci presubmits for unsupported providers

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml

See https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirtci-provider-presubmit-remover/1465348864146935808
/cc @enp0s3 @fgimenez

Fix bazel call of presubmit-remover

---

github/ci/prow-deploy/files/orgs.yaml

1.  I have reviewed the community code of conduct (https://github.com/kubevirt/kubevirt/blob/master/CODE_OF_CONDUCT.md)
2.  I have enabled 2FA on my GitHub account (https://github.com/settings/security)
3.  I have subscribed to the kubevirt-dev e-mail list (https://groups.google.com/forum/#!forum/kubevirt-dev)
4.  I am actively contributing to KubeVirt
5.  I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
6.  I have spoken to my sponsors ahead of this application and they have agreed to sponsor my application
7.  I have publicly introduced myself to the community through one of the community communication channels (https://github.com/kubevirt/community#socializing)
@iholder-redhat 
@stu-gott 
https://github.com/kubevirt/kubevirt/pull/6724 …

Add Barakmor1 to the community

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.48.yaml

add presubmit job for branch release-0.48

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml

/cc @kubevirt/prow-job-taskforce

Ping prow job task force to review automated Prow bump PRs

---

github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml

The post submit job publish and release need to be fixed too. This
change use the golang image and the GIMMI env var and also align release
with publish job.

knmstate: Use golang image at postsubmit

---

github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml

Knmstate release add GitHub token

Knmstate release add GitHub token

---

github/ci/prow-deploy/files/orgs.yaml

Make maintainers admin for branch-protection to work

---

github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml

Fix qe-tools path in branch-protection config

---

github/ci/prow-arm-workloads/bootstrap.yml
github/ci/prow-arm-workloads/hack/bootstrap.sh
github/ci/prow-arm-workloads/hack/common.sh
github/ci/prow-arm-workloads/hack/deploy.sh
github/ci/prow-arm-workloads/inventory/prow-arm-workloads/group_vars/all/all.yml
github/ci/prow-arm-workloads/inventory/prow-arm-workloads/group_vars/all/docker.yml
github/ci/prow-arm-workloads/inventory/prow-arm-workloads/group_vars/etcd.yml
github/ci/prow-arm-workloads/inventory/prow-arm-workloads/group_vars/k8s-cluster/addons.yml
github/ci/prow-arm-workloads/inventory/prow-arm-workloads/group_vars/k8s-cluster/k8s-cluster.yml
github/ci/prow-arm-workloads/inventory/prow-arm-workloads/group_vars/k8s-cluster/k8s-net-calico.yml
github/ci/prow-arm-workloads/inventory/prow-arm-workloads/inventory.ini
github/ci/prow-arm-workloads/roles/bootstrap/tasks/additional_kernel_modules.yml
github/ci/prow-arm-workloads/roles/bootstrap/tasks/main.yml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml

Add ARM cluster deployment jobs

---

github/ci/prow-deploy/files/orgs.yaml

@razo7
* @slintes 
* @dhiller 
- https://github.com/kubevirt/node-maintenance-operator/pull/168
- https://github.com/kubevirt/node-maintenance-operator/pull/169
- https://github.com/kubevirt/node-maintenance-operator/pull/170
- none yet

Add Or Raz to org members

---

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.5.yaml

Since it is broken and no longer supported
Signed-off-by: orenc1 <ocohen@redhat.com>

[HCO] Deprecating k8s-1.19 lane for release-1.5

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Fix presubmit and periodic TARGET value for k8s-1.23

---

github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.65.yaml

A new stable branch on CNAO was created.

Register CI for CNAO's release-0.65

---

github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits-0.64.yaml

knmstate: Add release-0.64 jobs

---

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-postsubmits.yaml

Fix errors regarding secret mounts and presets. Also set -e on so that the build directly terminates on error.

Add missing secret mount, activate quay preset

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.49.yaml

add presubmit job for branch release-0.49

---

github/ci/services/prometheus-stack/manifests/stack/production-control-plane/thanos.yaml

Increase resources for thanos-query and thanos-store

---

hack/update-jobs-with-latest-image.sh

Instead of sorting we just use the last entry of the list of tags.
/cc @fgimenez @brianmcarey

Use latest image tag by fetching the last list entry

---

github/ci/prow-deploy/vars/ibmcloud-production/main.yml
github/ci/prow-deploy/vars/workloads-production/main.yml

Remove explicit path for kubectl to use binary in PATH

---

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml

Trying to understand what is happening since we bumped img in #1616, until then, lets rollback the image bump

Rollback bootstrap image on some CDI lanes

---

github/ci/prow-deploy/files/jobs/kubevirt/user-guide/user-guide-postsubmits.yaml
github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
images/kubevirt-user-guide/Dockerfile

Partially fixes: https://github.com/kubevirt/user-guide/issues/430

Changing default branch of user-guide repo to main

---

images/README.md

Describes how to build and publish the images. Also describes how to
update the prow job configurations.
/cc @brianmcarey @slintes @machadovilaca

Add README for images folder

---

github/ci/prow-deploy/files/orgs.yaml

* @dhiller 
* @jean-edouard 
- [kubevirt/kubevirt/#6681](https://github.com/kubevirt/kubevirt/pull/6681)
- [kubevirt/kubevirt/#6725](https://github.com/kubevirt/kubevirt/pull/6725)
- [kubevirt/kubevirt/#6741](https://github.com/kubevirt/kubevirt/pull/6741)
- [kubevirt/kubevirt/#6762](https://github.com/kubevirt/kubevirt/pull/6762)
- [kubevirt/kubevirt/#6780](https://github.com/kubevirt/kubevirt/pull/6780)
- [kubevirt/kubevirt/#6814](https://github.com/kubevirt/kubevirt/pull/6814)
- [kubevirt/kubevirtci/#709](https://github.com/kubevirt/kubevirtci/pull/709)
- [kubevirt/user-guide/#505](https://github.com/kubevirt/user-guide/pull/505)
- [kubevirt/kubevirt/#6931](https://github.com/kubevirt/kubevirt/pull/6931) …

Add fossedihelm to org member

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Also rename it accordingly.
/cc @iholder-redhat @vasiliy-ul

Bump sig-compute 1.20 cgroupsv2 lane to 1.23

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Bump nonroot lanes to 1.23

---

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.6.yaml

HCO: Add tests for the new release-1.6 branch

---

OWNERS

Add brianmcarey to reviewers in OWNERS

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml

Add presets for github credentials to project infra presubmit

Add presets for github credentials to project infra 

---

github/ci/prow-deploy/files/jobs/kubevirt/user-guide/user-guide-presubmits.yaml

Signed-off-by: jbpratt <jbpratt78@gmail.com>

user-guide: check-links presubmit

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Rename the NonRoot featureGate to correct one

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

This seems to be needed for an unknown reason.

Set storage backend for migrations lanes

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml

Remove check-provision for 1.20 providers

---

github/ci/prow-deploy/files/orgs.yaml

* @AlonaKaplan
* @maiqueb 
**PRs reviewed and/or authored** 
- https://github.com/kubevirt/kubevirt/pull/7074
- https://github.com/kubevirt/kubevirt/pull/7051
- https://github.com/kubevirt/kubevirt/pull/7023
- https://github.com/kubevirt/kubevirt/pull/6833
**Issues responded to** 
- https://github.com/kubevirt/kubevirt/issues/6538
Signed-off-by: Diana Teplits [dteplits@redhat.com](mailto:dteplits@redhat.com)

Add dteplits to the organization

---

github/ci/prow-deploy/files/jobs/kubevirt/community/community-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
hack/update-jobs-with-latest-image.sh

Also fix small error in the update-jobs script (optional 'v' in image
tag)
Fixes #1933
/cc @brianmcarey @enp0s3 @rmohr

Update kubevirt builder image for newer bazel version

---

github/ci/prow-deploy/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-presubmits-release-0.11.yaml

- postsubmit was calling too many targets
- added release-0.11 presubmit

Fix postsubmit, add release-0.11 config

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Signed-off-by: Ryan Hallisey <rhallisey@nvidia.com>
Fixes: https://github.com/kubevirt/project-infra/issues/1947

Run performance precheck only when kubevirt core components change

---

github/ci/prow-deploy/files/orgs.yaml

Also create GitHub teams for the repo as kickstart.
/cc @ksimon1 @dominikholler 
Please note that after this PR got merged you may get an invite from GitHub that you need to accept in order to be able to access the repository.

Create tekton-tasks-operator project repo

---

github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml

See https://github.com/goproxyio/goproxy/issues/198#issuecomment-1069060125
/cc @rmohr @brianmcarey @enp0s3

Remove goproxy.io for INTERNAL_ERROR issue

---

github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml

This PR adds a new monitoring lane that runs prometheus related tests.

cnao, Add e2e monitoring lane

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
robots/pkg/kubevirt/cmd/remove/testdata/should_modify/kubevirt-periodics.yaml
robots/pkg/kubevirt/cmd/remove/testdata/should_not_modify/kubevirt-periodics.yaml

Update deprecated argument from `--noColor` to `--no-color`

Adapt to ginkgo 2.0 params

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

kubevirt-builder: Add manual build job

---

github/ci/services/prometheus-stack/manifests/stack/production-control-plane/grafana.yaml

Update prow job load with alerting

---

github/ci/prow-deploy/files/orgs.yaml

@lyarwood
* @davidvossel 
* @vladikr 
-  https://github.com/kubevirt/kubevirt/pull/7241
-  https://github.com/kubevirt/kubevirtci/pull/743
-  https://github.com/kubevirt/community/pull/165

Add lyarwood to the org

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml

Signed-off-by: Ryan Hallisey <rhallisey@nvidia.com>
depends-on: https://github.com/kubevirt/kubevirt/pull/7265

Use the load generators refactored config

---

hack/flake-report-creator.sh
robots/cmd/flake-report-creator/cmd/jenkins.go

In case of no latest build for a job found there is a 404 returned. In
that case we must not exit but just return.
/cc @brianmcarey @rmohr

flake-report-creator: no latest build fix

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.50.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.51.yaml

/cc @brianmcarey @rmohr 
FYI @fossedihelm @davidvossel 
See kubevirt/project-infra#1563

Add kubevirt/kubevirt job config forks for 0.50 and 0.51

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml

Use less CI resources at no impact.

Switch retest-bot to use /retest-required

---

github/ci/services/prometheus-stack/manifests/stack/production-control-plane/grafana.yaml

https://grafana.com/docs/grafana/latest/alerting/unified-alerting/opt-in/

Enable Grafana unified alerting

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml

checkconfig image is quite outdated, we need to update it.

Update config-check image

---

github/ci/prow-deploy/files/orgs.yaml

Add igor to prow taskforce

---

github/ci/prow-deploy/files/jobs/kubevirt/cloud-provider-kubevirt/cloud-provider-kubevirt-presubmits.yaml

Signed-off-by: Nir Argaman <nargaman@redhat.com>

cloud-provider-kubevirt: Make unit-tests presubmit mandatory

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

The successful run can be seen https://github.com/kubevirt/kubevirt/pull/7442#issuecomment-1084938684

Require pull-kubevirt-e2e-kind-1.23-vgpu-nonroot

---

images/bootstrap/README.md
images/bootstrap/runner.sh

In order to debug the "unknown blob" error when pushing to quay repositories, we enable the docker debug log.
This PR also contains a job that was modified to use it.
/cc @brianmcarey @slintes

Add docker debug

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Fix wrong revert of the regular network nonroot job and revert now the right job.

Revert sriov rootless

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Move all non sriov jobs to non sriov nodes

---

github/ci/services/prometheus-stack/manifests/stack/production-control-plane/grafana.yaml

Update branch name for Tide Daily Merge Rate grafana panel

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Allow regular e2e workloads to be scheduled on SR-IOV nodes

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.30.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.34.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.36.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.37.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.38.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.39.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.40.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.41.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.42.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.43.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.44.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.45.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.46.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.47.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.48.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.49.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.50.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.51.yaml

Add priority classes to sriov and vgpu

---

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml

Had an 'o' instead of 'p' in script name

Typo in one the new CDI lanes

---

github/ci/prow-deploy/kustom/overlays/workloads-production/resources/bootstrap.yaml

Relabel the nodes on every deployment rollout.

Add node label configuration to prow config

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml

kubevirtci: Add alpine provision presubmit job

---

github/ci/prow-deploy/files/orgs.yaml

@alromeros
- @aglitke 
- @awels 
- https://github.com/kubevirt/containerized-data-importer/pull/2222

Request adding alromeros to org members

---

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml

Signed-off-by: orenc1 <ocohen@redhat.com>

Bump kubevirtci test lane in HCO to k8s-1.23

---

github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml

Topics related to code-quality are now discussed in a dedicated forum.
Having a label assigned to PR/s will allow to distinguish and filter
the work.

labels: Introduce a new sig/code-quality label

---

github/ci/prow-deploy/files/jobs/kubevirt/common-templates/common-templates-periodics.yaml

Update base image common templates jobs

Update base image common templates jobs

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-velero-plugin/kubevirt-velero-plugin-presubmits.yaml
github/ci/testgrid/gen-config.yaml

Add plugin to testgrid dashboard

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Increase kubevirt mem and job memory
fixes: https://github.com/kubevirt/kubevirt/issues/7658

Increase performance job memory

---

github/ci/prow-deploy/files/jobs/kubevirt/secrets/secrets-presubmits.yaml
github/ci/prow-deploy/files/orgs.yaml
github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml

Adds a presubmit to check whether the files can get decrypted by the
key prow uses. Also enabled configuration for lgtm, approve,
branch-protection and tide.
/cc @xpivarc @brianmcarey @enp0s3

Add presubmit for decryption checking

---

OWNERS

Add brianmcarey to approvers in OWNERS

---

github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-periodics.yaml

This update includes the fix to the sorting algorithm from 8aeca1a5 .
/cc @brianmcarey @enp0s3 @qinqon

Update flakefinder images with sort fix

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.53.yaml

Release configs for kubevirt/kubevirt release branch release-0.53

---

github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.76.yaml

cnao, Add a new stable branch release-0.76

---

github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits-v0.38.yaml

kmp, add a new stable branch release_v0.38

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.47.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.48.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.49.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.50.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.51.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.52.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

The test suite looks specifically for `NonRoot`

Use NonRoot instead of NonRootExperimental

---

github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.65.yaml

cnao: add monitoring lane for release-0.65

---

github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.76.yaml

cnao: add monitoring lane to release-0.76

---

github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml

/cc @brianmcarey @jean-edouard

Add custom highlighter patterns for kubevirt

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-velero-plugin/kubevirt-velero-plugin-periodics.yaml
github/ci/testgrid/gen-config.yaml

Add periodic job for kubevirt-velero-plugin

---

github/ci/prow-deploy/files/orgs.yaml

@kvaps
* @maiqueb
* @dhiller
PRs reviewed and/or authored
* https://github.com/kubevirt/kubevirt/pull/7648
* https://github.com/kubevirt/kubevirt/pull/7768
* https://github.com/kubevirt/kubevirt/pull/7769
* https://github.com/kubevirt/macvtap-cni/pull/59
* https://github.com/kubevirt/macvtap-cni/pull/67

Add kvaps to org members

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml

Also remove the 1.19 sriov check

Add 1.23 vgpu cluster up check

---

github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml

We add a couple of labels to better determine and be able to group
issues and PRs.
Also some label issues are fixed.

Update labels for project-infra, fix some issues

---

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.7.yaml

HCO: Add tests for the new release-1.7 branch

---

github/ci/prow-deploy/files/orgs.yaml

Signed-off-by: prnaraya <prnaraya@redhat.com>
@prnaraya
* @ksimon1
* @jean-edouard 
- [kubevirt/kubevirt#6913](https://github.com/kubevirt/kubevirt/pull/6913)
- [kubevirt/kubevirt#6956](https://github.com/kubevirt/kubevirt/pull/6956)
- [kubevirt/kubevirt#7093](https://github.com/kubevirt/kubevirt/pull/7093)
- [kubevirt/kubevirt#7494](https://github.com/kubevirt/kubevirt/pull/7494)
- [kubevirt/common-templates#449](https://github.com/kubevirt/common-templates/pull/449)

Add prnaraya to the org

---

github/ci/prow-deploy/files/orgs.yaml

Signed-off-by: boukhanov@redhat.com
---
@codingben
* @maya-r
* @EdDev
- https://github.com/kubevirt/kubevirt/pull/7830
- https://github.com/kubevirt/kubevirt/pull/7829
- https://github.com/kubevirt/kubevirt/pull/7828
- https://github.com/kubevirt/kubevirt/pull/7827
- https://github.com/kubevirt/kubevirt/pull/7826
- https://github.com/kubevirt/kubevirt/pull/7825
- https://github.com/kubevirt/kubevirt/pull/7824
- https://github.com/kubevirt/kubevirt/pull/7823
- https://github.com/kubevirt/kubevirt/pull/7822
- https://github.com/kubevirt/kubevirt/pull/7821
- https://github.com/kubevirt/kubevirt/pull/7820
- https://github.com/kubevirt/kubevirt/pull/7818
- https://github.com/kubevirt/kubevirt/pull/7817
- …

Add codingben to members

---

robots/cmd/flake-report-creator/cmd/jenkins.go

Extend default artifact filename regex

---

github/ci/prow-deploy/files/orgs.yaml

@usrbinkat
* @xpivarc 
* @dhiller

add member usrbinkat

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.50.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.51.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.52.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.53.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

priorityClassName has to be added to the spec section in the prowjob
definition or it does not get applied correctly.
/cc @dhiller

Fix windows priority class by adding to prowjob spec

---

github/ci/prow-deploy/files/orgs.yaml

Signed-off-by: aburdenthehand <aburden@redhat.com>
@aburdenthehand
[X] I have reviewed the community code of conduct (https://github.com/kubevirt/kubevirt/blob/master/CODE_OF_CONDUCT.md)
[X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
[X] I have subscribed to the kubevirt-dev e-mail list (https://groups.google.com/forum/#!forum/kubevirt-dev)
[X] I am actively contributing to KubeVirt
[X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
[X] I have spoken to my sponsors ahead of this application and they have agreed to sponsor my application
[X] I have publicly introduced myself to the community through one of the community communication channels
* …

Adding aburdenthehand to the KubeVirt org

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Increase node memory by 1Gb per node.

Increase node memory for perf jobs

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Monitor more folders for changes.

cgroups, storage: Add additonal folders

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml

kubevirtci, alpine: Increase timeout to 20m

---

go.mod
go.sum
robots/cmd/kubevirtperiodics/main.go

Creates a program to print out when kubevirt periodics run in human readable format. Output is like this:
```
$ go run robots/cmd/kubevirtperiodics/main.go  --job-config-path-kubevirt-periodics=/home/dhiller/Projects/github.com/kubevirt.io/project-infra/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
+------------------------------------------------------------+-------------------------------------------------+
| job_name                                                   | runs                                            |
+============================================================+=================================================+
| periodic-kubevirt-e2e-k8s-1.19-sysprep                     | At 12:00 AM                                     | …
```

Add kubevirt periodics cron timetable printer

---

hack/images_to_mirror.csv

Signed-off-by: howard zhang <howard.zhang@arm.com>

Mirror kind-node image from docker.io to quay.io

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

sig-network, ipv6: Bump provider to 1.24

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml

Increase to every 3h instead every 12h

kubevirtci kubevirt bump: Increase periodic rate

---

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml

Add optional CDI Ceph lane with DV GC enabled

---

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml

Fix CDI Ceph GC lane automation script call

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Set the 1.24 lanes to required

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.55.yaml

Release configs for kubevirt/kubevirt release branch release-0.55

---

github/ci/prow-deploy/files/jobs/kubevirt/cloud-provider-kubevirt/cloud-provider-kubevirt-presubmits.yaml

kubvirt: Add e2e job for cloud-provider-kubevirt

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Add optional sig-storage lane with DV GC enabled

---

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml

Set CDI ceph-gc lane to always_run

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Remove skip_report from DV GC lane

---

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml

Fix CDI CI presubmits skip_branches

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml

kubevirt, peridoc: Store dump at gc bucket

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.56.yaml

Release configs for kubevirt/kubevirt release branch release-0.56

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml

This periodic seems to timeout
regularly. Let's see if an additional
hour will be enough.

Single-node increase timeout

---

github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-presubmits.yaml

Add a job that runs unit tests

Add presubmit unit test job for csi-driver

---

github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner-operator/hostpath-provisioner-operator-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner/hostpath-provisioner-postsubmits.yaml

Intended to fix https://github.com/kubevirt/hostpath-provisioner/issues/98

Adjust HPP push jobs to build multi-arch images

---

github/ci/prow-deploy/files/jobs/kubevirt/libguestfs-appliance/libguestfs-appliance-periodics.yaml

Print additional information during the appliance build.

add debug info for libguestfs-appliance job

---

github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-presubmits.yaml

add linter lane to csi-driver

---

external-plugins/rehearse/plugin/handler/handler.go
external-plugins/rehearse/plugin/main.go
external-plugins/release-blocker/main.go
github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
github/ci/prow-deploy/kustom/base/manifests/local/release-blocker_deployment.yaml

Fix and enable release blocker plugin

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml

Since we are adding slim mode, increase the timeout,
to have more margin.

publish-kubevirtci: Increase timeout

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml

Fix path to kubevirt-user-guide image in build and publish

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
images/kubevirt-kubevirt.github.io/Dockerfile

- Bump Fedora from 34 to 36
- Fix packages diff between versions
- Go with system python 3.10 from Fed 36
- Fix casperjs dependency issue

Update kubevirt.github.io container Dockerfile

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
images/kubevirt-kubevirt.github.io/Dockerfile

We need ruby and other files from the kubevirt.github.io repo during build.

Update kubevirt.github.io jobs to pull from repo

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
images/kubevirt-kubevirt.github.io/Dockerfile

Replaced CWD reference in COPY

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml

Update project-infra prowjobs to use the new podman based bootstrap

---

github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-presubmits.yaml
github/ci/testgrid/gen-config.yaml

Correct the e2e test lane to execute functional tests

csi-driver presumbits: Correct e2e test lane

---

github/ci/prow-deploy/files/jobs/kubevirt/cluster-api-provider-kubevirt/cluster-api-provier-kubevirt-presubmits.yaml

capk: sonobuoy conformance lane

---

github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/ovs-cni/ovs-cni-presubmits.yaml

ovs-cni: Use podman on presubmit jobs

---

github/ci/prow-deploy/files/jobs/kubevirt/bridge-marker/bridge-marker-presubmits.yaml

bridge marker: Use podman on presubmit jobs

---

github/ci/prow-deploy/files/jobs/kubevirt/secrets/secrets-periodics.yaml

Fix secrets periodic key check clone reference

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Set always_run: true for DV GC lane

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

In #2284 it was discovered that they were missing in the job specs.

Add podAntiAffinity for vgpu presubmits

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Enable nonroot sriov

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Make DV GC lane required

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml

Remove slack notifications from vgpu periodic

---

images/kubevirt-kubevirt.github.io/Dockerfile

Keep make in the final image as well as git

---

github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml

cnao: Use podman on presubmit jobs

---

github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits.yaml

kubemacpool: Use podman on presubmit jobs

---

github/ci/prow-deploy/files/jobs/kubevirt/macvtap-cni/macvtap-cni-postsubmits.yaml

macvtap: Use podman on postsubmit jobs

---

github/ci/prow-deploy/files/jobs/kubevirt/bridge-marker/bridge-marker-postsubmits.yaml

bridge marker: Use podman on postsubmit jobs

---

github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-postsubmits.yaml

cnao: Use podman on postsubmit jobs

---

github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-postsubmits.yaml

kmp: Use podman on postsubmit jobs

---

github/ci/prow-deploy/files/jobs/kubevirt/secrets/secrets-periodics.yaml

Waiting for updates on https://github.com/kubernetes/test-infra/issues/22084

Disable slack reporting for secrets periodic

---

github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits.yaml

knmstate: Rebase on rust branch at future lane

---

github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml

k8s nmstate: Use podman on postsubmit jobs

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml

Check provision for k8s-1.24-psa

---

github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-presubmits.yaml

Add csi sanity check lane to kubevirt csi-driver presubmit

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml

Update kubevirt periodic prowjobs to use the new podman bootstrap

---

github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits.yaml

k8s-nmstate: Use podman on presubmit jobs

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.57.yaml

Release configs for kubevirt/kubevirt release branch release-0.57

---

github/ci/services/loki/manifests/common/rules.yaml

Fix yaml format for ThanosCompactHalted alert

---

docs/ci-operations-group.md

Define the group, set responsibilites and non-responsibilities, contact,
meetings etc.

Initial documentation of KubeVirt CI Operations Group

---

hack/update-dockerfiles-with-latest-image.sh
images/pr-creator/Dockerfile

Also create a script that can update Dockerfile `FROM` references to use latest image.

Update pr creator to latest bootstrap

---

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml

HCO: add lane for K8s 1.24

---

hack/clear-bazel-cache.sh

Add script to clear bazel cache

---

github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml

Adds two new labels for general usage:
* `hacktoberfest`
* `spam`

Add Hacktoberfest labels

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml

Preparation for updating golang version in project infra: https://github.com/kubevirt/project-infra/pull/2344#discussion_r982388189

Add releng presubmit

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.58.yaml

Release configs for kubevirt/kubevirt release branch release-0.58

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Update kubevirt prowjobs to use the new podman in container setup

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Update nonroot lanes to latest k8s version

---

github/ci/prow-deploy/files/jobs/kubevirt/cloud-provider-kubevirt/cloud-provider-kubevirt-presubmits.yaml

cloud-provider-kubevirt: go 1.19

---

github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.79.yaml

New stable branch of CNAO was created. This introduces a pre-submit job for it.

Add pre-submit for CNAO release-0.79

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-velero-plugin/kubevirt-velero-plugin-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-velero-plugin/kubevirt-velero-plugin-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-velero-plugin/kubevirt-velero-plugin-presubmits.yaml

Update kubevirt-velero-plugin jobs to use new podman bootstrap

---

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml

Update CDI prow jobs to use the podman bootrap

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml

Mirror cri-o version 1.25 to be used by 1.25 provider

---

github/ci/prow-deploy/files/jobs/kubevirt/kubectl-virt-plugin/kubectl-virt-plugin-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubectl-virt-plugin/kubectl-virt-plugin-presubmits.yaml

Update to kubectl-virt-plugin prowjobs to use podman

---

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.8.yaml

HCO: Add tests for the new release-1.8 branch

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml

Make check-provision job for 1.25 provider required

---

hack/generate-prow-debug-kubeconfig.sh

If there's no default ns defined in the current kubeconfig the script will fail. This commit sets an explicit ns for the secret generation and fetches, so that it will find the tokens.
/cc @EdDev @brianmcarey

Fix the namespace assignment for hack/generate-prow-debug-kubeconfig.sh

---

github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-presubmits.yaml

Update csi-driver prowjobs to use podman bootstrap

---

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml

/cc @tiraboschi @machadovilaca 

Update hco prowjobs to use the podman bootstrap image

---

github/ci/prow-deploy/files/orgs.yaml

Ad Shelly as a velero-plugin admin

---

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Remove DV GC lanes, as it is enabled by default

---

github/ci/prow-deploy/files/jobs/nmstate/nmstate/nmstate-presubmits.yaml

Update nmstate presubmit to use podman bootstrap

---

github/ci/prow-deploy/kustom/base/manifests/local/prow-rehearse-deployment.yaml

Upgrade rehearsal deployment to latest image version

---

github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml

Signed-off-by: Miguel Duarte Barroso <mdbarroso@redhat.com>

cnao: make multus-dynamic-networks lane mandatory

---

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml

Signed-off-by: Lee Yarwood <lyarwood@redhat.com>

Add common-instancetypes pre and post submit jobs

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Add optional presubmit to test cluster-sync against perf cluster

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Kubevirt merged default nonroot and therefore
changes in naming and configuration is needed

Swap root and nonroot

---

github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/ovs-cni/ovs-cni-postsubmits.yaml

Update ovs-cni postsubmit jobs to use podman

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.47.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.48.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.49.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.50.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.51.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.52.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.53.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.54.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.55.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.56.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.57.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.58.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/secrets/secrets-presubmits.yaml
github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
robots/pkg/kubevirt/cmd/remove/testdata/should_modify/kubevirt-periodics.yaml
robots/pkg/kubevirt/cmd/remove/testdata/should_not_modify/kubevirt-periodics.yaml

Adding the pgp-bot-key preset for prowjobs
Issue #2449
Signed-off-by: Rabin Yasharzadehe <rabin@redhat.com>

Replace inline pgp-bot-key volumes with a preset

---

github/ci/prow-deploy/files/jobs/kubevirt/user-guide/user-guide-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/user-guide/user-guide-presubmits.yaml

Should fix https://github.com/kubevirt/user-guide/issues/623

Use the new unified web container image for user-guide

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml

See https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/publish-kubevirtci/1596047252369969152
/cc @brianmcarey @xpivarc @Barakmor1

Increase timeout for publish kubevirtci

---

github/ci/prow-deploy/files/orgs.yaml
github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml

prow: Add KubeSecondaryDNS basic config

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

As we are trying to run parallel test on Arm64 CI server. We need the two tests to verify if parallel test works well. Hold until we put Arm64 servers into the kubevirt prow cluster.
/hold

Add unit test and e2e test for Arm64

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Add k8s-1.25-ipv6-sig-network lane.

kubevirt, presubmit: Introduce k8s-1.25-ipv6-sig-network 

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml

Switch to k8s-1.25-ipv6 (from k8s-1.24-ipv6)
Additional change:-
Bump the non required lanes to future lane k8s-1.26-ipv6
instead of deleting them and recreating next time.

single stack: Switch to k8s-1.25-ipv6

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml

See https://github.com/kubevirt/kubevirtci/pull/945

Add check-provision-k8s-1.26-centos9

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml

Add periodic test lanes for new k8s-1.26-centos9 provider

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml

Enable PSA on 1.26 provision-check presubmits

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml

Add cri-o version 1.26 to kubevirt mirror

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml

Preparation for updating golang version in project infra: https://github.com/kubevirt/project-infra/pull/2344#discussion_r982388189 and https://github.com/kubevirt/project-infra/pull/2362

Add pull-project-infra-test-github-ci-services

---

github/ci/prow-deploy/files/orgs.yaml

@jcanocan
[X] I have reviewed the community code of conduct (https://github.com/kubevirt/kubevirt/blob/master/CODE_OF_CONDUCT.md)
[X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
[X] I have subscribed to the kubevirt-dev e-mail list (https://groups.google.com/forum/#!forum/kubevirt-dev)
[X] I am actively contributing to KubeVirt
[X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
[X] I have spoken to my sponsors ahead of this application and they have agreed to sponsor my application
[X] I have publicly introduced myself to the community through one of the community communication channels
* @0xFelix 
* @xpivarc
- …

Add jcanocan tot the Kubevirt org

---

github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml

knmstate: Use podman for presubmit

---

github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml

This reverts commit 92ea80888b4c1140eae66ba3ab408d37fdb2401e.

Revert "knmstate: Use podman for presubmit"

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Due to https://github.com/kubevirt/project-infra/pull/2577#issuecomment-1406544238

Restore 1.26 compute lane name

---

releng/release-tool/release-tool.go

With the new kubevirt release process, we need to be able to create tags directly out of the main branch of kubevirt/kubevirt. This updates the release tool to be able to cut a tag directly out of an specific existing branch

Update release-tool with --existing-branch cli arg for cutting tags out of specific branches

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Make 1.26 PSA network lane gating

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Make 1.26 PSA storage lane gating

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.59.yaml

Release configs for kubevirt/kubevirt release branch release-0.59

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

There are voting jobs already and therefore
there is no need for optional ones.

Remove PSA optional jobs

---

go.mod
go.sum

See https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-project-infra-check-prow-jobconfigs/1623609676253892608

Update go.mod for job-config-validator

---

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml

common-instancetypes: Fix run_if_changed for func test

---

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml

/cc @0xFelix 
The previous attempt didn't work, so here's one final attempt with actually valid regex [1].
[1] https://regex101.com/r/dcAdWM/1

common-instancetypes: rework run_if_changed one final time

---

github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml

containerdisks - Mark both presubmits as required and increase the golang version to 1.19

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml

Remove PSA from rootful kubevirt perodic lanes

---

github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml

/cc @brianmcarey @alicefr 
FYI @aburdenthehand 
Fixes #2642

Create initial label config for good-first-issue

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Depends on https://github.com/kubevirt/kubevirtci/pull/979
Should be merged after [bump](https://github.com/kubevirt/kubevirt/pull/9384) on kubevirt.

kubevirt, vgpu: Update lane name

---

github/ci/prow-deploy/files/jobs/kubevirt/controller-lifecycle-operator-sdk/controller-lifecycle-operator-sdk-presubmits.yaml

https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_controller-lifecycle-operator-sdk/23/pull-controller-lifecycle-operator-sdk-e2e-k8s-1.18/1637548276976717824

Revert lifecycle-operator-sdk presubmit to docker

---

github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-periodics.yaml
github/ci/testgrid/gen-config.yaml

Send alert emails to fmatouschek@redhat.com and lyarwood@redhat.com for failures in the containerdisk periodics.

containerdisks: Send alert emails for failures in periodics

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Migrate sig-compute e2e lanes to the new workloads cluster

---

github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml

Move CNAO presubmits to new cluster

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml

Remove check provision lane for 1.25 PSA as no longer needed

---

external-plugins/rehearse/plugin/main.go

Improve plugin help for rehearse plugin

---

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits-1.34.yaml
github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits-1.38.yaml
github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits-1.43.yaml
github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits-1.49.yaml
github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml

Move CDI e2e lanes to the new workloads cluster

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml

Successful run here: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/publish-test-report-image/1654484003857633280

Create publish job for test-report image

---

images/kubevirt-infra-bootstrap/Dockerfile
images/prow-deploy/Dockerfile
images/ruby/Dockerfile
images/shared-images-controller/Containerfile
images/vm-image-builder/Dockerfile

Updated with `./hack/update-containerfiles-with-latest-baseimage.sh`

Bump base images for infra containers

---

github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-presubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner/hostpath-provisioner-presubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-velero-plugin/kubevirt-velero-plugin-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-velero-plugin/kubevirt-velero-plugin-presubmits.yaml

Move hpp, kvp and csi prow jobs to new workloads cluster

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml

Move kubevirtci prowjobs to new workloads cluster

---

robots/cmd/perf-report-creator/main.go
robots/cmd/perf-report-creator/plot.go

perf-report-creator: update regex and plot.go to include all graphs in one index.html

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

FOSSA job is still reporting due to this.
/cc @enp0s3 @xpivarc

Fix skip report job config attribute

---

github/ci/prow-deploy/files/orgs.yaml

Also:
* add @alaypatel07 to the org, since he's contributing to sig-scale for a while now already, see below
* create `sig-scale` GitHub team
See #2705
See https://github.com/kubevirt/community/blob/main/membership_checklist.md
@alaypatel07
@dhiller
@xpivarc 
* https://github.com/kubevirt/kubevirt/issues/8027
* https://github.com/kubevirt/kubevirt/issues/8215
* https://github.com/kubevirt/kubevirt/issues/8273
* https://github.com/kubevirt/kubevirt/issues/8541
* https://github.com/kubevirt/kubevirt/issues/8616
* https://github.com/kubevirt/kubevirt/issues/9390
* https://github.com/kubevirt/kubevirt/issues/9614
Source: https://github.com/search?q=org%3Akubevirt+author%3Aalaypatel07+is%3Apr&type=issues
* …

Create storage repo for performance data

---

hack/images_to_mirror.csv

Mirror mentioned image to quay.

mirror: Add kindest/node:v1.27.1

---

github/ci/prow-deploy/files/orgs.yaml

Currently we have old and not relevant description and it needs to be updated.
This PR is related to https://github.com/kubevirt/ssp-operator/pull/545.

docs: update ssp-operator description

---

robots/cmd/perf-report-creator/main.go

This is a follow up PR from #2741. With the change in regex, it is now also possible to scrape the sig-scale jobs in the density cluster.
The difference between the performance and density jobs is that the former has 3 different results, vmi, vm and vm with preference types, while the density jobs are specifically for vmis. 
This PR changes the code execution such that results will not be collected for vms in case of density jobs and handles other corner cases in weekly-report
cc @rthallisey

perf-report-creator: modify to scrape sig-scale jobs in density cluster

---

robots/cmd/perf-report-creator/scrape.sh

Add a script to scrape results of two jobs and aggregate it into weekly folder
as well as copy it into performance benchmark directory

add scrape.sh to automate generating weekly perf-report

---

robots/cmd/perf-report-creator/scrape.sh

stop using relative paths for OUTPUT_DIR

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml

kind-1.23-sriov doesn't exists anymore, use kind-1.27-sriov

periodic, sriov: Fix version

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.0.yaml

Release configs for kubevirt/kubevirt release branch release-1.0

---

github/ci/prow-deploy/kustom/base/manifests/local/prow-rehearse-deployment.yaml

Adopts fix from #2788 
Closes #2783

Use rehearse image with fix for release branch issue

---

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml

disable cdi apidocs job

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.59.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.0.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

The presubmit for apidocs is passing again so it should be enabled.

Enable presubmit to check make apidocs

---

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-postsubmits.yaml

It works fine with buildah/podman

Switch CDI postsubmit jobs to use podman

---

github/ci/services/prometheus-stack/manifests/stack/production-control-plane/thanos.yaml

Also includes some updates to the thanos-receive configuration to improve performance
/cc @dhiller

Configure thanos-query to use thanos-receive as a store for queries

---

github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml

Enable prow for the new kubernetes.kubevirt repository

---

github/ci/prow-deploy/files/orgs.yaml

@germag
[X] I have reviewed the community code of conduct (https://github.com/kubevirt/kubevirt/blob/master/CODE_OF_CONDUCT.md)
[X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
[X] I have subscribed to the kubevirt-dev e-mail list (https://groups.google.com/forum/#!forum/kubevirt-dev)
[X] I am actively contributing to KubeVirt
[X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
[X] I have spoken to my sponsors ahead of this application and they have agreed to sponsor my application
[X] I have publicly introduced myself to the community through one of the community communication channels
* @0xFelix 
* @xpivarc
- …

Add germag to the Kubevirt org

---

github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml

Enabling Prow for the new go-based operator

Enable prow for the new managed-tenant-quota repository

---

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml

https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/2815/pull-containerized-data-importer-e2e-ceph-wffc/1682795926009155584

Increase ceph-wffc lane timeout

---

github/ci/prow-deploy/files/jobs/kubevirt/managed-tenant-quota/OWNERS
github/ci/prow-deploy/files/jobs/kubevirt/managed-tenant-quota/managed-tenant-quota-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/managed-tenant-quota/managed-tenant-quota-presubmits-1.1.yaml
github/ci/prow-deploy/files/jobs/kubevirt/managed-tenant-quota/managed-tenant-quota-presubmits.yaml
github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml

Add presubmit and postsubmit jobs to mtq operator

Configure mtq jobs

---

github/ci/prow-deploy/files/orgs.yaml

Fix indentation of neighboring yaml along side.
/cc @aburdenthehand  @alicefr @brianmcarey @xpivarc

Add k8s-seccomp-generator repository and team

---

github/ci/prow-deploy/files/orgs.yaml

Add sudo-NithishKarthik and xpivarc as maintainers to k8s-seccomp-generator repo.

k8s-seccomp-generator: update maintainers

---

robots/cmd/flake-stats/flake-stats.gohtml
robots/cmd/flake-stats/main.go

Also do some clean up, like
* simplifying css,
* cleaning up table border mess and
* moving a method towards the other Sorter methods.
/cc @xpivarc @brianmcarey

Add anchor link to each test

---

github/ci/prow-deploy/files/orgs.yaml

@avlitman
* @dhiller
* @nunnatsa 
- https://github.com/kubevirt/kubevirt/pull/8774
- https://github.com/kubevirt/kubevirt/pull/9822
- https://github.com/kubevirt/kubevirt/pull/10006
- https://github.com/kubevirt/kubevirt/issues/9714
- https://github.com/kubevirt/kubevirt/issues/9836
- https://github.com/kubevirt/containerized-data-importer/issues/2773
**Note to reviewer:**
Member list was ordered alphabetically.

Add avlitman to kubevirt members

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Adding the sig-monitoring presubmit to testgrid
Signed-off-by: enp0s3 <ibezukh@redhat.com>

[testgrid]: adding sig-monitoring lane

---

github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml

* sig-documentation
* sig-testing
See https://github.com/kubevirt/community/pull/236

Add labels for sigs

---

github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.89.yaml

Copied latest release presubmit file, changed to 0.89 all over.
Compared to main one, and took the relevant changes:
1. optional for dynamic networks
2. update bootstrap image

cnao, release 0.89: Add presubmits

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Fix typo in cluster name for kubevirt build presubmit

---

robots/cmd/test-label-analyzer/cmd/filter/matching-tests.go

Fixes a minor issue that when a required parameter is omitted, no specific error is thrown. This PR adds a call to the `validate()` func of the parameter struct.
Fixes #

test-label-analyzer: validate command line args

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml

Fixes the job that updates the k8s support matrix for kubevirt/kubevirt inside kubevirt/sig-release.
Successful run here: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/push-kubevirt-update-support-matrix/1706977342695411712
Fixes #
/cc @brianmcarey @aburdenthehand

Fix update-support-matrix job for sig-release

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml

/hold
For #3005 to be merged first.

Move remaining jobs to the new control plane cluster

---

images/shared-images-controller/BUILD.bazel

Fix bazel dependencies for shared-images-controller

---

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml

Update the list of maintainers for the kubevirt-velero-plugin repository to reflect current situation.
Fixes #
FYI @awels @mhenriks

Update kubevirt-velero-plugin maintainers

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Update the compute-migrations test lanes to use the k8s-1.28 provider

---

github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml

Adds a label that can be used to mark issues and pull requests related to flaky tests.
Source: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/flaky-tests.md#github-issues-for-known-flakes
Fixes #
/cc @brianmcarey @xpivarc @aburdenthehand

Add kind/flake label for marking issues and PRs

---

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml

Antonio needs write access to create and edit kubevirt releases
/cc @xpivarc @aburdenthehand @davidvossel

Give acardace write permissions to help with kubevirt releases

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.1.yaml

Release configs for kubevirt/kubevirt release branch release-1.1

---

github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits-v0.33.yaml

Those were missing for release-0.33 (note it doesn't have v)

kmp, release-0.33: Add presubmits

---

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml

- Add timeout to postsubmit job building the image
- Add presubmit testing the build of the image
- Update used builder image to latest version

common-instanctypes: Overhaul builder jobs

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml

Fixes the newlines in the PR description for prow bumps.

Fix prow bump PR comment newlines

---

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml

Add 0xFelix to common-instancetypes maintainers

Add 0xFelix to common-instancetypes maintainers

---

docs/how-to-add-a-prow-cluster.md

We add more detail on how to add new clusters to the federated prow setup, so that the later us can read how it's done. (This also applies to updating cluster secrets)

docs: update prow federated cluster section

---

github/ci/prow-deploy/files/jobs/kubevirt/applications-aware-quota/OWNERS
github/ci/prow-deploy/files/jobs/kubevirt/applications-aware-quota/applications-aware-quota-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/applications-aware-quota/applications-aware-quota-presubmits-1.1.yaml
github/ci/prow-deploy/files/jobs/kubevirt/applications-aware-quota/applications-aware-quota-presubmits.yaml
github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml

Add presubmit and postsubmit jobs to aaq operator

Configure aaq jobs

---

docs/how-to-add-a-prow-cluster.md

Extend on how the cluster has to be prepared to run prow jobs.

docs: update how-to-add-a-prow-cluster

---

github/ci/prow-deploy/tasks/deploy.yml
github/ci/prow-deploy/vars/ibmcloud-production/main.yml
github/ci/prow-deploy/vars/kubevirt-prow-control-plane/main.yml
github/ci/prow-deploy/vars/kubevirt-prow-workloads/main.yml
github/ci/prow-deploy/vars/kubevirtci-testing/secrets.yml

Since the deck deployment doesn't pick up the deployment updates we rescale the deployment.
Closes #3085

Rescale deck deployment after control plane deploy

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Hold until https://github.com/kubevirt/kubevirt/pull/10303 get merged.

kubevirt, presubmits: add conformance testing for Arm64

---

github/ci/services/grafana/manifests/grafana.yaml

Add dashboards from old grafana instance - the json dashboard definitions were largely imported from the old grafana instance

Fix grafana dashboards for new instance and cluster

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml

fix, botreview, publish: needs to run privileged

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml

Set the kubevirtci 1.29 presubmit lane to be required

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml

/cc @dhiller @xpivarc @orelmisan

kubevirt,periodics: update rootful lanes to 1.29

---

WORKSPACE
external-plugins/botreview/review/review_test.go
go.mod
images/golang/Dockerfile

Also update go version in golang image.

Update golang to 1.21.6

---

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-0.1.yaml
github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-0.3.yaml
github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-0.4.yaml

Add the release version to the job names of release branches to make it easier identifying these jobs.
Fixes #
**Checklist**
```release-note
None
```

common-instancetypes: Add release version to job names

---

github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml

Update containerdisks presubmits and periodics to use golang 1.21.6.
Fixes #
**Checklist**
```release-note
None
```

containerdisks: Update to golang 1.21.6

---

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml

This reverts commit 8e222b45ef9870f306584cfc92f4f142db07049c.
The original PR with this commit removed @codingben from the org, while this PR reverts that action.
However, it does not revert the changes to the `OWNERS` files that were
part of this commit, since adding @codingben to the `OWNERS` is only
allowed after he will be part of the org again.
Fixes #
/cc @0xFelix @brianmcarey @akrejcir 
**Checklist**
**Release …

Revert "Remove 'codingben' from the kubevirt org"

---

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml

Removes users that are no longer active in the KubeVirt org from the KubeVirt org admin group.
Moves @stoniko to the KubeVirt members section, since he's member of the sig-security GitHub team.
Fixes #
/cc @fabiand @brianmcarey 
**Checklist**
```release-note
```

Remove emeritus admins

---

github/ci/services/grafana/manifests/grafana.yaml

Query using regex operator on state label was not working anymore, this change removes them.
Also reduce default date range to now-7days.
Fixes #
This is the current version of the dashboard: https://grafana.ci.kubevirt.io/d/asdfare79we8r/prow-job-load-1h-resolution?orgId=1&refresh=1d&from=now-7d&to=now
**Checklist**
```release-note
```

Fix prow job load dashboard

---

github/ci/prow-deploy/files/jobs/kubevirt/application-aware-quota/OWNERS
github/ci/prow-deploy/files/jobs/kubevirt/application-aware-quota/application-aware-quota-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/application-aware-quota/application-aware-quota-presubmits-1.1.yaml
github/ci/prow-deploy/files/jobs/kubevirt/application-aware-quota/application-aware-quota-presubmits.yaml
github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml

Fixes #
**Checklist**
```release-note
NONE
```

Rename AAQ operator name to the new name

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml

Makes the script for updating [upcoming-changes.md](https://github.com/kubevirt/sig-release/blob/main/upcoming-changes.md) exit with a zero exit code in case no changes have been generated.
Fixes #
/cc @brianmcarey @aburdenthehand 
**Checklist**
```release-note
NONE
```

kubevirt, upcomingChanges: exit 0 if nothing changed

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.2.yaml

Manual fork of the prow job configurations for the release branch release-1.2 in the kubevirt/kubevirt repository.
Fixes #
/cc @brianmcarey @acardace 
**Checklist**
```release-note
NONE
```

Manual fork of prow configs for kubevirt/kubevirt release-1.2

---

external-plugins/rehearse/plugin/handler/handler.go
external-plugins/rehearse/plugin/rehearse_test.go

1) ok-to-test on a PR enables any commenter to run rehearsal for a prow
job
2) only PRs to prow jobs from community members are safe to rehearse
This change makes sure that author and user are both members of the org. The check for ok-to-test label present is removed.
Fixes #
/cc @xpivarc @brianmcarey
**Checklist**
```release-note
```

prow, rehearse: make rehearsal org member only

---

github/ci/prow-deploy/kustom/base/manifests/local/prow-rehearse-deployment.yaml

Applies changes from #3244 to rehearse plugin.
Fixes #
/cc @xpivarc @enp0s3 
**Checklist**
```release-note
```

rehearse, deployment: update with changes from #3244

---

README.md

`github/ci/prow-workloads` directory no longer exists since the migration of workloads cluster to OCP so it should be removed from the README
Add a couple of the newer tools under `robots/` to the README including botreview, dependabot and flake-stats.
Fixes #
**Checklist**
```release-note
```

Update README to capture some recent changes

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml

Arm lanes are currently failing every time, let's exclude them from the report to have a clearer picture until the lanes are fixed.
https://testgrid.k8s.io/kubevirt-presubmits#pull-kubevirt-e2e-arm64
Fixes #
**Checklist**
```release-note
```

flake-stats, report: filter arm64 until fixed

---

github/ci/services/grafana/manifests/grafana.yaml

Adds the e2e test runtimes dashboard to the grafana configuration, which was missed in a previous PR.
Fixes #
**Checklist**
```release-note
```

grafana, dashboard, e2e-tests: add entry for e2e tests

---

github/ci/services/grafana/manifests/grafana.yaml

Re-enable two dashboards that seem to have missed their GrafanaDashboard objects in the configuration.
Fixes #
/cc @brianmcarey @xpivarc @enp0s3 
**Checklist**
```release-note
```

monitoring, prow: enable prow-jobs and job-load

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml

`preset-kubevirtci-installer-pull-token` is an old preset that is no longer used so it can be removed
Fixes #
**Checklist**
```release-note
```

prow,preset: Remove old unused preset that is no longer required

---

images/bootstrap/Dockerfile

The github cli could be useful for checking PR diff
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```

bootstrap: Add github cli client gh to bootstrap image

---

images/pr-creator/Dockerfile

Update base image for pr-creator to latest and bump go version to 1.21
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```

images,pr-creator: Update base image to latest and bump go version to 1.21

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

This test lane was missed as part of https://github.com/kubevirt/project-infra/pull/3286
Fixes #
**Checklist**
```release-note
```

kubevirt,presubmit: Remove podman in container setup for lint lane

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml

There is an issue with `make cluster-up` when the centos base is published with podman - updating to publish with docker to unblock docker users of kubevirtci
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```

kubevirtci,periodic: Publish centos base using docker

---

external-plugins/referee/Makefile
github/ci/prow-deploy/kustom/base/manifests/local/referee-deployment.yaml
hack/container-tag.sh

We now use the image digest instead of `latest`, since we want to know the exact image version that is running. We also update the deployment inside the `make push` target now, so that it contains the latest build image tag.
Fixes #
**Checklist**
```release-note
```

prow, plugin, referee: use image digest for pushing

---

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-periodics.yaml

Fixes #https://github.com/kubevirt/common-instancetypes/issues/162
Depends on https://github.com/kubevirt/kubevirt/pull/11368 and https://github.com/kubevirt/ssp-operator/pull/900
**Checklist**
```release-note
NONE
```

Common instancetypes periodics stable release sync

---

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-periodics.yaml

/cc @0xFelix 
Use absolute askpass path as suggested by [dceff08](https://github.com/kubevirt/project-infra/commit/dceff08aaa243063dec95ffb1bf1a5ba3239f57f). This should fix the following failure:
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-update-common-instancetypes-bundles-release-0.3/1772458511167393792#1:build-log.txt%3A474
```
+ git push -f https://kubevirt-bot@github.com/kubevirt-bot/kubevirt.git HEAD:update-common-instancetypes-release-1.1
push_pin
fatal: cannot run ../project-infra/hack/git-askpass.sh: No such file or directory
fatal: could not read Password for 'https://kubevirt-bot@github.com/': No such device or address
```
Additionally the /releases/latest API provided by GitHub does not list …

Fix common-instancetypes-periodics

---

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml

Add dependabot configuration to automatically update the dependencies of this repository.
Fixes #
**Checklist**
```release-note
```

Add containerdisks-maintainers org

---

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml

RoniKishner
* @0xFelix 
* @lyarwood 
- https://github.com/kubevirt/kubevirt/pull/11448
- https://github.com/kubevirt/kubevirt/pull/10334

Add RoniKishner to kubevirt members list

---

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml

HCO: add new line for K8s 1.29

---

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-periodics.yaml

Apologies I thought the tooling did this automatically as with the `/cherry-pick` command.
Fixes #
**Checklist**
```release-note
NONE
```

common-instancetypes-periodics: Add stable branch names to subject of PRs

---

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.0.yaml

/cc @0xFelix 
$subject
Fixes #
**Checklist**
```release-note
NONE
```

common-instancetypes: Add release-1.0 pre-submits

---

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-periodics.yaml

/cc @0xFelix 
Nightly syncs are constantly rebasing the PRs and rerunning CI wasting resources when not required
Fixes #
**Checklist**
```release-note
NONE
```

common-instancetypes-periodics: Limit syncs to once a week

---

github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml

Add sig/observability label
sig-observability charter: https://github.com/kubevirt/community/pull/282
KubeVirt ownerships: https://github.com/kubevirt/kubevirt/pull/11249
/cc @sradco @dhiller @fabiand 
Fixes #
**Checklist**
```release-note
NONE
```

prow, labels, github: Add sig/observability label

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
github/ci/prow-deploy/kustom/base/manifests/local/branch-protector.yaml
github/ci/prow-deploy/kustom/base/manifests/local/cherrypicker_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/local/label-sync-kubevirt.yaml
github/ci/prow-deploy/kustom/base/manifests/local/label-sync-nmstate.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/crier_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/deck_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/ghproxy.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/hook_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/horologium_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/needs-rebase_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/prow_controller_manager_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/sinker_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/statusreconciler_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/tide_deployment.yaml
github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/resources/prow-exporter-deployment.yaml

This reverts commit 90e7b7f6450080b2d559b004edaf7bab198f452a.
There have been a number of infra jobs failing since this prow bump - revert for now.
For example:
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-project-infra-close/1780511996244922368
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```

Revert "Run hack/bump-prow.sh (#3340)"

---

github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml

Bump go version in containerdisks periodis and presubmits to 1.22.2.
Fixes #
**Checklist**
```release-note
None
```

containerdisks: Bump go version to 1.22.2

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
github/ci/prow-deploy/kustom/base/manifests/local/branch-protector.yaml
github/ci/prow-deploy/kustom/base/manifests/local/cherrypicker_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/local/label-sync-kubevirt.yaml
github/ci/prow-deploy/kustom/base/manifests/local/label-sync-nmstate.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/crier_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/deck_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/ghproxy.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/hook_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/horologium_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/needs-rebase_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/prow_controller_manager_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/sinker_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/statusreconciler_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/tide_deployment.yaml
github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/resources/prow-exporter-deployment.yaml

This reverts commit 82e80c31eb67ab513ef3fc5c292d2cf2a558dda3.
Since [periodic jobs fail](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-project-infra-close-build-watcher-triage/1781270513658630144) after the update with a strange message
```
Failed to open /logs/process-log.txt: open /logs/process-log.txt: no such file or directory
```
we need to investigate this.
Fixes #
**Checklist** …

Revert "Run hack/bump-prow.sh (#3354)"

---

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml

@EduardGomezEscandell 
Requirements
@aglitke 
@awels 
- https://github.com/kubevirt/containerized-data-importer/pull/3164
- https://github.com/kubevirt/containerized-data-importer/pull/3165
- https://github.com/kubevirt/containerized-data-importer/pull/3171
- https://github.com/kubevirt/containerized-data-importer/pull/3176
- https://github.com/kubevirt/containerized-data-importer/pull/3177
- https://github.com/kubevirt/containerized-data-importer/pull/3178
- https://github.com/kubevirt/containerized-data-importer/pull/3179
- https://github.com/kubevirt/containerized-data-importer/pull/3195
- https://github.com/kubevirt/containerized-data-importer/pull/3200
- https://github.com/kubevirt/containerized-data-importer/pull/3204
- …

Request adding EduaredGomezEscandell to org members

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
hack/bump-prow-deployment-images.sh

Creates a script that can update the deployments with the latest images. Adds a job that periodically calls the script and creates a pull request with the updates.
Fixes #
**Checklist**
```release-note
```

prow, deployments: update with latest images

---

github/ci/prow-deploy/files/jobs/kubevirt/application-aware-quota/application-aware-quota-presubmits-1.2.yaml

Fixes #
**Checklist**
```release-note
NONE
```

Add test lanes to AAQ version 1.2

---

github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.93.yaml

This PR adds a new presubmit file to the new CNAO stable branch https://github.com/kubevirt/cluster-network-addons-operator/tree/release-0.93
Fixes #
**Checklist**
```release-note
```

cnao: Add new release-0.93 stable branch presubmit

---

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.12.yaml

Fixes #
**Checklist**
```release-note
HCO: Set tests for release 1.12
```

HCO: Set tests for release 1.12

---

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml

This will be super useful when we want to test destructive-natured backports.
Fixes #
**Checklist**
```release-note
NONE
```

CDI destructive dummy job for release branches

---

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml

Fixes #
**Checklist**
```release-note
HCO - now use golang 1.22
```

HCO: Bump golang to 1.22

---

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml

```release-note
HCO: add 1.30 lane; remove 1.28 lane
```

HCO: add 1.30 lane; remove 1.28 lane

---

external-plugins/rehearse/plugin/handler/handler.go

The comment text in the detail part is malformatted, we need to add a newline and a missing asterisk.
Example: https://github.com/kubevirt/project-infra/pull/3400#issuecomment-2098248869
Fixes #
**Checklist**
```release-note
```

prow, rehearse: fix comment formatting for non approver

---

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml

Missing `v`
Fixes #
**Checklist**
```release-note
NONE
```

Correct skip branch regex in pull-cdi-goveralls

---

images/bootstrap/Dockerfile

This reverts commit 5938a5fac4aafbe17f2a96a2bb92d99deb133942.
There is more work involved in getting the bootstrap image upgrade to Fedora 40 as can bee seen from the issues in the bump prow images PR[1][2]
Move back to f39 for now in case we need to take other changes to bootstrap
[1] https://github.com/kubevirt/project-infra/pull/3378
[2] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/3378/rehearsal-pull-kubevirt-build/1788914298303549440
Fixes #
/cc @dhiller 
**Checklist**
This checklist is not enforcing, but it's a …

Revert "bootstrap: Bump to Fedora 40 (#3373)"

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/crier_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/deck_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/ghproxy.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/grandmatriarch.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/hook_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/horologium_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/needs-rebase_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/pipeline_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/prow_controller_manager_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/sinker_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/statusreconciler_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/tide_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/tot_deployment.yaml
github/ci/prow-deploy/prow-autobump-config.yaml

Some of the services are currently missed by the prow-autobump.
Including the test_infra directory to config insures that these services are bumped.
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```

prow-deploy: Add test_infra dir to prow-autobump-config 

---

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-periodics.yaml

This will stop the jobs from pushing updates to the PR if they have a hold,lgtm or approve label.
Fixes #
/cc @lyarwood @0xFelix 
**Checklist**
```release-note
```

periodic,common-instancetype: Add label checker to jobs to avoid unnecessary CI churn

---

github/ci/services/grafana/manifests/grafana.yaml

Adds the presubmit lanes sig-compute-serial and sig-compute-migrations to the lane runtime dashboards, which were missing previously.
Fixes #
/cc @brianmcarey @enp0s3 
**Checklist**
```release-note
```

kubevirtci, monitoring: add sig-compute-serial and sig-compute-migrations

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml

Fixes #
**Checklist**
```release-note
```

kubevirci, presubmit: Fix run if changed condition

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml

Prow commenter seems to have an issue with private issues [1].
Modify query to only search for public issues.
[1]: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-project-infra-stale/1795096221174468608#1:build-log.txt%3A2
Fixes #
**Checklist**
```release-note
```

prow, stale, bot: query only public issues

---

github/ci/prow-deploy/kustom/base/kustomization.yaml
github/ci/prow-deploy/kustom/base/manifests/local/referee-service.yaml
github/ci/prow-deploy/kustom/base/manifests/local/referee-servicemonitor.yaml
github/ci/prow-deploy/kustom/overlays/kubevirtci-testing/resources/monitoring.coreos.com/monitoring.coreos.com_servicemonitors.yaml
github/ci/prow-deploy/tasks/deploy.yml
github/ci/services/grafana/manifests/grafana.yaml

Adds an initial dashboard that shows retest metrics:
[![image](https://github.com/kubevirt/project-infra/assets/809335/6205a9b2-f532-4faa-81b7-4a5fbffb00a0)](https://grafana.ci.kubevirt.io/d/uAoSeksSk/referee-retests?orgId=1&from=now-12h&to=now&refresh=15m)
This requires a ServiceMonitor that exposes the referee metrics to the system.
Also this PR updates the Service object to add a name for the port so that the
ServiceMonitor can find it.
Fixes #
/cc @brianmcarey @xpivarc @iholder101 
We haven't added alerts yet, since we think we need historical data to see …

prow, referee, monitoring: add retest metrics dashboard

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml

The correct make target is container-push[1]
[1] https://github.com/kubevirt/project-infra/blob/6875019d3c4a3f8cf2fad1c7efe1762f981d8ac7/releng/release-tool/Makefile#L19
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```

release-tool: fix make target in release-tool image publish postsubmit

---

github/ci/prow-deploy/files/jobs/kubernetes-sigs/cluster-api-provider-kubevirt/cluster-api-provider-kubevirt-presubmits.yaml

fix capk presubmit

---

github/ci/services/grafana/manifests/grafana.yaml

Using the increase function makes the graphs better understandable.
Also improved the legend labels and set the min interval to 15m.
Fixes #
**Checklist**
```release-note
```

monitoring, referee, retests: replace with increase

---

github/ci/services/grafana/manifests/grafana.yaml

Adds the dashboard with a panel [e2e job failures / h](https://grafana.ci.kubevirt.io/d/_6XBEfyIk/e2e-job-failures-h?from=now-24h&to=now) and a panel to monitor job abortions to the monitoring dashboards.
Fixes #
**Checklist**
```release-note
```

prow, e2e, monitoring: add failure rate panel

---

docs/labels.md
github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml

This reverts commit 5fae7e4a6393bb9f06a33eae5ef32c3d8736213c.
At the end, we will present an external repo for the project.
So atm we don't need this.
Fixes #
**Checklist**
```release-note
```

Revert "labels: Add wg/ipam group label (#3455)"

---

github/ci/services/grafana/manifests/grafana.yaml

If the referee instance is restarted, metrics per PR look as if there's multiple entries per PR. We fix this by grouping on `pull_request`. See screenshot:
Fixes #
**Checklist**
```release-note
```

prow, external-plugin, referee: fix instance

---

docs/how-to-renew-docker-mirror-proxy-ca-cert.md
hack/check-docker-proxy-ca-cert.sh

Document how to renew the docker-mirror-proxy CA certificate
Fixes #
**Checklist**
```release-note
```

doc: document how to renew the docker-mirror-proxy CA certificate

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.3.yaml

Release configs for kubevirt/kubevirt release branch release-1.3

---

github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml

Fixes #
**Checklist**
```release-note
```

prow: Add ipam-extensions basic config

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml

Fixes #
**Checklist**
```release-note
```

kubevirtci,presubmit: Add test lane for kind-1.30-vgpu provider

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml

The list [1] is outdated - the job definition needs to get updated manually for the release branches.
This change adds a shell generation for the last three release branch configs so we avoid dealing with this manually.
Successful run here [2].
[1] https://storage.googleapis.com/kubevirt-prow/reports/e2ejobs/kubevirt/kubevirt/presubmits.html
[2] https://prow.ci.kubevirt.io/log?container=test&id=1809192423146917888&job=post-project-infra-kubevirt-e2e-jobs-overview
Fixes #
**Checklist**
This checklist is not enforcing, but it's a reminder of items that could be …

ci, reporting: fix kubevirt presubmit list generation

---

github/ci/prow-deploy/files/jobs/kubevirt/controller-lifecycle-operator-sdk/controller-lifecycle-operator-sdk-presubmits.yaml

Fixes #
**Checklist**
```release-note
NONE
```

operator lifecycle sdk: delegate k8s version decisions to repo scripts

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Hi @brianmcarey 
I am adding a periodic and pre submit job for running unit tests on s390x.
Please do review when you have some time.

Add presubmit prow job to run unit tests on s390x cluster

---

github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml

Make main branch protected in ssp-operator repository.
```release-note
None
```

chore: add ssp-operator branch protection

---

github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-presubmits.yaml

```release-note
CSI-Driver: Bump go to 1.22.5
```

CSI-Driver: Bump go to 1.22.5

---

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.0.yaml
github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.1.yaml

Use kubevirtci in release branches of common-instancetypes to save resources. Rebuilding a released KubeVirt version is not required.
Fixes #
**Checklist**
```release-note
None
```

common-instancetypes: Use kubevirtcti in release branches

---

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml

Fixes #
**Checklist**
```release-note
Fix flaky test in HCO, by increasing the memory
```

Increasing the HCO tests memory, to try to fix flaky tests

---

images/golang/Dockerfile

Some of the kubevirtci check-provision jobs require a newer version of go to build[1]
Update to the latest minor release - v1.22.6
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/1217/check-provision-k8s-1.30/1823271740063617024#1:build-log.txt%3A32
Fixes #
/cc @xpivarc 
**Checklist**
```release-note
```

image,golang: Update default go version to v1.22.6

---

github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.95.yaml

This PR adds the stable release-0.95 branch presubmit job
Fixes #
**Checklist**
```release-note
NONE
```

cnao: Add stable release-0.95 branch presubmit

---

github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml

Bump containerdisks to golang 1.22.6
Fixes #
**Checklist**
```release-note
None
```

Bump containerdisks to golang 1.22.6

---

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml

Third attempt to fix the dra-driver-pci repository configuration
Fixes #
**Checklist**
```release-note
```

Fix configuration for dra-pci-driver repo

---

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml

Fixes a spelling error in the configuration for the maintainer team.
Fixes #
/cc @alicefr

dra-pci-driver: update team config in orgs.yaml

---

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml

- @orelmisan 
- @akalenyu 
- https://github.com/kubevirt/kubevirt/pull/12353
- https://github.com/kubevirt/kubevirt/pull/12532
- https://github.com/kubevirt/kubevirt/pull/12617
- https://github.com/kubevirt/kubevirt/pull/12522
- https://github.com/kubevirt/kubevirt/pull/12652
- https://github.com/kubevirt/kubevirt/pull/12664
- https://github.com/kubevirt/kubevirt/pull/12667
Additionally wrote a PoC for a bridge-marker device plugin replacement for https://github.com/kubevirt/bridge-marker:
https://github.com/Acedus/bridge-marker-dp
My organization actively uses KubeVirt in moderately sized production clusters. My goal is to contribute to the project and, in the process, gain a deeper understanding of its inner workings.

Add Acedus to KubeVirt Members

---

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml

@aliamerj
@fossedihelm 
@0xFelix 
https://github.com/kubevirt/kubevirt/pull/12414
https://github.com/kubevirt/kubevirt/pull/12339
https://github.com/kubevirt/kubevirt/pull/12275
https://github.com/kubevirt/kubevirt/pull/12229
https://github.com/kubevirt/kubevirt/pull/12224
https://github.com/kubevirt/kubevirt/pull/12095
https://github.com/kubevirt/kubevirt/pull/12284
Member list was ordered alphabetically.

add aliamerj to kubevirt members

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml

Sets up the job for successfully signing the release source tarball by:
* mounting the gpg key to the job pod,
* setting the env var to the user-id of the key and
* importing the key ahead of signing.
Fixes #
See kubevirt/kubevirt#12228
**Checklist**
```release-note
```

release, verification: add gpg key setup to release job

---

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml

* @dhiller 
* @brianmcarey 
- https://github.com/kubevirt/kubevirtci/pull/1217
- https://github.com/kubevirt/kubevirtci/pull/1209
- https://github.com/kubevirt/kubevirtci/pull/1255
- https://github.com/kubevirt/kubevirtci/pull/1230
- https://github.com/kubevirt/kubevirtci/pull/1247
- https://github.com/kubevirt/kubevirtci/issues/1222
- https://github.com/kubevirt/kubevirtci/issues/1110
- https://github.com/kubevirt/kubevirtci/issues/1185

add aerosouund to the KubeVirt org

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml

This change was missed in the previous bump PR - https://github.com/kubevirt/project-infra/pull/3600
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```

kubevirt,periodic: Update compute migrations periodic to kubernetes v1.31

---

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.13.yaml

```release-note
HCO: add test to new release branch 1.13
```

HCO: add test to new release branch 1.13

---

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml

Fixes #
**Checklist**
```release-note
none
```

hco: add lane 1.31; remove lane 1.29

---

OWNERS

This PR removes all reviewers from the global OWNERS file, except the ci-maintainers group, which should lead to more specifically assigned PRs in sub folders, in contrast to assigning reviewers from ci-maintainers group for more general PRs.
The reviewers removed show a low PR review activity [1], so this also should help reduce the noise for them:
[1]: https://kubevirt.devstats.cncf.io/d/46/pr-reviews-by-contributor?orgId=1&var-period=d7&var-repo_name=kubevirt%2Fproject-infra&var-reviewers=%22aglitke%22&var-reviewers=%22davidvossel%22&var-reviewers=%22phoracek%22&var-reviewers=%22rmohr%22&var-reviewers=%22tiraboschi%22&var-reviewers=%22vladikr%22&from=1709161200000&to=1724968799000
@aglitke @davidvossel @phoracek @rmohr @tiraboschi @vladikr please …

project-infra: remove root reviewers with low activity

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml

This PR adds a periodic prow job for running e2e tests on s390x.
Fixes #
**Checklist**
```release-note
```

add periodic e2e tests job for s390x.

---

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml

@dasionov
* @enp0s3
* @stu-gott
- https://github.com/kubevirt/kubevirt/pull/12427
- https://github.com/kubevirt/kubevirt/pull/12473
- https://github.com/kubevirt/kubevirt/pull/12573
- https://github.com/kubevirt/kubevirt/pull/12373
- https://github.com/kubevirt/kubevirt/pull/12640
- https://github.com/kubevirt/kubevirt/pull/12690

Add dasionov as a community member

---

github/ci/prow-deploy/files/jobs/kubevirt/application-aware-quota/application-aware-quota-presubmits-1.3.yaml

Fixes #
**Checklist**
```release-note
NONE
```

Adding presubmits for aaq release-v1.3

---

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.0.yaml
github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.1.yaml

/cc @0xFelix 
This reverts commit 47a1b0c93fab598da698f846aee00d5595d3b9c2.
This is required to allow us to test against merged but unreleased API changes to the release branches of KubeVirt.
Fixes #
**Checklist**
```release-note
NONE
```

Revert "common-instancetypes: Use kubevirtcti in release branches

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml

Fixes the label name in the query.
Fixes #

approver,review: fix label name in query

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Fixes #
**Checklist**
```release-note
```

kubevirt,presubmits: fix typo in kwok presubmit

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml

Adds check-up for kind-1.28 kubevirtci provider.
Fixes #

kubevirtci,kind,check-up: add for 1.28

---

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml

Fixes #
**Checklist**
```release-note
None
```

HCO: only build the test utils image on the main branch

---

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml

* @EdDev 
* @orelmisan 
- https://github.com/kubevirt/kubevirt/pull/12959
- https://github.com/kubevirt/kubevirt/pull/12936
- https://github.com/kubevirt/kubevirt/pull/12923
- https://github.com/kubevirt/kubevirt/pull/12921
- https://github.com/kubevirt/kubevirt/pull/12859

Add nirdothan to KubeVirt Members

---

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.2.yaml
github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-periodics.yaml

Add configuration for release-1.2 of common-instancetypes
Fixes #
**Checklist**
```release-note
Added configuration for release-1.2 of common-instancetypes
```

common-instancetypes: Add configuration for release-1.2

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

This will provide feedback for the conformance tests. (runtime, flakiness and other attributes)
```release-note
NONE
```

Create optional sig-compute conformance lane

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml

As per #3712 this PR adds a periodic prow job that removes the label `needs-approvers-review` from closed PRs.
Fixes #
/cc @vladikr @alicefr @brianmcarey

approvers,labels: remove needs-approvers-review

---

robots/cmd/flake-stats/main.go
robots/cmd/flake-stats/main_test.go
robots/cmd/per-test-execution/BUILD.bazel
robots/cmd/per-test-execution/config.yaml
robots/cmd/per-test-execution/main.go
robots/cmd/per-test-execution/main_test.go
robots/pkg/flakefinder/BUILD.bazel
robots/pkg/flakefinder/test_names.go
robots/pkg/flakefinder/test_names_test.go

Prototype for aggregating per test results from periodic lanes.
Fixes #

tests,stats: generate per-test execution statistics csv 

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
github/ci/prow-deploy/kustom/base/manifests/local/branch-protector.yaml
github/ci/prow-deploy/kustom/base/manifests/local/cherrypicker_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/crier_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/deck_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/ghproxy.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/grandmatriarch.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/hook_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/horologium_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/needs-rebase_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/pipeline_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/prow_controller_manager_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/sinker_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/statusreconciler_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/tide_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/tot_deployment.yaml
github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/resources/prow-exporter-deployment.yaml
hack/bump-prow.sh

The prow autobump has not been picking up the new prow images - manually bump the images for now until this is resolved.
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```

prow: Manual bump of prow components

---

github/ci/prow-deploy/files/jobs/kubevirt/community/community-postsubmits.yaml

Updates the community postsubmit to propagate changes to sigs.yaml by creating a PR for the CNCF devstats repo_groups.sql
https://github.com/kubevirt/community/pull/332
Fixes kubevirt/community#330
**Checklist**
```release-note
```

devstats,repo_groups: modify job to use go generator

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.4.yaml

Release configs for kubevirt/kubevirt release branch release-1.4

---

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml

Fixes #
**Checklist**
```release-note
None
```

CDI periodic: add missing build for amd64

---

github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml

Bump containerdisks to golang 1.22.8
Fixes #
**Checklist**
```release-note
None
```

Bump containerdisk to golang 1.22.8

---

github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml

Bump golang 1.22.9 in containerdisk
Fixes #
**Checklist**
```release-note
None
```

Bump golang 1.22.9

---

github/ci/services/grafana/hack/test.sh

cluster-up has been moved inside of the kubevirt repo so the path needs to updated here too
Fixes #
**Checklist**
```release-note
```

grafana: update cluster-up path for grafana test presubmit

---

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-periodics.yaml

increase the hco periodic timeout

---

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml

Sponsored by: @lyarwood and @0xFelix
**What this PR does / why we need it**: s390x enablement
Fixes #
**Checklist**
- [] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
```release-note
NONE
```

ci: Add nestoracunablanco as a member of the community

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml

Adds missing settings to job configuration for the push job of the nightly build for KubeVirt. Successful test run [1] . Example of failing job run [2] .
[1]: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-push-nightly-build-main/1858831073388007424
[2]: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-push-nightly-build-main/1858677288028082176
Fixes #
/cc @brianmcarey @xpivarc @acardace

kubevirt,nightly: fix periodic push job

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-tekton-tasks/tekton-tasks-periodics.yaml

fix: wrong path of Containerfile
```
NONE
```

[tekton-tasks] fix: wrong path of Containerfile

---

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml

Since @cfilleke is already a long term contributor (see below) and also one of the [chairs of wg-arch-s390x](https://github.com/kubevirt/community/blob/49df68bff7923940df0b0b8da5b9400a441b7da8/sigs.yaml#L279), add her officially to the org members.
I'd be happy to be a sponsor on this PR.
(@cfilleke, would you be able to add the following passage as a comment on this PR and confirm that you have gone through the list below? Thank you!)
* @dhiller
* @brianmcarey 
* PRs
- authored: https://github.com/search?q=org%3Akubevirt+author%3Acfilleke&type=pullrequests
- reviewed (): https://github.com/search?q=org%3Akubevirt+reviewed-by%3Acfilleke&type=pullrequests
* Issues
- authored (18): …

org,members: add cfilleke as org member

---

github/ci/prow-deploy/files/jobs/kubevirt/community/community-presubmits.yaml

This will be obsolete as of the latest changes in the validation update PR https://github.com/kubevirt/community/pull/350, therefore we are deleting this presubmit.
Fixes #
/cc @brianmcarey @aburdenthehand 
**Checklist**
```release-note
```

community,sigs.yaml: remove sigs.yaml validation

---

hack/remove-users-without-contributions.sh

We are using a different statistic [1] as input for user activity, since that appears much more complete and easier to use.
Therefore we adjust the script to the new format.
The previous approach was flawed, since it didn't catch activity that clearly was there: https://github.com/kubevirt/project-infra/pull/3736
[1]: https://kubevirt.devstats.cncf.io/d/9/developer-activity-counts-by-repository-group-table?orgId=1&var-period_name=Last%20year&var-metric=contributions&var-repogroup_name=All&var-country_name=All
Fixes #
/cc @brianmcarey @aburdenthehand

governance,org: replace devstats source

---

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml

this one was forgotten when we switched over to in mem etcd for the others.
Fixes #
**Checklist**
```release-note
NONE
```

etcd in mem for non CSI lane as well

---

github/ci/services/grafana/manifests/grafana.yaml

Adds links to Prow and Testgrid for quicker navigation to the test lanes.
Fixes #

monitoring,grafana: add links to prow and testgrid

---

docs/labels.md
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml

Enable skipping reviews for k8s minor version bumps (example PR [1]) within kubevirtci.
[1]: https://github.com/kubevirt/kubevirtci/pull/1335
Fixes #

skip-review: add for kubevirtci minor version bump

---

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml

With some of these not required, they are not retriggered on PR merges and breaking changes could sneak in.
Fixes #
**Checklist**
```release-note
NONE
```

Make some critical CDI lanes required

---

images/bootstrap/gcs_restapi.sh

As we are calling get_access_token() almost in every function in gcs_restapi.sh, we are trying to get too many access tokens and there are limits to number of refresh tokens that are issued per client-user combination in GCS, and beyond limits it may make old token to stop working, so we are re-using refresh token with this fix. 
Ref: https://developers.google.com/identity/protocols/oauth2#5.-refresh-the-access-token,-if-necessary.
Hopefully this will fix the flakiness in s390x publish jobs like in the [build](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirtci-bump-centos-base-s390x/1863795357893267456)
With these changes when tested spinning a pod, I don't see above …

Fix repeated access token generation for gcs calls in s390x

---

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml

Add periodic to bump common-instancetype releases of release-1.2 branch
in Kubevirt's release-1.4 branch.
Specify that golang 1.22.9 should be installed in the presubmits of
common-instancetypes.
Fixes #
**Checklist**
```release-note
None
```

chore:(common-instancetypes): Add periodic and specify golang version

---

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.14.yaml

```release-note
Add HCO presbmit lanes for branch release-1.14
```

Add HCO presbmit lanes for branch release-1.14

---

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml

```release-note
HCO: bump golang to 1.23
```

HCO: bump golang to 1.23

---

github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-periodics.yaml

Since we have updated the flakefinder jobs they are failing, as the execution path of the binary inside the image has changed [1]
This updates the image references to the latest.
[1]: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-flakefinder-hourly-rolling-window-report/1875154010793578496
Fixes #

flakefinder: update image references

---

github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml

/kind bug
seemingly neither CMD nor ENTRYPOINT is used when running the flakefinder image inside the periodic, therefore we explicitly set the binary via command property.
Fixes #

flakefinder: add command

---

github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-periodics.yaml

Some other prowjob definitions need the `command` addtion.
Examples for indexpagecreator: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-update-flakefinder-indexpage/1876219499313631232
Examples for knmstate and k8snwplumbing:
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-publish-kubemacpool-flakefinder-daily-report/1876063720430374912
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-publish-knmstate-flakefinder-weekly-report/1876072528527495168
Fixes #

flakefinder: fix indexpagecreator

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml

Moves periodic jobs for `project-infra` repository to use go for execution instead of bazel.
Fixes #

project-infra,periodics: execute jobs with go

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml

/kind bug
Running go command inside the git-pr.sh requires to be called from runner script. Also there were some leftovers from bazel calls that needed cleanup.
Successful run here: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirtci-provider-presubmit-creator/1877334718131736576
Fixes #

bugfix: use proper command setup for pr-creator go

---

external-plugins/phased/Containerfile
external-plugins/rehearse/Containerfile
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
go.mod
images/ci-usage-exporter/Containerfile
images/flake-report-creator/Containerfile
images/flakefinder/Containerfile
images/golang/Containerfile
images/indexpagecreator/Containerfile
images/referee/Containerfile
images/release-blocker/Containerfile
images/release-tool/Containerfile
images/test-report/Containerfile

Updates golang to 1.23.4
Fixes #

chore,go: update go to 1.23

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml

Go needs to be run through the runner script.
Successful run here: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-image-bump/1881300138903736320
Fixes #

bug,kubevirt image bump: fix periodic job

---

hack/git-pr.sh

Since characters at and number sign are not allowed in commit messages that appear in GitHub we remove them.
Fixes #

bug: fix git-pr.sh commit message

---

github/ci/prow-deploy/kustom/base/manifests/local/release-blocker_deployment.yaml
github/ci/prow-deploy/kustom/overlays/kubevirt-prow-workloads/resources/shared-images-controller.yaml
hack/update-deployments-with-latest-image.sh

Fixes #3892 
/cc @dhiller 
**Checklist**
```release-note
```

prow,bump: include shared-images-controller in prow deployment bump 

---

images/shared-images-controller/main.go

Fixes #
/cc @dhiller 
**Checklist**
```release-note
```

shared-images: Reduce some duplication by moving golci and registry pull to for loop

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
github/ci/prow-deploy/kustom/base/manifests/local/branch-protector.yaml
github/ci/prow-deploy/kustom/base/manifests/local/cherrypicker_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/crier_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/deck_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/ghproxy.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/grandmatriarch.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/hook_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/horologium_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/needs-rebase_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/pipeline_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/prow_controller_manager_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/sinker_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/statusreconciler_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/tide_deployment.yaml
github/ci/prow-deploy/kustom/base/manifests/test_infra/current/tot_deployment.yaml
github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/resources/prow-exporter-deployment.yaml

This (partly) reverts commit 71ab658db6eadb488db37d4be820e46b8801a5a3. Failure example when clicking on to a job run link:
```
error rendering spyglass page: error rendering template: template: spyglass.html:46:106: executing "content" at <$config.IframeSandboxPermissions>: can't evaluate field IframeSandboxPermissions in type lenses.LensConfig
```
Fixes #
/sig ci
/priority critical-urgent

Revert "autobump,fix: update generic-autobumper (#3932)"

---

github/ci/prow-deploy/files/jobs/kubevirt/user-guide/user-guide-postsubmits.yaml
images/kubevirt-kubevirt.github.io/Dockerfile

Exclude removing python3 in cleanup.
Failure example: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/push-user-guide-main-build-and-push-to-gh-pages/1884907694863683584
Successful run: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/push-user-guide-main-build-and-push-to-gh-pages/1886816884871925760
Fixes kubevirt/user-guide#867
/cc @aburdenthehand @brianmcarey

user-guide,push: fix python3 missing in image

---

images/bootstrap/Containerfile

Adds `ripgrep` to the binary tools install list. Also sorts the install list.
Fixes #

image,bootstrap: add ripgrep to binaries

---

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-periodics.yaml

/cc @0xFelix 
Fixes #
**Checklist**
```release-note
NONE
```

common-instancetypes: Bump periodic bundles job to v1.3.0

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.5.yaml

Release configs for kubevirt/kubevirt release branch release-1.5

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.5.yaml

Phase 2 jobs are enabled
Fixes #
```release-note
NONE
```

Fix 1.5 jobs

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml

Since there seems to not be any users for the four-weekly report we are removing the jobs for the four-weekly flakefinder report.
Fixes #

k/kubevirt,flakefinder: remove four-weekly report

---

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml

* @brianmcarey
* @dankenigsberg 
- https://github.com/kubevirt/project-infra/pull/2455
- https://github.com/kubevirt/kubevirt/pull/11125
- https://github.com/kubevirt/kubevirt/pull/13978
- https://github.com/kubevirt/kubevirtci/pull/873
- Search: https://github.com/search?q=org%3Akubevirt+author%3Arabin-io+&type=pullrequests
- https://github.com/kubevirt/kubevirt.core/issues/19
- https://github.com/kubevirt/kubevirt.core/issues/145
- https://github.com/kubevirt/kubesecondarydns/issues/79
- Search: https://github.com/search?q=org%3Akubevirt+author%3Arabin-io+&type=issues&s=created&o=desc

Add rabin-io to KubeVirt Members

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml

The weekly job seems to suffer from resource starvation [1], so we increase
requests for cpu and mem to make it more stable. Example rehearsal: https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/logs/periodic-publish-kubevirt-flakefinder-weekly-report?buildId=1894549351951241216
[1]: https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/logs/periodic-publish-kubevirt-flakefinder-weekly-report?buildId=1894549351951241216
Fixes #

flakefinder,weekly: increase resource requests

---

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.3.yaml

Add presubmits for common-instancetypes release-1.3
Fixes #
**Checklist**
```release-note
None
```

common-instancetypes: Add presubmits for release-1.3

---

github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml

ci: Ubuntu s390x containerdisks job

---

external-plugins/phased/Makefile

Fixes #
**Checklist**
```release-note
None
```

phased plugin: Fix makefile

---

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-periodics.yaml

/cc @0xFelix 
Fixes #
**Checklist**
```release-note
NONE
```

common-instancetypes: Introduce v1.3 periodic update bundle job

---

github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/ovs-cni/ovs-cni-presubmits-0.32.yaml
github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/ovs-cni/ovs-cni-presubmits-0.34.yaml
github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/ovs-cni/ovs-cni-presubmits-0.36.yaml

New stable branches were introduced to OVS CNI. This adds presubmit jobs for them.
Fixes #
None
**Checklist**
```release-note
NONE
```

Register OVS CNI 0.32 0.34 0.36

---

github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml

Bump golang version of containerdisks jobs to 1.24.1.
Fixes #
**Checklist**
```release-note
None
```

containerdisks: Bump golang version

---

external-plugins/referee/main.go
external-plugins/referee/server/server.go
github/ci/prow-deploy/kustom/base/manifests/local/referee-deployment.yaml

Make the no of max retests which is currently hard coded configurable. This will allow us to gradually decrease the value.
Fixes #
/cc @brianmcarey @dankenigsberg

feat: make configurable no of max retests

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml

Since we are seeing Insufficient resources, we increase the requested memory to 16Gi
Fixes #

fix: increase memory for check-provision-k8s

---

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.3.yaml

Fixes #
**Checklist**
```release-note
NONE
```

common-instancetypes: Correct Debian release-1.3 job branch

---

github/ci/prow-deploy/kustom/base/manifests/local/referee-deployment.yaml

The number of retests per commit is decreased to 3 with this PR.
Fixes #

fix: decrease number of max retests per commit

---

external-plugins/test-subset/plugin/handler/handler.go

Add some more log statements so we can follow the execution path.
Fixes #
/cc @oshoval

feat(test-subset): add debug statements to follow execution

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml

Fixes #
**Checklist**
```release-note
```

add periodic kwok job with 100 vmi count to compare real vs simulated

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

In PR https://github.com/kubevirt/kubevirt/pull/13977 a variable was renamed from TARGET_COMMIT to TARGET_COMMIT_RANGE, therefore this change fixes the call.
Fixes #

fix(check-tests-for-flakes): update env var used

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Simplify prow job configurations by moving environment variables to automation/test.sh in kubevirt/kubevirt where the majority of job configuration occurs currently. This makes it easier to see how each test lane is configured as it is all included in one place. 
This PR requires the following PR to be merged in kubevirt first: 
https://github.com/kubevirt/kubevirt/pull/14386
Fixes #
**Checklist** …

kubevirt,e2e: consolidate environment variables to automation/test.sh

---

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.15.yaml

```release-note
add tests for HCO 1.15.0
```

add tests for HCO 1.15.0

---

Makefile
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
go.mod
hack/lint.sh

Fixes #4084 
/cc @dhiller 
**Checklist**
```release-note
```

lint: Remove the local install of golangci-lint binary

---

.golangci.yaml
external-plugins/botreview/main.go
external-plugins/botreview/review/prow_autobump.go
external-plugins/botreview/review/review.go
external-plugins/botreview/server/server.go
external-plugins/referee/main.go
external-plugins/rehearse/plugin/handler/handler.go
external-plugins/release-blocker/main.go
external-plugins/release-blocker/server.go
robots/cmd/botreview/main.go
robots/cmd/flake-report-creator/cmd/cmd_suite_test.go
robots/cmd/flake-report-creator/cmd/jenkins.go
robots/cmd/flake-report-creator/cmd/prow.go
robots/cmd/flake-report-creator/cmd/prow_test.go
robots/cmd/flake-stats/main.go
robots/cmd/flakefinder/main.go
robots/cmd/kubevirtci-bumper/main.go
robots/cmd/kubevirtci-presubmit-creator/main.go
robots/cmd/kubevirtci-presubmit-creator/main_test.go
robots/cmd/kubevirtci-presubmit-remover/main.go
robots/cmd/perf-report-creator/plot.go
robots/cmd/release-querier/main.go
robots/pkg/kubevirt/cmd/get/support-matrix.go

- Enable unused linter
Ref #3837 
**Checklist**
```release-note
none
```

Enabled unused linter

---

.golangci.yaml
external-plugins/botreview/review/result.go
external-plugins/botreview/review/review.go
external-plugins/phased/plugin/handler/handler.go
external-plugins/rehearse/plugin/handler/handler.go
limiter/limiter_test.go
releng/release-tool/release-tool.go
robots/cmd/flake-report-creator/cmd/prow.go
robots/cmd/indexpagecreator/main.go
robots/cmd/job-config-validator/main.go
robots/cmd/kubevirt-lanes-overview/main.go
robots/cmd/org-access-check/main.go
robots/cmd/perf-report-creator/main.go
robots/cmd/retests-to-merge/main.go
robots/cmd/test-label-analyzer/cmd/stats.go
robots/cmd/test-report/cmd/filter/filter.go
robots/pkg/flakefinder/downloader.go
robots/pkg/flakefinder/report_data.go
robots/pkg/git/git.go
robots/pkg/kubevirt/cmd/check/providers.go
robots/pkg/kubevirt/cmd/copy/jobs.go
robots/pkg/kubevirt/cmd/get/support-matrix.go
robots/pkg/kubevirt/prowjobconfigs/jobconfig.go
robots/pkg/test-report/test_report.go
robots/pkg/test-report/test_report_test.go

- enabled go simple linter
Ref #3837
**Checklist**
```release-note
none
```

Enabled gosimple linter

---

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml

@shubham-pampattiwar
* @mhenriks 
* @aglitke 
* @ShellyKa13 
- https://github.com/kubevirt/kubevirt-velero-plugin/pull/344 
- https://github.com/kubevirt/kubevirt-velero-plugin/pull/345
- https://github.com/kubevirt/kubevirt-velero-plugin/pull/346

Add shubham-pampattiwar to KubeVirt members

---

github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml

This PR adds a workflow nightly job to the CNAO periodics.
Fixes #
Pending https://github.com/kubevirt/cluster-network-addons-operator/pull/2216 merge
**Checklist**
```release-note
NONE
```

cnao: Add nightly workflow job

---

hack/contributions.sh
images/contributions/Containerfile

Adds a Containerfile that builds an image from the kubevirt community repository containing the contributions cli.
Also adds a shell script for running that cli conveniently.
Example call:
```
$ ./hack/contributions.sh /path/to/github/oauth \
--username dhiller \
--repo project-infra \
--months 12
```
Fixes #
FYI @vladikr

feat(contributions): containerize cli

---

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml

@Sreeja1725 
- @alaypatel07 
- @dhiller 
**PRs reviewed and/or authored**
- [Add unit tests to check for API backward compatibility #11856](https://github.com/kubevirt/kubevirt/pull/11856)
- [Add memory/cpu utilization of components to kubevirt benchmarks #12116](https://github.com/kubevirt/kubevirt/pull/12116)
- [Integrate kwok with sig-scale tests #12117](https://github.com/kubevirt/kubevirt/pull/12117)
- [Update promql query of cpu and memory metrics for sig-performance tests #12546](https://github.com/kubevirt/kubevirt/pull/12546)
- [Update kubevirt_rest_client_request_latency_seconds to count list cal… #12716](https://github.com/kubevirt/kubevirt/pull/12716)
- [Add virt-handler cpu and memory usage metrics …

Add Sreeja1725 as  a member to kubevirt org

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
hack/bump-fedora-images-version.sh

Every few months a new release is created for Fedora - adding automation for updating this will help to keep us up to date
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```

images: Add script and periodic to automate the update of fedora based containers

---

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml

This adds @fossedihelm to the release-team GitHub team.
It also gives the release-team write access to the `k/kubevirt` Github repository, as that is (still) required for doing releases.
Fixes #
/cc @fossedihelm @xpivarc

access(org): add fossedihelm to release-team

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml

The label [`skip-review`](https://github.com/kubevirt/project-infra/blob/main/docs/labels.md#skip-review) will allow the PR to merge automatically if all required CI checks are green.
Also we are adding the `release-blocker` label as we don't want any of these PRs to fail unnoticed.
Fixes #
/cc @enp0s3 @xpivarc @jean-edouard 
See https://github.com/kubevirt/kubevirt/pull/13406#issuecomment-2783672232

chore: skip review for automatic kubevirt rpm bump

---

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml

GitHub Username
@aqilbeig
Requirements
[ ✅] I have reviewed the community code of conduct (https://github.com/kubevirt/kubevirt/blob/master/CODE_OF_CONDUCT.md)
[ ✅] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
[ ✅] I have subscribed to the kubevirt-dev e-mail list (https://groups.google.com/forum/#!forum/kubevirt-dev)
[ ✅] I am actively contributing to KubeVirt
[ ✅] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
[ ✅] I have spoken to my sponsors ahead of this application and they have agreed to sponsor my application
[ ✅] I have publicly introduced myself to the community through one of the community communication channels
Sponsors
@dhiller
@vladikr …

adding aqilbeig as a KubeVirt member

---

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml

Removes @acardace from some GitHub teams, since he's moved on to other endeavours.
Fixes #
/cc @xpivarc @stu-gott

chore(orgs.yaml): remove acardace from GitHub teams

---

github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
hack/checkconfig.sh

The config was accidentally placed inside the section for project-infra
repository, as it makes sense to have it for the whole org we move it
into the org section.
Also we add a script which we can use to validate prow configuration locally.
Fixes #
/cc @fossedihelm

fix(restricted_labels): move approved-vep into org section

---

github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml

ci: Fedora s390x containerdisks job

---

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml

@lerrigatto
* @dhiller 
* @fossedihelm
- https://github.com/kubevirt/project-infra/pull/4093

Adds lerrigatto as member

---

github/ci/services/grafana/deploy/base/grafana.yaml

feat(monitoring): add e2e lane runtimes dashboard

---

github/ci/prow-deploy/prow-autobump-config.yaml

Adds the path for the checkconfig script to the autobump config, so that it will be on the recent version.
Fixes #
/cc none

chore(autobump): add checkconfig script path

---

github/ci/prow-deploy/files/jobs/kubevirt/application-aware-quota/application-aware-quota-presubmits-1.4.yaml

Fixes #
**Checklist**
```release-note
NONE
```

Add presubmits for AAQ 1.4

---

github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubesecondarydns/kubesecondarydns-presubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.4.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.5.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

This reverts commit 93740f81c7e94c89e36b481bedbf8fe5c4a4740b.
Cluster is online again.
Fixes #
/cc @jschintag

Revert "fix(s390x): disable reporting for most s390x presubmits"

---

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml

```release-note
HCO: Bump golang to 1.24
```

HCO: Bump golang to 1.24

---

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml

**GitHub Username:** @salawhaaat  
- @0xFelix  
- @victortoso  
1. [#14150](https://github.com/kubevirt/kubevirt/pull/14150) - Replaced `NewMinimalVMI` with `libvmi`  
2. [#14198](https://github.com/kubevirt/kubevirt/pull/14198) - Lint cleanup in `virtctl/create/vm`  
3. [#14085](https://github.com/kubevirt/kubevirt/pull/14085) - Version cleanup PR  
- Actively working on [#386](https://github.com/kubevirt/community/issues/386)  
---
Thank you to the sponsors and the community as a whole.

Add salawhaaat as a kubevirt member

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml

The ARM cluster has been changed - update the liveness check to check the new cluster
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```

project-infra,periodic: fix arm cluster liveness check

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Explicitly set provider for windows job
This will unblock https://github.com/kubevirt/kubevirt/pull/14999
Fixes #
**Checklist**
```release-note
none
```

Explicitly set provider for windows job

---

hack/contributions.sh

Modify the `/tmp` dir mount in contributions.sh by adding the labelling suffix `:z` to the tmp mount so the output can be written to the tmp directory.
Fixes #

fix(contributions.sh): add labelling suffix to tmp

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Bump the K8s version of the following lanes to v1.33:
- IPv6 single stack
- Multus v4 + dynamic-networks-controller
Both for pre-submit and periodic lanes.
Fixes #
**Checklist**
```release-note
NONE
```

Bump network lanes to K8s 1.33

---

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml

@Dsanatar
* @awels 
* @alromeros 
[#15254](https://github.com/kubevirt/kubevirt/pull/15254)
[#15308](https://github.com/kubevirt/kubevirt/pull/15308)
[#3764](https://github.com/kubevirt/containerized-data-importer/pull/3764)
[#3744](https://github.com/kubevirt/containerized-data-importer/pull/3744)
[#3843](https://github.com/kubevirt/containerized-data-importer/pull/3843)

Add Dsanatar as a kubevirt member

---

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml

@frenzyfriday
* @eddev
* @orelmisan
https://github.com/kubevirt/kubevirt/pull/15255
https://github.com/kubevirt/kubevirt/pull/15197
https://github.com/kubevirt/kubevirt/pull/15301
https://github.com/kubevirt/kubevirt/pull/15108

Add frenzyfriday as kubevirt member

---

github/ci/prow-deploy/files/jobs/kubevirt/application-aware-quota/application-aware-quota-presubmits-1.5.yaml

Fixes #
**Checklist**
```release-note
```

Add presubmits jobs to aaq 1.5

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Fixes #
**Checklist**
```release-note
none
```

Bump compute non-standard lanes to 1.33

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

/wg arch-arm
This moves the arm64 periodic, e2e and conformance presubmits for main to `kind-1.33`.
Fixes #
**Checklist**
```release-note
NONE
```

arm64: Move presubmits to kind-1.33

---

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml

@gustab-kamil
* @nunnatsa
* @machadovilaca
[Added reconcile after modifying secret labels #3625](https://github.com/kubevirt/hyperconverged-cluster-operator/pull/3625)
[Move the enableApplicationAwareQuota feature gate to new field #3391](https://github.com/kubevirt/hyperconverged-cluster-operator/pull/3391)
[Ensure safe initialization with sync.Once #3631](https://github.com/kubevirt/hyperconverged-cluster-operator/pull/3631)

Add gustab-kamil as kubevirt member

---

.golangci.yaml
Makefile
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
go.mod
images/shared-images-controller/Containerfile
images/shared-images-controller/go.mod
limiter/limiter_test.go
robots/cmd/kubevirtci-presubmit-creator/main.go
robots/cmd/test-report/cmd/dequarantine/execute.go
robots/cmd/test-report/cmd/dequarantine/execute_test.go

chore: bump go to 1.25

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
robots/cmd/perf-report-creator/README.md
robots/cmd/perf-report-creator/main.go
robots/cmd/perf-report-creator/plot.go
robots/cmd/perf-report-creator/release-graph.sh
robots/cmd/perf-report-creator/shape.yaml

Added a script to add benchmarks data to the ci-performance-benchmarks repo during every release.
Fixes #
- Currently, we have a script that clones and pushes data to CI-performance benchmarks as part of a periodic KubeVirt CI job. In this PR, we added few flags and a script to mark important dates during releases, such as previous release dates and Kubernetes upgrade dates, when plotting graphs for a release. The shape.yaml file contains these important dates along with other relevant information.
- This script is run during every release.
- Updated the …

Automate creation of benchmarks data during kubevirt release

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml

Also include the istioctl version that is planned to be introduced https://github.com/kubevirt/kubevirtci/pull/1535
Fixes #
/cc @dhiller @nirdothan 
**Checklist**
```release-note
```

periodic,mirror: Update istioctl versions to mirror to match what has been used recently in kubevirtci

---

robots/cmd/perf-report-creator/shape.yaml

Added v1.5 date to generate benchmarks graph and to submit a PR with the benchmarks data.
Fixes #
**Checklist**
```release-note
NONE
```

Generate v1.6 benchmarks data

---

github/ci/prow-deploy/files/jobs/kubernetes-sigs/cluster-api-provider-kubevirt/cluster-api-provider-kubevirt-presubmits.yaml

CAPK: bump golang version to v1.24.7

---

github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml

Adds `do-not-merge/invalid-commit-message` that should be checked by tide to the query.
Fixes #

feat(tide): add invalid-commit-message label to tide query

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Fixes #
**Checklist**
```release-note
none
```

Bump compute non-standard lanes to 1.34

---

robots/cmd/per-test-execution/main.go

In case the file ends before the top X failures have been read, handle the EOF return value by stopping the loop.
Fixes: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-push-per-test-execution-results-six-months/1973232755101667328#1:build-log.txt%3A2484
Fixes #

fix(per-test-execution): handle EOF

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Fixes #
/cc @dhiller 
**Checklist**
```release-note
```

kubevirt: update remaining k8s-1.31 lanes to k8s-1.34

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml

This change is required to update kubevirtci to go v1.24 until the golang bootstrap image default is updated to go v1.24
https://github.com/kubevirt/kubevirtci/pull/1545
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```

kubevirtci: update jobs to run with GIMME_GO_VERSION=1.24.7
