kubevirt/project-infra

github/ci/services/prometheus-stack/manifests/stack/production-control-plane/thanos-receive-ingress.yaml, github/ci/services/prometheus-stack/manifests/stack/production-control-plane/thanos.yaml
Thanos Receive is required on the control plane cluster so that the new workloads cluster can federate prometheus metrics using remote write. 
[1] https://thanos.io/v0.21/components/receive.md/
[2] https://docs.openshift.com/container-platform/4.12/monitoring/configuring-the-monitoring-stack.html#configuring_remote_write_storage_configuring-the-monitoring-stack
=> Add files to deploy thanos receive to control plane cluster

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The realtime presubmit lane was mistakenly removed as part of #2790
The lane should of been upgraded rather than removed.
Reintroducing the lane in this change.
/cc @vasiliy-ul @xpivarc @dhiller
=> Add 1.27 sig-compute realtime presubmit

robots/cmd/test-report/cmd/filter/BUILD.bazel, robots/cmd/test-report/cmd/filter/filter.go
`test-report filter` command filters the `json` output of the test-report that contains the data of the observed timeframe of tests being run over a set of lanes. In detail the json captures whether a test was seen to have run on any lane or whether it was seen inside a dont_run_tests.json file, which indicates it's not supported on a version.
From this data we had created a YAML file that contained all data spanning all versions and groups, but the yaml output was too complicated for the audience to look at.
We are now generating one file per group per version in order to make it easy to consume the files. Each of these files contains a plaintext set of test names.
/cc @dominikholler
=> test-report filter: convert yaml output into text and create several files

github/ci/services/prometheus-stack/manifests/stack/production-control-plane/thanos.yaml
The previous volume ran out of space
`panic: write header: write /var/thanos/receive/default-tenant/chunks_head/000067.tmp: no space left on device`
=> Increase size of persistent volume attached to thanos receive

docs/reports.md
Doc page that holds links to the reports we generate regularly.
=> Add page to link to available reports for kubevirt org

github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-postsubmits.yaml
Make target had changed and the environment variable indicating which repo to push to has changed as well. Converging on kubevirt-csi-driver repo.
=> Fix csi-driver post submit

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
This is possible since:
https://github.com/kubevirt/kubevirtci/pull/996
The follow CI would benefit from it:
https://github.com/kubevirt/kubevirt/pull/10015
=> Add usb emulation for hostdev testing

robots/cmd/flake-stats/flake-stats.gohtml, robots/cmd/flake-stats/main.go
Since the data is available for other projects as well, we make `org` and `repo` configurable, while keeping defaults for `kubevirt/kubevirt`.
=> flake-stats: make org and repo configurable

robots/pkg/test-label-analyzer/stats.go, robots/pkg/test-label-analyzer/stats_test.go
There was a case where parsing git blame info failed on special characters in the author name. 
Simplified the regex first, then added test case and fixed the expression. Refactored the test cases into a table, also created a struct that holds the expected data.
=> Fix test label analyzer parsing

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Very high memory usage has been seen in the sig-storage presubmit lanes
that does not appear in the periodic lanes.
The periodic lanes do not include running etcd from memory.
Presubmit lanes use about 32.5 GB RAM at max usage while the periodic lanes use just 26.5 GB RAM.
=> Remove running etcd in memory from sig-storage lanes

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Seems to be on Go 1.19 even though go.mod says otherwise.
=> Update go version to 1.19 for testgrid config presubmit

github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner/hostpath-provisioner-postsubmits.yaml
because doing qemu compile of arm64 and ppe releases. That takes some time and it is currently timeing out during the build while it is progressing.
=> Increase hostpath provisioner timeout to 3 hours

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
In order to have a lookback we store a timestamped copy so we can compare with earlier days.
Example: https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flake-stats-14days-2023-07-19.html
=> Preserve a copy of the flake-stats report with timestamp

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
The 1.28 beta will be released soon  - add this prowjob to allow testing of the new provider. 
/cc @xpivarc @dhiller @enp0s3
=> Add check provision job for 1.28 kubevirtci provider to allow for testing

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
More storage providers use WaitForFirstConsumer not just for local volumes,
but also generally to do things like availability zone distribution and so forth.
Let's make sure we integrate well with those.
Currently we only test HPP with WaitForFirstConsumer and
that leaves some open integration points like snapshots/csi clones
=> Add CDI ceph waitforfirstconsumer lane

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
The 1.28 provider was merged[1] so lets enable this lane to always run so that we prevent issues being introduced.
[1] https://github.com/kubevirt/kubevirtci/pull/1059
/cc @dhiller
=> Always run the check provision job for 1.28

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
This is a draft of the implementation on how we use vm-image-builder image to build multi-arch fedora-realtime and fedora-with-test-tooling images.
I do not integrate the publish process into the job `publish-kubevirtci`. I only trigger the build job when related files changes.
As fedora-realtime and fedora-with-test-tooling do not change often, and it resource consuming to do the muti-arch build, it is not necessary to publish them in every release.
=> kubevirtci, presubmit: add jobs to build multi-arch fedora-realtime and fedora-with-test-tooling image

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Once the k8s-1.28 provider[1] is published to kubevirt/kubevirt - these prowjobs will allow us to get early feedback for the e2e jobs. 
[1] https://github.com/kubevirt/kubevirtci/pull/1059
/hold
=> Add 1.28 periodics & presubmits to allow early testing

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Should help us keep in sync and fail upstream instead of during downstream build processes
=> Add gate for CDI deps update

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
This doubles the node memory from the default of 4096 to 8192 so we can start VirtualMachines using the u1.medium instance type that itself requires 4Gi.
=> common-instancetypes: Increase node memory in functest

github/ci/prow-deploy/files/orgs.yaml, github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml, github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Rename https://github.com/kubevirt/kubernetes.kubevirt to https://github.com/kubevirt/kubevirt.core. This repo will hold lean Ansible bindings for KubeVirt.
=> Rename kubernetes.kubevirt repo to kubevirt.core

github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
This is required so the Ansible Middleware release automation is able to create and push the necessary commits.
=> Disable required status checks in kubevirt.core

github/ci/prow-deploy/files/orgs.yaml
@sudo-NithishKarthik
[x] I have reviewed the community code of conduct (https://github.com/kubevirt/kubevirt/blob/master/CODE_OF_CONDUCT.md)<br>
[x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)<br>
[x] I have subscribed to the kubevirt-dev e-mail list (https://groups.google.com/forum/#!forum/kubevirt-dev)<br>
[x] I am actively contributing to KubeVirt<br>
[x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines<br>
[x] I have spoken to my sponsors ahead of this application and they have agreed to sponsor my application<br>
[x] I have publicly introduced myself to the community through one of the community communication channels<br>
* @alicefr
* @xpivarc
* …
=> Add Nithish Karthik as a Community Member

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Currently the tests are not run in parallel, therefore they are timing out sometimes. See i.e. https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-check-tests-for-flakes/1691415578037719040#1:build-log.txt%3A3438
Let's run them in parallel.
Also fix resource request on linter job.
=> Run check-tests-for-flakes in parallel, set memory

github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-presubmits.yaml
Its currently at 1.18, and I am updating the libraries to k8s 1.26 which requires a newer golang.
=> Update kubevirt-csi-driver presubmit golang to 1.20

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Whoops - never meant to run this on any release branches. just main is enough
=> Skip ceph wffc lane on release branches

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml, github/ci/prow-deploy/files/orgs.yaml
These have been unused for some time now and even marked as deprecated within the repo README so lets archive.
=> ssp-operator: Archive kubevirt-ssp-operator & kubevirt-template-validator

github/ci/prow-deploy/files/orgs.yaml
I was added as a Kubevirt community member two weeks back (https://github.com/kubevirt/project-infra/pull/2925). I have changed my Github handle after that, because of which I was removed from the `kubevirt` organization. This PR updates my Github handle in prow configuration files. 
Relevant PR: https://github.com/kubevirt/project-infra/pull/2925
=> [Fix] Nithish Karthik - Update Github Handle 

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
1.28 periodics are stable enough to give them a try for running them on PRs:
* [sig-compute](https://testgrid.k8s.io/kubevirt-periodics#periodic-kubevirt-e2e-k8s-1.28-sig-compute)
* [sig-network](https://testgrid.k8s.io/kubevirt-periodics#periodic-kubevirt-e2e-k8s-1.28-sig-network)
* [sig-operator](https://testgrid.k8s.io/kubevirt-periodics#periodic-kubevirt-e2e-k8s-1.28-sig-operator)
* [sig-storage](https://testgrid.k8s.io/kubevirt-periodics#periodic-kubevirt-e2e-k8s-1.28-sig-storage)
Make 1.28 lanes run by default, but not yet voting. Turn off 1.25 default sig lanes for PRs.
In short:
* `always_run: false` for 1.25 sig lanes
* `always_run: true` for 1.28 sig lanes
/cc @rthallisey @aburdenthehand @xpivarc
=> Turn `always_run` off for 1.25 and on for 1.28

images/bootstrap-legacy/Dockerfile, images/golang-legacy/Dockerfile
Amend Dockerfile of bootstrap-legacy and golang-legacy to enable multiarch image build
=> Add ARG ARCH in Dockerfile of bootstrap-legacy and golang-legacy

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
The k8s-1.25 provider will be removed soon. We no longer need to check the provisioning of the provider against every kubevirtci PR.
=> Set check-provision-k8s-1.25 to always-run false

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
As the job will build both x86_64 images and Arm64 images which consumes more memory, we increase the memory limit for the job.
In terms of the corresponding presubmit job, it only builds x86_64 images, so it is not necessary to increase its memory limit.
=> project-infra postsubmit: increase the memory limit for build multiarch legacy images

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
Current timeout default of 2h is not sufficient:
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/publish-bootstrap-legacy-images/1696460103638585344#1:build-log.txt%3A5526
/cc @brianmcarey @zhlhahaha
=> Increase timeout for publish bootstrap legacy job

.github/PULL_REQUEST_TEMPLATE/add_repo.md, .github/PULL_REQUEST_TEMPLATE/pull_request_template.md, docs/how-to-add-a-new-repository.md
This PR adds a document that describes the process of adding a new repository to the KubeVirt org.
It also adds two pull request templates:
* a default template
* a PR template that can be used for add-repo PR
The latter template contains a checklist of things to consider when adding a repository.
See docs for adding templates here: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository
=> Add process document and PR template for adding repos 

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
We have disabled the FOSSA license check to remove strain for contributors, since those were failing due to erroneous things (i.e. license failures that weren't even present in the dependency tree any more).
Since the licensing issues have been resolved, we can enable them again.
/cc @stu-gott @xpivarc
=> Reenable FOSSA license check

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-postsubmits.yaml
Sometimes we need to create a specific builder for a release branch (maybe new version of go). Right now it is not possible to push a new builder from a branch This modifies the job to also push from release branches if there is a new builder.
=> CDI push builder images on release branches

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
As the k8s-1.25 provider is due to be removed[1] - this job is no longer required.
[1] https://github.com/kubevirt/kubevirtci/pull/1074
=> Remove check provision job for k8s-1.25 provider

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml, github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml, github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
The jobs are really using podman rather than docker so it is more clear for everyone to swap to using podman in the scripts.
`docker` is just symlinked to podman in the bootstrap image[1].
[1] https://github.com/kubevirt/project-infra/blob/33c4878341d4274b58052616bbebd61b5513716e/images/bootstrap/Dockerfile#L84
/cc @enp0s3 @dhiller
=> Switch docker to podman in prowjob scripts

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml, github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml, images/fcos/Dockerfile, images/fedora-coreos-kubevirt/Dockerfile
The fedora coreos kubevirt image was using the wrong container, this PR rename the directory and point to the proper one.
=> Use correct container for fcos image, rename dir

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Since 1.25 is going to be removed soon, we are bumping presubmits to use 1.27.
* performance
* network single stack
/cc @rthallisey @acardace
=> Bump performance and network single stack presubmits to use 1.27

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Since 1.25 is going to be removed soon, we are bumping the sig-performance jobs to 1.27.
/cc @rthallisey @brianmcarey
=> Bump sig-performance periodics to use 1.27

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
cri-o v1.28.0 has been released[1] - this should be added to the mirror so that it can be installed to the 1.28 kubevirtci provider
[1] https://github.com/cri-o/cri-o/releases/tag/v1.28.0
=> Add cri-o version 1.28 to the kubevirt mirror

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
The go version in the legacy image is getting quite old and can cause the publish job to fail[1].
Lets update this job to use the podman based golang image which has a more up to date version of go.
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/publish-kubevirtci/1697339447776907264#1:build-log.txt%3A8
=> Update kubevirtci to use podman based golang image

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml, github/ci/prow-deploy/kustom/overlays/kubevirtci-testing/resources/ingress-nginx-controller.yaml, github/ci/prow-deploy/molecule/default/Dockerfile.j2, github/ci/prow-deploy/molecule/default/molecule.yml, github/ci/prow-deploy/molecule/default/prepare.yml, github/ci/prow-deploy/molecule/default/smoke_tests.yml, github/ci/prow-deploy/molecule/default/vars/kubevirtci-testing.yml, images/prow-deploy/Dockerfile, images/prow-deploy/requirements.txt
The prow-deploy presubmit job is quite out of date running against kubernetes v1.21.1
This change updates the test lane to use more recent components including:
- Update the job to use podman in container rather than the old docker in docker setup.
- Test against Kubernetes v1.25.11 
- Update kind from v0.11.1 to the latest v0.20.0
- Upgrade ansible and other python dependencies to the latest available
- Update the ingress controller for the newer Kubernetes version
=> Update the prow-deploy test job to use podman and latest kind

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
Providers that have been published since the switch to publishing with podman[1] are failing to start up correctly when run with docker so we need to change back to publishing with docker for now.
[1] https://github.com/kubevirt/project-infra/pull/2972
=> Switch publish kubevirtci prowjob back to docker

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.10.yaml, github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
Golang 1.19 got EOL with the release of Golang 1.21 (08 Aug 2023):
require Golang 1.20.8 on release-1.10 stabilization branch and 1.21.1
on main.
=> hco: require fresher golang env

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
There seems to be an issue starting the kind cluster on the new control plane cluster[1]. Temporarily moving back to the old cluster while investigating the issue.
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/2994/pull-project-infra-prow-deploy-test/1704811297931005952
/cc @dhiller
=> Temporarily move prow deploy test lane back to old cluster

go.mod, robots/cmd/flakefinder/BUILD.bazel, robots/cmd/flakefinder/main.go, robots/cmd/flakefinder/report.go, robots/pkg/flakefinder/BUILD.bazel, robots/pkg/flakefinder/api/BUILD.bazel, robots/pkg/flakefinder/api/types.go, robots/pkg/flakefinder/downloader.go, robots/pkg/flakefinder/downloader_test.go, robots/pkg/flakefinder/flakefinder.go, robots/pkg/flakefinder/github/BUILD.bazel, robots/pkg/flakefinder/github/github.go
Move github structs and clients behind interfaces which allow working on gerrit and gerrit Change Requests in the future as well.
* `PullRequest` is now hidden behind an `api.Change` interface
* GitHub client is hidden behind a `api.Query` interface
Checking if a prow job was executed on the latest change was moved behind the `api.Query` interface.
=> Generalize flakefinder for future gerrit usage

robots/cmd/flake-stats/flake-stats.gohtml, robots/cmd/flake-stats/main.go
Since we currently can't see when the failures that are shown per date occurred we are adding to each per day header (that contains a date) a link to the flakefinder report of that day.
Example flake-stats report: https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flake-stats-14days-2023-09-25-preview.html
Background: since the failures in a pull request may occur many days before that PR gets merged, but are shown in the report window of the day and thus appear as if they happened on that day in the flake-stats report, we need a way to check whether the failures are current or not.
See also [flake-stats: per day values not correct](https://github.com/kubevirt/project-infra/issues/2980)
**Which issue(s) this PR …
=> Add flakefinder urls to flake-stats report per day headlines

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml, robots/pkg/kubevirt/cmd/get/BUILD.bazel, robots/pkg/kubevirt/cmd/get/get.go, robots/pkg/kubevirt/cmd/get/release-model.go, robots/pkg/kubevirt/cmd/get/support-matrix.go, robots/pkg/kubevirt/cmd/get/support-matrix.gomd
Generates from the testing job configurations a markdown document a matrix of all kubevirt versions vs. the k8s versions, including information about which versions are already EOL.
Information is reduced to a reasonable amout:
* only the last three k8s EOL versions are shown, regardless of how many are there, resulting in 6 k8s versions shown at any time
* all the K6t versions that don't support any of the former K8s versions are removed from the data set
Result:
---
| KubeVirt version | 1.27               | 1.26               | 1.25               | 1.24<sup>EOL</sup> | 1.23<sup>EOL</sup> | 1.22<sup>EOL</sup> |
|------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|
|              1.0 | ✓ …
=> Generate support matrix for kubevirt/kubevirt

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml, github/ci/prow-deploy/kustom/components/docker-mirror-proxy/pv/patches/JsonRFC6902/deployment.yaml, github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/kustomization.yaml, github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/patches/JsonRFC6902/prow-namespace.yaml, github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/patches/StrategicMerge/docker-mirror_deployment.yaml, github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/resources/admin-rbac.yaml, github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/resources/bootstrap.yaml, github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/resources/docker-mirror-proxy_pvc.yaml, github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/yq_scripts/README, github/ci/prow-deploy/vars/kubevirt-prow-control-plane/main.yml
Greenhouse(Bazel cache) and the docker-mirror-proxy are required on the new cluster in order to enable the migration of workloads from the existing control plane cluster.
/cc @xpivarc @dhiller @enp0s3
=> Deploy greenhouse and docker-mirror-proxy to new control plane cluster

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml, robots/cmd/perf-report-creator/graph.sh
The periodic jobs already clones https://github.com/kubevirt/ci-performance-benchmarks repository. This means the graphing utility will have all the data from the history. Running the graph.sh immediately after scraping will update the index.html
fixes https://github.com/kubevirt/project-infra/issues/2926
=> add graphing to periodic job

github/ci/prow-deploy/files/jobs/kubevirt/managed-tenant-quota/managed-tenant-quota-presubmits-1.1.yaml, github/ci/prow-deploy/files/jobs/kubevirt/managed-tenant-quota/managed-tenant-quota-presubmits.yaml
Since we descovered that there should
be version alignment between kubevirt
and mtq so we should always check the
latest version for main and use v1.0.0
for mtq v1.1
=> No reason to keep nightly jobs for mtq

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
We do not want deployments running while the prow services are being moved over to the new control plane cluster.
/cc @dhiller 
/hold 
Only to be merged when ready to move cluster.
=> Remove the auto deploy postsubmit for the old control plane cluster

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
A couple of recent issues were hit in the rootful periodic lanes - optional presubmit lanes will be useful if testing with root is needed. 
/cc @xpivarc
=> Add optional rootful presubmit lanes for kubevirt

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml, github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml, github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml, github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml, github/ci/prow-deploy/kustom/base/manifests/local/branch-protector.yaml, github/ci/prow-deploy/kustom/base/manifests/local/cherrypicker_deployment.yaml, github/ci/prow-deploy/kustom/base/manifests/local/label-sync-kubevirt.yaml, github/ci/prow-deploy/kustom/base/manifests/local/label-sync-nmstate.yaml, github/ci/prow-deploy/kustom/base/manifests/test_infra/current/crier_deployment.yaml, github/ci/prow-deploy/kustom/base/manifests/test_infra/current/deck_deployment.yaml, github/ci/prow-deploy/kustom/base/manifests/test_infra/current/ghproxy.yaml, github/ci/prow-deploy/kustom/base/manifests/test_infra/current/hook_deployment.yaml, github/ci/prow-deploy/kustom/base/manifests/test_infra/current/horologium_deployment.yaml, github/ci/prow-deploy/kustom/base/manifests/test_infra/current/needs-rebase_deployment.yaml, github/ci/prow-deploy/kustom/base/manifests/test_infra/current/prow_controller_manager_deployment.yaml, github/ci/prow-deploy/kustom/base/manifests/test_infra/current/sinker_deployment.yaml, github/ci/prow-deploy/kustom/base/manifests/test_infra/current/statusreconciler_deployment.yaml, github/ci/prow-deploy/kustom/base/manifests/test_infra/current/tide_deployment.yaml, github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/prow-exporter-deployment.yaml, github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/patches/JsonRFC6902/crier_deployment.yaml, github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/patches/JsonRFC6902/deck_deployment.yaml, github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/patches/JsonRFC6902/hook_deployment.yaml, github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/patches/JsonRFC6902/prow_controller_manager_deployment.yaml, github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/patches/JsonRFC6902/sinker_deployment.yaml, github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/patches/JsonRFC6902/tide_deployment.yaml, github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/resources/prow-exporter-deployment.yaml, github/ci/prow-deploy/molecule/default/prepare.yml, hack/bump-prow.sh
There was another kubeconfig `kubeconfig-k8s-infra-kops-prow-build` added to the prow service deployment specs - this change adds patches to remove the volumes and mounts for this new kubeconfig. 
This also included the prow bump from #3009 
Closes #3009 
=> Remove unnecessary kubeconfig from prow deployments to fix auto bump

robots/cmd/flake-stats/flake-stats.gohtml, robots/cmd/flake-stats/main.go, robots/cmd/flake-stats/main_test.go
Instead of sorting just by number of failures which disregards the recency of failures we first take into account how recent a failure in a set is compared to another. This yields a list where the tests with most recent failures appear earlier than those with less recent failures.
See:
* [preview report](https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flake-stats-14days-2023-09-27-preview.html)
* [original report](https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flake-stats-14days-2023-09-27.html)
Fixes #
**Special notes for …
=> flake-stats: sort flakes with more recent failures first

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
feat: add kubevirt-snyk user as an admin to kubevirt org
Snyk is a platform to perform security scans. The snyk integration requires a special github user to able to do scans of PRs and repos.
=> feat: add kubevirt-snyk user as an admin to kubevirt org

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Forgotten in https://github.com/kubevirt/project-infra/pull/3023/
Increasing by 3G per 4 nodes = 12G. Now the total is 15G per 4 nodes = 60G and we are running with 70G requests.
=> Increase performance presubmit node size

OWNERS
The automation for creating kubevirt releases requires write access to proeject-infra to create the job configs for the release branches.
Antonio is part of the release team and requires write access to project-infra as a result.
/cc @davidvossel @fabiand @xpivarc
=> Add acardace to OWNERS of project-infra

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
The release team require write permissions for project-infra to create release job configs as part of the kubevirt release. 
/cc @acardace @xpivarc
=> Add write permissions for project-infra to release team

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.59.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.0.yaml
Resources had to be increased in the main branch presubmit[1][2] due to a change in memory overhead[3]
This change is being backported to 0.59 & 1.0 so the resources have to be increased there aswell
[1] https://github.com/kubevirt/project-infra/pull/3023
[2] https://github.com/kubevirt/project-infra/pull/3024
[3] https://github.com/kubevirt/kubevirt/pull/10566
/cc @xpivarc @fossedihelm @rthallisey
=> Increase resources for performance lanes in 0.59 and 1.0

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
In PR https://github.com/kubevirt/project-infra/pull/3023 we considered 35M for each virt-launcher pod.
Actually, since the performance tests uses
guaranteed pod, the guest log container
will request 60M.
Thus, we need to increase more:
100*(60M-35M) = 100 * 25M = 2.5G
Let's round to 3Gi more.
Also, increase the KUBEVIRT_MEMORY_SIZE up to 16G.
Serial console container request function:
https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-controller/services/serialconsolelog.go#L65-L92
/cc @brianmcarey @tiraboschi @xpivarc @EdDev
=> [performance] Increase performance job memory

OWNERS
Antonio was added to the project-infra OWNERS file[1] in order to get write permissions on project-infra which are required to carry out kubevirt releases. The release team was given write permissions[2] so Antonio no longer needs to be in the OWNERS file.
Discussed this with Antonio and he is happy to be removed.
[1] https://github.com/kubevirt/project-infra/pull/3026
[2] https://github.com/kubevirt/project-infra/pull/3028
/cc @acardace @xpivarc @dhiller
=> Remove acardace from OWNERS as not required

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.49.yaml
This causes the job to remain in a triggered state - never getting run. 
/cc @dhiller
=> Fix typo in cluster name in 0.49 sig-compute presubmit

github/ci/prow-deploy/files/jobs/kubevirt/bridge-marker/bridge-marker-presubmits-0.6.yaml, github/ci/prow-deploy/files/jobs/kubevirt/bridge-marker/bridge-marker-presubmits-0.9.1.yaml
These jobs were missed in the initial move - these jobs currently remain in triggered state so need to be updated to move the new cluster
/cc @0xFelix @dhiller
=> Update bridge-marker release presubmits to use new workloads cluster

github/ci/prow-deploy/kustom/overlays/kubevirt-prow-workloads/resources/shared-images-controller.yaml
This upgrades the shared-images-controller daemonset to `quay.io/kubevirtci/shared-images-controller:v20231027-376988b`
This image includes changes from https://github.com/kubevirt/project-infra/pull/3036
=> Upgrade shared-images daemonset to latest released image

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.49.yaml
This was missed as part of https://github.com/kubevirt/project-infra/pull/2731
The pod fails to schedule without this update[1]
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/10622/pull-kubevirt-e2e-kind-1.22-sriov-0.49/1719636138815131648
/cc @EdDev @ormergi @dhiller
=> Fix cni paths for 0.49 SRIOV presubmit lane

github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits-0.64.yaml
This is needed to bump some of its dependencies.
=> Bump kubernetes-nmstate release 0.64 to go 1.17

github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.79.yaml, github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.85.yaml
To improve podman init timeout.
Note:
Older branches still use docker, so didnt change them.
=> cnao, presubmit: Bump bootstrap for release 0.85, 0.79

github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.85.yaml
Due to known flakes, as on other branches.
=> presubmit, dynamic-networks: Make it optional

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml, github/ci/services/grafana/BUILD.bazel, github/ci/services/grafana/manifests/grafana.yaml, github/ci/services/grafana/manifests/ingress.yaml
Includes integration with the built in cluster-monitoring prometheus instance and a basic set of dashboards
=> Deploy grafana instance to control plane cluster

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
This PR adds the repository applications-aware-quota to the KubeVirt organization.
**Why this repository is needed**:
In a multi-tenant environment, a cluster administrator creates a namespace for each tenant and controls the amount of resources that they can use by creating a ResourceQuota object within the namespace.
During the migration process, there is a hidden cost involved in creating a new virt-launcher pod before terminating the old one. This differs from how standard pods are moved and can result in unexpected resource utilization from the user's perspective. This poses a challenge where the hidden cost of live migration can prevent live migrating a VM for reasons not reflected to the VM creator / namespace owne
When upgrading KubeVirt, it …
=> Create applications-aware-quota repo entry inside orgs.yaml

robots/cmd/kubevirtci-bumper/main.go, robots/pkg/kubevirtci/kubevirtci.go, robots/pkg/querier/queries.go
Adds two new flags for `-ensure-latest`:
* `--force-target-major-minor` to override the target version without relying on the release k8s version
* `--pre-release-version` to add a suffix for a prerelease version inside the `version` file
This way 
```sh
bazel run //robots/cmd/kubevirtci-bumper -- \
--ensure-latest=true \
--force-target-major-minor '1.29' \
--pre-release-version='alpha.3' \
--github-token-path='' \
--k8s-provider-dir=$PROJECTS/github.com/kubevirt.io/kubevirtci/cluster-provision/k8s \
--cluster-up-dir=$PROJECTS/github.com/kubevirt.io/kubevirtci/cluster-up/cluster
```
generates manually a new provider without relying on any fetched versions with this content:
```sh
cat cluster-provision/k8s/1.29/version
1.29.0-alpha.3
```
See https://github.com/kubevirt/kubevirtci/pull/1093 …
=> `kubevirtci-bumper`: force target prerelease version for new provider

robots/pkg/kubevirtci/kubevirtci.go, robots/pkg/querier/queries.go
Since we don't want to accidentally slip pre-release versions into our automation we create another function to use it only where needed for the manual generation of pre-release candidates.
=> Minimize usage for full SemVer regex usage

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
When the prow job image bump PR is created, reviews are requested from 15+ people. This can be annoying for these reviewers as it is not really relevant to them.
=> Stop adding large number of reviewers to bump prow images PR

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-periodics.yaml
Add a periodic job to update the vendored manifest bundles in kubevirt and ssp-operator to the latest released version of common-instancetypes.
=> common-instancetypes: Add periodics to update kubevirt and ssp-operator

images/prow-deploy/Dockerfile, images/prow-deploy/requirements.txt
kind and molecule are no longer required in the prow-deploy image as the presubmit has been moved to use kubevirtci[1] for the test cluster
Also includes bump to base images.
[1] https://github.com/kubevirt/project-infra/pull/3061
=> Remove kind and molecule from prow-deploy image

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Seems that the presubmit is not picking up changes to the orgs.yaml any more, maybe due to moving the file around.
=> Update run_if_changed for peribolos orgs.yaml presubmit

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-0.3.yaml, github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
Update the functest jobs to trigger on the correct changed files and provide the necessary resources for the tests to pass.
=> common-instancetypes: Update functest jobs

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
Update builder image used in common-instancetypes-presubmits to v20231124-0bd5b70.
=> common-instancetypes-presubmits: Update builder image

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
This should alert the members of this team that a bump prow images PR has been created by the periodic job.
/cc @dhiller
=> Add mention of prow-job-taskforce to bump prow images periodic

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
This allows to preview instancetypes and preferences in the artifacts of a presubmit job.
=> common-instancetypes: Store artifacts in presubmits

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
Bump the builder image used in the presubmits to v20231205-3b7ed7e.
Unblocks https://github.com/kubevirt/common-instancetypes/pull/132 and https://github.com/kubevirt/project-infra/pull/3109
=> common-instancetypes: Bump builder image

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.49.yaml
0.49 network lanes are failing here due to a DNS issue[1] - an update of the bootstrap image resolves this DNS issue. 
[1] https://github.com/kubevirt/kubevirt/pull/10622
=> Update bootstrap image of 0.49 sig-network lanes

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.53.yaml
Follow up for forgotten lanes in https://github.com/kubevirt/project-infra/pull/3108.
=> Switch 0.53 nonroot network lanes to podman bootstrap

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
Run the check-clean-tree Makefile target in the presubmits of common-instancetypes.
=> common-instancetypes: Check for clean tree in presubmits

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
We want to have PodSecurityAdmission enabled by default, therefore we add it to the lanes that are missing it.
I.e. this is the reason why the virtiofs unprivileged test cases are failing.
=> Enable PodSecurityAdmission for remaining lanes

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml, hack/mirror-crio.sh
cri-o have moved the location where they publish their rpms[1]. Update the mirror-crio.sh to reflect this change.
[1] https://kubernetes.io/blog/2023/10/10/cri-o-community-package-infrastructure/
/cc @dhiller
=> Update mirror-crio.sh to sync new cri-o repos

docs/infrastructure-components.md
The cluster contexts have been changed following cluster migrations - this should be updated in the doc
Also added the bot-review plugin to list of external plugins. 
=> Update infra components doc to capture recent changes

external-plugins/botreview/review/BUILD.bazel, external-plugins/botreview/review/bump_kubevirtci.go, external-plugins/botreview/review/bump_kubevirtci_test.go, external-plugins/botreview/review/image_update.go, external-plugins/botreview/review/image_update_test.go, external-plugins/botreview/review/prow_autobump.go, external-plugins/botreview/review/prow_autobump_test.go, external-plugins/botreview/review/result.go, external-plugins/botreview/review/review.go
There was lots of duplication wrt storing review result data, i.e. there was a struct specialized holding the result data per review strategy. This was unnecessary since all these were doing the same thing, like storing hunks that were special and storing whether the result would be mergable right away.
These structs all have been replaced by the `BasicReviewResult` struct that is used for every review strategy now.
Furthermore the `BasicReviewResult` itself and the result interface have been moved to their own file.
=> refactor, botreview: align result structs into one

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml, robots/cmd/flake-stats/main.go
Since our reports are currently polluted from the sig-storage-root lanes we add a filter regex to exclude them from the report.
=> report, flake-stats: filter root lanes from report

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
With the introduction of the 1.29 provider[1] - the presubmit should become required.
The 1.26 presubmit is no longer required as this provider will be removed shortly.
[1] https://github.com/kubevirt/kubevirtci/pull/1094
/cc @dhiller
=> Make the 1.29 kubevirtci presubmit required

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
This adds presubmit jobs that validate individual preferences by trying to boot a guest os with its preference.
Blocked by https://github.com/kubevirt/common-instancetypes/pull/135
=> common-instancetypes: Add presubmits to validate individual preferences

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Still keeps the enablement for `check-tests-for-flakes` lane.
=> Revert enable psa for root

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
Add a presubmit that tests the windows.11 preference with Validation OS.
Also, remove the unneeded gcs-credentials presets from all jobs.
=> common-instancetypes: Add Validation OS presubmit

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-0.4.yaml, github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml, github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
- Update the focus regexes in the presubmits to match the new test names with added test ids.
- Add common-instancetypes presubmits for the release-0.4 branch.
- Enable branch-protection for all branches.
=> Update common-instancetypes presubmits and add presubmits for release-0.4

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-periodics.yaml
Use bump-common-instancetypes.sh in the periodics that update kubevirt/kubevirt to the latest common-instancetypes version.
Also, add the 'periodic-' prefix to the job name and run the job on the
smaller control plane cluster instead.
=> common-instancetypes: Use bump-common-instancetypes.sh

github/ci/prow-deploy/files/jobs/kubevirt/managed-tenant-quota/managed-tenant-quota-presubmits-1.2.yaml
- Add presubmits for mtq 1.2
- Update kubevirt version formtq 1.1 presubmits
Just a note this operator is likely to be deleted soon due to the development of
aaq-operator but we need to support mtq until aaq is fully supported.
=> Add presubmits for mtq 1.2

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
If the PR has been reviewed with lgtm and approve applied - it should be safe to retest the PR.
=> Remove filtering of needs-ok-to-test from retester query

images/bootstrap/Dockerfile
`sysctl` is used as part of the runner.sh script[1] - this is no longer available in the bootstrap image[2] so the install of `procps-ng`, which provides sysctl, needs to be included.
```
procps-ng-4.0.3-4.fc39.x86_64 : System and process monitoring utilities
Repo        : fedora
Matched from:
Provide    : /sbin/sysctl
Filename    : /usr/sbin/sysctl
```
[1] https://github.com/kubevirt/project-infra/blob/39b00ed5d81df148e5c05e3855d17d61d510d472/images/bootstrap/runner.sh#L66
[2] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/batch/pull-kubevirt-build/1742892493294276608#1:build-log.txt%3A11
=> Add sysctl to bootstrap image as needed by runner script

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
In order to reduce the load on the CI clusters, the unsupported test lanes should be disabled in the same PR that enables the new lanes for the latest kubernetes version.
Example of the resulting PR: https://github.com/kubevirt/project-infra/pull/3147
=> Add step to disable unsupported lanes when enabling new lanes

github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.91.yaml
This PR adds a new presubmit job for stable branch [release-0.91](https://github.com/kubevirt/cluster-network-addons-operator/tree/release-0.91)
=> cnao, release 0.91: Add presubmits

github/ci/prow-deploy/tasks/deploy.yml
The ibm-prow-jobs cluster context no longer exists and causes the postsubmit prow deployment to fail[1].
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/post-project-infra-kubevirt-prow-control-plane-deployment/1745118472339197952#1:build-log.txt%3A208
/cc @dhiller
=> prow-deploy: fix context name in reconcile webhook task

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml, github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Currently only maintainers (i.e. the folks inside kubevirtorg-label) can apply good-first-issue to project-infra issues.
Symptom: https://github.com/kubevirt/project-infra/issues/3031#issuecomment-1867689102
Adds a group that can apply good-first-issue to project-infra issues.
=> project-infra, labels: add group to allow applying labels

external-plugins/botreview/review/BUILD.bazel, external-plugins/botreview/review/kubevirt_uploader.go, external-plugins/botreview/review/kubevirt_uploader_test.go, external-plugins/botreview/review/result.go, external-plugins/botreview/review/review.go, external-plugins/botreview/review/review_test.go, external-plugins/botreview/review/testdata/kubevirt/uploader/uploader-autoupdate.patch00
This PR adds the strategy to review GCS upload PRs for kubevirt/kubevirt.
=> botreview, strategy: add kubevirt uploader

docs/infrastructure-components.md, external-plugins/phased/Makefile, external-plugins/phased/plugin/BUILD.bazel, external-plugins/phased/plugin/handler/BUILD.bazel, external-plugins/phased/plugin/handler/handler.go, external-plugins/phased/plugin/main.go, external-plugins/phased/plugin/phased_suite_test.go, external-plugins/phased/plugin/phased_test.go, external-plugins/phased/plugin/server/BUILD.bazel, external-plugins/phased/plugin/server/eventsserver.go, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml, github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml, github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml, github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml, github/ci/prow-deploy/kustom/base/kustomization.yaml, github/ci/prow-deploy/kustom/base/manifests/local/prow-phased-deployment.yaml, github/ci/prow-deploy/kustom/base/manifests/local/prow-phased-service.yaml, images/phased
Phased plugin allows running jobs that will be considered as "phase 2"
only once both lgtm / approve are presented.
We are running 3 k8s versions for each sig on kubevirt, for each PR.
With this plugin we can declare the non latest one as "phase 2"
and run it only when the PR is entering the merge queue,
This will save CI resources.
A job will be declared as "phase 2",  if it has `always_run=false`, `optional=false`,
without additional conditions such as `run_if_changed`, `skip_if_only_changed`.
Since the jobs are `always_run=false` it means that a potential race condition might happen
between running the job and merging.
For this we use `require_manually_triggered_jobs` which will block the PR entering 
the merge queue / being merge by tide before all "phase 2" jobs finish.
It will also …
=> plugins: Introduce phased plugin

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Kubernetes 1.26 is no longer a supported version for main branch kubevirt - update these lanes to test against 1.29
/cc @ormergi @EdDev @dhiller
=> Update multus v4 lanes to test against kubernetes 1.29

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Following the introduction of the phased plugin, required jobs that are manually triggered are allowed[1] - this leaves 1.26 jobs as required but not triggered on kubevirt PRs which is preventing merge queue PRs from being merged.
Updating these lanes to be explicitly optional so that they no longer appeared as required.
[1] https://github.com/kubevirt/project-infra/blob/0c8c659783c24fe4b5b939455169fb6535bf052a/github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml#L274
/cc @dhiller @oshoval
=> kubevirt,presubmits: make 1.26 lanes optional

github/ci/prow-deploy/kustom/base/manifests/test_infra/current/statusreconciler_rbac.yaml, github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/resources/admin-rbac.yaml
Role and RoleBinding for statusreconciler are only present in kubevirt-prow, but prowjob objects are created in kubevirt-prow-jobs ns.
We therefore add the missing things for test-pods ns, which is then changed to kubevirt-prow-jobs during deployment kustomization.
Aside from that we remove an admin account from the setup, since that account is inactive for quite a while now.
=> prow-deploy, fix: Role and RoleBinding for statusreconciler

github/ci/prow-deploy/kustom/base/manifests/local/prow-phased-deployment.yaml
Seems the kubevirt-bot isnt allowed to trigger /test commands.
Lets use the commenter bot that does it usually.
Also updated the image, based on the new bootstrap to fix the [glibc](https://github.com/kubevirt/project-infra/pull/3175) error.
Thanks @brianmcarey
=> phased plugin: Use commenter bot token

external-plugins/phased/plugin/handler/handler.go, external-plugins/phased/plugin/phased_test.go
In order to make the bot more self explanatory,
add a comment describing why it trigger jobs.
=> phased plugin: Add intro to bot comments

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Seems tide has a bug, it doesnt run the phase 2 for batches. 
A simple wa until it is fixed is to use `run_before_merge`, which force a batch to run it.
Real fix is to consider manually triggered jobs as well on this line at `presubmitsForBatch`
`shouldRun, err := ps.ShouldRun(baseBranch, c.changedFiles.batchChanges(prs), ps.RunBeforeMerge, false)`
The required logic exists on https://github.com/kubernetes/test-infra/pull/30191
=> phased: Enable run_before_merge for phase 2 jobs

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml, releng/feature-announce/BUILD.bazel, releng/feature-announce/feature-announce.go, releng/feature-announce/feature-announce_test.go, releng/feature-announce/upcoming-changes.gomd
This PR adds two things:
1) a tool in `releng` folder that will fetch all merge commits since the last release tag, then it will fetch the release notes from the PRs and generate a markdown document.
2) a periodic job that executes the above tool and creates a PR to add the document to sig-release repo
Preview of the document generated here: https://github.com/kubevirt/sig-release/pull/18/files?short_path=bdbf887#diff-bdbf887f46278abcf7309f79a391ef07e23d20ee143b5a01389004dfead19a27
/cc @aburdenthehand @xpivarc @fabiand
=> sig-release: create upcoming-changes.md periodically

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
There is ongoing work to enable KubeVirt for s390x[1] - having a presubmit to verify the s390x crossbuild will help to prevent build failures.
[1] https://github.com/kubevirt/kubevirt/pull/10490
=> kubevirt,s390x: Add optional presubmit to test s390x crossbuild of kubevirt

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The lanes have been running for the last week without issue - update them to be required.
/cc @dhiller
=> kubevirt,presubmits: Make 1.29 lanes required

github/ci/services/grafana/manifests/grafana.yaml
Adds a simple prow control-plane metrics dashboard, using metrics provided as described here: https://docs.prow.k8s.io/docs/metrics/
https://grafana.ci.kubevirt.io/d/d5v42J5Ik/prow-control-plane-metrics?orgId=1&from=now-24h&to=now
=> Add prow control-plane metrics dashboard

github/ci/prow-deploy/kustom/base/manifests/local/prow-phased-deployment.yaml
In order to include the [intro](https://github.com/kubevirt/project-infra/pull/3179) string.
The post submit publishes a new image but doesnt auto update the deployment.
=> phased plugin: Update image

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
When there is a large number of jobs kicked off at once, we can see that the control-plane cluster gets overwhelmed and jobs fail early to start the podman socket[1].
Doubling the memory request will reduce the number of running jobs by half and should help with this problem.
These jobs are generally very short so this should not really impact feedback time.
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11041/pull-kubevirt-verify-go-mod/1748262393516920832
=> kubevirt,presubmits: increase memory requests for prow-control-plane jobs

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Converting 1.27 / 1.28 to phase 2.
sriov lane as well.
`pull-kubevirt-e2e-k8s-1.28-sig-compute-migrations` was bumped to 1.29,
so now we have 1.29 phase 1, and older k8s versions + sriov phase 2.
Note: since tide has a bug with `require_manually_triggered_jobs`,
`run_before_merge` should be set meanwhile on phase 2 jobs,
it act exactly as required, causing tide to include phase 2 jobs as part of the gating,
and include them in the batches etc.
=> kubevirt, presubmit: Make k8s-1.27/1.28 lanes phase2

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
For some reason the lanes got mixed (seems a rebase after some changes caused it).
Fix that 1.29 are phase 1 and
1.27/1.28 are phase 2.
Fixes #
**Checklist**
```release-note
None
```
=> presubmits: Fix phases

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
During code review the flag name for log-level <sup>[1]</sup> was changed to better reflect what it's doing, but it was forgotten to update the job definition, causing the periodic to fail <sup>[2]</sup>
This PR fixes the flag name in the job definition.
/cc @brianmcarey @aburdenthehand 
[1]: https://github.com/kubevirt/project-infra/blame/9c575a8f1e736d80c3e1f539d84688d2dbefa5d5/releng/feature-announce/feature-announce.go#L76
[2]: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-update-upcoming-changes/1749609378622738432#1:build-log.txt%3A54
=> Fix flag for feature-announce call

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Since `GIMME_GO_VERSION` doesn't accept a `major.minor` any more<sup>[1]</sup>, we now set the go version explicitly.
Also we add the missing gcs credentials preset to access the gcs buckets of the prow jobs.
Fixes #
**Checklist**
```release-note
NONE
```
[1]: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-push-test-metrics/1749966741523402752#1:build-log.txt%3A4
=> Fix kubevirt push-test-metrics job

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
Since @omeryahud has left the project a while ago, we are removing him from the team.
Fixes #
/cc @dominikholler @brianmcarey 
**Checklist**
```release-note
```
=> Remove omeryahud from ssp team

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/OWNERS, github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/OWNERS, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-tekton-tasks/OWNERS, github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
Removed `codingben` from the `kubevirt` organization.
**Checklist**
```release-note
None
```
=> Remove 'codingben' from the kubevirt organization

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The sig-monitoring lane was bumped to kubernetes 1.29[1] however there are
tests that always fail against this version[2].
Setting the lane to be optional and to be triggered manually
[1] https://github.com/kubevirt/project-infra/pull/3212
[2] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11052/pull-kubevirt-e2e-k8s-1.29-sig-monitoring/1750798923670228992
Fixes #
**Checklist** …
=> kubevirt,presubmits: set monitoring lane to trigger manually

github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
Since the rhcos and rhcosprerelease containerdisks are going to be dropped, the rhcos test lane is no longer needed.
See https://github.com/kubevirt/containerdisks/pull/78
Fixes #
**Checklist**
```release-note
None
```
=> containerdisks: Drop rhcos test lane

github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
Now that the problems were solved we can make it required.
Fixes #
**Checklist**
```release-note
None
```
=> cnao, presubmits: Convert multus-dynamic-networks to required

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Converted windows and vgpu to phase 2.
Fixes #
**Checklist**
```release-note
None
```
=> kubevirt, presubmits: Convert more jobs to phase 2

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Kubernetes have released an alpha version for v1.30 - this optional presubmit would allow us to get early feedback on if there are any issues.
https://github.com/kubevirt/kubevirtci/pull/1127
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> kubevirtci,presubmit: Add test lane for upcoming k8s-1.30 provider

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
This lane is running against an unsupported kubernetes version for the kubevirt main branch.
There is no kubevirtci cluster provider available to even run this lane against.
It is causing some of our automation to fail[1] as old unsupported versions are not expected.
Removing this presubmit - a FIPS job can be added again using a more recent kubernetes version if its needed.
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirtci-cluster-unsupported-version-remover/1753079938228948992#1:build-log.txt%3A67
Fixes #
/cc @dhiller …
=> kubevirt,presubmit: remove 1.25 FIPS test lane

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Uses new `kind-sriov` provider on kubevirtci.
Fixes #
Depends on https://github.com/kubevirt/kubevirtci/pull/1122
**Checklist**
```release-note
None
```
=> kubevirtci, sriov: Use new generic name on kubevirtci

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Uses new `kind-sriov` provider on kubevirt.
Fixes #
Once https://github.com/kubevirt/kubevirtci/pull/1122 is bumped on kubevirt
and then we can remove the old provider / jobs.
**Checklist**
```release-note
None
```
=> kubevirt, sriov: Use new generic name

github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/patches/JsonRFC6902/deck_deployment.yaml
For PRs that have a lot of history the pr-history page has a risk of timing out with a 504 error.
I.e. https://prow.ci.kubevirt.io/pr-history/?org=kubevirt&repo=kubevirt&pr=11054
Increase the CPU limit to raise the chance of the call being successful.
Note: kubernetes/test-infra issue created here
https://github.com/kubernetes/test-infra/issues/31850
Fixes #
/cc @brianmcarey @jean-edouard 
**Checklist**
**Release …
=> Increase resources for deck deployment to lower 504 risk

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The external linter on the kubevirt/kubevirt project has been stable for at least a year now.
The linter protects the areas of code it covers well and it has proven useful to keep the codebase clean and reduce potential bugs.
Lately the nogo embedded linters have partially been disabled due to some incompatibility when the Go version and bazel have been upgraded. Therefore, the external linter is also a good backup to keep around.
As of now, the golangci-lint meta linter is running 31 linters.
Fixes #
**Checklist**
This checklist is not enforcing, but it's a …
=> kubevirt-presubmits: Make the lint target job required

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
The presubmit compute-migrations lane has already been updated to use
1.29[1] and the periodic was missed.
[1] https://github.com/kubevirt/project-infra/commit/9a785bdbd08ae62513efa2a04f4259fdbe70586a
Fixes #
/cc @dhiller
**Checklist**
```release-note
```
=> kubevirt,periodics: update compute-migrations lane to use 1.29 provider

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The arm conformance lane has been very stable[1] in the last couple of weeks. We can start reporting the result of this lane on PRs.
[1] https://testgrid.kubernetes.io/kubevirt-presubmits#pull-kubevirt-conformance-arm64
/cc @zhlhahaha @dhiller
=> arm64,conformance: enable reporting of the arm conformance presubmit

github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Makes prow trigger plugin ignore `ok-to-test` label on PRs of non-org-member contributions, so it will not trigger retesting of latest changes automatically for those PRs.
Fixes #
/cc @0xFelix @fabiand @EdDev @brianmcarey @xpivarc 
**Checklist**
```release-note
```
=> kubevirt, prow: ignore ok-to-test

docs/how-to-add-a-prow-cluster.md
The current example of periodic prow job for kubeVirtCI external provider is pointing to a wrong job and also the link is not a permanent link so as we add more jobs the link is likely to change, and it is error prone. In this PR I have corrected the link and added a permanent link for the example job.
Fixes #
**Checklist**
```release-note
none
```
=> Fix and add the permalink for kubeVirtCI external provider periodic prow job example.

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
Old configuration was [failing on the podman login](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/publish-rehearse-image/1757092049229713408#1:build-log.txt%3A12), also it used the legacy bootstrap.
Update job with latest bootstrap and podman in container enabled. [Successful job run](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/publish-rehearse-image/1757092049229713408)
Fixes #
/cc @xpivarc @enp0s3 
**Checklist**
Approvers are expected to …
=> rehearse, image: fix publish

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The arm64 e2e lane is failing constantlyi[1]. Update the job to stop reporting on PRs to reduce noise for contributors until the issue is resolved.
[1] https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-arm64
Fixes #
/cc @dhiller @xpivarc @zhlhahaha 
**Checklist**
```release-note
```
=> arm64,presubmit: Stop reporting the failing arm64 e2e lane

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
These jobs are CPU intensive and may be better suited running on the larger workloads cluster
Fixes #
/cc none
**Checklist**
```release-note
```
=> kubevirt,presubmit: Move build and cross build presubmits to workloads cluster

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
The k8s-1.30 cluster provider was merged recently[1] - lets always run the presubmit for this provider so that we can see if any PRs break this provider
[1] https://github.com/kubevirt/kubevirtci/pull/1127
Fixes #
**Checklist**
```release-note
```
=> kubevirtci,presubmit: update check-provision to always run for new provider

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
This presubmit is no longer needed as the provider it was testing has been removed.
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> kubevirtci,presubmit: remove k8s-1.26 check-provision

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.1.yaml
Cache failures on older releases can make it difficult to merge PRs - remove the bazel cache preset from release v1.1 presubmits.
Fixes #
**Checklist**
```release-note
```
=> kubevirt,presubmit: Remove bazel cache preset from release v1.1 presubmits

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.0.yaml
Older release branches can cause cache failures which makes it difficult to merge backport PRs.
This was missed as part of https://github.com/kubevirt/project-infra/pull/3260
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> kubevirt,presubmits: Remove bazel cache preset from 1.0 kubevirt presubmits

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.0.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.1.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.2.yaml
The corresponding jobs for the main branch have been moved to the workloads cluster[1] and this has improved the stability of the jobs.
Move the build jobs from recent releases to the larger workloads cluster
[1] https://github.com/kubevirt/project-infra/pull/3249
Fixes #
**Special notes for your reviewer**:#
/cc @dhiller 
**Checklist**
```release-note
```
=> kubevirt,presubmits: Move build jobs to larger workloads cluster

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml, github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Enable `from-branch-protection`.
Removes `run_before_merge` workaround.
Now that Tide bug was solved, Tide should detect manually required jobs
as required with those fixes, as if they had `run_before_merge`.
To be merged only when we update tide to a version that includes
https://github.com/kubernetes/test-infra/pull/31687 (done)
Fixes #
**Checklist**
```release-note
None
```
=> phased plugin: Enable from-branch-protection for kubevirt/kubevirt main

github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Update the PR state also whenever a comment is placed on a PR, this should avoid cases where PRs are getting stale, but not updated:
https://github.com/kubevirt/kubevirt/pull/11238
https://github.com/kubevirt/kubevirt/pull/11099
Fixes #
**Checklist**
```release-note
```
=> prow, plugin, needs-rebase: enable for issue_comment

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml, github/ci/services/grafana/manifests/grafana.yaml, github/ci/services/grafana/secrets/testing/grafana/client-id, github/ci/services/grafana/secrets/testing/grafana/client-secret
This should enable members of the kubevirt github org to access the KubeVirt Grafana instance as Viewers only.
https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/github/#steps
Fixes #
**Checklist**
```release-note
```
=> grafana: enable github oauth authentication

github/ci/services/grafana/manifests/grafana.yaml
This is required in order for the github oauth to work correctly as the instance is running behind an ingress controller
Fixes #
/cc @dhiller
**Checklist**
```release-note
```
=> grafana: add root_url to the grafana configuration

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml, github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Reverts #3221 
This reverts commit a6702ffa26dfe8f2d15ce122bd3707cf82ffb6bf.
Tide doesn't act as a backstop when event is missed
(for example when labels were added when PR is drafted).
Until we fix it lets keep CI healthy.
The reason is that we enabled `FromBranchProtection`, so Tide won't include the PR as part of 
the merge queue until all required lanes are passed.
With this flag phase 2 are considered required.
Draft just shows a private case where we didn't trigger phase 2,
it can happen also due to missing events, rarely but happens.
In order to fully use `FromBranchProtection` we will need either to implement our
own controller so no missing events occur or to ask developers to run manually in case
an event is lost. 
**Which issue(s) this PR …
=> Revert "phased plugin: Enable from-branch-protection…"

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml, github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
This should allow us to use github cli to check PR diff in kubevirt e2e
presubmit jobs.
Fixes #
/cc @dhiller @oshoval 
**Checklist**
```release-note
```
=> kubevirt,presubmit: Add unprivileged token preset to e2e lanes

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
prnaraya has left the project, thus we remove her from the org.
Fixes #
**Checklist**
```release-note
```
=> kubevirt org chore: remove prnaraya from org

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml, github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml, images/bootstrap/Dockerfile
gh is no longer required because we can get PR diff using `git diff
PULL_BASE_SHA...PULL_PULL_SHA`
Fixes #
/cc @dhiller @oshoval 
**Checklist**
```release-note
```
=> bootstrap,kubevirt: Revert changes introducing github cli to bootstrap image

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Enable reporting of arm64 e2e presubmit once lane is passing again. 
Requires https://github.com/kubevirt/kubevirt/pull/11366 to be merged
Fixes #
/cc @dhiller @zhlhahaha 
**Checklist**
```release-note
```
=> kubevirt,arm64,e2e: enable reporting of arm64 e2e presubmit

github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
With https://groups.google.com/g/kubevirt-dev/c/-5TLpOcRkco it was proposed to create sigs to better distribute ownership.
We need to add the new labels for the sigs to the prow label configuration, otherwise we can not apply them to pull requests, i.e. as possible in OWNERS files.
Fixes #
/cc @EdDev @fabiand 
**Checklist**
```release-note
```
=> prow, labels, github: add new labels for sigs used in OWNERS

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml, github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
This new periodic job will publish a new centos stream base image for kubevirtci every week and create a PR to update the tag in the kubevirtci repo.
This relies on https://github.com/kubevirt/kubevirtci/pull/1140 being merged into the kubevirtci repo
Also update the existing check-provision jobs to run just the kubernetes phase of provisioning.
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> kubevirtci,periodic: prowjob to publish new CentOS stream base

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> kubevirtci,presubmit: Make k8-1.30 check-provision required

images/bootstrap/runner.sh
There are cases where we don't require to run the podman in container setup but we still want to use podman and the docker-mirror-proxy for caching images. Move the setup of the image cache proxy out of podman in container setup so that it is setup for every job.
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> bootstrap: Set image proxy at the start of jobs

images/bootstrap/Dockerfile, images/publish_multiarch_image.sh
There is an effort to enable support for s390x for KubeVirt[1].
This adds an s390x bootstrap image to our multiarch publish flow.
This bootstrap image does not include bazel as it will have to rely on
the s390x builder image[2] for bazel.
This image will allow us to run native s390x builds and unit tests on a
s390x cluster[3].
[1] https://github.com/kubevirt/kubevirt/pull/10490
[2] https://github.com/kubevirt/kubevirt/pull/11097
[3] https://github.com/kubevirt/project-infra/issues/3140
=> bootstrap,s390x: Add s390x support to multiarch bootstrap build

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
Add myself to kubevirtkubevirt-label to allow adding `good-first-issue` labels in kubevirt/kubevirt.
Fixes #
**Checklist**
```release-note
None
```
=> Add 0xFelix to kubevirtkubevirt-label

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
Previously kubevirtci providers that were published with podman used to break `make cluster-up` for docker users. This was due to an empty `/run/.containerenv` being added to the image when published with podman. This broke some IF statements that setup the iptables rules to communicate with the VM.
This should be fixed when
https://github.com/kubevirt/kubevirtci/pull/1149 is merged.
Fixes #
/cc @dhiller 
**Checklist** …
=> kubevirtci,publish: Publish kubevirtci using podman

images/bootstrap/runner.sh
The google cloud utilities now require an extra step to be added to the `$PATH` before they can be executed[1].
Without this, lanes will fail due to not being able to find some of the gcloud utilities[2].
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/publish-bootstrap-image/1765415256181444608#1:build-log.txt%3A2856
[2] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11297/pull-kubevirt-e2e-windows2016/1765751732119277568#1:build-log.txt%3A222
Fixes #
**Checklist**
This checklist is not …
=> bootstrap: Add gcloud utilities to PATH during container start

github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml, github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
We add the labels that are required for the prow help plugin to work.
Also we enable them for the kubevirtci and the project-infra repos
and add the initial configuration.
This is related to the help-wanted doc added with [this PR](https://github.com/kubevirt/community/pull/269)
Fixes #
/cc @xpivarc @brianmcarey 
**Checklist**
```release-note
```
=> prow, plugin, help: add required labels, enable for kubevirtci and project-infra

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
label-sync job is failing with:
```
$ k logs label-sync-kubevirt-28497557-xqksl -n kubevirt-prow
{"component":"label_sync","error":"invalid config: description for sig/buildsystem is too long","file":"k8s.io/test-infra/label_sync/main.go:757","func":"main.main","level":"fatal","msg":"failed to load --config=/etc/config/labels.yaml","severity":"fatal","time":"2024-03-07T23:17:48Z"}
```
Check was not triggered for linked files, therefore we update `run_if_changed` and config path in jobs to new locations.
Fixes #
/cc @xpivarc @brianmcarey 
**Checklist**
This …
=> prow, labels: fix label precheck

github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
Fixes the label definitions. Label sync jobs are failing as described here: https://github.com/kubevirt/project-infra/pull/3307 , also the prechecks for the labels were not working.
Fixes #
**Checklist**
```release-note
```
=> github, labels: fix description, remove duplicates

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml, hack/remove-users-without-contributions.sh
Removes inactive users from the org.
[Announcement to kubevirt-dev](https://groups.google.com/g/kubevirt-dev/c/TFyLNxFQG-s/m/VMdgplqJAAAJ)
Also adds a script that can be used to automate the process of removing
users from the org that have no contributions according to the input
file.
List of removed users:
```
AdamJ
adityaramteke
alonsadan
alosadagrande
andreyod
ArthurSens
ashleyschuett
bardielle
beanh66
beekhof
booxter
borod108
brybacki
crobinso
cynepco3hahue
danielBelenky
danielerez
dcritch
djzager
doron-fediuck
dshchedr
dteplits
duyanyan
eedri
e-minguez
erkanerol
ezrasilvera
fabiendupont
fedepaol
fgimenez
gabrielecerami
gbenhaim
gonzolino
gsr-shanks
guy9050
hritvi
hroyrh
humblenginr
ibesso-rh
idanshaby
ifireball
igoihman
ILpinto
InbarRose
iranzo …
```
=> governance, kubevirt, org: remove inactive users

github/ci/prow-deploy/kustom/base/manifests/local/referee-deployment.yaml
Disable until the bot is fixed.
Fixes #
**Checklist**
```release-note
```
=> prow, external-plugin: disable referee

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The perf jobs rely heavily on the monitoring pkg so trigger the performance presubmit job when there are changes in that pkg.
```release-note
NONE
```
=> Trigger the performance presubmit on monitoring changes

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Kubernetes v1.27 is no longer relevant for the main branch as 1.27 support will be dropped in the next release (v1.3)
Update the performance lanes to Kubernetes v1.29
Fixes #
/cc @dhiller @alaypatel07 @rthallisey 
**Checklist**
```release-note
```
=> kubevirt,perf: Update performance lanes to kubernetes 1.29

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml, robots/cmd/perf-report-creator/graph.sh, robots/cmd/perf-report-creator/scrape.sh
update sig-scale automation for 1.29 provider change
Fixes #
Added a note for future updates to cover sig-scale automation as well
**Checklist**
```release-note
update sig-scale automation for 1.29 provider change
```
cc @brianmcarey @dhiller @rthallisey
=> update sig-scale automation with 1.29 provider

external-plugins/botreview/Makefile, github/ci/prow-deploy/kustom/base/manifests/local/botreview-deployment.yaml
Use image sha when pushing new image version and for deployment.
Fixes #
**Checklist**
```release-note
```
=> prow, plugin, botreview: use image sha

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
Iam planning to add s390x support for the kubevirt builder. This will make us to enable CI/CD for the  kubevirt on s390x. My area of focus is to enable and maintain the CI/CD pipeline for kubevirt on s390x and make sure any new changes do not break the s390x support on kubevirt. In order to achieve this, I want myself to be added to the kubevirt community. 
@vamsikrishna-siddu 
**Requirements:**
**Sponsors**
- @dhiller 
- @brianmcarey 
**List of contributions to the KubeVirt project**
- **PRs reviewed and/or authored.**
- https://github.com/kubevirt/kubevirt/pull/11097
**Note To Reviewer:**
- Member list was ordered alphabetically.
=> Add Vamsikrishnasiddu to kubevirt members.

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.2.yaml
Cache evictions are causing the v1.2 presubmits to fail[1] - remove the bazel cache for the v1.2 lanes.
[1] https://github.com/kubevirt/kubevirt/pull/11582
Fixes #
/cc @xpivarc 
**Checklist**
```release-note
```
=> kubevirt,v1.2: Remove bazel cache from kubevirt v1.2 presubmits

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
This repository will eventually help avoid importing the whole application-aware-quota project by only exporting the API of Application Aware Quota.
Fixes #
**Checklist**
```release-note
NONE
```
=> Request an API repository for Application Aware Quota

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
The sysprep lane just uses the default kubevirtci provider in the kubevirt repo. This can lead to a versioned job name becoming out of date and confusing people. Remove the version to avoid this from happening.
Fixes #
**Checklist**
```release-note
```
=> kubevirt,periodic: remove kubernetes version from sysprep lane name

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
@jschintag
* @brianmcarey 
* @dhiller 
- https://github.com/kubevirt/kubevirt/pull/10490
- https://github.com/kubevirt/kubevirt/pull/10836
- https://github.com/kubevirt/kubevirt/pull/11047
- https://github.com/kubevirt/kubevirt/pull/11493
- https://github.com/kubevirt/kubevirt/pull/11602
- https://github.com/kubevirt/kubevirt/pull/11097
- https://github.com/kubevirt/kubevirt/issues/8765
-
-
I am currently working on enabling kubevirt to run on the s390x architecture. For that reason i would like to join the kubevirt org to be able to better maintain the s390x support, as well as general multi-arch support.
> [!IMPORTANT]
> After this pull request has been merged, an invitation to the …
=> Add jschintag to kubevirt members

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Otherwise in cluster-up fails, it will continue with failed
cluster-sync and eventually fails on tests with panic.
This cause noise and waste resources.
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11410/pull-kubevirt-e2e-k8s-1.29-sig-performance/1777644706390347776
Fixes #
**Checklist**
```release-note
```
=> sig-performance: Fail on error

github/ci/prow-deploy/files/jobs/kubevirt/kubectl-virt-plugin/kubectl-virt-plugin-presubmits.yaml
Remove shellcheck presubmit, as it has never worked reliably [^1].
Fixes #
[^1]: https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/pull-kubectl-virt-plugin-shellcheck
=> kubectl-virt, presubmit: remove shellcheck since it's unreliable

github/ci/prow-deploy/tasks/tests.yml
The prow-deploy presubmit lane can fail sometimes due to pods not being
created by the time the check to see if they are ready is run[1].
Adding a 60 second wait to allow for the pods to be created stops
this from flaking
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/3331/pull-project-infra-prow-deploy-test/1774455964104134656
Fixes #
**Checklist** …
=> prow-deploy,presubmit: Wait for prow pods to be created before checking if ready

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Add an optional lane to check that provisioning the centos base image completes successfully
Fixes #
**Checklist**
```release-note
```
=> kubevirtci,presubmit: Add presubmit to check centos base provisioning

external-plugins/rehearse/plugin/BUILD.bazel, external-plugins/rehearse/plugin/handler/BUILD.bazel, external-plugins/rehearse/plugin/handler/handler.go, external-plugins/rehearse/plugin/handler/handler_test.go, external-plugins/rehearse/plugin/main.go, external-plugins/rehearse/plugin/rehearse_test.go, external-plugins/testutils/fakegithub.go
Restricts access to job rehearsal creation to project-infra top level approvers and job approvers. In case the user that triggers the rehearsal is an org member, adds a comment telling the user who can help him.
Fixes #
**Checklist**
```release-note
```
=> prow, plugin, rehearse: restrict access to rehearsal to project-infra top level approvers and job approvers

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml, github/ci/prow-deploy/prow-autobump-config.yaml, github/ci/prow-deploy/prow-job-autobump-config.yaml, hack/bump-prow.sh
Since prow moved to it's own repository (see https://github.com/kubernetes/test-infra/issues/31728), our update automation updated images for commenter with non-existing image tags, and we had to revert bump PRs. See https://github.com/kubernetes-sigs/prow/issues/121#issue-2252926381 for details. This was caused since the images for commenter etc. were created in another job (see [comment](https://github.com/kubernetes-sigs/prow/issues/121#issuecomment-2067220948)). Therefore we need to adapt our update mechanism, so it's a good time to switch to using the [`gcr.io/k8s-prow/generic-autobumper`](https://github.com/kubernetes-sigs/prow/tree/main/cmd/generic-autobumper).
`generic-autobumper` needs configuration files per update. We create two, one for …
=> prow, autobump: add config files, modify bump script

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-postsubmits.yaml, github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
**What this PR does / why we need it**: Enables Coveralls report for the copntainerised-data-importer repo, wich has not made any upload since early 2021. https://coveralls.io/github/kubevirt/containerized-data-importer
Fixes CNV-22942
The idea is to merge this optional job now and test it in some PR of mine, and iterate until we're confident it works. Then I'll set alwaysRun=true and optional=false, although the latter may require some tweaking to avoid being too overbearing.
**Checklist**
Approvers …
=> Enable goveralls in containerized-data-importer

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
This provider will be removed once the k8s-1.30 provider is running in kubevirt/kubevirt - remove the check provision job.
Fixes #
**Checklist**
```release-note
```
=> kubevirtci,presubmit: Remove check provision job for k8s-1.27 provider

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml, github/ci/prow-deploy/tasks/secrets.yml, github/ci/prow-deploy/vars/kubevirtci-testing/secrets.yml
Recently, PR #3350 enabled goveralls in kubevirt/containerized-data-importer.
I tested it in this PR https://github.com/kubevirt/containerized-data-importer/pull/3197 and the report went to the `kubevirt/kubevirt` project ([see report](https://coveralls.io/jobs/141056711)) instead of `kubevirt/containerized-data-importer`.
I tracked down the issue and the problem is that each repository has its own unique coveralls token. This PR adds this token to the secrets and makes the CDI job use it.
You can check out a repository's coveralls token by going to coveralls, logging in with your GitHub account, and going to the URL https://coveralls.io/github/kubevirt/containerized-data-importer (replace the URL accordingly). …
=> Fix: CDI goveralls job must use its repository's token

github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/kustomization.yaml
PRs #3350 and #3369 have laid the ground work to enable Coveralls reports for the Containerized Data Importer repository. This has been a bit of a trial and error, and the error now is that the secret coveralls token is not available to the cluster running the job:
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/3197/pull-cdi-goveralls/1783542761547370496
This PR fixes this.
**Checklist**
```release-note
NONE
```
=> Fix: CDI control plane has no access to Goveralls token

docs/labels.md, github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
Updates the description of the labels `help wanted` and `good first issue`.
Fixes #
**Checklist**
```release-note
```
=> prow, labels: update help wanted and good first issue

github/ci/prow-deploy/kustom/base/manifests/local/referee-deployment.yaml
This PR enables the referee plugin, which is responsible for halting PRs that are being retested beyond the boundaries.
Latest examples:
* https://github.com/kubevirt/kubevirt/pull/11710
* https://github.com/kubevirt/kubevirt/pull/11659
Fixes #
**Checklist**
```release-note
```
=> prow, referee: enable plugin for halting prs

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.59.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.0.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.1.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.2.yaml
These vgpu e2e lanes are failing due to missing a kernel module vfio_mdev[1] after the workloads cluster upgrade.
The mdev kernel module is already loaded on the nodes as the nvidia operator is installed.
This updates the vgpu providers on the release branches to laod the mdev
kernel module instead of vfio_mdev.
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-kind-1.27-vgpu/1784918657499926528#1:build-log.txt%3A310
Fixes #
/cc none
**Checklist**
This checklist is not enforcing, but it's a reminder of items that could be …
=> kubevirt,releases: Add change to mdev module name in vgpu release presubmits

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.58.yaml
There are some backports targeting 0.58 - this was missed as part of https://github.com/kubevirt/project-infra/pull/3377
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> kubevirt,vgpu: Add change to mdev module name in vgpu 0.58 presubmits

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.0.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.1.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.2.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
These lanes are failing due to missing a kernel module vfio_mdev[1] after the workloads cluster upgrade. Updating them to be optional to allow time for fixes and backports.
The loading of this kernel module[2] is probably not required as the nvidia operator is installed on the workloads cluster
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-kind-1.27-vgpu/1784918657499926528#1:build-log.txt%3A310
[2] https://github.com/brianmcarey/kubevirtci/blob/62457f28dae83fc916a013fadc33dedde3e5e138/cluster-up/cluster/kind-1.27-vgpu/provider.sh#L38
Fixes #
**Special notes …
=> kubevirt,presubmits: Move vgpu e2e test lanes to optional for main and recent releases

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.59.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.0.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.1.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.2.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
I have noticed multiple vgpu e2e lanes running on the one node at once which causes the test lane to fail as these require access to the GPU on the node.
This fixes the antiaffinity rules to avoid these collisions.
The SRIOV lanes have similar antiaffinity rules[1] and do not collide on the SRIOV nodes.
[1] https://github.com/kubevirt/project-infra/blob/5756c30ab7cea66a9aa4334d92b06eb7a2e0a00c/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml#L204C1-L211C25
Fixes #
**Checklist**
This checklist is not enforcing, …
=> kubevirt,vgpu: Fix antiaffinity rules for vgpu lanes to prevent collisions

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.58.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.59.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.0.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.1.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.2.yaml
The previous change[1] caused a reload of the mdev kernel module which causes the VGPU nodes to get a bad state and the vgpu test lanes to fail constantly.
This change just completely removes the modprobe from the script as has been done in the kubevirtci main branch[2].
[1] https://github.com/kubevirt/project-infra/commit/e6e653ec530d76dbbb0eed99226eb5e806d6de0c
[2] https://github.com/kubevirt/kubevirtci/commit/239678e4ccf7eac19748be3bb80def74c3956b6b
Fixes #
**Checklist**
This checklist is not enforcing, but it's a reminder of items …
=> kubevirt,vgpu: Remove modprobe of vfio_mdev from release vgpu test lanes

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
gcloud is no longer added to PATH by default. This change adds gcloud to PATH which allows the job to complete sccessfully[1].
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirtci-mirror-crio-repository-weekly/1785980497139077120
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> kubevirtci, crio: Fix crio mirror by adding gcloud to PATH

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The fossa check is failing against the main kubevirt branch[1] and the presubmit check is failing too as a result.
Move the test lane to optional in order to not block PRs until the issue is resolved.
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/push-kubevirt-fossa/1785920712284835840
Fixes #
/cc @xpivarc @acardace @dhiller 
**Checklist**
```release-note
```
=> kubevirt,fossa: Update fossa presubmit to be optional

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
This reverts commit 68dcecc93bdb67a00d5e37614a8f7dafa0e01370.
The fossa issues have been cleared against kubevirt[1] - this job can be set to required again.
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/push-kubevirt-fossa/1786330531420442624
Fixes #
/cc @dhiller @acardace @xpivarc 
**Checklist**
```release-note
```
=> Revert "kubevirt,fossa: Update fossa presubmit to be optional (#3389)"

external-plugins/rehearse/plugin/handler/handler.go, external-plugins/rehearse/plugin/handler/handler_test.go
If user name on GitHub handle differs from the user name in the OWNERS file, it is not properly recognized when validating if eligible for rehearsal.
Example: https://github.com/kubevirt/project-infra/pull/3383#issuecomment-2085123369
Thus we normalize to lower case when comparing it.
Fixes #
/cc @brianmcarey @RamLavi 
**Checklist**
```release-note
```
=> prow, plugin, rehearse: fix case issue for user name

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
This sig-compute-serial test lane will be responsible for running all of the sig-compute serial tests.
The other sig-compute lanes are updated to just run the parallel tests.
This change requires the following PR in kubevirt/kubevirt: https://github.com/kubevirt/kubevirt/pull/11740
The sig-compute lane is by far the longest running lane - over 3.5 hours on average[1]. Splitting this lane will give quicker CI feedback to contributors
[1] https://grafana.ci.kubevirt.io/d/gY4hNc5Iz/kubevirt-kubevirt-e2e-test-runtimes?orgId=1&viewPanel=2&from=now-90d&to=now
Fixes #
**Special notes for your …
=> kubevirt,presubmits: Add sig-compute-serial e2e test lane

images/referee/Containerfile
The build for referee is currently pointing to @dhiller fork of project-infra, this PR points it to the kubevirt/project-infra repo.
Fixes #
**Checklist**
```release-note
```
=> prow, referee: fix build to point to kubevirt repo

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Fixes #
**Checklist**
```release-note
```
=> kubevirt,presubmit: Bump single stack ipv6 lane to 1.30

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.2.yaml
https://github.com/kubevirt/project-infra/pull/3385 was supposed to update the release-1.2 vgpu test lane to optional however the windows lane was mistakenly made optional instead - fixing to correctly set the vgpu lane to optional.
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> kubevirt,release-1.2: Fix setting vgpu test lane to optional

github/ci/prow-deploy/files/jobs/kubevirt/application-aware-quota/application-aware-quota-postsubmits.yaml
We need to trigger some of the post-submit jobs
when a new tag is created instead of checking
for branch changes.
Fixes #
**Checklist**
```release-note
NONE
```
=> AAQ: trigger post submit jobs on new tag

external-plugins/rehearse/plugin/handler/BUILD.bazel, external-plugins/rehearse/plugin/handler/handler.go, external-plugins/rehearse/plugin/handler/handler_test.go, external-plugins/rehearse/plugin/handler/labels.go, github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
There are situations where we want to allow rehearsal for users that
otherwise would not be allowed to rehearse (not an approver in the
project).
Therefore we enable rehearsals for pull requests where the label
`ok-to-rehearse` is present.
Fixes #
/cc @brianmcarey @oshoval @qinqon 
**Checklist**
```release-note
```
=> prow, rehearse: add ok-to-rehearse label check

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-periodics.yaml
/cc @0xFelix 
This change introduces a new sync job for release-1.0 to KubeVirt
release-1.2, replacing the previous release-0.4 sync. This moves us
inline with the versions shipped downstream by Red Hat.
Additionally the main sync job now also targets the release-1.0 branch
as we tagged v1.0.0 on this branch accidentally breaking the version
lookup logic of this job. In future we will avoid rc tags and will
branch directly from the release tag instead hopefully avoiding this.
This PR also reverts the move to a weekly sync schedule to allow us to catch up on things. This revert will itself be reverted once we are all caught up.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the …
=> common-instancetypes-periodics: Add sync jobs for release-1.0

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.0.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.1.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.2.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The vgpu presubmit test lanes are failing consistently[1] due to an issue with the CI nodes themselves.
Set alway_run to false to reduce noise on PRs for contributors.
[1] https://prow.ci.kubevirt.io/?job=*vgpu*
Fixes #
**Checklist**
```release-note
```
=> kubevirt,vgpu: Stop vgpu presubmit lanes from always running against PRs

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-postsubmits.yaml, github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
- Makes coverage checks compulsory
- Runs coverage in the main branch
https://issues.redhat.com/browse/CNV-22942
**Checklist**
```release-note
NONE
```
=> CDI: Make goveralls job always run, and run it on main

github/ci/prow-deploy/hack/test.sh
The previous static kubevirtci provider has been removed causing the prow-deploy test lane to fail[1].
Update to use the latest available kubevirtci provider
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/3410/pull-project-infra-prow-deploy-test/1788554621812215808#1:build-log.txt%3A26
Fixes #
/cc @dhiller @lyarwood 
**Checklist**
```release-note
```
=> prow-deploy: Update prow-deploy test lane to use latest provider

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-periodics.yaml
This was missed in 03ab998980 and leads to the sync scripts within kubevirt and ssp-operator looking for a release on main.
Fixes #
**Checklist**
```release-note
NONE
```
=> common-instancetypes-periodics: Pass branch in main sync job

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
The periodic job that updates the istio mirror is failing due to being unable to find the gcloud command[1]. Adding gcloud to PATH should fix this issue.
This is a similar change to what was done for the cri-o mirror job[2]
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-project-infra-mirror-istioctl/1789829270676180992#1:build-log.txt%3A93
[2] https://github.com/kubevirt/project-infra/pull/3391
Fixes #
/cc @dhiller 
**Checklist**
Approvers …
=> istio,mirror: Fix istio mirror by adding gcloud to PATH

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
The bump-rpms-weekly periodic job is failing currently due to it having an old builder image[1]. Its better to rely on the default builder image that is in kubevirt main branch.
Successful run here with these changes - https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/bump-kubevirt-rpms-weekly/1789947081960460288
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/bump-kubevirt-rpms-weekly/1789781454918520832
Fixes #
/cc @dhiller 
**Checklist** …
=> kubevirt,periodic: Update bump-rpms job to use bootstrap image instead of the builder

external-plugins/referee/BUILD.bazel, external-plugins/referee/README.md, external-plugins/referee/ghgraphql/pullrequests.go, external-plugins/referee/main.go, external-plugins/referee/main_test.go, external-plugins/referee/metrics/BUILD.bazel, external-plugins/referee/metrics/doc.go, external-plugins/referee/metrics/metrics.go, external-plugins/referee/metrics/metrics_suite_test.go, external-plugins/referee/metrics/metrics_test.go, external-plugins/referee/metrics/retests.go, external-plugins/referee/metrics/retests_test.go, external-plugins/referee/server/BUILD.bazel, external-plugins/referee/server/server.go
We add metrics that capture the total number of retests encountered and the current state of retests per PR.
Fixes #
**Checklist**
```release-note
```
=> prow, referee: add retest metrics

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Bumps network lanes to using 3 nodes.
It is needed when running two or more VMs in parallel which have a higher memory requirement.
The issue was accidentally discovered during the work on https://github.com/kubevirt/kubevirt/pull/11659.
```release-note
NONE
```
=> bump network lanes to using 3 nodes

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
There looks to be an issue with fossa as the presubmit lanes have been failing for the last couple of hours - update these lanes to be optional
https://prow.ci.kubevirt.io/?job=*fossa*
Fixes #
/cc @dhiller @awels @orelmisan 
**Checklist**
```release-note
```
=> presubmit,fossa: Set fossa presubmit lanes to optional

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
This reverts commit 95cc1791138ba3698dffccc0ef37b7cc058c98d3.
The fossa service looks to have recovered and the test lanes are passing again[1].
They can go back to being required.
[1] https://prow.ci.kubevirt.io/?job=*fossa*
Fixes #
/cc @dhiller @awels 
**Checklist**
```release-note
```
=> Revert "presubmit,fossa: Set fossa presubmit lanes to optional (#3428)"

github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
There is an issue pulling images in the e2e jobs due to an expired certificate. 
Disable the in cluster image cache
Fixes #
**Checklist**
```release-note
```
=> image,cache: Disable images cached for e2e jobs

github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
The e2e jobs are failing to pull images due to an expired certificate - images can be pulled directly from quay.io
Temporarily disable the in cluster image cache
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> image,cache: Disable image cache for e2e jobs

github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
This reverts commits https://github.com/kubevirt/project-infra/commit/2b02a21043e59b01c2d09eea83d488192930c691 & https://github.com/kubevirt/project-infra/commit/0b03484bbe504c16849e80dc000284a6d22b6b9a
The issue with the certificates has been resolved
Fixes #
**Checklist**
```release-note
```
=> image,cache: Enable the in cluster container image cache

docs/labels.md, github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
Fixes #
**Checklist**
```release-note
```
=> labels: Add wg/ipam group label

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.0.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.1.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.2.yaml
The release branch jobs for pull-kubevirt-goveralls are failing for some time - reason are timeout issues.
We disable reporting to avoid confusion for users and give us time to fix the issue.
Fixes #
/cc @brianmcarey @acardace 
**Checklist**
```release-note
```
=> kubevirt, goveralls, releases: skip reporting

images/bootstrap/Dockerfile
Updating the bootstrap image to a Fedora 40 base - this includes an update to podman v5.0.3
Fixes #
**Checklist**
```release-note
```
=> bootstrap: update to Fedora 40

images/golang/Dockerfile
Kubevirt has been updated to build with go v1.22.2[1]
The golang image should be updated to include this version
[1] https://github.com/kubevirt/kubevirt/blob/2f1721f595853d7c0800622363361c8c09aa5fbd/WORKSPACE#L161
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> images,golang: Bump go version 1.22.2

external-plugins/referee/metrics/retests.go, external-plugins/referee/metrics/retests_test.go, external-plugins/referee/server/server.go
This shows state from Friday around noon. There we clearly see that PRs that have already been merged at that time still appear in the dashboard.
Since we don't want to see metrics for merged (and closed) PRs, we remove the values for closed (or merged) PRs. When PRs are reopened we restore the metrics for those again.
Fixes #
**Checklist**
```release-note
```
=> prow, referee, metrics: update metrics on open/close

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml, hack/check-docker-proxy-ca-cert.sh
There was a recent issue where the CA certificate for the docker-mirror-proxy image cache expired causing the majority of the jobs that rely on the cache to pull images to fail[1].
This can have a big impact on CI and our ability to merge PRs.
This periodic check will start failing when the CA certificate will expire in the next 90 days. This should give us enough warning to plan for renewing this certificate
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/3451/pull-project-infra-prow-deploy-test/1797955833284268032#1:build-log.txt%3A14
Fixes #
**Special …
=> periodic,docker-proxy: Add check for docker mirror proxy CA certificate expiration

docs/labels.md, github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml, github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
Add configuration to prioritize pull requests by adding label `priority/critical-urgent`. This will take effect for the label combinations configured at `priority` segment.
Fixes #
**Checklist**
```release-note
```
=> prow, tide, priority: add configuration

images/vm-image-builder/Dockerfile
Updated the  vm-image-builder to support the building of s390x MultiArch VM images.
=> vm-image-builder: update vm-image-builder for s390x

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
This PR adds the s390x cross-build nightly prow job. It will cross build all the kubevirt images and manifests of s390x and pushes it to the upstream quay.io .
Fixes #
cc: @brianmcarey 
There is an ongoing work to enable cross-compilation of s390x on kubevirt This is the PR: https://github.com/kubevirt/kubevirt/pull/11991. Once the PR got merged, we have s390x cross compilation support on kubevirt.  Here i am adding the prow job that will utilize the cross-compilation and push the nightly images.
**Checklist**
This checklist is not enforcing, but it's a …
=> add periodic s390x cross-build nightly job.

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.3.yaml
As the phased plugin is not looking at release branch PRs - there are a number of test lanes that are not executed against 1.3 PRs[1]
Update these test lanes to `always_run: true` so that these checks are not missed on backport PRs.
[1] https://prow.ci.kubevirt.io/pr-history/?org=kubevirt&repo=kubevirt&pr=12132
Fixes #
/cc @oshoval @dhiller @xpivarc 
**Checklist**
```release-note
```
=> kubevirt,v1.3: Update required jobs for v1.3 to always run

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
This check is supposed to run against the workloads cluster and check the expiry of the certificate there.
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> periodic: Update docker proxy CA cert check to run on workloads cluster

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The fuzz make target was added to kubevirt some time ago[1].
Adding a presubmit will help to uncover issues with fuzzing & prevent any regressions.
Set the job as optional initially to make sure its stable
[1] https://github.com/kubevirt/kubevirt/pull/9866
Fixes #
**Checklist**
```release-note
```
=> kubevirt,presubmit: Add optional presubmit lane to run fuzz testing

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
This PR adds the periodic prow job for running unit tests on s390x cluster.
Fixes #
From the discussion happened here: https://github.com/kubevirt/project-infra/pull/3298#issuecomment-2152467586
Raised the PR to add periodic prow job to run unit tests on s390x cluster.
**Checklist**
```release-note
```
=> add periodic prow job to run on s390x cluster.

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.0.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.1.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.2.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.3.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The vgpu presubmit lanes were disabled following the upgrade of the cluster which caused these lanes to fail constantly[1]
These failures were due to an issue with the version of the vgpu driver installed on the nodes. Updating to a later version of the driver has resolved this issue and the periodic vgpu lane is passing consistently[2].
The vgpu presubmit test lanes can be reintroduced and set as required.
[1] https://github.com/kubevirt/project-infra/pull/3408
[2] https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-kind-1.27-vgpu
Fixes #
**Special notes for your …
=> kubevirt,presubmit: Enable vgpu presubmits and set to required

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.3.yaml
Cache evictions are causing v1.3 presubmits to fail[1] - remove the bazel cache from the v1.3 presubmits
This has been done for previous release branches too[2]
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/12146/pull-kubevirt-e2e-k8s-1.28-sig-storage-1.3/1804197967217823744
[2] https://github.com/kubevirt/project-infra/pull/3332
Fixes #
/cc @xpivarc @dhiller @acardace 
We should look at adding this to release-tool so this is done automatically. 
**Checklist**
This checklist is not enforcing, but it's a reminder of items …
=> kubevirt,presubmits: Remove bazel cache from v1.3 presubmits

images/bootstrap/runner.sh
Both the control plane cluster and workloads cluster are running with cgroups v1.
Since Podman v5, warning messages have started to appear in jobs logs[1]
Add environment variable to ignore these warnings and reduce noise in job logs.
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/12196/pull-kubevirt-e2e-k8s-1.29-sig-compute/1805168405502758912#1:build-log.txt%3A323
Fixes #
**Checklist**
Approvers are …
=> bootstrap: Ignore podman warning for deprecation of cgroups v1

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The periodic nightly s390x build is passing[1]  - The presubmit s390x build
so be enabled to always run to ensure the build is not broken.
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-push-nightly-build-main-s390x/1805768650733391872
Fixes #
**Checklist**
```release-note
```
=> kubevirt,s390x: Enable s390x cross compilation build to always run

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-periodics.yaml
/cc @0xFelix 
For the time being this just syncs releases from release-1.0 to KubeVirt release-1.3 while we wait for the full v1.1.0 release of common-instancetypes.
This should keep these branches in line with the older release branches for now where we still sync release-1.0 releases.
Fixes #
**Checklist**
```release-note
NONE
```
=> common-instancetypes-periodics: Add initial job for release-1.1

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.0.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.1.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.2.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.3.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The goveralls test lane consistently fails against the release branches
these jobs were previously set to not report[1] but there is no point in
running them - lets remove the jobs from the release configs.
This also updates the main branch config to stop the goveralls test lane being included in new release branch forks. 
[1] https://github.com/kubevirt/project-infra/pull/3457
Fixes #
/cc @dhiller 
**Checklist** …
=> kubevirt,presubmits: Remove goveralls jobs from recent release job configs

github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
/cc @0xFelix 
This PR adds presubmits ahead of PRs being posted that introduce support for both Tumbleweed and LEAP to the containerdisks project.
Fixes #
**Checklist**
```release-note
NONE
```
=> Add OpenSUSE presubmits for containerdisks

github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
/cc @0xFelix 
The artifacts now live under an opensuse directory and have had opensuse pre appended to their names.
Fixes #
**Checklist**
```release-note
```
=> containerdisks: Update opensuse presubmits

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Enable NodeRestriction fg for 1.30 lanes
This allow us to get wider feedback on the
feature.
Ref https://github.com/kubevirt/kubevirt/pull/12009
Fixes #
```release-note
NONE
```
=> Enable NodeRestriction fg for 1.30 lanes

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
/cc @0xFelix 
$subject, will be used by https://github.com/kubevirt/common-instancetypes/pull/193
Fixes #
**Checklist**
```release-note
NONE
```
=> common-instancetypes: Add OpenSUSE Tumbleweed and Leap presubmits

github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
/cc @0xFelix 
CentOS 7 is now EOL and no longer sync'd as of
https://github.com/kubevirt/containerdisks/pull/148 so we can now remove the presubmit.
Fixes #
**Checklist**
```release-note
NONE
```
=> containerdisks: Remove centos presubmit

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml, github/ci/prow-deploy/kustom/overlays/kubevirt-prow-workloads/kustomization.yaml
We're seeing some flakes related to time which would not be trivial to refactor for proper time mocking:
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/3336/pull-cdi-goveralls/1809334945819136000
So for now, switching to the regular workload cluster which is known to rarely flake on unit tests.
Fixes #
**Checklist**
```release-note
NONE
```
=> Move pull-cdi-goveralls to kubevirt-prow-workloads

images/bootstrap/containers.conf
When the workloads cluster was upgraded to cgroups v2, an issue with the vgpu lanes appeared[1]. After some investigation, we suspect that it is due to cgroups being disabled in podman in container setup.
Removing this option does not cause any impact to other workloads so it is not required.
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-kind-1.27-vgpu/1803735246215057408
Fixes #
**Checklist**
Approvers …
=> bootstrap: Remove cgroups=disabled from containers.conf

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml, robots/pkg/validation/content.go
Adding to our effort to move away from bazel we are moving some presubmits towards pure go:
* pull-project-infra-test-robots
* pull-project-infra-test-releng
* pull-project-infra-test-external-plugins
* pull-project-infra-ci-search-deploy-test
(the latter still uses bazel k8s gitops rules, which needs to get converted to kustomize and kubectl apply, but testing is done via go)
Along the way we fix an error wrt formatting placeholder mismatch. 
Fixes #
**Checklist**
This checklist is not enforcing, but it's a reminder of items that could be relevant to every …
=> project-infra, bazel: move presubmits to pure go

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
Fixes #
**Checklist**
```release-note
NONE
```
=> common-instancetypes: Introduce Fedora arm64 presubmits

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
This adds the remaining (for now) arm64 presubmits for common-instancetypes in support of https://github.com/kubevirt/common-instancetypes/pull/170.
Fixes #
**Checklist**
```release-note
NONE
```
=> common-instancetypes: Add remaining arm64 presubmits

docs/labels.md, github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
We want to have a label sig/ci that we can apply whenever we create issues i.e. from the sig-ci weekly or sig-ci tests quarantine meetings. This way we can find the issues that are our responsibility better. 
Note: in the same way labels are added (automatically via OWNERS files) for kubevirt/kubevirt).
This PR adds a label to use for sig CI.
Currently we can't use the label for marking issues [1]
**Checklist**
Approvers are expected to …
=> sig-ci: add label for sig

external-plugins/referee/Makefile, external-plugins/referee/server/server.go
In cases where there's a push to a PR (which is marked by the synchronize action [1]) we need to update the metrics on PRs, since the number of retests has very likely changed.
We also remove the bazel(isk) calls from the Makefile to use go only.
Fixes #
**Checklist**
```release-note
```
[1]: https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=synchronize#pull_re …
=> referee, prow: update metrics for commit changes

images/bootstrap/Dockerfile
fuse-overlayfs is no longer dragged in as a dependency in the latest
bootstrap image. This causes the smaller jobs on the control-plane
cluster to fail.
Installing fuse-overlayfs allows these jobs to pass successfully
```
$ podman run -ti quay.io/kubevirtci/bootstrap:v20240709-bdabeda rpm -qa | grep fuse
fuse3-libs-3.16.2-3.fc40.x86_64
fuse-libs-2.9.9-21.fc40.x86_64
fuse-common-3.16.2-3.fc40.x86_64
fuse3-3.16.2-3.fc40.x86_64
$ podman run -ti quay.io/kubevirtci/bootstrap:v20240607-febc467 rpm -qa | grep fuse
fuse3-libs-3.16.2-3.fc40.x86_64
fuse-libs-2.9.9-21.fc40.x86_64
fuse-common-3.16.2-3.fc40.x86_64
fuse3-3.16.2-3.fc40.x86_64
fuse-overlayfs-1.13-1.fc40.x86_64
```
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes …
=> bootstrap: add explicit install of fuse-overlayfs

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The ARM64 unit test lane is failing consistently[1] - stop reporting these failures on PRs to reduce noise and as the lane is optional.
This will allow time for investigation into the failures.
[1] https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-unit-test-arm64
Fixes #
/cc @zhlhahaha @dhiller 
**Checklist**
```release-note
```
=> kubevirt,presubmit: Stop reporting failing arm64 unit tests

github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
A number of jobs have started to fail due ot having the wrong bazel version set[1]
The kubevirt repo now uses v5.4.1[2] - update the default to match.
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/bump-kubevirt-rpms-weekly/1784708159516971008#1:build-log.txt%3A161
[2] https://github.com/kubevirt/kubevirt/blob/a37a2b317c335bc1a662d57bd9137d715f52e202/.bazelversion#L1
Fixes #
/cc @dhiller 
**Checklist** …
=> prow,config: Update default bazel version v5.4.1

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
The nightly builds have been broken[1] since a recent prow image bump[2]
Revert back to the previous image to get the nightlies working again
[1] https://github.com/kubevirt/kubevirt/issues/12351
[2] https://github.com/kubevirt/project-infra/pull/3491
Fixes #
**Checklist**
```release-note
```
=> kubevirt,nightly: revert nightly builds to use previous job image

images/bootstrap/runner.sh, images/publish_multiarch_image.sh
There was a recent change in how the containers-common rpm is built[1] which led to a slight formatting change to registries.conf.
This results in short-name-mode remaining in enforcing mode which breaks a number of jobs that still do not use full names for images[2]
[1] https://github.com/containers/common/commit/5c5b1120aaa2970d1b6c961ba2d48996fb240c6a
[2] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/1209/check-provision-alpine-with-test-tooling/1812792004837380096#1:build-log.txt%3A792
Fixes #
/cc @dhiller …
=> fix,bootstrap: Fix sed to change to permissive for short-name-mode

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
The k8s-1.31 cluster provider will be introduced soon[1]
Add an optional check-provision lane to help with testing the new provider
[1] https://github.com/kubevirt/kubevirtci/pull/1220
Fixes #
**Checklist**
```release-note
```
=> kubevirtci,presubmit: Add check-provision lane for new k8s-1.31 provider

github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml, github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
chore: enable branch protection for kubevirt-tekton-tasks
```
NONE
```
=> chore: enable branch protection for kubevirt-tekton-tasks

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
The k8s-1.31 provider has been merged in kubevirtci [1] - move the k8s-1.31 presubmit to required
[1] https://github.com/kubevirt/kubevirtci/pull/1220
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> kubevirtci,presubmit: Set check-provision for k8s-1.31 to always run and be required

github/ci/prow-deploy/files/jobs/kubevirt/user-guide/user-guide-postsubmits.yaml
If there's no pushable changes after web site generation of user-guide the job errors out [1]. This change checks whether there are changes beforehand and only then commits and pushes to the target branch.
[1]: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/push-user-guide-main-build-and-push-to-gh-pages/1815341295258832896
Fixes #
/cc @aburdenthehand @jean-edouard 
**Checklist** …
=> user-guide, publish: fix job error on no pushable changes

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
This lane is currently failing all of the time[1] - the lane is not required due to previous flakiness but now let's stop reporting the failures to reduce the noise.
Once the lane has been returned to a stable state reporting can be turned back on.
[1] https://prow.ci.kubevirt.io/?job=pull-kubevirt-conformance-arm64
Fixes #
/cc @zhlhahaha @dhiller
**Checklist**
```release-note
```
=> kubevirt,arm64: Skip reporting on the arm64 conformance lane

images/bootstrap/runner.sh
Setting short-name-mode to permissive was a temporary workaround for scripts which hadn't been updated to use full image names.
Setting short-name-mode to enforcing forces scripts to be updated with full image names which is best practice and clarifies which image is being used.
Any jobs failing following this update should be updated to use the full image name
Fixes #
**Checklist**
**Release …
=> bootstrap: leave short-name-mode as default enforcing

robots/pkg/kubevirtci/BUILD.bazel, robots/pkg/kubevirtci/kubevirtci.go, robots/pkg/kubevirtci/kubevirtci_test.go
We currently add new providers when they are in beta state already. Therefore the bump automation that removes old providers needs to take into account that some of the "unsupported" providers are actually newer than the currently supported, so they won't get deleted. We add a comparison by version to check this.
See example PR [1]
[1]: https://github.com/kubevirt/kubevirtci/pull/1226
Fixes #
/cc @xpivarc @brianmcarey 
**Checklist**
Approvers are expected to …
=> kubevirtci, ensure-only-latest-three: fix future provider removal

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Lanes created by manually running the following:
```
bazel run //robots/cmd/kubevirt copy jobs -- --job-config-path-kubevirt-presubmits=$(pwd)/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml --job-config-path-kubevirt-periodics=$(pwd)/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml --github-token-path= --k8s-release-semver 1.31 --dry-run=false
```
The k8s-1.31 provider has been added to the kubevirt repo[1]
[1] https://github.com/kubevirt/kubevirt/pull/12408
Fixes #
**Checklist** …
=> kubevirt: Add optional kubernetes 1.31 presubmits & periodics

external-plugins/referee/server/server.go, github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
The referee plugin didn't react to pull_request events, since it was not enabled to do so in the plugin configuration.
Also switch in go works differently - there's no fallthru. This is fixed with this change.
Finally we add some more cases to update the metrics, i.e. converted to draft vs. ready for review.
Fixes #
**Checklist**
```release-note
```
=> prow, referee: enable pull_request events, fix switch

external-plugins/referee/server/server.go
Since the commenter might be a bot user, we need to notify the PR author that their PR is held. Otherwise they might miss the notification about the PR being held (example [1])
[1]: https://github.com/kubevirt/kubevirt/pull/12383#issuecomment-2240907431
Fixes #
**Checklist**
```release-note
```
=> prow, referee: notify PR author instead of commenter

external-plugins/botreview/Makefile, external-plugins/referee/Makefile, github/ci/prow-deploy/kustom/base/manifests/local/referee-deployment.yaml, hack/update-deployments-with-latest-image.sh
Instead of fetching the tag from the image repository via skopeo
list-tags, which is error-prone [1], we add the generated tag as an
argument to the script, since we have tagged the pushed image with
exactly that tag anyway.
[1]: https://github.com/kubevirt/project-infra/pull/3554#issuecomment-2252217582
Fixes #
**Checklist**
```release-note
```
=> project-infra, deployment, update: use generated tag

docs/how-to-add-a-prow-cluster.md
While following the guide to add a prow cluster, exporting the secret token data happens in the default namespace even though `prow-workloads-cluster-automation` is created in the `kubevirt-prow-jobs` namespace
---
```release-note
NONE
```
=> Doc: change namespace for token export

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-tekton-tasks/tekton-tasks-periodics.yaml
fix: add -c param to kubevirt-tekton-tasks script
The git-pr.sh script requires -c parameter which holds the command. This commit updates the teton-tasks periodics script to pass the -c parameter to git-pr.sh script
**Which issue(s) this PR fixes**:
Fixes https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-update-libguestfs-container-version/1812668534048690176
```
fix: add -c param to kubevirt-tekton-tasks script
```
=> fix: add -c param to kubevirt-tekton-tasks script

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The s390x unit-tests are now stable, thus they should be set to required to prevent future PRs from breaking them.
Set s390x unit-tests to required
Fixes #
**Checklist**
```release-note
NONE
```
=> kubevirt, presubmits: Set unit-tests for s390x to be required

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
`pull-kubevirt-apidocs` is failing consistently[1] and blocking merges.
Move this lane to optional
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/12462/pull-kubevirt-apidocs/1818350491675922432#1:build-log.txt%3A178
Fixes #
/cc @jean-edouard @xpivarc 
**Checklist**
```release-note
```
=> kubevirt,presubmits: Set failing apidocs presubmit to optional

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
This reverts commit 0f3c4cc83d10b1e4f53a4f5f7dde1910885b9e95.
The failures in the apidocs presubmit looked to have due to a network issue which has resolved itself since. This lane can be moved back to required.
https://prow.ci.kubevirt.io/?job=pull-kubevirt-apidocs
Fixes #
/cc @xpivarc 
**Checklist**
```release-note
```
=> Revert "kubevirt,presubmits: Set failing apidocs presubmit to optional (#3560)"

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
Following an update to some modules in kubevirtci[1] - the publish now fails to build using go 1.19.9[2]
Update the job to use go 1.22.5
[1] https://github.com/kubevirt/kubevirtci/pull/1236
[2] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/publish-kubevirtci/1818984235680141312#1:build-log.txt%3A19
Fixes #
/cc @xpivarc 
**Checklist**
```release-note
```
=> kubevirtci,publish: update golang version to v1.22.5

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.1.yaml, github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-periodics.yaml
This updates the periodics and adds presubmits for common-instancetypes release-1.1.
Fixes #
**Checklist**
```release-note
None
```
=> Add/Update configuration for common-instancetypes release-1.1

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.1.yaml, github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
Update common-instancetypes-builder to v20240802-59e70de in common-instancetypes presubmits for main and release-1.1.
Fixes #
**Checklist**
```release-note
None
```
=> common-instancetypes: Update common-instancetypes-builder

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml, github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
The dra-pci-driver repository will host the DRA drivers to handle PCI passthrough devices.
Fixes #
**Checklist**
```release-note
```
=> Create dra-pci-driver repository

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-0.1.yaml, github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-0.3.yaml, github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-0.4.yaml, github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.0.yaml, github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.1.yaml, github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
Make pull-common-instancetypes required across all release branches and the main branch.
Fixes #
**Checklist**
```release-note
None
```
=> common-instancetypes: Make pull-common-instancetypes required

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.1.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.2.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.3.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
This lane has been failing consistently since yesterday evening and has been unstable recently[1]. It
looks like an issue with resolving some gradle dependencies.
[1] https://search.ci.kubevirt.io/?search=Could+not+resolve+all+artifacts+for+configuration+%27%3Aclasspath%27&maxAge=48h&context=1&type=all&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
Fixes #
/cc @xpivarc @akalenyu 
**Checklist**
**Release …
=> kubevirt,presubmit: Set failing pull-kubevirt-apidocs to optional

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
TheRealSibasishBehera
- @alicefr 
- @victortoso 
- [Add support for ResourceClaim in HostDevices](https://github.com/kubevirt/kubevirt/pull/12533)
- [refactor: drop GetPodByVirtualMachineInstance,getPodsByLabel . Use libpod.GetPodByVirtualMachineInstance instead at all its callers.](https://github.com/kubevirt/kubevirt/pull/11474)
- [Independent DRA driver for host devices](https://github.com/TheRealSibasishBehera/kubevirt-dra-driver)
I want to actively contribute to kubevirt . I am currently working on separate component for kubevirt focussing on host-device assignment using [DRA](https://kubernetes.io/docs/concepts/scheduling-eviction/dynamic-resource-allocation/)  kept [here](https://github.com/TheRealSibasishBehera/kubevirt-dra-driver), which will be further maintained in …
=> Add TheRealSibasishBehera to KubeVirt Members

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.1.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.2.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.3.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
This reverts commit 815faa80671f6c82a1006020e2d22affccd99256.
`pull-kubevirt-apidocs` is looking much more stable[1] since the change to using the swagger2markup-cli jar[2]
[1] https://prow.ci.kubevirt.io/?job=pull-kubevirt-apidocs
[2] https://github.com/kubevirt/kubevirt/pull/12552
Fixes #
/cc @xpivarc 
**Checklist**
```release-note
```
=> Revert "kubevirt,presubmit: Set failing pull-kubevirt-apidocs to optional"

github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-postsubmits.yaml
Currently the postsubmit takes the first tag that is set on HEAD. This assumes that there is only one tag.
However, since this postsubmit is triggered by the tag added, it only makes sense the it should take the last one.
This change would fix issues where a new release tag is set on a commit with an already set tag (theoretically valid). What will happen then is that the new tag will be taken, and not the old one.
Fixes #
**Checklist**
Approvers are expected to …
=> kubemacpool, postsubmit: Fix to push last added tag

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-postsubmits.yaml
Missing `v` here as well,
Was missed with https://github.com/kubevirt/project-infra/pull/3420
Fixes #
**Checklist**
```release-note
NONE
```
=> Correct skip branch regex in push-cdi-goveralls

github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Fixes #
**Checklist**
```release-note
```
=> Missing dra-pci-driver for approve and lgtm

hack/update-deployments-with-latest-image.sh
job periodic-project-infra-prow-deployment-image-bump is failing [1] due to unbound variable, this change assigns the empty string as default.
[1]: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-project-infra-prow-deployment-image-bump/1826058066550853632#1:build-log.txt%3A77
Fixes #
=> update-deployments-with-latest-image.sh: fix image_tag unbound var

images/autoowners/Dockerfile
During updating URLS of prow bumper [1] we noticed that the image build for autoowners is not working any more [2]
[1]: https://github.com/kubevirt/project-infra/pull/3587
[2]: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/3587/rehearsal-build-autoowners-image/1828001341071429632
This PR updates autoowners container file to use full qualified image name, also bumps the go version, since the source go.mod has been updated.
Fixes #
=> Update autoowners container file to use full qualified image name

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
This periodic job requires a newer version of go[1] than what is available in the pr-creator image by default
Adding the updated go version allows the job to succeed[2]
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirtci-bump-centos-base/1828281508075409408#1:build-log.txt%3A2369
[2] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirtci-bump-centos-base/1828708775083642880
Fixes #
/cc @dhiller 
**Checklist** …
=> kubevirtci.periodic: Update go version used by bump centos periodic

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
This job fails occasionally hitting the timeout[1] - 5 minutes is very tight - lets increase it to 15 minutes.
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/1255/check-provision-manager/1828733329004826624
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> kubevirtci,presubmit: Increase time out for check of provision manager

images/bootstrap/containers.conf
The nightly build jobs have been failing[1] due to default podman pids_limit (2048)[2] in the bootstrap image being too low.
Increasing this to 4096 allows the nightly build jobs to complete successfully[3].
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-push-nightly-build-main/1828599108043018240
[2] https://docs.podman.io/en/v5.2.2/markdown/podman-update.1.html#pids-limit-limit
[3] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-push-nightly-build-main/1828835977469104128
Fixes #
/cc @dhiller …
=> bootstrap: Increase podman pids_limit to 4096

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-postsubmits.yaml
This will only run the publish of the CDI builder image when there have been changes merged for the builder image. 
It should remove the need for `git diff` checks in the underlying scripts[1[ which block us from publishing a fresh image by triggering the postsubmit manually. 
[1] https://github.com/kubevirt/containerized-data-importer/blob/40fd89cd3b8c9896a5049d8dfc90d33d3117b4b6/hack/build/bazel-build-builder.sh#L38
Fixes #
/cc @akalenyu @awels 
**Checklist** …
=> cdi,postsubmit: Update the push of CDI builder to only run when there are changes

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
bump-kubevirt-rpms-weekly has been failing due to the pr-creator tool not being available[1]
Update the job to use the dedicated pr-creator image
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/bump-kubevirt-rpms-weekly/1830562918236688384#1:build-log.txt%3A8385
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> kubevirt,periodic: Use pr-creator image for bump-rpms periodic job

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Serial tests are covered by the serial lane - this lane only needs to run the parallel tests.
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> kubevirt,presubmits: Update to sig-compute lane to only run parallel

docs/how-to-add-a-prow-cluster.md
When creating a serviceaccount for a new prow cluster, the admin role is a ClusterRole. Additionally the namespace should be defined, as otherwise it likely lands in the default namespace.
Fix the rolebinding step when adding a new prow-cluster
Fixes #
**Checklist**
```release-note
NONE
```
=> docs: Fix rolebinding example for serviceaccount creation

github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
Renames the label `topic/testing` to `area/testing`.
Note: after merge it will take a while for the labels to consolidate, since the jobs runs only once every day.
Fixes #
/cc @vladikr @brianmcarey
=> github, labels: move testing to category area

github/ci/services/grafana/manifests/grafana.yaml
Adds a new per SIG failures panel to the e2e failures dashboard:
---
---
Fixes #
=> prow, monitoring: add panel of failure % by SIG

docs/labels.md, github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
Adds `triage/infra-issue` to the GitHub labels. 
Also syncs the labels.md with missing changes (which was seen after executing `make update-labels`)
Fixes #3632
/cc @iholder101 @brianmcarey
=> github, labels: add triage/infra-issue

images/bootstrap/Dockerfile
This pr updates the bootstrap image to include `which` package.
Why we need it?
The which pkg is required to fetch the installed kubectl path and set the KUBECTL variable for the external provider. Check here: https://github.com/kubevirt/kubevirt/blob/main/cluster-up/cluster/external/provider.sh#L29 . Since it is not there the s390x e2e job is not able to set the kubectl env variable and the access_test.go test files are getting skipped. 
These are the logs:
```
00:38:02: /home/prow/go/src/github.com/kubevirt/kubevirt/cluster-up//cluster/external/provider.sh: line 28: which: command not found
00:38:02: /home/prow/go/src/github.com/kubevirt/kubevirt/cluster-up//cluster/external/provider.sh: line 34: which: command not found 
``` …
=> update bootstrap to include which pkg.

images/bootstrap/Dockerfile
There are a number of jobs that are failing to pull images due to corruption and a crc32mismatch[1]
There is an open issue for this problem in the podman repo[2] that suggests this change as a workaround.
This workaround should be removed when the related issues are resolved.
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/12677/pull-kubevirt-e2e-k8s-1.31-sig-compute/1833657514537783296#1:build-log.txt%3A262
[2] https://github.com/containers/podman/issues/23822
[3] https://github.com/zlib-ng/zlib-ng/issues/1772
Fixes #
/cc …
=> bootstrap: Add workaround for corrupted image pulls with podman

github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-postsubmits.yaml
Currently, kubemacpool pushes to QUAY only when a release tag is set, or for every main branch commit.
This behavior is wanted also for stable branch commits, in order to be able to consume them from latest commits by other repos.
Adding another postsubmit for stable branches.
Fixes #
**Checklist**
```release-note
NONE
```
=> kumemacpool, postsubmit: Push stable branch latest commits

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The s390x bare-metal cluster should now be available to prow - moving the unit test job to the bare-metal cluster to start running some jobs there.
Fixes #
/cc @vamsikrishna-siddu @jschintag  @dhiller 
**Checklist**
```release-note
```
=> kubevirt,presubmit: Move s390x unit test job to new bare-metal cluster

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml, github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml, images/pr-creator/Dockerfile
This PR updates base image (golang) version and Go version to newer versions and mainly enables multi-arch images for pr-creator.
Multi-arch images for pr-creator are needed as now with #3566 we want to move PR creation part into periodic-kubevirtci-bump-centos-base-s390x. So that after x86 centos images are built, followed by s390x builds and manifest-list, we will create the PR in the s390x machine. 
Fixes #
**Checklist**
Approvers are expected to review this …
=> Enable multiarch builds for pr-creator image

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Switch the s390x periodic unit-test job for kubevirt from the IBM Cloud cluster to the new bare-metal s390x cluster.
Use the bare metal cluster for s390x unit-test jobs
Fixes #
**Checklist**
```release-note
NONE
```
=> kubevirt,periodic: Switch s390x unit test jobs to new cluster

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
There is an issue with the arm64 e2e lanes[1] - stop reporting on PRs while the issue is being investigated.
[1] https://testgrid.kubernetes.io/kubevirt-presubmits#pull-kubevirt-e2e-arm64
Fixes #
/cc @dhiller @xpivarc @zhlhahaha 
**Checklist**
```release-note
```
=> kubevirt,arm64: Stop reporting on failing ARM64 e2e lane

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
Archive the no longer maintained ansible-kubevirt-modules repository.
See https://groups.google.com/g/kubevirt-dev/c/f6sb7kMikkI
Fixes #
**Checklist**
```release-note
None
```
=> Archive repository ansible-kubevirt-modules

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
**What this PR does / why we need it**: Added an optional presubmit job to test against https://github.com/kubevirt/kubevirt/pull/12117
Fixes #
**Checklist**
```release-note
```
=> Add an optional presubmit job for kwok performance tests

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
As next step it would be nice to have s390x nightly build available
The automation script hast to be adjusted first though
**Checklist**
```release-note
- s390x nightlies made available
```
=> Add nightly build periodic job for s390x

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.2.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.3.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The storage e2e lanes see a large number of lane failures due to etcd timeouts[1] - running these lanes with etcd in memory should stop these etcd timeouts from occurring as we have seen with the other e2e lanes.
We saw instability when running with the default tmpfs size of 512M as this was filling up and causing etcd to restart. 
```
{"level":"fatal","ts":"2024-09-18T12:16:27.580544Z","caller":"etcdserver/raft.go:224","msg":"failed to save Raft hard state and entries","error":"no space left on device","stacktrace":"go.etcd.io/etcd/server/v3/etcdserver.(*raftNode).start.func1\n\tgo.etcd.io/etcd/server/v3/etcdserver/raft.go:224"}
```
Increasing this to 1G improves the stability greatly. 
[1] …
=> kubevirt,presubmits: update storage lanes to run with etcd in mem

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
We want to have the report updated ahead of the sig-ci meetings. Thus we switch to using a cron expression instead of an interval.
Fixes #
/cc @xpivarc @brianmcarey
=> sig-ci: run quarantined tests report in the morning

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
We've been struggling with etcd failures across all lanes with the latest occurence in CDI being
https://github.com/kubevirt/containerized-data-importer/pull/3439#issuecomment-2360283272.
Since we're not going to swap the storage setup for CI
(non-dedicated storage per worker)
This is our best way forward.
Fixes #
**Checklist**
```release-note
NONE
```
=> CDI,presubmits: update lanes to run with etcd in mem

images/bootstrap/Dockerfile
The fix for the issue that this workaround was added for has been included in Fedora 40.
https://bugzilla.redhat.com/show_bug.cgi?id=2307237
```
[root@b873a1829fa1 /]# cat /etc/redhat-release
Fedora release 40 (Forty)
[root@b873a1829fa1 /]# rpm -qa | grep zlib-ng
zlib-ng-compat-2.1.7-2.fc40.x86_64
```
This reverts commit 16816d317dbe52c99d80c652c46d0ee7e7c0e115.
Fixes #
/cc @dhiller 
**Checklist** …
=> Revert "bootstrap: Add workaround for corrupted image pulls with podman (#3639)"

github/ci/prow-deploy/kustom/overlays/kubevirtci-testing/resources/ingress-nginx-controller.yaml
A number of nginx containers failed to create due to the image tag /sha combo.
```
message: 'checking signature of "registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20230407@sha256:543c40fd093964bc9ab509d3e791f9989963021f1e9e4c9c7b6700b02bfb227b":
creating docker:// reference for "registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20230407@sha256:543c40fd093964bc9ab509d3e791f9989963021f1e9e4c9c7b6700b02bfb227b":
Docker references with both a tag and digest are currently not supported'
reason: CreateContainerError
```
Update the nginx deployment to only use image tag
Fixes #3667 
**Special …
=> prow-deploy,presubmit: update nginx deployment to use only image tag

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-periodics.yaml
SSP no longer creates common instance types. This commit removes the automation that posts PRs with new versions.
**Which issue(s) this PR fixes**:
Fixes: https://issues.redhat.com/browse/CNV-44448
**Checklist**
```release-note
None
```
=> common-instancetypes-periodics: Don't post PR to SSP

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The vgpu lanes are currently testing against kubernetes v1.27 which is no longer supported on the main branch of kubevirt.
Update these lanes to use the new provider kind-1.30-vgpu.
This requires the following PR to be merged into kubevirt first: https://github.com/kubevirt/kubevirt/pull/12244
Fixes #
**Checklist**
```release-note
```
=> kubevirt,vgpu: Bump vgpu lanes to use new kind-1.30-vgpu provider

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
This reverts commit d45f40014047274277f6bbb2ae422f8c1e383eab.
Following a reboot of the nodes the lane is passing consistently enough now that reporting can be reenabled.
https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-arm64
Fixes #
/cc @dhiller @zhlhahaha 
**Checklist**
```release-note
```
=> Revert "kubevirt,arm64: Stop reporting on failing ARM64 e2e lane"

images/bootstrap/Dockerfile, images/bootstrap/gcs_restapi.sh
This is a pre-requisite for enabling publishing jobs for k8s provider for s390x (#3566 ), as those jobs need to interact with gcs from s390x machines
Fixes #
**Checklist**
```release-note
NONE
```
=> Added REST based API calls for GCS as gsutil isn't supported for s390x in bootstrap image

docs/labels.md, github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
The label `sig/code-quality` is used to mark pull requests that target improvements to our code base[1]. However, the prefix `sig` gives the impression that there is a SIG that is actively caring for such PRs.
Given the fact that there's neither an entry inside sigs.yaml[2], nor a proper sig folder in the community repository, nor any publicly held meetings that are announced in the community calendar[3], we can assume that such a sig doesn't exist.
During the discussion at the community meeting[4] about this topic there was the suggestion to just rename the label into a `kind` label. Looking at Kubernetes labels provided a general label `kind/cleanup`[5] that matches a broader set of scenarios and seems to be well suited for covering all the …
=> kubevirt, labels: rename code-quality into cleanup

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
This PR adds optional presubmit  prow job named check-provision-k8s-1.30-s390x, which is used for checking the provisioning of k8s 1.30 provider on s390x arch. As we've a PR #1252 enabling k8s 1.30 provider on s390x, this prow job once merged can be used in that job as presubmit check.
Created the PR as discussed [here](https://github.com/kubevirt/kubevirtci/pull/1252#issuecomment-2377029863)
**Checklist**
```release-note
NONE
```
=> Added optional presubmit  check-provision-k8s-1.30-s390x

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
The kubevirt builder publish post submit prow job is failing with timeout. The default timeout for the job is 2h and the graceperiod is 15s. I have increased the timeout and grace period to 4h and 5m. 
Here I am attaching the failure job logs.
```
{"component":"entrypoint","file":"sigs.k8s.io/prow/pkg/entrypoint/run.go:169","func":"sigs.k8s.io/prow/pkg/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 2h0m0s timeout","severity":"error","time":"2024-09-27T17:47:13Z"}
{"component":"entrypoint","file":"sigs.k8s.io/prow/pkg/entrypoint/run.go:267","func":"sigs.k8s.io/prow/pkg/entrypoint.gracefullyTerminate","level":"error","msg":"Process did not exit before 15s grace …
```
=> Increase the timeout to 4hrs for the kubevirtbuilder post submit job .

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
As s390x cluster doesn't have dokcer mirror proxy, removing the label from the prow job.
As pre-submit job check-provision-k8s-1.30-s390x is failed and discussed [here](https://github.com/kubevirt/project-infra/pull/3681/files#r1780748224), this follow-up PR fixes the failure.
**Checklist**
```release-note
NONE
```
=> fix: removing docker-mirror-proxy label for check-provision-k8s-1.30-s390x

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
The image proxy was removed from the wrong job -reverting https://github.com/kubevirt/project-infra/pull/3684
The s390x cluster does not have a image proxy deployed - remove the
preset for now
Fixes #
/cc @vamsikrishna-siddu @chandramerla 
**Checklist**
```release-note
```
=> kubevirtci,presubmit: Remove image proxy from s390x presubmit 

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
As conformance-s390x.yaml is required for running check-cluster-up.sh in 1.30 k8s provider which being enabled for s390x in slim mode, added it.
**Checklist**
```release-note
NONE
```
=> Copy conformance-s390x.yaml to GCS in periodic-kubevirt-push-nightly-build-main-s390x

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Currently if check-provision-k8s-1.30-s390x  runs on s390x PR [#1252](https://github.com/kubevirt/kubevirtci/pull/1252), it fails as part of that PR only 1.30 k8s provider in SLIM mode is enabled. So, added SLIM=true env variable, so that check-provision-k8s-1.30-s390x runs in slim mode.
**Checklist**
```release-note
NONE
```
=> Add slim mode to check-provision-k8s-1.30-s390x prow job

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.13.yaml
There was an issue pulling images with some previous version of the bootstrap images - this should be fixed in the latest build of the images.
v1.13 HCO lanes are failing pulling images[1] - update to use latest.
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_hyperconverged-cluster-operator/3121/pull-hyperconverged-cluster-operator-e2e-k8s-1.30/1842110165982121984
Fixes #
**Checklist** …
=> hco,presubmit: Update golang image to fix issue pulling images in v1.13 lanes

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Skips Kubevirt conformance tests temporarily for check-provision-k8s-1.30-s390x job.
To allow presubmit job of checking k8s 1.30 provider on s390x (i.e.,check-provision-k8s-1.30-s390x) to pass, only conformance tests are failing on [PR](https://github.com/kubevirt/kubevirtci/pull/1252). As these failing tests are being looked into separately and needs enabling other parts of kubevirt for s390x, skipping them temporarily on check-provision-k8s-1.30-**s390x** and same would enabled in follow-up PRs.
P.S: This PR also fixes incorrect SLIM=true env variable on check-provision-k8s-1.31 (which I only introduced in wrong job in my [earlier PR](https://github.com/kubevirt/project-infra/pull/3688)) and now added the same variable to correct job i.e., …
=> Skip Kubevirt conformance tests temporarily for check-provision-k8s-1.30-s390x job

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
Add a new unit-test job to hco presubmits for s390x. Mark the job as optional until it has proven to be stable.
This PR adds unit-tests for HCO as a presubmit. This is the first step in ensuring HCO is running stable on s390x.
Fixes #
This is my first time adding a completely new job to project-infra.
Additionally, since there is no x86 unit-test job, i made a guess by the Memory requirements for the job.
**Checklist** …
=> hco,presubmit: Add unit-test job for s390x

images/bootstrap/Dockerfile
In bootstrap image for s390x, iinstall kubectl. kubectl is already getting installed for non-s390x. 
As for jobs like check-provision-k8s-1.30-**s390x**, the golang image(based on bootstrap) needs to execute kubectl commands as given in cluster-up/cluster/k8s-provider-common.sh, this is required to be installed for s390x as well.
**Checklist**
```release-note
NONE
```
=> Add kubectl installation to bootstrap image for s390x

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Makes running the gocli unit tests a mandatory presubmit job for kubevirtCI
Fixes #
https://github.com/kubevirt/kubevirtci/pull/1287
**Checklist**
=> feat: Run the gocli tests on all presubmit runs to KubevirtCI

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
@chandramerla 
[x] I have reviewed the community code of conduct (https://github.com/kubevirt/kubevirt/blob/master/CODE_OF_CONDUCT.md)<br>
[x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)<br>
[x] I have subscribed to the kubevirt-dev e-mail list (https://groups.google.com/forum/#!forum/kubevirt-dev)<br>
[x] I am actively contributing to KubeVirt<br>
[x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines<br>
[x] I have spoken to my sponsors ahead of this application and they have agreed to sponsor my application<br>
[x] I have publicly introduced myself to the community through one of the community communication channels<br>
* @brianmcarey 
* @dhiller …
=> Add chandramerla as kubevirt org member

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
This is a followup to https://github.com/kubevirt/project-infra/pull/3710
The storage presubmit lanes already include this increase in etcd capacity[1] - including it here to keep the lanes consistent
[1] https://github.com/kubevirt/project-infra/blob/51c8fa2c0465e0f703eb9ffb70909b796c24f3e4/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml#L1549C1-L1550C22
Fixes #
**Checklist**
Approvers are expected to review …
=> kubevirt,periodic: Increase etcd in mem capacity to 1G for storage periodics

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The arm64 e2e presubmit lane is failing consistently[1] - disable reporting of this lane to reduce noise on PRs.
[1] https://testgrid.kubernetes.io/kubevirt-presubmits#pull-kubevirt-e2e-arm64
Fixes #
/cc @zhlhahaha @dhiller @xpivarc 
**Checklist**
```release-note
```
=> kubevirt,presubmit: Disable reporting on the failing arm64 e2e lane

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
For some reason, the compute conformance lane is appearing as required on PRs:
Source: https://github.com/kubevirt/kubevirt/pull/13129
Explicitly set it as optional to avoid blocking PRs as the target has not been introduced in kubevirt yet
Fixes #
**Checklist**
```release-note
```
=> kubevirt,presubmit: Explicitly set compute conformance lane as optional

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
This PR adds optional presubmit prow job named check-provision-k8s-1.31-s390x, which is used for checking the provisioning of k8s 1.31 provider on s390x arch. As we've a PR https://github.com/kubevirt/kubevirtci/pull/1316 enabling k8s 1.31 provider on s390x, this prow job once merged can be used in that job as presubmit check.
@brianmcarey The job added here is just a copy of check-provision-k8s-1.30-s390x, replacing string 1.30 with 1.31
**Checklist**
```release-note
NONE
```
=> Added optional presubmit  check-provision-k8s-1.31-s390x

github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
This pr adds the preset-kubevirt-s390x-icr-credential label which allows us to pull the s390x images from IBM Cloud Container Registry(icr.io)
Fixes #
**Checklist**
```release-note
None
```
=> add preset-kubevirt-s390x-icr-credential to pull the s390x images from icr.io

images/shared-images-controller/main.go
The location of the latest kubevirtci tag in the kubevirt repo has been
updated[1] resulting in the shared-images-controller trying to pull an
empty tag.
Update this path to the new location.
[1] https://github.com/kubevirt/kubevirt/commit/92624b1a351420f8cc2b587a64ba4ac6dd97bac1
Move sleep to start of loop in shared-images-controller and add continues when errors occur during the loop so that dependent tasks are skipped.
Fixes #
/cc @dhiller 
**Checklist** …
=> images: Update path to latest kubevirtci tag in shared-images 

github/ci/prow-deploy/hack/test.sh
Since the move of kubevirtci from k/kubevirt into it's own folder the deployment check is failing [1] - we need to adjust the script to reckon that.
[1]: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/3724/pull-project-infra-prow-deploy-test/1853793403578355712#1:build-log.txt%3A468
Fixes #
=> prow,deploy,check: fix kubevirtci path

github/ci/prow-deploy/files/jobs/kubevirt/community/community-presubmits.yaml
Replaces the previous python based check, which is obsolete after the changes to the generation of repo_groups.sql got merged, with a simple call to make generate and checking whether there's uncommitted changes.
This change will:
* allow us to bundle further checks below the make generate target, and
* remind us whenever we change i.e. `sigs.yaml` that we need to call `make generate`
Fixes #
/cc @iholder101 @brianmcarey @aburdenthehand
=> community,sigs: replace presubmit with make call

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.2.yaml
/cc @0xFelix 
Using the cluster-{up,sync,functest} targets uses the stable v1.3.1 that is missing various things that we require in release-1.2.
Fixes #
**Checklist**
```release-note
NONE
```
=> common-instancetypes, release-1.2: Use kubevirt HEAD until 1.4 is released

github/ci/prow-deploy/kustom/overlays/kubevirt-prow-workloads/resources/shared-images-controller.yaml
This is a followup to https://github.com/kubevirt/project-infra/pull/3727
The image has been published successfully[1]
Bumping the image in order to include the changes.
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/publish-shared-images-controller-image/1853770763174154240#1:build-log.txt%3A335
Fixes #
**Checklist**
```release-note
```
=> prow-workloads: bump shared-images-controller to v20241105-ed1a7bc

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
(Followup #3739)
bazel failed to build with BUILD_ARCH=amd64, as it's not supported. 
See failure here: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-containerized-data-importer-push-nightly-AMD64/1853996433422684160
This PR changes the arch to `x86_64`, instead.
```release-note
None
```
=> CDI: Fix amd64 nightly build

hack/remove-users-without-contributions.sh
There's two tools with the same name `yq` and we are using both from time to time and their syntax of handling yaml files differs.
Therefore we need to check which version we're using from inside the script and adjust the usage of the tool accordingly.
Fixes #
**Checklist**
```release-note
```
=> kubevirt,governance: improve script to remove inactive org users

robots/cmd/perf-report-creator/main.go
This PR moves the perf/scale tool to read data from results directory json file, instead of grepping it from build log.
This is needed because a recent change in the build log output format broke the regex matching of build log files.
Fixes #
**Checklist**
```release-note
NONE
```
=> use artifacts result directory to read pref/scale data

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
The HCO pre-submit test lanes are with the right names but with the wrong K8s versions, that are not match to their name and too old.
This PR bumps the K8s versions, and make them match the lane names.
```release-note
HCO: Bump K8s version
```
=> HCO: Fix K8s versions

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Make check-provision-k8s-1.30-s390x required now, so that s390x provisioning is tested as well.
@brianmcarey As discussed created the PR
**Checklist**
```release-note
NONE
```
=> Made optional presubmit check-provision-k8s-1.30-s390x mandatory now

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Made optional presubmit check-provision-k8s-1.31-s390x mandatory, to make any changes in 1.31 provider to not to break s390x provider build.
Also increased timeout for check-provision-k8s-1.31-s390x and check-provision-k8s-1.30-s390x jobs as sometimes it is taking lot of time executing kubernetes conformance tests and job is timing out. Ex: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/1316/check-provision-k8s-1.31-s390x/1855052914712645632
This PR needs to be merged after https://github.com/kubevirt/kubevirtci/pull/1316 is merged.
**Checklist**
Approvers are …
=> Made optional presubmit check-provision-k8s-1.31-s390x mandatory

github/ci/prow-deploy/files/jobs/kubevirt/community/community-presubmits.yaml
Since we want to use the configuration files inside the project-infra to validate community documents as `sigs.yaml` we add an extra ref so that they are availabe when running the presubmit.
Fixes #
/cc @brianmcarey @aburdenthehand 
See https://github.com/kubevirt/community/pull/350#issuecomment-2470970471
=> community,generate: add project-infra extra_ref

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml, github/ci/testgrid/gen-config.yaml
Adds an email alias for sending mails in case of job failures for the push-release-kubevirt-tag job.
Fixes #
**Checklist**
```release-note
```
=> kubevirt,release: add alert email

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
GitHub search currently lacks being able to query for PRs that are missing a review by an approver, since the concept of approver vs. reviewer is enforced via OWNERS, which GitHub doesn't know about.
This change adds a condition to the search query that selects PRs to label with `needs-approver-review` in order to exclude PRs where changes have been requested.
> [!IMPORTANT]
> For this to work approvers need to explicitly request changes on the review though
Fixes #
/cc @jean-edouard @brianmcarey
FYI @vladikr @alicefr
=> needs-approver-review: avoid labelling PRs with changes requested

docs/labels.md, github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
The label `sig/virtualization`i [1] seems to be a leftover from previous times - we should migrate it into the sig/compute label.
[1]: https://github.com/kubevirt/kubevirt/labels?q=sig%2Fvirtualization
Fixes #
/cc @iholder101 @vladikr @brianmcarey
=> labels,sig/compute: migrate sig/virtualization

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.0.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.1.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.2.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.3.yaml
The vgpu lanes for older release branches are failing since updating the CI worker nodes to cgroups v2[1]
This bootstrap image was built specifically for these lanes
It has an updated containers.conf with `cgroupns="private"` - this allows the older vgpu lanes to run the tests successfully
[1] https://github.com/kubevirt/kubevirt/issues/13324
Fixes #
**Checklist**
```release-note …
```
=> kubevirt,presubmits: Update release vgpu lanes to use custom bootstrap image

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml, github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Currently the only user who can apply or remove the label `needs-approver-review` is the `kubevirt-bot` user.
This change introduces a new GitHub team under the KubeVirt org that contains the people who will be allowed to apply or remove the label - changing the orgs.yaml to achieve this.
Then the `label` config is extended to allow above created group to manage the label - changing plugins.yaml.
Fixes #
/cc @vladikr @iholder101 @alicefr @aburdenthehand
=> needs-approver-review: enable management by GH team

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Since we are approaching the timeout value [1] and had a failure due to timeout recently, we are increasing the timeout by 1/2 hour.
[1]: https://prow.ci.kubevirt.io/?type=periodic&job=*org*
Fixes #
=> peribolos,org: increase job timeout

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
The k8s-1.32 cluster provider is due to be introduced soon[1] - add optional check-provision jobs to help with testing the new provider
[1] https://github.com/kubevirt/kubevirtci/pull/1327
Fixes #
/cc @dhiller @chandramerla 
**Checklist**
```release-note
```
=> kubevirtci,presubmits: Add optional presubmit lanes to test k8s-1.32 provider

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
Run ValidationOS lane on when its tag or image changes
Fixes #
**Checklist**
```release-note
None
```
=> common-instancetypes: Run ValidationOS lane on when tag/image changes

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> kubevirtci,presubmit: Enable check-provision for new k8s-1.32 provider

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
This PR adds multi-arch publish jobs for centos9 images.
As we've added s390x support in k8s provider (started with 1.30 slim), centos9 and gocli images as part of https://github.com/kubevirt/kubevirtci/pull/1252, this PR does changes required in project-infra repo to enable the prow jobs for publishing centos9 multi-arch image.
There is another PR where publishing of multi-arch images of k8s provider is handled: https://github.com/kubevirt/project-infra/pull/3566
**Checklist**
```release-note
NONE
```
=> Prow jobs for publishing centos9 multi arch image

github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/kustomization.yaml, github/ci/prow-deploy/tasks/secrets.yml, github/ci/prow-deploy/vars/kubevirtci-testing/secrets.yml
This secret is required to enable some cleanup in the google cloud account
The secret already exists in our secrets repo.
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> prow-deploy: Add virtci-gcs secret to the prow control plane cluster

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
As we don't use all the versions of k8s provider for s390x currently and we plan to start with latest version (1.31) to be used for e2e tests once enabled using provider, making this 1.30 job as optional. In future when required, we will make it always run.
@brianmcarey As discussed, created the PR.
**Checklist**
```release-note
NONE
```
=> Made pre-submit job check-provision-k8s-1.30-s390x optional

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Lanes created by running:
```
bazel run //robots/cmd/kubevirt copy jobs -- --job-config-path-kubevirt-presubmits=$(pwd)/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml --job-config-path-kubevirt-periodics=$(pwd)/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml --github-token-path= --k8s-release-semver 1.32 --dry-run=false
```
The k8s-1.32 is now available in kubevirt/kubevirt since https://github.com/kubevirt/kubevirt/pull/13366 merged.
Fixes #
/cc @dhiller 
**Checklist**
This checklist is not enforcing, …
=> kubevirt: Add optional presubmit and periodic lanes for new k8s-1.32 provider

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Following the introduction of the k8s-1.32 lanes, the k8s-1.32 sig-compute serial lane is appearing as required and blocking merges.
Set this lane to be optional explicitly in the config to unblock PRs.
Fixes #
**Checklist**
```release-note
```
=> kubevirt,presubmit: Set k8s-1.32 sig-compute-serial to be explicitly optional

github/ci/prow-deploy/files/jobs/kubevirt/kubesecondarydns/OWNERS
Alona is not as active on the project anymore. I believe that Or showed his maintainer qualities on cluster-network-addons-operator, and that he's the logical choice to become the new approver of KSD.
Fixes #
None.
**Checklist**
```release-note
NONE
```
=> KubeSecondaryDNS: Nominate Or Shoval for approver

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml, hack/gcp-cluster-deprovision.sh
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> periodics: Job to cleanup leftover machines in the Google Cloud account

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.4.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The s390x cluster has a maintainance window tomorrow on the 04.12.2024 from 14-19 CET.
Fixes #
**Checklist**
```release-note
NONE
```
=> kubevirt, presubmits: Temporarily switch s390x tests to optional

github/ci/prow-deploy/files/jobs/kubevirt/kubesecondarydns/kubesecondarydns-presubmits.yaml
Add testing for building and unit-tests on s390x to kubesecondarydns
Fixes #
**Checklist**
```release-note
NONE
```
=> kubesecondarydns, presubmits: Add build and unit-tests for s390x

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> kubevirtci,presubmit: Remove unnecessary dind preset from kind presubmit lane

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.4.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Maintenance will be over on 19:00 CET.
This reverts commit 68a62efe412b22f9dcc841aa8f7de262c5f47a71.
Fixes #
Do not merge before 19:00 CET.
**Checklist**
```release-note
NONE
```
=> Revert "kubevirt, presubmits: Temporarily switch s390x tests to optional (#3796)

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml, robots/cmd/perf-report-creator/graph.sh, robots/cmd/perf-report-creator/scrape.sh
With the introduction of the k8s-1.32 into kubevirtci[1] - the v1.29 provider will be removed soon.
Update the performance lanes to use the k8s-1.31 provider to keep them working
[1] https://github.com/kubevirt/kubevirtci/commit/4d4c8fe3fade746d3408715b06e9e9e741c3ab5b
Fixes #
/cc @alaypatel07 @rthallisey @dhiller 
**Checklist**
```release-note
```
=> kubevirt,performance: Bump presubmit and periodic performance lanes to kubernetes v1.31

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml, github/ci/services/ci-search/patches/statefulset.yaml
Some contributors have been looking for more history in ci-search to improve their ability of identifying trends with flaky tests.
Increasing the max age from the default 14 days[1] to 28 days
[1] https://github.com/openshift/ci-search/blob/6356b951587bd1ca473de97e41a2422ae02c7efd/cmd/search/main.go#L72
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> ci-search: Increase max-age for results to 28 days

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml, github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
The dind preset only works with the legacy bootstrap images - as these jobs are using the new bootstrap image  - they should be using the podman in container setup
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> preset,cleanup: Remove dind preset which is no longer used by these project-infra prow jobs

hack/gcp-cluster-deprovision.sh
Occasionally the deprovisioning periodic job can hit the timeout limit of 30m and cause the job to fail[1] - increase this timeout to 60m to reduce the possiblity of failure
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-project-infra-gcp-cluster-deprovision/1866388755863048192
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> periodics: Increase deprovisioning timeout to 60 mins

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
The lane is failing consistently since December 6th[1] - move to optional to allow time to investigate
[1] https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/check-provision-alpine-with-test-tooling
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> kubevirtci,presubmit: Move failing check-provision-alpine-with-test-tooling to optional

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Add a presubmit check for the new kind provider introduced by https://github.com/kubevirt/kubevirtci/pull/1334
Fixes #
**Checklist**
```release-note
```
=> kubevirtci,presubmit: Add check for new kind-1.31 provider

github/ci/prow-deploy/files/jobs/kubevirt/bridge-marker/bridge-marker-postsubmits.yaml
This update ensures that the PLATFORMS environment variable is set to "all" before executing the `make docker-build docker-push` command in both `main-bridge-marker` and `release-bridge-marker` jobs. This change enables building multi-platform supported bridge marker image.
This commit ([892ccdd](https://github.com/kubevirt/bridge-marker/commit/892ccddb8ba33a687d42de425810605eb6f71625)) enables multi-platform support. By default, the image is built based on the host architecture. To build a multi-platform image that supports amd64, arm64, and s390x, the PLATFORMS=all environment variable needs to be exported before running the make docker-build command.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, …
=> Add export PLATFORMS=all to post-submit jobs for bridge-marker

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml, robots/cmd/per-test-execution/main.go
1.32 stable release has happened, but since we don't have a lot of data for periodics on 1.32 we are fixing the version to 1.31 as there's more data to report over.
Background is that the k8s version is auto retrieved, which currently doesn't make sense for us.
Also there's a bug in the k8s regexp that disallows v1.32.0 to pass: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-project-infra-gcp-cluster-deprovision/1867113551571718144
Fixes #
=> per-test-execution: run with set k8s version

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
With the introduction of the Kubernetes v1.32, it will soon be time to remove the k8s-1.29 provider - remove the check-provision presubmit as no longer needed
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> kubevirtci,presubmit: Remove the check-provision job for k8s-1.29

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
This PR adds multi-arch publish jobs for centos9 and k8s provider images. 
As we've added s390x support in k8s provider (started with 1.30 slim), centos9 and gocli images as part of https://github.com/kubevirt/kubevirtci/pull/1252, this PR does changes required in project-infra repo to enable the prow jobs for the same.
This PR makes sense to be merged along with changes said above.
**Checklist**
```release-note
NONE
```
=> Prow jobs for publishing k8s provider multi arch images

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
Fixes #
**Checklist**
```release-note
NONE
```
=> chore(common-instancetypes): Bump builder to v20241217-0005325

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
It onboard a new test lane for CentOS Stream 10 containerdisk. It also enables CentOS Stream 10 in the arm64 CentOS test lane.
Fixes # [CNV-52778](https://issues.redhat.com/browse/CNV-52778)
**Checklist**
```release-note
Enables common-instancetypes CentOS Stream 10 test lanes.
```
=> chore(common-instancetypes): Add tests lanes for CentOS Stream 10

.golangci.yaml, Makefile, github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml, hack/lint.sh, releng/release-tool/release-tool.go, robots/pkg/kubevirt/cmd/get/support-matrix.go
Adds the coverage and lint make targets and the initial .golangci-lint configuration.
Also it adds `//nolint` directive to some of the files.
Fixes #3822
=> project-infra: add make targets lint and coverage

.golangci.yaml
Currently builds of `make lint` are failing when trying to dowload stuff [1] 
The changed setting will make golangci-lint fail instead of implicitly updating if go.mod requires that.
See https://golangci-lint.run/usage/configuration/#run-configuration
[1]: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/3824/pull-project-infra-lint/1869719164365574144
Fixes #
=> golangci-lint: disallow automatic updating of go.mod

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.2.yaml
It onboard a new test lane for amd CentOS Stream 10 containerdisk in the release 1.2.
Fixes # [CNV-52778](https://issues.redhat.com/browse/CNV-52778)
**Checklist**
```release-note
Enables common-instancetypes CentOS Stream 10 test lane in release 1.2
```
=> chore(common-instancetypes): Add test lane for CentOS Stream 10 in release 1.2

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
Remove the old k8s 1.30 lane
<
```release-note
HCO: Add new lane for k8s-1.32
```
=> HCO: Add new lane for k8s-1.32

github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits-v0.45.yaml
This PR adds a stable branch [release-0.45](https://github.com/k8snetworkplumbingwg/kubemacpool/tree/release-0.45) lane for kubemacpool.
Fixes #
**Checklist**
```release-note
NONE
```
=> kubemacpool: Add stable branch release-0.45 lane

github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.97.yaml
This PR adds a stable branch presubmit for `release-0.97` branch
Fixes #
**Checklist**
```release-note
NONE
```
=> cnao: Add stable release-0.97 branch presubmit

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The v1.29 kubernetes provider will be removed from kubevirtci soon -
update the monitoring lane to use the latest stable provider
Adding a periodic lane for the sig-monitoring e2e tests allows us to
check the health of this lane against the main branch and also gives us
feedback on the state of any quarantined monitoring e2e tests
Fixes #
/cc @machadovilaca @sradco @dhiller 
**Checklist** …
=> kubevirt,monitoring: Update monitoring presubmit to v1.31 and add periodic monitoring lane

.golangci.yaml
golangci-lint job seems to frequently exceed it's timeout value [1], so we increase it to 5m.
[1]: https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/pull-project-infra-lint
Fixes #
=> lint: increase timeout

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The v1.32 presubmit lanes appear to be stable - move them to required and move v1.31 to phase 2. 
https://testgrid.k8s.io/kubevirt-presubmits
Fixes #
**Checklist**
```release-note
```
=> kubevirt,presubmits: Set v1.32 e2e lanes to required 

github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-postsubmits.yaml
This update ensures that the PLATFORMS environment variable is set to "all" before executing the `make container docker-push` . This change enables building multi-platform images for kubemacpool cni.
Currently, we are only posting an amd64-supported image for the Kubemacpool CNI: [link to image](https://quay.io/repository/kubevirt/kubemacpool?tab=tags&tag=latest).
To build a multi-platform image that supports amd64, arm64, and s390x, the PLATFORMS=all environment variable must be exported before running the make container command.
Fixes #
**Checklist**
This …
=> Add export PLATFORMS=all to post-submit jobs for kubemacpool.

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Move Root CI lanes to 1.31 k8s provider
Fixes #
**Checklist**
```release-note
NONE
```
=> Move root CI lanes to 1.31

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
Following the recently accepted proposal to create a new repository to track KubeVirt enhancements https://github.com/kubevirt/community/pull/362
This is a PR that aims to request this new repository. 
```release-note
NONE
```
=> Create a new repo to track KubeVirt enhancements

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml, robots/cmd/test-label-analyzer/cmd/BUILD.bazel, robots/cmd/test-label-analyzer/cmd/stats.go
Since we can't rely on the ginkgo binary being present, we replace the call of the cli with a direct call of the Command. We capture the output of the command and replace the evaluation using the captured output.
Fixes #
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/3851/pull-project-infra-test-robots/1874869025570295808
=> test-label-analyzer: replace ginkgo cli call with stdout

github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml, github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml, github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
This PR drops the admin privileges and enables tide for the kubevirt/enhancements repo
```release-note
NONE
```
=> enhancements repo: drop admin and enable tide

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Upgrading the remaining lanes as the old provider is being removed from kubevirtci[1]
[1] https://github.com/kubevirt/kubevirtci/pull/1342
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> kubevirt: Bump remaining v1.29 to Kubernetes v1.32

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
The lane is failing against multiple PRs unrelated to kind providers
https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/check-up-kind-sriov
FYI @EdDev @ormergi 
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> kubevirtci,presubmit: Move check-up-kind-sriov to optional as constantly failing 

images/shared-images-controller/main.go
This should reduce cluster-up failures due to issues pulling the gocli
image or registry image
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> shared-images: Add gocli and registry images to shared-images 

github/ci/prow-deploy/kustom/overlays/kubevirt-prow-workloads/resources/shared-images-controller.yaml
Fixes #
I've created an issue to get this automatically bumped with hack/bump-prow-deployment-images.sh - https://github.com/kubevirt/project-infra/issues/3892
**Checklist**
```release-note
```
=> shared-images: Bump shared-images controller to the latest image v20250115-57bca5c

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml, hack/bump-prow-deployment-images.sh, hack/describe-pr-from-updated-images-in-diff.sh
Currently we rely on a fixed image list, which has to be modified
whenever a new image is added.
This change greps over the manifests and extracts all image names that
match `quay.io/kubevirtci` - this list is then used as input for the
update script.
Also the change expands on the PR description that is attached - changing the git-pr.sh call to replace the hard coded description with a call to al description generation script. That script retrieves a list of images from the diff being updated and returns a markdown suited to be inserted into the PR description.
Fixes #3891
**Special notes for …
=> chore,image updates: fetch names from manifests

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
It looks like the the s390x centos 9 base image failed to build which is causing the check-provision-k8s-1.31-s390x to fail constantly.
https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/check-provision-k8s-1.31-s390x
Move to optional until we have a stable base image for s390x.
FYI @chandramerla @vamsikrishna-siddu 
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> kubevirtci,presubmit: Move check-provision-k8s-1.31-s390x to optional due to constant failure

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
This lane has been passing consistently and can be moved back to being required.
https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/check-up-kind-1.30-vgpu
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> kubevirtci,presubmits: Set vgpu presubmit lane back to being required

images/bootstrap/runner.sh
We still occasionally see e2e lanes fail due to the podman socket not being ready in time.
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/13537/pull-kubevirt-e2e-k8s-1.31-sig-compute/1880903900127563776 
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11266/pull-kubevirt-e2e-k8s-1.30-sig-storage/1881735319955443712
This is indicative of poor disk performance and high IO wait times.
In the short term, increase the wait timeout to stop failing the e2e lanes failing.
In the long term, we need to investigate improving the storage setup on the CI cluster
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) …
=> bootstrap: Increase max wait time for podman socket to be ready

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-periodics.yaml
Reschedule the HCO nightly build to 4:02 AM, to make sure the CDI nightly (scheduled to 3:02 AM) was already done, and the new CDI images and manifests are ready to use.
```release-note
None
```
=> Delay HCO periodic, to catch CDI nightly build

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
This PR reverts https://github.com/kubevirt/project-infra/pull/3878, making kubevirt/kubevirtci "check-up-kind-sriov "lane gating.
The PR https://github.com/kubevirt/kubevirtci/pull/1348 fixes the issue and stabilize the lane, once it merge this PR can be merged.
Fixes #
**Checklist**
```release-note
```
=> kubevirtci,presubmit: Make check-up-kind-sriov lane as required

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml, images/test-label-analyzer/Containerfile
install of ginkgo binary is removed as the dependency is used directly now.
Also memory requests and limits are increased since it seems the job suffers from starvation sometimes: https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/pull-project-infra-coverage
Fixes #
=> chore: remove ginkgo install

robots/cmd/test-label-analyzer/cmd/stats.go, robots/cmd/test-label-analyzer/cmd/stats_test.go, robots/cmd/test-label-analyzer/cmd/testdata/simple-basic_test.go
After the changes around using the ginkgo command instead of the osexec for ginkgo binary handling the case of ginkgo outline failing due to missing import did not work any more. This commit fixes the issue by recovering from the panic that is caused in the case, also returning the error in all other cases by setting the named return argument.
Fixes failing job periodic-kubevirt-quarantined-tests-daily-report https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-quarantined-tests-daily-report/1882318824603127808
=> bug,ginkgo: fix handling no ginkgo import

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Upgrade sig-network IPv6 lane to use latest kubevirtci provider - k8s-1.32.
Fixes #
**Checklist**
```release-note
NONE
```
=> presubmits: Upgrade sig-network IPv6 lane

images/shared-images-controller/main.go
gocli is available locally to the test pod however the registry image is still pulled by the test pod.
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/13670/pull-kubevirt-e2e-k8s-1.32-sig-network/1884223087730233344#1:build-log.txt%3A475
The wrong target is being pulled for the registr step.
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> fix,shared-images: Registry image is not being pulled due to wrong image name

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
This PR archives 25 inactive repos in the project due to lack of relevance or maintenance. 
It follows an announcement of intentions on the mailing list: https://groups.google.com/g/kubevirt-dev/c/QpIaRzmNh4c/m/3lA87gdAAAAJ
Fixes: https://github.com/kubevirt/community/issues/239
Once merged, it would be a good idea to go through these repos and update the individual READMEs with a deprecation notice. 
```release-note
NONE
```
=> Archiving 25 inactive repos

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml, github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml, github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml, github/ci/prow-deploy/kustom/base/manifests/local/branch-protector.yaml, github/ci/prow-deploy/kustom/base/manifests/local/cherrypicker_deployment.yaml, github/ci/prow-deploy/kustom/base/manifests/test_infra/current/crier_deployment.yaml, github/ci/prow-deploy/kustom/base/manifests/test_infra/current/deck_deployment.yaml, github/ci/prow-deploy/kustom/base/manifests/test_infra/current/ghproxy.yaml, github/ci/prow-deploy/kustom/base/manifests/test_infra/current/grandmatriarch.yaml, github/ci/prow-deploy/kustom/base/manifests/test_infra/current/hook_deployment.yaml, github/ci/prow-deploy/kustom/base/manifests/test_infra/current/horologium_deployment.yaml, github/ci/prow-deploy/kustom/base/manifests/test_infra/current/needs-rebase_deployment.yaml, github/ci/prow-deploy/kustom/base/manifests/test_infra/current/pipeline_deployment.yaml, github/ci/prow-deploy/kustom/base/manifests/test_infra/current/prow_controller_manager_deployment.yaml, github/ci/prow-deploy/kustom/base/manifests/test_infra/current/sinker_deployment.yaml, github/ci/prow-deploy/kustom/base/manifests/test_infra/current/statusreconciler_deployment.yaml, github/ci/prow-deploy/kustom/base/manifests/test_infra/current/tide_deployment.yaml, github/ci/prow-deploy/kustom/base/manifests/test_infra/current/tot_deployment.yaml, github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/resources/prow-exporter-deployment.yaml, github/ci/prow-deploy/prow-autobump-config.yaml, github/ci/prow-deploy/prow-job-autobump-config.yaml, hack/bump-prow.sh
Switch to avoiding target reference version, since u/s bumping seems to
have been disabled or is not working.
See https://github.com/kubernetes/test-infra/blob/9267e9caa24d42d6547cc1d99b1307aed9326bc7/config/prow/cluster/deck_deployment.yaml#L41
Also adds path of prow job images to config path.
Fixes #3711, #3749
=> autobump,fix: update generic-autobumper

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
We have seen an number of performance lanes fail due to etcd timeouts. 
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/13722/pull-kubevirt-e2e-k8s-1.31-sig-performance/1879967726319964160 
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/13713/pull-kubevirt-e2e-k8s-1.31-sig-performance/1881726950221811712
The rest of the e2e lanes have moved to using etcd in memory to stop these flaky failures.
Update perf e2e lanes to use etcd in memory
Fixes #
/cc @dhiller @rthallisey @alaypatel07 …
=> kubevirt,perf: Use etcd in memory to stop etcd failures in perf lanes

hack/gcp-cluster-deprovision.sh
Also set the log level to info to see more information on which clusters are failing to remove within the timeout
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> gcp,deprovision: Remove SIGQUIT signal to reduce noise

github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
Due to the lack of support for the s390x architecture in Cirros, we propose selecting CentOS Stream as the default container disk. CentOS Stream supports a broader range of architectures, making it a more versatile choice.
```release-note
NONE
```
=> ci: default containerdisk ci run for CentOS Stream

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Fixes #
**Checklist**
```release-note
```
=> kubevirt,e2e: Move 1.32 e2e jobs to new prow-workloads cluster

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.5.yaml
The bazel cache is usually disabled for release lanes as it can cause problems due to cache evictions.
Fixes #
**Checklist**
```release-note
```
=> kubevirt,presubmits: disable bazel cache for release-1.5 presubmits

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> kubevirt,e2e: Move remaining kubevirt main branch e2e jobs to new workloads cluster

github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
This job tests the CentOS Stream 9 in the container disks on the s390x cluster for every pull request.
The containerdisks tooling publishes containerdisks to quay.io, making early detection essential from the s390x perspective. For example, an error in the tooling may produce correct images for the amd64 architecture while generating incorrect ones for s390x. Without this check, along with others, incorrectly generated s390x images could also be published.
```release-note
NONE
```
=> ci: s390x CentOS Stream 9 containerdisks always_run job

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The image kubevirtci/bootstrap-legacy:v20240523-1a2c9b8 does not contain Arm64 arch image. Revert to v20230829-f2e4ded.
make the conformance test line works on Arm64
Fixes https://github.com/kubevirt/kubevirt/issues/13673
```release-note
NONE
```
=> arm64, e2e: revert bootstrap-legacy image

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml, github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml, github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml, github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Move the prow jobs for the project-infra and kubevirtci repos to the new workloads cluster as the old cluster is affected by a data centre closure. 
This move does not include SRIOV and VGPU based kubevirtci jobs as these are not
enabled on the new cluster yet
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> prow: Move project-infra and kubevirtci jobs to the new workloads cluster

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.49.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.50.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.51.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.52.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.53.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.54.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.55.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.56.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.57.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.58.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.59.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.0.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.1.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.2.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.3.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.4.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.5.yaml
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> kubevirt,releases: Update kubevirt release presubmit lanes to use new workloads cluster

hack/_include_image_funcs.sh, hack/bump-prow-deployment-images.sh
We don't want to bump the bootstrap-legacy image, it's there for legacy reasons. Any change there should be done by intention. This PR avoids bumping in in the automation script. 
Fixes #
=> bump-prow-job-images: avoid bumping bootstrap-legacy

docs/labels.md, github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml, github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml, github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
We repeatedly had the issue that binaries mirrored to the gcs to avoid losing them were not reachable any more, as the mirroring PR was not merged ahead of branching the release.
This change enables skip-review label, which will make tide merge PRs that have all lanes succeeded and no forbidden labels, i.e. `do-not-merge/hold`.
Fixes #
/cc @brianmcarey @xpivarc @jean-edouard @stu-gott
=> skip-review: enable for k/kubevirt uploader prs

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.59.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.0.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.1.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.2.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.3.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.4.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.5.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Fixes #
**Checklist**
```release-note
```
=> kubevirt,vgpu: Move vgpu e2e lanes to the new cluster

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml, robots/cmd/test-label-analyzer/cmd/root.go, robots/cmd/test-label-analyzer/cmd/stats.go
This PR fixes the quarantined test report generation, which was broken since the changes wrt prow dependencies.
Changes:
* Integrates the auto-determination of the latest commit id from the test
repository into the test repository url.
* Adds the capability to write the report directly to a gcs bucket.
* Updates the job configuration to reflect the added flags.
Successful rehearse run: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-quarantined-tests-daily-report/1892152494935511040
Fixes #3925
=> fix,test-label-analyzer: move glue code from job into stats

hack/update-deployments-with-latest-image.sh, robots/cmd/kubevirtci-presubmit-creator/main.go
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> prow,automation: Update automations to point to new cluster

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml, github/ci/prow-deploy/kustom/components/greenhouse/base/resources/deployment.yaml, github/ci/prow-deploy/kustom/overlays/prow-workloads/.gitignore, github/ci/prow-deploy/kustom/overlays/prow-workloads/kustomization.yaml, github/ci/prow-deploy/kustom/overlays/prow-workloads/resources/bootstrap.yaml, github/ci/prow-deploy/kustom/overlays/prow-workloads/resources/greenhouse-storage.yaml, github/ci/prow-deploy/kustom/overlays/prow-workloads/resources/place-holder.yaml, github/ci/prow-deploy/kustom/overlays/prow-workloads/resources/priority-classes.yaml, github/ci/prow-deploy/kustom/overlays/prow-workloads/resources/shared-images-controller.yaml, github/ci/prow-deploy/kustom/overlays/prow-workloads/resources/sriov-passthrough-ds.yaml, github/ci/prow-deploy/vars/prow-workloads/main.yml
A new prow workloads cluster is required due to the old cluster being affected by a datacentre closure.
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> prow,workloads: Add files to bootstrap the new prow workloads cluster

github/ci/prow-deploy/files/jobs/kubevirt/application-aware-quota/application-aware-quota-presubmits.yaml
The target was initailly added when scheduling gate Was disable by default for k8s <= 1.27 , all
the supported versions of k8s are now higher than 1.27 so there is no need for the target anymore
Fixes #
**Checklist**
```release-note
NONE
```
=> Remove AAQ target k8s from main branch

docs/infrastructure-components.md
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> docs: remove reference to old workloads cluster from docs

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
The hco s390x unit-tests have been running stable now for months. Change it to required.
Changing the hco unit-tests running on s390x to required.
Fixes #
**Checklist**
```release-note
NONE
```
=> hco,presubmit: Make s390x unit-test required

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
There are occasions when there a two or three PRs being actively worked on and tested. In this case having a max concurrency of 1 leads to major bottle necks and slows down delivery of fixes.
Increase this to three to reduce this bottle necking.
Fixes #
**Checklist**
```release-note
```
=> kubevirtci,presubmit: Increase max concurrency from 1 to 3

github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
=> fix: set the job as optional until the s390x pipelines are stable.

Makefile, images/release-tool-base/Containerfile, images/release-tool/Containerfile, releng/release-tool/release-tool.go, releng/release-tool/release-tool_test.go, releng/release-tool/testdata/jobconfig/kubevirt-presubmits-1.6.yaml
config-forking was broken in a couple of ways:
* it used an old version of the config-forker from test-infra which didn't retain the value for `run_before_merge`
* it didn't update the forked config, since for release branches the phase plugin didn't work in the same way, therefore the values had to be converted from `run_before_merge` to `always_run`
This PR fixes the issues.
We also now use this opportunity to remove the bazel cache label since
we need to do that every time anyways: https://github.com/kubevirt/project-infra/pull/3961
Fixes #3478
/cc …
=> release-tool: fix config-forking

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
release-tool image push job has to run privileged [1]. Rehearse run [2]
[1]: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/publish-release-tool-image/1900115653214343168
[2]: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/publish-release-
tool-image/1900118963895930880
Fixes #
=> fix: release-tool image push

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
The new k8s-1.33 provider is due to be introduced shortly[1] - add a presubmit lane to verifiy that the provider is built correctly
[1] https://github.com/kubevirt/kubevirtci/pull/1392
Fixes #
**Checklist**
```release-note
```
=> kubevirtci,presubmit: Add check-provision lane for new k8s-1.33

external-plugins/phased/plugin/handler/handler.go, external-plugins/phased/plugin/phased_test.go, robots/pkg/github/labels/labels.go
We noticed that the automated tests aren't being run if a PR with `skip-review` label is added and the phased plugin is active for a repository. I.e. this hinders auto bump PRs in k/kubevirt to get merged. Example: https://github.com/kubevirt/kubevirt/pull/14211
This change adds `skip-review` support to the phased plugin.
Fixes #
/cc @oshoval @brianmcarey @iholder101
**Checklist**
```release-note
```
=> fix: let phased plugin run tests for skip-review PRs

docs/infrastructure-components.md, external-plugins/test-subset/Containerfile, external-plugins/test-subset/Makefile, external-plugins/test-subset/plugin/handler/handler.go, external-plugins/test-subset/plugin/main.go, external-plugins/test-subset/plugin/server/eventsserver.go, external-plugins/test-subset/plugin/specify_suite_test.go, external-plugins/test-subset/plugin/specify_test.go, github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml, github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml, github/ci/prow-deploy/kustom/base/kustomization.yaml, github/ci/prow-deploy/kustom/base/manifests/local/test-subset-deployment.yaml, github/ci/prow-deploy/kustom/base/manifests/local/test-subset-rbac.yaml, github/ci/prow-deploy/kustom/base/manifests/local/test-subset-service.yaml, github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/kustomization.yaml, github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/patches/JsonRFC6902/test-subset-deployment.yaml, images/test-subset
Allows to run specific labels on a lane
`/test-subset <job-name> <labels>`
It will create a job, inject the label to its env var, and give it a unique suffix, so it won't
affect the official jobs.
Opposed to focus (which is also not encouraged, now that we have labels), the job won't fail if all lanes
pass, which reduce emails, comments, and the need to manually look on the job results on both cases.
=> plugins: Introduce test-subset plugin

github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
We are currently relying on the Kubernetes managed prow and documentation, but we want to link to our own prow instance and documentation. This change links to the merge automation doc which contains a description of the basic merge workflow.
It also links to our own prow command help page, since the installed plugins differ from the main k8s prow instance.
Fixes kubevirt/community#370
/cc @aburdenthehand @brianmcarey
=> fix: add links to own prow and own merge workflow

external-plugins/test-subset/Containerfile, github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml, github/ci/prow-deploy/kustom/base/manifests/local/test-subset-deployment.yaml
Changes
* fixes the compile path for the test-subset external-plugin.
* adds a presubmit that checks whether the image for test-subset is buildable
* updates the image for test-subset to latest in deployment
Fixes #
/cc @brianmcarey @oshoval
=> fix: correct test-subset external-plugin compile source path

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml, github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
Onboards test lanes for projects:
* CommonInstanceTypes: Four test lanes for Debian 11 and 12 containerdisk for each arch amd64 and arm64.
* Containerdisks: One test lane for Debian contaierdisks
Fixes # [CNV-51711](https://issues.redhat.com/browse/CNV-51711) and [CNV-51712](https://issues.redhat.com/browse/CNV-51712)
**Checklist**
```release-note
Added test lanes for Debian 11 and 12 in containerdisk …
```
=> Adds test lanes for Debian 11 and 12 preferences and containerdisks.

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
Fix test job debian names.
pull-common-instancetypes-kubevirt-debian-11 -> pull-common-instancetypes-kubevirt-functest-debian-11
pull-common-instancetypes-kubevirt-debian-12 -> pull-common-instancetypes-kubevirt-functest-debian-12
Fixes #
**Checklist**
```release-note
None
```
=> fix(common-instancetypes): Fix test job debian names.

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml, images/bootstrap/gcs_restapi.sh
In s390x publish centos9 and kubevirtci jobs, do GCS calls to check for existence and contents of the publicly available files under kubevirt-prow/release/kubevirt/kubevirtci/ without authentication
As there are limits to number of refresh tokens that are issued per client-user combination in GCS, and beyond limits it may make old token to stop working, so we are reducing the token usage with this fix.
Ref: https://developers.google.com/identity/protocols/oauth2#5.-refresh-the-access-token,-if-necessary.
https://github.com/kubevirt/project-infra/pull/3812
This PR is adds to the previous PR [3812](https://github.com/kubevirt/project-infra/pull/3812) to fix the issue
This should address prow job failures like: …
=> In s390x publish centos9 and kubevirtci jobs, do GCS calls without auth where possible

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.3.yaml
Add presubmits of Debian for release-1.3
Fixes #
**Checklist**
```release-note
None
```
=> chore(common-instancetypes): Add presubmits of Debian for release-1.3

hack/describe-pr-from-updated-images-in-diff.sh
The grep for the image name only worked if the image was at the top of the container configuration. This change makes the hyphen optional.
Also it simplifies the determination of the absolute path name.
Fixes #4033
/cc @enp0s3 @brianmcarey
=> fix: describe-images has a non optional hyphen

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.0.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.1.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.2.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.3.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.4.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.5.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The timeout of 1 hour is regularly hit during periods of heavy load on the CI workloads cluster causing the performance jobs to fail.
These failures are counted as part of the SIG CI failures and make up over half of total SIG CI failures in the last week.
Increase the timeout to 2 hours as there is more value in receiving the results of these runs rather than timing out.
Recent failures:
https://prow.ci.kubevirt.io//view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/14250/pull-kubevirt-e2e-k8s-1.31-sig-performance/1901635014685102080
https://prow.ci.kubevirt.io//view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/14232/pull-kubevirt-e2e-k8s-1.29-sig-performance-1.3/1900224038391779328
https://prow.ci.kubevirt.io//view/gs/kubevirt-prow/pr-logs/pul …
=> kubevirt,presubmit: Increase timeout for performance e2e presubmits

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.5.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Fixes #
```release-note
NONE
```
=> Move migration lane to 1.32 Kubernetes

github/ci/prow-deploy/kustom/overlays/prow-workloads/kustomization.yaml, github/ci/prow-deploy/kustom/overlays/prow-workloads/patches/JsonRFC6902/docker_mirror_deployment.yaml, github/ci/prow-deploy/kustom/overlays/prow-workloads/patches/JsonRFC6902/greenhouse_deployment.yaml
These services run on a dedicated cache node in the workloads cluster - it doesn't make sense to limit there resources so much.
It has also been seen that there are performance issues with the docker image cache when a large number of jobs are run and the jobs begin to fail to pull the images[1]. When these issues occur, the docker-mirror-proxy pod hits it's CPU limits and starts to throttle the CPU usage.
Increase the resource requests & limits for both the docker-mirror-proxy and greenhouse (bazel cache).
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/14352/pull-kubevirt-e2e-k8s-1.30-sig-storage-1.3/1905156088500588544#1:build-log.txt%3A385
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue …
=> prow,workloads: Increase resource requests/limits for image proxy and bazel cache

images/bootstrap/gcs_restapi.sh
This fixes the bug https://github.com/kubevirt/kubevirtci/issues/1405 in the file images/bootstrap/gcs_restapi.sh used by s390x image publish jobs. The auth_header was malformed, due to improper quotes. This is fixed now!
**Which issue(s) this PR fixes**:
Fixes https://github.com/kubevirt/kubevirtci/issues/1405
Earlier I've tested only stat_gcs_file and cat_gcs_file functions and as for these functions I was passing public file for testing, though auth was malformed they were working. So the issue [#1405](https://github.com/kubevirt/kubevirtci/issues/1405) isn't identified. Now I've tested all functions (rm_gcs_file and upload_to_gcs) w/ and w/o auth they support and found all are working as …
=> Escape auth_header value with quotes

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.2.yaml
pull-kubevirt-e2e-k8s-1.27-sig-compute-1.2 has been failing constantly for the last number of weeks[1]. The other compute presubmit lanes pass successfully.
Move this lane to optional to allow some time for investigation.
[1] https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.27-sig-compute-1.2
Fixes #
/cc @fossedihelm @dhiller 
**Checklist** …
=> kubevirt,release-1.2: Move 1.27 sig-compute to optional due to constant failures

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
This configuration is being moved into automations/test.sh in kubevirt/kubevirt [1]
[1] https://github.com/kubevirt/kubevirt/pull/14354
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> kubevirt,presubmit: Remove KUBEVIRT_NUM_NODES from compute-migrations lane

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-postsubmits.yaml
It seems like this times out sometimes:
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/push-release-containerized-data-importer-images/1905401265668493312
Fixes #
**Checklist**
```release-note
NONE
```
=> Bump timeouts on CDI image release job

github/ci/prow-deploy/files/jobs/kubevirt/libguestfs-appliance/libguestfs-appliance-periodics.yaml
This PR updates the prow job to push the s390x libguestfs-appliance tar file and version file.
Fixes #
This is dependent on the libguestfs-appliance fix pr: https://github.com/kubevirt/libguestfs-appliance/pull/19 . It should not be merged until the above pr gets merged.
**Checklist**
```release-note
None.
```
=> update libguestfs-periodics prow job to include s390x files.

github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
Added a new Prow job to run the CNAO workflow functional tests for the s390x architecture
This PR adds Prow jobs for CNAO workflow functional tests on s390x.
We have recently released CNAO (Cluster Network Addons Operator) as a multi-architecture release(starting with v0.98.0), supporting amd64, arm64, and s390x architectures
Link to the multi-arch release: [CNAO on Quay.io](https://quay.io/repository/kubevirt/cluster-network-addons-operator?tab=tags&tag=latest)
However, currently, we don't have Prow jobs or test lanes set up for s390x and arm64 architectures.
Fixes #
**Special notes for your …
=> cnao, presubmit: add cnao workflow functests for s390x

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
It onboards four new test lanes for Oracle Linux 8 and 9 preferences for each arch amd64 and arm64.
Fixes # [CNV-58724](https://issues.redhat.com/browse/CNV-58724)
**Checklist**
```release-note
Add Oracle Linux 8 and 9 preferences test jobs
```
=> chore(common-instancetypes): Add tests lanes for Oracle Linux 8 and 9

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.3.yaml
Add presubmits of Oracle Linux for release-1.3
Fixes # [CNV-58724](https://issues.redhat.com/browse/CNV-58724)
**Checklist**
```release-note
Added tests jobs for common-instancetypes Oracle Linux preferences in release 1.3
```
=> chore(common-instancetypes): Add presubmits of Oracle Linux for release-1.3

github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-periodics.yaml, github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml, github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-periodics.yaml
A while ago the base branch for projects
* k8snetworkplumbingwg/kubemacpool
* kubevirt/cluster-network-addons-operator
* nmstate/kubernetes-nmstate
has been moved from `master` to `main`, which caused the flakefinder to not find any PRs any more.
This change updates the base branch flag `pr_base_branch` for above projects, so PRs can be found again.
Fixes #
FYI @RamLavi
=> fix(flakefinder): update pr_base_branch for jobs

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.0.yaml, github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.1.yaml, github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.2.yaml
Add presubmits for Oracle Linux and Debian for releases 1.0, 1.1 and 1.2
Fixes #
**Checklist**
```release-note
Added presubmits for Oracle Linux and Debian for releases 1.0, 1.1 and 1.2
```
=> chore(common-instancetypes): Add presubmits for Oracle Linux and Debian for releases 1.0, 1.1 and 1.2

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Moving this job over to the workloads cluster as it is one of the heavier jobs. Also it suffers from timeouts, probably related to resouce issues.
Fixes #4077
=> fix(kubevirt generate): move presubmit to workloads

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
Improved automation by enabling skip-review alike [kubevirt/project-infra/pull/3937](https://github.com/kubevirt/project-infra/pull/3937)
**Which issue(s) this PR fixes**
Fixes  [kubevirt/kubevirtci/issues/1389](https://github.com/kubevirt/kubevirtci/issues/1389)
@dhiller - saw your talk at KubeCon so taking your advice and getting involved.. albeit starting very small to find my feet, but eager to get involved with KubeVirt :)
=> skip-review: enable for automatic bump of CentOS Stream to latest

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
This job seems to be getting killed on PRs that are trying to increase the number of linters supported in project-infra.
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/4081/pull-project-infra-lint/1912396565205487616
Increase the memory request and limit for the job to ensure that it has enough resources
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> project-infra,lint: Bump memory resources used by the linting lane

Makefile
The GOLANGCI_LINT_VERSION env var is no longer required since the removal of the install of golangci-lint binary[1]
[1] https://github.com/kubevirt/project-infra/pull/4087
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> lint: Remove GOLANGCI_LINT_VERSION env var from Makefile

github/ci/prow-deploy/kustom/overlays/prow-workloads/resources/place-holder.yaml
Since the placeholder is currently requesting less memory than the SRIOV e2e jobs, a scheduled SRIOV job pod can lead to other test lane pods being deleted unexpectedly due to the higher priority that the SRIOV job has.
Update the place-holder memory request to match that of the SRIOV e2e jobs
https://github.com/kubevirt/project-infra/blob/355ba1d4fed242dd7223e5d2785056275cadd025/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml#L233
Fixes #
/cc @dhiller 
**Checklist**
This checklist is not enforcing, but it's a reminder of items …
=> sriov,place-holder: Update memory request to match the request of the SRIOV jobs

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
The current configuration is trying to call git-pr.sh with `-d`, pointing to not existing script. That causes failing of the job.
Fixing by removing the `-d` parameter and adding the `-R` to add release-notes of None in the PR description.
```release-note
Fix the periodic-kubevirtci-bump-kubevirt job
```
=> Fix the periodic-kubevirtci-bump-kubevirt job

github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
This PR fixes the nightly job
Fixes #
**Checklist**
```release-note
NONE
```
=> cnao: Fix nightly cluster name

github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
Moves nightly job to 2AM UTC
Fixes #
**Checklist**
```release-note
NONE
```
=> cnao, nightly: Move time of nightly job

images/bootstrap/Containerfile
Following the upgrade to F42, awk is no longer included in the image by default.
This causes a number of jobs to fail that rely on awk being available in the image[1]
Explicitly install gawk in bootstrap image to ensure it is included
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-performance-cluster-100-density-test/1917801303015165952#1:build-log.txt%3A55
Fixes #4138
/cc @dhiller 
**Checklist**
Approvers are expected to review this …
=> bootstrap: include awk in the bootstrap required by some jobs

robots/cmd/test-label-analyzer/cmd/stats.go
In a previous change the regexp was changed to using multiline string - this supports basically less verbose expressions since backslashes don't need to get escaped. However it was forgotten to remove the duplicate backslashes, thus the matching expression didn't work any more.
Fixes #4126
/cc @brianmcarey @anishbista60
=> fix: repair broken regexp for PermaLinks

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
It adds test lane for Fedora preferences
targeting the s390x architecture.
As of today, there are no test lanes for preferences on the s390x architecture in [kubevirt/common-instancetypes](https://github.com/kubevirt/common-instancetypes).
To get started, this PR adds a test lane for Fedora on s390x.
Fixes #
Please note that for now, the optional flag is set to true. Once the lane proves to be stable, we will remove the optional setting.
**Checklist**
Approvers …
=> common-instancetypes: Add tests lanes for fedora preferences s390x

github/ci/prow-deploy/files/jobs/kubevirt/application-aware-quota/application-aware-quota-postsubmits.yaml
Adapt to the changes introduced by the new scripts for building the image. Ensure that the builder image is only built when needed.
Adapt the CI lane to the changes of https://github.com/kubevirt/application-aware-quota/pull/135.
Fixes #
Needs to be merged before https://github.com/kubevirt/application-aware-quota/pull/135
**Checklist**
```release-note
NONE
```
=> aaq,builder: Ensure builder image is multi-arch

external-plugins/test-subset/plugin/handler/handler.go
In order to ease debugging.
Required for the debug logs of https://github.com/kubevirt/project-infra/pull/4044
Fixes #
**Checklist**
```release-note
None
```
=> test-subset: Increase log level

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
@sseago
* @mhenriks
* @ShellyKa13
* [Bump github.com/vmware-tanzu/velero from 1.14.0 to 1.16.0](https://github.com/kubevirt/kubevirt-velero-plugin/pull/355 )
* [Fix backup of CloudInit secrets](https://github.com/kubevirt/kubevirt-velero-plugin/pull/359)
* [Include VMI's datavolume type in restore graph](https://github.com/kubevirt/kubevirt-velero-plugin/pull/328)
=> Add Scott Seago (sseago) to kubevirt maintainers

github/ci/prow-deploy/files/jobs/kubevirt/application-aware-quota/application-aware-quota-postsubmits.yaml
Since the job requires emulation, it should be run on prow-workloads to ensure that it runs smoothly.
Follow up for https://github.com/kubevirt/project-infra/pull/4110#discussion_r2075753431
Fixes #
**Checklist**
```release-note
NONE
```
=> aaq,builder: Move job to prow-workloads for better performance

github/ci/prow-deploy/kustom/base/manifests/local/test-subset-deployment.yaml
Since we need both to be allowed to trigger the plugin, and prow jobs, update the secret to kubevirt-bot that have both.
Fixes #
**Checklist**
```release-note
None
```
=> test-subset: Fix secret

hack/contributions.sh
Improves the contributions script to emit the path of the detailed contributions report, as that is hidden in a temp file path and one would need to actually guess where it is.
Example:
```bash
$ ./hack/contributions.sh /home/dhiller/.tokens/github/kubevirt-bot/oauth --username dhiller
{"level":"info","msg":"creating report for user \"dhiller\"","time":"2025-05-07T10:03:19Z"}
activity log:
user:          dhiller
...
{"level":"debug","msg":"user activity log: \"/tmp/user-activity-dhiller-kubevirt-3277565534.yaml\"","time":"2025-05-07T10:03:27Z"}
Stored user activity report in /tmp/contributions-sm4oBV/user-activity-dhiller-kubevirt-3277565534.yaml
```
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, …
=> feat: show detailed report output file path

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
The k8s-1.33 based e2e lanes are soon to be enabled in kubevirt/kubevirt
Move the check-provision presubmit for k8s-1.33 to required to ensure
that the provider remains in good health.
The k8s-1.30 provider is going to be removed soon once the k8s-1.33
provider is introduced.
Remove the check-provision lane for k8s-1.30
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> kubevirtci,presubmit: Move the k8s-1.33 lane to required 

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
This job is trying to push PRs to the kubevirt repository, instead of to the hyperconverged-cluster-operator repository. see here for example: https://github.com/kubevirt/kubevirt/pull/14659
```release-note
Fix the periodic-kubevirtci-bump-hco job
```
=> Fix the periodic-kubevirtci-bump-hco job

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
=> Add the `release-note-none` label to the HCO kvci bump job

github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml, github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml, github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
…ontainer
This is related to https://groups.google.com/g/kubevirt-dev/c/gZCZQkcuKCU. This is in reference to feedback received from @dhiller https://github.com/kubevirt/project-infra/pull/4063#pullrequestreview-2804758188
```
Currently, KubeVirt VMs do not support IAM roles for service accounts when running on EKS clusters.
If you are using a service account as a filesystem with a KubeVirt VM, and that service account has the annotation [eks.amazonaws.com/role-arn](http://eks.amazonaws.com/role-arn), the IRSA mutates the virt-launcher pod of the VM with the following volume:
volumes:
- name: aws-iam-token
projected:
defaultMode: 420
sources:
- serviceAccountToken:
audience: [sts.amazonaws.com](http://sts.amazonaws.com/)
expirationSeconds: 86400 …
```
=> IRSA mutation webhook for injecting virtiofs container to virt-launcher pod

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.1.yaml, github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.2.yaml, github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.3.yaml, github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
It drops the following test jobs because the preferences are no longer available:
* pull-common-instancetypes-kubevirt-functest-centos-7-1.3
* pull-common-instancetypes-kubevirt-functest-centos-7-1.2
* pull-common-instancetypes-kubevirt-functest-centos-7
It adds the following test jobs, which have preferences available but, are not currently being tested:
* pull-common-instancetypes-kubevirt-functest-leap-1.2
* pull-common-instancetypes-kubevirt-functest-tumbleweed-1.2
* pull-common-instancetypes-kubevirt-functest-leap-1.1
* pull-common-instancetypes-kubevirt-functest-tumbleweed-1.1
Fixes # …
=> chore(common-instancetypes): Adjust CentOS 7 and OpenSuse test jobs

github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits-v0.47.yaml
This PR adds a presubmit job for the new kubemacpool stable branch `release-0.47`
Fixes #
**Checklist**
```release-note
NONE
```
=> kubemacpool: 0.47 stable branch presubmit

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
The job runs into timeouts frequently, so let's move it onto the workloads cluster.
Fixes #
=> fix(cluster): move push-kubevirt-main to workloads

github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.99.yaml
This PR sets presubmit job for new stable branch release-0.99
Fixes #
**Checklist**
```release-note
NONE
```
=> cnao: Add presubmit job for release-0.99 stable branch

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
The current auto generated PR description is crypt and not helpful.
This PR uses a script in HCO to generate the PR description, to make it readable and understandable.
```release-note
None
```
=> Add proper description for HCO's bump kubevirtci PRs

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml, github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
There was quite a mess related to GitHub teams that were allowed to manage different restricted labels via the Prow `label` plugin. Since those teams largely overlap it makes sense to merge them into one.
The result is now one team called `restricted-labels-kubevirt` that holds all the members of the previous teams.
Also some team members who have decided to step down from reviewer obligations have not been included in the new team, since it's unlikely that they will need to use those labels.
> [!NOTE]
> **After merging this PR will cause a short period of around 2 hours of friction, since the Prow config will very likely get into effect before the GitHub team changes are applied.**
In a later step the old teams will be removed.
**Which issue(s) …
=> chore(restricted_labels,gh teams): reorg & simplify

github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
We need (preliminary) maintainers for the charts repo.
My plan is to add the bare minimum to the repo (readme, codeowners) and start opening issues to discuss the implementation of the charts design doc: https://github.com/kubevirt/community/pull/224
And, obviously, to write the charts :)
The charts repo have been created recently: https://github.com/kubevirt/project-infra/pull/4093
I have added a new group for charts maintainers, I added @dhiller and myself but it doesn't need to be. Please let me know who should be in that list instead.
I added the repo to the release team, as for sure it's going to be related to them.
**Checklist**
Approvers are …
=> add maintainers for charts

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Recent executions failed with a timeout - as this is a required job let's move it to the workloads cluster to avoid it failing due to lack of resources.
https://search.ci.kubevirt.io/?search=Execution+took+20m&maxAge=336h&context=1&type=build-log&name=pull-kubevirt-code-lint&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
Fixes #
/cc @enp0s3
=> fix(code-lint): move job to workloads cluster

github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml, github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
/cc @vladikr 
/cc @xpivarc 
I think this was discussed a while ago but never followed through with, IMHO we don't need the release note plugin for this repo, it's already dropped from the PR template after all, so remove it.
Fixes #
**Checklist**
```release-note
NONE
```
=> chore(plugins): Remove release-note plugin from enhancements repo

hack/mirror-crio.sh
The location of the cri-o repos have changed[1] causing the mirror to fail[2] - update to match the latest path
[1] https://github.com/cri-o/packaging/commit/b1333931567703820da23ce2dd87954a4b95f7ef
[2] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirtci-mirror-crio-repository-weekly/1931870219546923008
Fixes #
/cc @xpivarc @iholder101 @dhiller 
**Checklist**
```release-note
```
=> cri-o,mirror: fix cri-o repo location to match latest

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.59.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.0.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.1.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.2.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.3.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.4.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.5.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml, github/ci/prow-deploy/kustom/overlays/prow-arm64-workloads/.gitignore, github/ci/prow-deploy/kustom/overlays/prow-arm64-workloads/kustomization.yaml
* add kustomize for secret for prow-arm64-workloads cluster
* revert commit that removed the arm lanes
* adjust cluster names to replace `...-2` with the current cluster name
Example runs:
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-kind-e2e-test-ARM64/1934632652430643200
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/14746/pull-kubevirt-e2e-arm64/1934638712851795968
Fixes #
=> feat(arm64): re-add arm lanes for new cluster

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
We are experiencing a lot less failures on the presubmit lane than on the periodic. A comparison of the lane configurations yielded a difference in the volume configurations - apparently the /sys/fs/cgroup hostpath mount was missing. This commit adds it.
Also the audit log mount is changed from empty dir to hostpath mount.
Fixes #
Example test run: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-kind-e2e-test-ARM64/1935322933262028800
=> fix(arm,periodic): missing cgroup host mount

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The pods on the new arm cluster are stuck in state Pending and Terminating
```
kubectl get pods -n kubevirt-prow-jobs
NAME                                   READY   STATUS        RESTARTS   AGE
01f33609-4a28-4730-b83c-dec324b34363   1/2     Terminating   0          25h
044f998c-9bef-4b29-b9d5-e30049f5d33c   0/2     Pending       0          4h53m
1267c1d0-7757-4152-bce0-0a6659f0dd2d   0/2     Pending       0          6h17m
21d77f2c-43cd-42c4-ac69-b566aec08bb3   1/2     NotReady      0          22h
231ad645-a8c5-4070-9399-f08b926e189e   0/2     Pending       0          13h
36c1b2ee-01b9-45df-9d13-e8da24a1c3a4   0/2     Pending       0          13h
3acabb4d-e4e8-4b9d-8a6d-e5e297878dd0   0/2     Pending       0          9h …
```
=> kubevirt,arm: Move ARM presubmits to always_run: false due to issue with cluster

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
We run the periodics as the other SIG jobs three times a day to get a baseline, also we reduce the maximum of concurrent jobs to 2 to avoid overloading the nodes.
Fixes #
Test run here: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/14994/pull-kubevirt-e2e-arm64/1937540913697918976
/cc @lyarwood
=> ci(jobs,arm): change periodic to 3xday, reduce concurrent runs

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
This job has been failing a lot lately due to hitting the timeout - increase timeout from 2 hours to 3 hours.
https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-org-github-config-updater
The job takes a long time to avoid rate limiting.
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> project-infra,presubmit: Increase timeout for github org config update presubmit

external-plugins/rehearse/plugin/handler/handler.go
The comment currently is not entirely correct. It neglects the recent changes due to the group of people being allowed to rehearse. Also the comment around how to use the plugin should be hidden in a details section, in order to reduce the visible size of the comment.
Fixes #https://github.com/kubevirt/project-infra/issues/3840
**Checklist**
```release-note
None
```
=> prow, rehearse: improvements to comment

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
https://github.com/kubevirt/kubevirt/pull/15030 introduces support for explicitly specifying the desire to deploy the dynamic-networks-controller in SIG-network`s lanes.
Add it to the relevant pre-submit and periodic jobs.
Fixes #
**Checklist**
```release-note
NONE
```
=> kubevirt, SIG-network: Specify KUBEVIRT_WITH_DYN_NET_CTRL

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
This lane is failing to reach a state to run the tests using the old legacy docker bootstrap
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/14967/pull-kubevirt-conformance-arm64/1941101895259000832
Update to use the podman bootstrap environment so that the tests will run
Fixes #
/cc @dhiller @lyarwood 
**Checklist**
```release-note
```
=> kubevirt,arm64: Update arm64 conformance to run using podman

github/ci/prow-deploy/hack/test.sh
Since the latest kubevirtci change [1] the job name is no longer part of the pod name.
[1]: https://github.com/kubevirt/kubevirtci/pull/1478/files
Fixes #
Rehearse run: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/4263/pull-project-infra-prow-deploy-test/1942880103373475840
=> fix(prow-deploy): remove podname modification on CI

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.5.yaml
This arm64 lanes are failing all of the time and are optional. 
https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-unit-test-arm64-1.5
Set always_run: false to stop running these lanes until a fix is in place
Fixes #
**Checklist**
```release-note
```
=> kubevirt,arm64: Stop running the arm64 presubmits on v1.5

robots/pkg/kubevirt/cmd/get/presubmits.go, robots/pkg/kubevirt/cmd/get/presubmits_test.go
Sorting is still broken
This PR fixes it.
Fixes #
**Checklist**
```release-note
```
=> fix(presubmits.html): sorting of k8s versions

github/ci/services/grafana/deploy/base/grafana.yaml
Adds another panel that shows the runtimes of the arch e2e test lanes to the e2e test runtimes dashboard.
Fixes #
**Checklist**
```release-note
```
=> obs(e2e,arch): add arch lanes to e2e runtimes

github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-periodics.yaml
This job utilizes the pipeline-periodic script while configuring environment variables to prevent image publication. The responsibility for publishing the images lies with the amd64 job.
```release-note
NONE
```
=> feat: add periodic job for containerdisks on s390x

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Following PR [1], this environment variable is no longer used.
Remove it from the presubmit and periodic lanes.
[1] https://github.com/kubevirt/kubevirt/pull/15286
Fixes #
**Checklist**
```release-note
NONE
```
=> KubeVirt, SIG-network: Remove unused KUBEVIRT_WITH_MULTUS_V3

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Add optional presubmit lane to help with testing new provider - https://github.com/kubevirt/kubevirtci/pull/1495
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> kubevirtci,presubmit: Add check provision job for upcoming k8s-1.34 provider

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
This lane is based on a beta provider and should not be required - set to optional.
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> kubevirt,presubmit: fix k8s-1.34 compute serial to be optional

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml, robots/cmd/per-test-execution/main.go
Main update:
* Determines the k8s version from the stable.txt and searches for an existing sig-compute-migrations lane, using the first found as basis for the report
Fixes:
* By accident the body is closed before even an attempt to read it has been made. Using a defer to close the body on returning from the func
Fixes #
=> feat(per-test-execution): determine k8s version for report

robots/cmd/perf-report-creator/main.go
Move the performance job tests up a directory level so results can be discovered by prow.
Related-to: https://github.com/kubevirt/kubevirt/pull/15345
**Checklist**
```release-note
NONE
```
=> Move perf results up a directory

github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.100.yaml
This PR is adding a new presubmit for the new stable branch `release-0.100`
Fixes #
**Checklist**
```release-note
NONE
```
=> cnao: Add presubmit for stable 0.100

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
The single node ARM cluster is no longer available - remove the liveness check.
https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/logs/periodic-project-infra-prow-arm-workloads-livez
Updating the check with the endpoint for the new ARM cluster also failed so removing the job for now to reduce noise.
Fixes #
/cc @dhiller @lyarwood @xpivarc 
**Checklist**
```release-note
```
=> arm: Disable failing liveness check for old ARM cluster

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
This PR also removes the check-kind-1.31 presubmit as the kind-1.31 is no longer used on any of the main branches.
```
:~/workspace/project-infra$ grep -lr kind-1.31 ./*
./config/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.6.yaml
./github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.6.yaml
./jobs/kubevirt/kubevirt/kubevirt-presubmits-1.6.yaml
```
Fixes #
/cc @xpivarc @lyarwood 
**Checklist** …
=> kubevirtci,presubmits: Require the kind presubmits to pass when the kind providers are changed

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.4.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.5.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.6.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
There is a DNS issue with the s390x cluster - move the unit test jobs to optional until this issue is resolved.
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/15488/pull-kubevirt-unit-test-s390x/1960586672219361280
Fixes #
/cc @dhiller @jschintag 
**Checklist**
```release-note
```
=> kubevirt,s390x: Temporarily move s390x unit test jobs to optional due to DNS issue

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
It adds a new test job for Debian 13.
Fixes # [CNV-68033](https://issues.redhat.com/browse/CNV-68033)
**Checklist**
```release-note
None.
```
=> chore(common-instancetypes): Add test job for Debian 13

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
We can save some CI resources and time.
the job should run only when hack/prom-rule-ci/* has changed this make target is related to unit tests of prometheus alerts and recording rules. The tests themselves reside in prom-rule-ci directory so there is no point to run this target unless the tests of the image were changed.
```release-note
NONE
```
=> [kubevirt/kubevirt]: make prom-rule-verify run conditional

github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.0.yaml, github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.1.yaml, github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.2.yaml, github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.3.yaml, github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.4.yaml
It enables Debian 13 testing jobs in releases:
* release-1.0
* release-1.1
* release-1.2
* release-1.3
* release-1.4
Fixes # [CNV-68033](https://issues.redhat.com/browse/CNV-68033)
**Checklist**
```release-note
None
```
=> chore(common-instancetypes): Add Debian 13 test jobs to releases

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
A new arm64 cluster has been provided - update these arm64 lanes to not always run to reduce noise on PRs until new cluster is integrated.
Fixes #
/cc @lyarwood @dhiller 
**Checklist**
```release-note
```
=> arm64,kubevirt: move lanes to always run false due to cluster change

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.13.yaml
k8s-provider of 1.30 has been removed in [PR 4239](https://github.com/kubevirt/project-infra/pull/4239), but release-1.13 branch in HCO still uses 1.30, causing a permanent failure. Update this lane to 1.31 to unblock this job in HCO CI.
Example of affected PR: https://github.com/kubevirt/hyperconverged-cluster-operator/pull/3750
Fixes #
**Checklist**
```release-note
NONE
```
=> HCO 1.13: Update k8s provider from 1.30 to 1.31

github/ci/prow-deploy/files/jobs/nmstate/nmstate/nmstate-presubmits.yaml
The rust compiler for nmstate takes more than 4G RAM. Hence request 16G
RAM for its tests.
=> Request 16G RAM for nmstate tests

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml, hack/bump-crio-mirror-versions.sh
Update the bump cri-o script to also update kubevirtci if its present in the environment
This should remove the need for these PRs: https://github.com/kubevirt/kubevirtci/pull/1534
Fixes #
**Checklist**
```release-note
```
=> crio,kubevirtci: automate the cri-o version bumps for the latest kubevirtci provider

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.6.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml, robots/pkg/kubevirt/cmd/require/presubmits.go
This change makes the 1.34 sig jobs required.
For a while now we also require sig-compute-serial for the latest k8s
version, which is now added to the code base.
Fixes #
/cc @brianmcarey @jean-edouard @fossedihelm 
/hold to wait until the backport for the operator flakes is merged.
=> chore(require-presubmits): make 1.34 sig jobs required

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
Dry run was enabled while creating the PR, disabled it .
Fixes #
**Checklist**
```release-note
None
```
=> Disable dry run and create a performance benchmarks PR

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Adds the INVOKE_FUNCTEST_ONCE environment variable to the
check-tests-for-flakes and dequarantine-test presubmit jobs.
This enables the new ginkgo --repeat functionality for faster test reruns.
=> feat: enable INVOKE_FUNCTEST_ONCE for flake checks

external-plugins/rehearse/plugin/handler/handler.go
Currently whenever the rehearse plugin comments on the PR the instructions section is added, however that section is quite big and that bloats the comment.
This change puts the instructions on how to trigger rehearsals into a GitHub style collapsed details section, so the comment is less chatty.
See https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections for details
Fixes #
=> feat(rehearse): collapse instructions

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Remove superfluous `--`, probably missed when moving job from bazel to pure go.
Fixes job failure: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-presubmit-requirer/1973191231248797696
Fixes #
=> fix(presubmit-requirer): remove superfluous double-dash

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml, github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
While trying to upgrade to go v1.24.7 - issues were hit due to inconsistencies between the builder and the bootstrap.
https://github.com/kubevirt/kubevirt/pull/15784#issuecomment-3351889264
Fixes #
**Checklist**
```release-note
```
=> kubevirt: Run jobs nested to use a consistent builder image

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Fixes #
/cc @dhiller 
**Checklist**
```release-note
```
=> kubevirt,presubmit: request cpu resources for the unit test presubmit
