github/ci/jenkins-master/templates/04-jobs.groovy

Enable concurrent builds

---

github/ci/jenkins-deps/tasks/main.yml

Install hg on all nodes

---

github/ci/jenkins-master/templates/02-security.groovy
github/ci/jenkins-slave/tasks/main.yml

Update Jenkins security configuration to latest recommendations

---

github/ci/jenkins-deps/tasks/main.yml

Make sure the jenkins user has docker at its disposal

Install docker on all nodes

---

github/ci/jenkins-slave/tasks/main.yml

Update docker swarm plugin

---

github/ci/jenkins-master/tasks/main.yml
github/ci/jenkins-slave/tasks/main.yml

Enable nested virtualization and make sure that the swarm jnlp port is

---

github/ci/jenkins-master/templates/01-plugins.groovy
github/ci/jenkins-master/templates/04-jobs.groovy

- xunit
- test-results-analyzer
Signed-off-by: Lukianov Artyom <alukiano@redhat.com>

Add jenkins plugins for test analysis

---

github/ci/jenkins-master/defaults/main.yml

Signed-off-by: Lukianov Artyom <alukiano@redhat.com>

Add OpenShift with CRIO job

---

github/ci/beaker/tasks/main.yaml
github/ci/jenkins-master/defaults/main.yml

- add new target
- get rid of vagrant word under our targets
- change soft and hard limits on beaker hosts
Signed-off-by: Lukianov Artyom <alukiano@redhat.com>

Add k8s-1.10.3 job

---

github/ci/jenkins-slave/tasks/main.yml

Permanently enable nested virtualization

---

github/ci/jenkins-master/templates/04-jobs.groovy

I would like to have the permissions since apparently I need them to trigger CI.

Make Ihar Hrachyshka (booxter) a github admin

---

github/ci/README.md
github/ci/decrypt.sh
github/ci/encrypt.sh

@cynepco3hahue @slintes if you know of a better way let me know.

Add script for sharing secrets

---

github/ci/jenkins-master/defaults/main.yml

Add os-3.10 job

---

github/ci/jenkins-master/templates/04-jobs.groovy

Allow the same job to run in parallel on a node

---

github/ci/jenkins-master/templates/04-jobs.groovy

Fix target check for windows job

---

github/ci/README.md
github/ci/prow/tasks/main.yml
github/ci/prow/templates/admin-rbac.yaml

Make sure that admins get permission to prow.

Add "prowAdmins" variable

---

github/ci/prow/files/plugins.yaml

Add containerized-data-importer to plugins.yaml

---

github/ci/prow/files/labels.yaml
github/ci/prow/templates/label-sync.yaml

Add lifecycle labels and prepare labels.yaml for multi-repo usage.

Add Lifecycle labels and prepoare for multi-repo use

---

github/ci/prow/files/plugins.yaml

Enable life cycle plugin.

---

github/ci/prow/templates/cherrypicker_deployment.yaml
github/ci/prow/templates/deck-deployment.yaml
github/ci/prow/templates/hook.yaml
github/ci/prow/templates/horologium-deployment.yaml
github/ci/prow/templates/needs-rebase_deployment.yaml
github/ci/prow/templates/plank-deployment.yaml
github/ci/prow/templates/sinker-deployment.yaml
github/ci/prow/templates/statusreconciler-deployment.yaml
github/ci/prow/templates/tide-deployment.yaml

Spyglass has now almost feature parity with gubernator.
Highilghts are:
* Improved junit test results
* Artifact links

Update prow to get new spyglass features

---

github/ci/prow/files/jobs/kubevirtci/kubevirtci-presets.yaml
github/ci/prow/tasks/main.yml

Allow referencing docker credentials in a build job for pushing via
prow.

Add docker credentials secret and preset

---

github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml

Add a job which can push and build k8s-genie-1.11.1.

Add presubmit job for kubevirtci which can push to docker hub

---

github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml

I think we should provide some test script under kubevirtci repository.

Add presubmit jobs for the provider k8s-1.13.3

---

github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml

Add a push job for k8s-1.13.3-multus which we forgot to add.

Add push job for k8s-1.13.3-multus

---

github/ci/prow/tasks/main.yml
github/ci/prow/templates/deck-rbac.yaml
github/ci/prow/templates/hook-rbac.yaml
github/ci/prow/templates/horologium-rbac.yaml
github/ci/prow/templates/plank-rbac.yaml
github/ci/prow/templates/sinker-rbac.yaml
github/ci/prow/templates/statusreconciler-rbac.yaml
github/ci/prow/templates/tide-rbac.yaml

The state here is applied to the cluster and first jobs are succeeding: https://deck-kubevirt-prow.apps.ovirt.org/

Separate namespace final fixes

---

github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml

- Reordered jobs to have check-provision and push jobs together for each cluster
- Added push jobs for os-3.11.0 / -crio / -multus

updated kubevirtci prow jobs

---

github/ci/prow/files/docker-daemon-mirror.conf

There seem to be pip issues regarding to refragment requests.

Set MTU to 1450 for DIND

---

github/ci/prow/files/config.yaml
github/ci/prow/files/jobs/kubevirt.github.io/kubevirt-github-io-periodics.yaml
github/ci/prow/files/jobs/kubevirt.github.io/kubevirt-github-io-presubmits.yaml
github/ci/prow/files/labels.yaml
github/ci/prow/files/plugins.yaml

* Enable specific config for community repos
* Added 3 jobs periodic/postsubmit/presubmit on kubevirt.github.io folder

Feat: Added jobs and config to manage kubevirt.github.io repo

---

github/ci/prow/files/jobs/kubevirt.github.io/kubevirt-github-io-periodics.yaml
github/ci/prow/files/jobs/kubevirt.github.io/kubevirt-github-io-presubmits.yaml

Otherwise we may be scheduled on bad nodes.

Limit jobs to primary region

---

github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml
github/ci/prow/templates/greenhouse-deployment.yaml
github/ci/prow/templates/mirror.yaml

* migrate greenhouse and docker mirror to new nodes
* trigger kubevirt/kubevirt jobs on new nodes only
/hold

Move kubevirt/kubevirt to new nodes

---

github/ci/prow/files/config.yaml
github/ci/prow/files/plugins.yaml

- Allowed automerge by squash method
- Added some plugins in order to start testing soon:
- config-updater
- skip
- override
- trigger

Feat: Added plugins on cloud-image-builder config

---

github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml

A lot of tests go added. The timeout needs to be increased.

Increate test timeout for kubevirt functests

---

github/ci/prow/files/config.yaml
github/ci/prow/files/jobs/project-infra/project-infra-presubmits.yaml
github/ci/prow/templates/deck-deployment.yaml
github/ci/prow/templates/ghproxy.yaml
github/ci/prow/templates/hook.yaml
github/ci/prow/templates/horologium-deployment.yaml
github/ci/prow/templates/needs-rebase_deployment.yaml
github/ci/prow/templates/plank-deployment.yaml
github/ci/prow/templates/sinker-deployment.yaml
github/ci/prow/templates/statusreconciler-deployment.yaml
github/ci/prow/templates/tide-deployment.yaml

Includes the annotation inheritance from prow jobs to pods.

Bump from v20190523-832050b39 to v20190703-132f32f32

---

limiter/limiter.go

From time to time we get events from the billing account, although we
did configure high limits until when we want to get notifications. Do
the check if the limits are exceeded, to avoid making the buckets
non-private when not necessary.

Actually check if limit really is exceeded

---

github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml

Things are still too flaky to let tide do everything for us.

Make all jobs mandatory again

---

github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml

tested on https://prow.apps.ovirt.org/?repo=kubevirt%2Fkubevirtci&pull=120

Added kubevirtci base and centos7 presubmit jobs

---

github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml

Add a new version of OKD to prow
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/project-infra/145)

Add the okd 4.1.2 provider to prow

---

github/ci/prow/files/jobs/kubevirt-tutorial/OWNERS
github/ci/prow/files/jobs/kubevirt.github.io/OWNERS

Added OWNERS on (same on both):
- kubevirt-tutorial related jobs
- kubevirt.github.io related jobs

Feat: Added OWNERS per job folder in order to manage just those jobs

---

github/ci/prow/files/jobs/virtblocks/virtblocks/OWNERS
github/ci/prow/files/jobs/virtblocks/virtblocks/virtblocks-periodics.yaml
github/ci/prow/files/plugins.yaml

Basic trigger plugin setup and fist presubmit jobs. @andreabolognani is added as approver, so that his team can modify the job definitions if they wish.

Enable CI integration for Virtblocks

---

github/ci/prow/files/jobs/project-infra/project-infra-presubmits.yaml

test flakefinder job
/assign @slintes

Create presubmit job for flakefinder for testing

---

github/ci/prow/files/jobs/project-infra/project-infra-presubmits.yaml

/assign @slintes 
Removed `command` from job spec, as image has an entry point

Remove command from job spec

---

github/ci/prow/files/jobs/project-infra/project-infra-presubmits.yaml

I guess the bad yaml formattting made the job not run :-(
/cc @slintes

Correct yaml formatting

---

github/ci/prow/files/jobs/project-infra/project-infra-presubmits.yaml

Flakefinder job

---

github/ci/prow/files/jobs/project-infra/project-infra-presubmits.yaml

Add gcs credentials to arg list

---

github/ci/prow/files/jobs/project-infra/project-infra-presubmits.yaml

Set gcs credentials as environment variable

---

github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml

- increased timeout, especially the okd lane runs into timeouts
- disabled k8s-1.11.0
- enabled k8s-1.15.1-ceph

timeout, k8s 1.15

---

github/ci/prow/files/jobs/virtblocks/virtblocks/virtblocks-periodics.yaml

Hopefully the last change needed for a while :)

Virt Blocks: Use newer container image

---

robots/flakefinder/README.md

- list formatting
- build howto
- test howto

Fix README issues

---

github/ci/prow/files/jobs/kubevirt/kubevirt-periodics.yaml
robots/flakefinder/main.go
robots/flakefinder/report.go
robots/flakefinder/report_test.go

Numbers are now colorized (green for passed, red for failed and grey for skipped tests)

Minor improvements for report

---

github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml

Add 1.14.6 to kubevirtci-presubmits

---

github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml

Create new test lane for k8s-1.14.6

---

github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml

- remove k8s-1.11
- make k8s-1.13 optional
- make k8s-1.14 mandatory
/cc @slintes

CI lane cleanup after k8s-1.14 addition

---

github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml

Required for okd-4.2, working on it at kubevirt/kubevirtci#150

create okd-4.2 provisioning jobs

---

github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml

This PR add the k8s multus 1.15.1 provider
Signed-off-by: Sebastian Sch <sebassch@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/project-infra/193)

Add build push and test for k8s multus 1.15.1

---

github/ci/prow/files/jobs/project-infra/project-infra-presubmits.yaml
limiter/limiter_test.go

Add a simple test lane that executes the go tests.

Add test job for flakefinder

---

github/ci/prow/files/jobs/project-infra/project-infra-presubmits.yaml

Disable go cache

---

github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml

Preparation to execute okd-4.2, see kubevirt/kubevirt#2770 for details.

Add okd-4.2

---

github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml

This PR create two prow jobs.
1. build the okd network 4.1 provider
2. push the okd network 4.1 provider to dockerhub
Signed-off-by: Sebastian Sch <sebassch@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/project-infra/215)

Create a okd network 4.1 provider build and deploy jobs

---

github/ci/prow/files/jobs/kubevirt/kubevirt-periodics.yaml

Changes the execution interval from weekly to daily.
/cc @rmohr

Make flakefinder weekly report execute daily

---

github/ci/prow/tasks/main.yml
github/ci/prow/templates/accounts.yaml
github/ci/prow/templates/exporter-deployment.yaml
github/ci/prow/templates/exporter-rbac.yaml

Allow us to track runtimes, queue times, and so on.

Add ProwJob Metrics exporter

---

github/ci/prow/files/jobs/kubevirt.github.io/kubevirt-github-io-periodics.yaml

Feat: Changed the way of periodic execution is done based on PR #366 from kubevirt.github.io repo
https://github.com/kubevirt/kubevirt.github.io/pull/366

Changing periodic Jobs for Kubevirt.github.io

---

github/ci/prow/files/jobs/kubevirt-tutorial/kubevirt-tutorial-periodics.yaml
github/ci/prow/files/jobs/kubevirt-tutorial/kubevirt-tutorial-presubmits.yaml

Signed-off-by: Pablo Iranzo Gómez <Pablo.Iranzo@gmail.com>

Use latest image on KubeVirt tutorial tests

---

github/ci/prow/files/config.yaml
github/ci/prow/files/jobs/containerized-data-importer/containerized-data-importer-presubmits.yaml

Make CDI jobs required on the CDI repo

---

github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml

Always run the OKD 4.1 job

---

github/ci/prow/files/config.yaml

Protect master branch, add check for travis-ci and (implicit) dco.
Closes #234
/cc @awels

Add branch protection for hostpath-provisoner

---

github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml

Add jobs for okd-4.3 provider

---

github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml

/cc @rmohr @fromanirh @slintes 

Disable okd-4.1 lane

---

github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml

Add cluster-provision and push for k8s-1.16.2

---

github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits-0.23.yaml
github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml

Added jobs for release 0.23

---

github/ci/prow/files/config.yaml
github/ci/prow/files/jobs/hostpath-provisioner/OWNERS
github/ci/prow/files/jobs/hostpath-provisioner/hostpath-provisioner-presubmits.yaml
github/ci/prow/files/plugins.yaml

Prepare PROW for hostpath provisioner

---

github/ci/prow/files/jobs/hostpath-provisioner/hostpath-provisioner-presubmits.yaml

Fix call to the cluster up script for hostpath provisioner.

---

github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml

Fix duplicate `annotations` key in
pull-kubevirt-e2e-kind-k8s-sriov-1.14.2 test lane.

Add pull-kubevirt-e2e-k8s-1.16.2 test lane.

---

github/ci/prow/files/config.yaml
github/ci/prow/files/labels.yaml
github/ci/prow/files/plugins.yaml

Add Katacoda-Scenarios for tide

Add Katacoda-Scenarios for tide

---

github/ci/prow/files/jobs/kubevirt/kubevirt-periodics.yaml
robots/flakefinder/main.go
robots/flakefinder/report.go
robots/flakefinder/report_test.go

Instead of using the PR number the PR id was used. This fixes the issue.

Fix source PR numbers

---

github/ci/prow/files/jobs/common-templates/OWNERS
github/ci/prow/files/jobs/common-templates/common-templates-presubmits.yaml
github/ci/prow/files/plugins.yaml

add kubevirt/common-templates under prow
Signed-off-by: Karel Šimon <ksimon@redhat.com>

add kubevirt/common-templates under prow

---

github/ci/prow/files/config.yaml
github/ci/prow/files/labels.yaml
github/ci/prow/files/plugins.yaml

Add kubevirt/demo under prow control

Add kubevirt/demo under prow control

---

github/ci/prow/files/jobs/containerized-data-importer/containerized-data-importer-presubmits.yaml

Add optional k8s-1.16.2 lane for CDI

---

github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml

Add OKD 4.2 jobs

---

github/ci/prow/files/jobs/project-infra/project-infra-postsubmits.yaml
github/ci/prow/files/jobs/project-infra/project-infra-presubmits.yaml
images/kubevirt-infra-bootstrap/Dockerfile
images/publish_image.sh

Some of our components need extra packages installed in
our test container. This PR adds a Dockerfile for this
container as well as Prow jobs to build and publish it.

Add custom kubevirt-infra boostrap image build and publish

---

github/ci/prow/files/jobs/containerized-data-importer/containerized-data-importer-presubmits.yaml

Make 1.16.2 lane required for CDI

---

github/ci/prow/files/jobs/common-templates/common-templates-presubmits.yaml

change of base image
tests will now always run
Signed-off-by: Karel Šimon <ksimon@redhat.com>

update name of common-templates tests

---

github/ci/prow/files/config.yaml
github/ci/prow/files/jobs/nmstate/OWNERS
github/ci/prow/files/jobs/nmstate/kubernetes-nmstate-presubmits.yaml
github/ci/prow/files/plugins.yaml

Add jobs for nmstate/kubernetes-nmstate

---

github/ci/prow/files/config.yaml
github/ci/prow/files/labels.yaml
github/ci/prow/files/plugins.yaml

Config for tide, branch protection, lgtm, approve
See also kubevirt/kubectl-virt-plugin#11

Add configuration for kubectl-virt-plugin repo

---

github/ci/prow/files/config.yaml
github/ci/prow/files/jobs/ovs-cni/OWNERS
github/ci/prow/files/jobs/ovs-cni/ovs-cni-presubmits.yaml
github/ci/prow/files/plugins.yaml

Add Prow jobs for ovs-cni

---

github/ci/prow/files/config.yaml
github/ci/prow/files/jobs/cluster-network-addons-operator/OWNERS
github/ci/prow/files/jobs/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
github/ci/prow/files/plugins.yaml

Add Prow Jobs for cluster-network-addons-operator

---

github/ci/prow/files/jobs/containerized-data-importer/containerized-data-importer-presubmits.yaml

Add optional k8s 1.16 hostpath provisioner lane

---

github/ci/prow/files/config.yaml
github/ci/prow/files/plugins.yaml

Enable tide queries for kubernetes-nmstate

---

github/ci/prow/files/jobs/kubevirtci/kubevirtci-presets.yaml
github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml

Add check-provision/push ocp-4.3 jobs

---

github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml

Use cat instead of < for quay user

---

github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml

Add provisioning for k8s 1.17

---

github/ci/prow/files/config.yaml
github/ci/prow/files/jobs/bridge-maker/OWNERS
github/ci/prow/files/jobs/bridge-maker/bridge-maker-presubmits.yaml
github/ci/prow/files/plugins.yaml

Add Prow jobs for kubevirt/bridge-maker

---

github/ci/prow/tasks/main.yml

Deploy quay.io bot credentials

---

github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml

Add check-up jobs for okd/ocp

---

github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml

Add check-up-ocp-4.3

---

github/ci/prow/files/jobs/containerized-data-importer/containerized-data-importer-presubmits.yaml

Add CDI OKD 4.3 lane with hpp.

---

images/kubevirt-infra-bootstrap/Dockerfile

slave-image: Add pkgs required by node-maintenance-operator

---

OWNERS

Since I'm going to help maintain this repo, adding myself
to the OWNERS file.

Add gbenhaim to the OWNERS file

---

github/ci/prow/files/config.yaml
github/ci/prow/files/jobs/node-maintenance-operator/OWNERS
github/ci/prow/files/jobs/node-maintenance-operator/node-maintenance-operator-presubmits.yaml
github/ci/prow/files/plugins.yaml

Adding jobs for node-maintenance-operator

---

github/ci/prow/files/jobs/node-maintenance-operator/node-maintenance-operator-presubmits.yaml

node-maintenance-operator: enable k8s jobs

---

github/ci/prow/files/config.yaml
github/ci/prow/files/jobs/ansible-kubevirt-modules/OWNERS
github/ci/prow/files/jobs/ansible-kubevirt-modules/ansible-kubevirt-modules-presubmits.yaml
github/ci/prow/files/plugins.yaml

Add jobs for ansible-kubevirt-modules

---

github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml

Until we can resolve the issues we see in this lane,
we should not block PRs from being merged.

Make sriov lane optional

---

github/ci/prow/files/jobs/nmstate/kubernetes-nmstate-presubmits.yaml

Add knmstate unit/test job

---

github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml

Until we sort the issues with this lane, we don't want to block the
progress of unrelated PRs.

Disable auto-run for the sr-iov lane

---

github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml

Allow testing https://github.com/kubevirt/kubevirt/pull/2950

Add optional ocp-4.3 lane to kubevirt

---

github/ci/prow/files/jobs/nmstate/kubernetes-nmstate-postsubmits.yaml

Add knmstate job to publish after master merge

---

github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits-0.24.yaml

Jobs for kubevirt/kubevirt release-0.24.

Fork release-0.24 jobs

---

github/ci/prow/files/jobs/nmstate/kubernetes-nmstate-postsubmits.yaml

It will run `make release` at merged PR that changes
version/version.go

Add a release job for kubernetes-nmstate

---

github/ci/prow/files/jobs/containerized-data-importer/containerized-data-importer-presubmits.yaml

enable optional 1.17 host path provisioner lane for CDI

---

github/ci/prow/files/jobs/nmstate/kubernetes-nmstate-periodics.yaml

Add kubernetes-nmstate flakefinder

---

github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml

Increase ocp-4.3 provision jobs timeout

---

github/ci/prow/files/config.yaml

Add nmstate/kubernetes-nmstate branch protection

---

github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml

Duplicate memory for ocp-4.3 jobs

---

github/ci/prow/files/jobs/nmstate/kubernetes-nmstate-presubmits.yaml

Disable knmstate OKD lane

---

github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml

Add ocp-4.4 jobs

---

OWNERS

We'd like to contribute more to the maintenance and improvents in our
automation. Having rights to merge PRs would make it much easier.

add qinqon and phoracek to OWNERS

---

github/ci/prow/files/jobs/containerized-data-importer/containerized-data-importer-presubmits.yaml

Make the multi upgrade lane required and automatic.

---

github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml

Add k8s kind jobs

---

github/ci/prow/files/jobs/containerized-data-importer/containerized-data-importer-presubmits.yaml

Add optional NFS storage lane for CDI

---

CONTRIBUTING.md
README.md

See kubevirt/project-infra#201
/cc @qinqon @oshoval

Initial CONTRIBUTING guide

---

github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml

Add jobs for ocp-cnao-4.4 provider

---

github/ci/prow/files/jobs/containerized-data-importer/containerized-data-importer-presubmits.yaml

Make NFS CDI lane required.

---

github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml

Skip reporting to GitHub for k8s-1.17 lane

---

github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml

Meh sorry for another PR :)
/cc @rmohr @qinqon

Enable always_run for k8s-1.17

---

github/ci/prow/files/config.yaml
github/ci/prow/files/jobs/project-infra/project-infra-periodics.yaml
github/ci/prow/files/jobs/project-infra/project-infra-presubmits.yaml
github/ci/prow/files/plugins.yaml
github/ci/prow/templates/branch-protector.yaml
github/ci/prow/templates/cherrypicker_deployment.yaml
github/ci/prow/templates/deck-deployment.yaml
github/ci/prow/templates/exporter-deployment.yaml
github/ci/prow/templates/ghproxy.yaml
github/ci/prow/templates/hook.yaml
github/ci/prow/templates/horologium-deployment.yaml
github/ci/prow/templates/needs-rebase_deployment.yaml
github/ci/prow/templates/plank-deployment.yaml
github/ci/prow/templates/sinker-deployment.yaml
github/ci/prow/templates/statusreconciler-deployment.yaml
github/ci/prow/templates/tide-deployment.yaml

Bump prow to v20200204-7e8cd997a

---

github/ci/prow/templates/plank-rbac.yaml

Plank now also patches prow jobs.

Adjust plank RBAC permissions

---

github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml

Add test lane for flake check

---

github/ci/prow/files/jobs/nmstate/kubernetes-nmstate-presubmits.yaml

knmstate: Set ocp lane as required

---

github/ci/prow/files/jobs/common-templates/common-templates-presubmits.yaml

Signed-off-by: Karel Simon <ksimon@redhat.com>

common-templates: always run win 2019 test

---

github/ci/prow/files/jobs/nmstate/kubernetes-nmstate-presubmits.yaml

knmstate: make ocp optional

---

github/ci/prow/templates/tide-rbac.yaml

Tide now uses the list/watch pattern.

Fix tide rbac roles

---

github/ci/prow/templates/deck-rbac.yaml

Deck uses now list/watch patterns

---

github/ci/prow/files/jobs/nmstate/kubernetes-nmstate-presubmits.yaml

knmstate: Disable ocp lane

---

github/ci/prow/files/config.yaml
github/ci/prow/files/jobs/hyperconverged-cluster-operator/OWNERS
github/ci/prow/files/jobs/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
github/ci/prow/files/plugins.yaml

Add jobs for the HCO

---

github/ci/prow/files/jobs/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml

The lane works, we can make it mandatory.

hco: Make ocp lane mandatory

---

github/ci/prow/files/jobs/nmstate/kubernetes-nmstate-postsubmits.yaml

knmstate: Use correct github oauth token

---

github/ci/prow/files/jobs/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-2.3.yaml

hco: Add jobs for 2.3 release branch

---

github/ci/prow/files/config.yaml

Move notifications from kubevirt tutorial to #EKO team

Notification of kubevirt-tutorial to EKO slack

---

github/ci/prow/files/config.yaml
github/ci/prow/files/jobs/nmstate/kubernetes-nmstate-presubmits-0.15.yaml
github/ci/prow/files/plugins.yaml

We branched out, let's keep testing.

add presubmit for knmstate 0.15

---

github/ci/prow/files/config.yaml
github/ci/prow/files/jobs/k8snetworkplumbingwg/OWNERS
github/ci/prow/files/jobs/k8snetworkplumbingwg/kubemacpool-presubmits.yaml
github/ci/prow/files/plugins.yaml

Let's start with unit and e2e tests. Releasing will be added later.

integrate kubemacpool

---

github/ci/prow/files/config.yaml
github/ci/prow/files/jobs/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.27.yaml

add presumbits for cnao 0.27 branch

---

github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml

kubevirtci: Remove pre 1.13 k8s jobs

---

github/ci/prow/files/jobs/nmstate/kubernetes-nmstate-presubmits.yaml

knmstate: Run k8s lane on VM

---

github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml

This PR add  check-up job for kind-sriov 1.14.2 provider

Add check-up job for kind-k8s-sriov-1.14.2 provider

---

github/ci/prow/files/jobs/nmstate/kubernetes-nmstate-presubmits.yaml

knmstate: k8s remove mem req

---

github/ci/prow/files/jobs/nmstate/kubernetes-nmstate-presubmits.yaml

knmstate: k8s Go back to type bare-metal aka Packet

---

github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml

Change kubevirtci provision jobs for k8s according to the needs of https://github.com/kubevirt/kubevirtci/pull/289

Adjust k8s provision jobs to simplified layout

---

github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits-0.26.yaml

Fork CI config for kubevirt release-0.26

---

github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml

Reverts kubevirt/project-infra#363

Revert "Adjust kubevirt jobs to the simplified provision layout"

---

github/ci/prow/files/jobs/containerized-data-importer/containerized-data-importer-presubmits.yaml

Make 1.17 provider mandatory, and always run

Remove k8s1.15 provider

---

github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml

kubevirtci: Add centos8 jobs

---

github/ci/prow/files/jobs/node-maintenance-operator/node-maintenance-operator-presubmits.yaml

Add 4.3 jobs to NMO

---

github/ci/prow/files/jobs/node-maintenance-operator/node-maintenance-operator-presubmits.yaml

The test image that we used doesn't have Pyyaml, we need to fix it.

NMO 4.3 update the test image

---

github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml

kubevirt: Add ipv6 lane

---

github/ci/prow/files/jobs/macvtap-cni/macvtap-cni-postsubmits.yaml

Signed-off-by: Miguel Duarte Barroso <mdbarroso@redhat.com>

Add macvtap-cni postsubmit jobs

---

github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml

Adjust kubevirt jobs to the simplified provision layout

---

github/ci/prow/files/jobs/containerized-data-importer/containerized-data-importer-presubmits.yaml

Add new ember ci lane.

---

github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits-0.26.yaml

Backport ipv6 lane to 0.26

---

github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml

kubevirt: Add cnao k8s 1.17 lane.

---

github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml

Enable reporting for test flake check

---

github/ci/prow/files/jobs/containerized-data-importer/containerized-data-importer-presubmits.yaml

Increase timeouts for certain CDI lanes so they don't fail.

---

github/ci/prow/files/labels.yaml
github/ci/prow/files/plugins.yaml

Add labels support to kubernetes-nmstate project

---

github/ci/prow/files/labels.yaml
github/ci/prow/templates/label-sync.yaml

Map the current knmstate labels to prow

---

github/ci/prow/files/labels.yaml

knmstate: Remove duplicated labels

---

github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml

Disabling the testing against it.

Kubernetes 1.14 is EOL

---

github/ci/prow/files/jobs/hyperconverged-cluster-operator/hyperconverged-cluster-operator-postsubmits.yaml

Build and push HCO test utils image

---

github/ci/prow/files/jobs/vm-import-operator/vm-import-operator-periodics.yaml

Use docker login in vm-import-operator job

---

github/ci/prow/files/jobs/vm-import-operator/vm-import-operator-periodics.yaml

Use bash instead of sh in vm-import-operator

---

github/ci/prow/files/jobs/hyperconverged-cluster-operator/OWNERS
github/ci/prow/files/jobs/hyperconverged-cluster-operator/hyperconverged-cluster-operator-postsubmits.yaml

Add github token to HCO to be able to call github API

---

github/ci/prow/files/jobs/nmstate/kubernetes-nmstate-presubmits.yaml

Add new operator e2e jobs and rename existing jobs as handler jobs.
Signed-off-by: Brad P. Crochet <brad@redhat.com>

knmstate: Operator e2e jobs

---

github/ci/prow/files/jobs/vm-import-operator/vm-import-operator-periodics.yaml

Preset docker creds for vm-import-operator

---

github/ci/prow/files/jobs/vm-import-operator/vm-import-operator-periodics.yaml

Preset quay creds for vm-import-operator

---

github/ci/prow/files/jobs/containerized-data-importer/containerized-data-importer-presubmits.yaml

Updated kubevirtci in CDI repo so have to change this for functional tests to work

Adjust target names for updated kubevirtci

---

github/ci/prow/files/jobs/vm-import-operator/vm-import-operator-postsubmits.yaml

This job will run per each PR merged and will test basic sanity for
default target provider.

Add vm-import-operator postsubmit job

---

github/ci/prow/files/jobs/containerized-data-importer/containerized-data-importer-presubmits.yaml

Restore ceph lane, on k8s-1.17 this time.

---

github/ci/prow/files/jobs/vm-import-operator/vm-import-operator-postsubmits.yaml

Rename the k8s name as per latest kubevirtci

---

github/ci/prow/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml

Make ceph lane required for CDI

---

github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Make pull-kubevirt-e2e-k8s-1.17 lane mandatory

---

github/ci/prow/files/jobs/kubevirt/vm-import-operator/vm-import-operator-presubmits.yaml

Don't clone repo on vm-import presubmit

---

github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.29.yaml

Fork jobs for kubevirt release-0.29

---

github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml

Required for kubevirt/kubevirtci#358

Add kubevirtci provisioning jobs for k8s-1.18

---

github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

First off we add this optional, and non-reporting to avoid friction.

Add kubevirt test lane for k8s-1.18

---

github/ci/prow/files/jobs/kubevirt/vm-import-operator/vm-import-operator-presubmits.yaml

Use k8s-1.18 for vm-import-operator

---

github/ci/prow/files/jobs/kubevirt/vm-import-operator/vm-import-operator-periodics.yaml

Use ocp-4.4 for vm-import-operator periodic

---

robots/flakefinder/index.go
robots/flakefinder/main.go
robots/flakefinder/report.go

Introduce back links to flakefinder

---

github/ci/prow/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-periodics.yaml

In order to point people to specific lines in the reports, add anchors to every line.
Further back-links will now ease the navigation between the generated tables.

Bump flakefinder to the latest version with anchors

---

github/ci/prow/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml

Increase ceph lane timeout to 5 hours.

---

github/ci/prow/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml

Other lanes are hitting the timeout as well, increase the timeoiut to 5 hours for all of them.

Update all cdi timeouts to be 5 hours.

---

github/ci/shared-deployments/files/docker-daemon-mirror.conf
github/ci/shared-deployments/tasks/main.yml
github/ci/shared-deployments/templates/admin-rbac.yaml
github/ci/shared-deployments/templates/docker-daemon-mirror-config.yaml
github/ci/shared-deployments/templates/memory-job-defaults.yaml

Those configurations are shared across different clusters

Add shared deployment assets

---

github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Want to replace existing ceph lane with this once it is proven to work correctly and  consistently.

optional k8s 1.17 with rook/ceph

---

github/ci/prow/files/labels.yaml

Add new build-officer label

---

github/ci/prow/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-presubmits.yaml

Signed-off-by: Andrew Beekhof <andrew@beekhof.net>

Replace OCP 3.x job with k8s 1.17

---

github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.30.yaml

Removing it since it blocks merges on release-0.30.

k8s-1.18 does not exist on release-0.30 of kubevirt

---

github/ci/prow/files/config.yaml
github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.39.yaml

add presumbits for cnao 0.39 branch

---

github/ci/remote-cluster/tasks/main.yml

Add Greenhouse deployment to the new cluster

---

github/ci/prow/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-periodics.yaml

Add kubemacpool to flakefinder

---

github/ci/prow/files/config.yaml
github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
github/ci/prow/files/plugins.yaml
github/ci/prow/tasks/main.yml
github/ci/prow/templates/branch-protector.yaml
github/ci/prow/templates/cherrypicker_deployment.yaml
github/ci/prow/templates/crier-deployment.yaml
github/ci/prow/templates/deck-deployment.yaml
github/ci/prow/templates/exporter-deployment.yaml
github/ci/prow/templates/ghproxy.yaml
github/ci/prow/templates/hook.yaml
github/ci/prow/templates/horologium-deployment.yaml
github/ci/prow/templates/label-sync-kubevirt.yaml
github/ci/prow/templates/label-sync-nmstate.yaml
github/ci/prow/templates/needs-rebase_deployment.yaml
github/ci/prow/templates/plank-deployment.yaml
github/ci/prow/templates/plank-rbac.yaml
github/ci/prow/templates/sinker-deployment.yaml
github/ci/prow/templates/statusreconciler-deployment.yaml
github/ci/prow/templates/tide-deployment.yaml

Update prow components to latest version as of 2020-06-23.
/cc @danielBelenky @rmohr

Update prow to 20200623

---

github/ci/prow/files/jobs/kubevirt/hostpath-provisioner/hostpath-provisioner-presubmits.yaml

Update hostpath provisioner lane to not have k8s version

---

github/ci/prow/files/labels.yaml

Fix kubernetes-nmstate priority/highest label color code

---

github/ci/prow/files/config.yaml

Valuable history and context is lost.
Signed-off-by: Andrew Beekhof <andrew@beekhof.net>

Do not squash NMO PRs into a single commit

---

github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml

Add CNAO flake finder periodic jobs

---

github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml

Fix arg for rolling window flakefinder job

---

github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.31.yaml

Release configs for kubevirt/kubevirt release branch release-0.31

---

github/ci/prow/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-presubmits.yaml

Removed k8s 1.13, does not exist anymore
Updated k8s 1.17 to 1.18
Updated ocp 4.3 to 4.4 (4.3 does not get healthy)

Update test lanes for NMO

---

github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml

This is how this kind of jobs are triggered at prow https://github.com/kubernetes/test-infra/issues/5962

Run kubernetes-nmstate release job at tagging

---

github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.32.yaml

Release configs for kubevirt/kubevirt release branch release-0.32

---

github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Disable sriov-lane so it wont run automaticly until https://github.com/kubevirt/kubevirt/issues/3850 is resolved.

sriov-lane job: disable

---

github/ci/prow/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml

Optional test lane needs to install libdevmapper.

---

github/ci/prow/files/config.yaml
github/ci/prow/files/plugins.yaml

Configured kubevirt-bot to merge PRs for ssp components when `/approve` is specified on the PR
Signed-off-by: Omer Yahud <oyahud@redhat.com>

Merge ssp repositories PRs when approved

---

github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

The right target also check the git directory is clean
after running make generate.
In order to see the expected status is met.

Fix make generate to run the right target

---

github/ci/prow/templates/statusreconciler-deployment.yaml

Let the reconciler use our github request cache

---

github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml

Change the retest timeout back to one hour

---

github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml

Add the jobs for provisioning and pushing the k8s 1.19 provider. See kubevirt/kubevirtci#434

Add jobs for provisioning and pushing k8s 1.19 provider

---

github/ci/prow/files/config.yaml
github/ci/prow/files/jobs/kubevirt/kubevirt-csi/OWNERS
github/ci/prow/files/plugins.yaml

No presubmit hooks at this time.

Prepare PROW for kubevirt-csi

---

github/ci/prow/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-presubmits-master.yaml
github/ci/prow/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-presubmits-release-0.7.yaml

and fixed master config (we have some more " release" branch name patterns :/ )

Added NMO release-0.7 config

---

github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.33.yaml

Release configs for kubevirt/kubevirt release branch release-0.33

---

github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.42.yaml

Add presubmits for CNAO release-0.42

---

github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml

Run KubeVirt conformance tests every night.
Exercised tests: https://github.com/kubevirt/kubevirt/pull/4115

Add nightly job exercising conformance tests

---

github/ci/prow/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml

to ensure we don't hard code the CDI CR anywhere

Randomize the CDI CR on the ceph lane.

---

github/ci/prow/files/jobs/kubevirt/controller-lifecycle-operator-sdk/OWNERS
github/ci/prow/files/jobs/kubevirt/controller-lifecycle-operator-sdk/controller-lifecycle-operator-sdk-presubmits.yaml
github/ci/prow/files/plugins.yaml

This PR adds pre-submit job for kubevirt/controller-lifecycle-operator-sdk
Signed-off-by: Jakub Dzon <jdzon@redhat.com>

Adding job for controller-lifecycle-operator-sdk

---

github/ci/prow/files/config.yaml
github/ci/prow/files/plugins.yaml

Enabling Prow for the new go-based operator 
/cc @danielBelenky 
Signed-off-by: Omer Yahud <oyahud@redhat.com>

Enable prow for the new ssp-operator repository

---

github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.31.yaml
github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.32.yaml
github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.33.yaml
github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Adjust configurations for main and forked job configurations.
Also, change the job name in forked configs and set context param to mitigate the
status reconciler error.
/cc @rmohr @danielBelenky

Make pull-kubevirt-unit-test report to GH and required

---

github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.34.yaml

Release configs for kubevirt/kubevirt release branch release-0.34

---

github/ci/prow/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-periodics.yaml

Bump golang to 1.15.2 for HCO nightly

---

github/ci/prow/files/config.yaml
github/ci/prow/files/plugins.yaml

Add configuration for kubevirt/must-gather

---

github/ci/prow/files/labels.yaml

Two properties have been added to each sig/* entry:
prowPlugin: label
addedBy: anyone

labels: Fix sig/* entries by specifying missing properties

---

github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
github/ci/prow/tasks/main.yml
images/rehearse

Add automated deployment to rehearse image

---

github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml

Needed to use gocli for provisioning the clusters.

Use for kubevirtci jobs an image which includes go

---

github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml

If the job is not logged in to dockerhub it can't push.

Login to dockerhub in the kubevirtci release job

---

github/ci/prow/files/config.yaml
github/ci/prow/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.2.yaml

Add configurations for HCO release-1.2 branch

---

github/ci/prow/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml

Add new test to HCO CI, to check node placement

---

github/ci/prow/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml

Remove HCO's node placement test

---

github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Turn-off reporting on SRIOV lane until kubevirt/kubevirt#4438 is merged

sriov lane: turn-off reporting 

---

github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits.yaml

The pull-kubernetes-nmstate-docs build the jekyll webpage

Add pull-kubernetes-nmstate-docs job

---

github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
plugins/cmd/uploader/README.md
plugins/cmd/uploader/uploader.go

Signed-off-by: Federico Gimenez <federico.gimenez@gmail.com>

Added uploader periodic job and uploader plugin readme

---

github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.35.yaml

Release configs for kubevirt/kubevirt release branch release-0.35

---

github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits-0.31.yaml

knmstate: Branchout jobs for v0.31

  knmstate: Branchout jobs for v0.31

---

github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml

This PR adds tier1 test lanes of the following components in CNAO: multus, bridge-marker, nmstate

cnao, Add components tier1 functests

---

github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml

This PR adds tier1 test lanes of the following components in CNAO: ovs-cni, macvtap

cnao, Add components tier1 functests cont.

---

github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits.yaml

knmstate: Always run as non optional the docs lane

---

github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml

cnao, Run macvtap-cni, ovs-cni tier1 tests on evey PR

---

github/ci/prow/files/config.yaml

Notify coreos/eko channel on all job failures for kubevirt.github.io

---

github/ci/prow/tasks/main.yml

Also fixes docker mirror proxy secret creation (missing b64encoding the value).

Add missing tasks for deploying docker mirror proxy resources

---

OWNERS

Add fgimenez to OWNERS

---

github/ci/prow/files/config.yaml
github/ci/prow/tasks/main.yml
github/ci/shared-deployments/files/docker-daemon-mirror-proxy.conf
github/ci/shared-deployments/tasks/main.yml
github/ci/shared-deployments/templates/docker-daemon-mirror-config.yaml

Modify jobs to use docker mirror proxy

---

images/bootstrap/runner.sh

The configuration with all the required settings will be mounted on `/etc/default/docker`

Do not configure docker on bootstrap containers

---

github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Update kubevirt e2e jobs on bare-metal to use docker proxy.

---

github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml

Reduce Go download progress in sriov lane jobs to reduce noise on job logs

SRIOV lane jobs remove Go download progress

---

github/ci/prow/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-periodics.yaml

Use docker proxy for nightly HCO

---

github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits.yaml

This PR marks the nmstate `parallel` lane as mandatory

Make nmstate parallel lane required

---

github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml

Fix arithmetic to work with bourne shell, also ignore exit code of expr
in case of result being 0.
/cc @fgimenez

Make counter work with bourne shell

---

github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.13.yaml
github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.17.yaml
github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.20.yaml
github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.22.yaml
github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.23.yaml
github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.24.yaml
github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.26.yaml
github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.29.yaml
github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.30.yaml
github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.31.yaml
github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.32.yaml
github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.33.yaml
github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.34.yaml
github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.35.yaml
github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Update kubevirt jobs to use docker proxy

---

github/ci/prow/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-periodics.yaml

replace the nightly test with a script from HCO repository

---

github/ci/prow/files/jobs/kubevirt/node-maintenance-operator/OWNERS
github/ci/prow/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-presubmits-master.yaml

- New jobs for build and check
- Updated owners

Updated NMO

---

github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.36.yaml

Release configs for kubevirt/kubevirt release branch release-0.36

---

github/ci/prow/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-periodics.yaml

Temporarily trigger HCO nightly every hour

---

github/ci/prow/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-periodics.yaml

This reverts commit 5238784f03588cc292087e1922f13a2af9ec6b95.

Revert "Temporarily trigger HCO nightly every hour (#754)"

---

github/ci/prow/files/config.yaml

Disable travis in HCO. Moved to github action

---

github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml

Use proper semver regex in kubevirt release image publish job

---

github/ci/prow/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-postsubmits.yaml

- push latest image on master branch
- push tagged image on release tags

Added postsubmit jobs for NMO

---

github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits-0.35.yaml

Use correct branch at knmstate-0.35 operator job

---

github/ci/prow-jobs-secrets/tasks/main.yml

This will allow using kubevirt/secrets on automated prow deployment.
cc/ @rmohr @dhiller 

Ansible task for creating PGP bot key secret

---

github/ci/prow/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits.yaml
github/ci/prow/files/jobs/kubevirt/ansible-kubevirt-modules/ansible-kubevirt-modules-presubmits.yaml
github/ci/prow/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.2.yaml
github/ci/prow/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-2.3.yaml
github/ci/prow/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-2.4.yaml
github/ci/prow/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
github/ci/prow/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-presubmits-release-0.7.yaml

Using the image built after these changes #750 

Modify all jobs depending on kubevirt-infra-bootstrap image to use docker proxy

---

github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits.yaml

Add a knmstate lane for future nmstate version

---

github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.35.yaml
github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.36.yaml

Stop the statusreconciler from repeatedly triggering jobs.

Fix sriov job names

---

github/ci/prow/files/jobs/kubevirt/kubectl-virt-plugin/kubectl-virt-plugin-postsubmits.yaml
github/ci/prow/files/jobs/kubevirt/kubectl-virt-plugin/kubectl-virt-plugin-presubmits.yaml

Add jobs to build and publish images for kubectl-virt-plugin

---

github/ci/prow/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-presubmits-release-0.8.yaml

NMO presubmit config for new release-0.8 branch

NMO: added presubmits for release-0.8

---

github/ci/kubernetes_crud/vars/main.yml
github/ci/prow/files/jobs/kubevirt/bridge-marker/bridge-marker-presubmits.yaml
github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-postsubmits.yaml
github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.27.yaml
github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.39.yaml
github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.42.yaml
github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
github/ci/prow/files/jobs/kubevirt/controller-lifecycle-operator-sdk/controller-lifecycle-operator-sdk-presubmits.yaml
github/ci/prow/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-postsubmits.yaml
github/ci/prow/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-2.4.yaml
github/ci/prow/files/jobs/kubevirt/kubevirt-tutorial/kubevirt-tutorial-periodics.yaml
github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
github/ci/prow/files/jobs/kubevirt/macvtap-cni/macvtap-cni-postsubmits.yaml
github/ci/prow/files/jobs/kubevirt/macvtap-cni/macvtap-cni-presubmits.yaml
github/ci/prow/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-presubmits-master.yaml
github/ci/prow/files/jobs/kubevirt/ovs-cni/ovs-cni-presubmits.yaml
github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml
github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits-0.35.yaml
github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits.yaml

Update jobs to use docker proxy

---

github/ci/OWNERS

That will improve autoassignment for infra related PRs.

Create a meaningful owners file for infra deployment code

---

github/ci/prow/files/jobs/kubevirt/kubectl-virt-plugin/kubectl-virt-plugin-periodics.yaml
github/ci/prow/files/jobs/kubevirt/kubectl-virt-plugin/kubectl-virt-plugin-presubmits.yaml

Create periodic to publish kubectl-virt-plugin

---

github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.42.yaml
github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.44.yaml
github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml

CNAO is moving from travis ci to a prow unit-test job.

cnao, Add unit test job for release and stable jobs

---

github/ci/services/cert-manager/README.md

Now that our ingress are working we are able to deploy cert-manager without having issues with HTTP01 challenges failures bc of random 404. 

cert-manager readme

---

github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml

Build job will run the build only whenever a PR gets updated, publish
job will push the image to the image registry.
/cc @fgimenez 
FYI @mazzystr

Create jobs for kubevirt-userguide image

---

github/ci/prow-deploy/kustom/base/manifests/local/nginx-ingress.yaml
github/ci/prow-deploy/kustom/overlays/ibmcloud-production/yq_scripts/config.yaml
github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
github/ci/services/ci-search/manifests/ingress.yaml

Also enabled TLS sections for prow ingresses.

update URLs to *.ci.kubevirt.io

---

github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml

Add presubmit for rehearse plugin

---

github/ci/prow/files/config.yaml
github/ci/prow/files/jobs/kubevirt/community/community-postsubmits.yaml
github/ci/prow/files/jobs/kubevirt/community/community-presubmits.yaml
github/ci/prow/files/labels.yaml
github/ci/prow/files/plugins.yaml

Adds configuration for enabling prow on the community repo¸ also adds jobs to generate the SQL code for cncf/devstats.
/cc @fgimenez @fabiand 
@codificat FYI

Create jobs for sigs update

---

github/ci/prow/files/config.yaml
github/ci/prow/files/jobs/kubevirt/user-guide/user-guide-periodics.yaml
github/ci/prow/files/jobs/kubevirt/user-guide/user-guide-presubmits.yaml
github/ci/prow/files/labels.yaml
github/ci/prow/files/plugins.yaml

Updates to add standard Prow jobs to user-guide repo CI
This is my first time working with Prow.  I copied what we had for kubevirt.github.io.  Hopefully I got it correct.

Update to add repo user-guide to CI automation

---

github/ci/services/ci-search/patches/statefulset.yaml

ci-search: set index-bucket to kubevirt-prow

---

github/ci/prow/files/jobs/kubevirt/user-guide/user-guide-periodics.yaml
github/ci/prow/files/jobs/kubevirt/user-guide/user-guide-presubmits.yaml

Update to set correct python image for user-guide builds per Netlify limitation
@pep @dhiller

Update to set correct python image for user-guide builds

---

github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits-0.37.yaml

Add jobs for kubernetes-nmstate release-0.37

---

images/kubevirt-userguide/Dockerfile

user-guide: Update to add htmlproofer plugin and dependencies

user-guide: Update to add htmlproofer plugin and dependencies

---

github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.37.yaml

Use the correct config-forker to create unique names.

jobconfig fork for release-0.37

---

github/ci/prow/files/jobs/kubevirt/user-guide/user-guide-periodics.yaml
github/ci/prow/files/jobs/kubevirt/user-guide/user-guide-presubmits.yaml

user-guide: Fix python environment

user-guide: Fix python environment

---

github/ci/prow/files/jobs/kubevirt/user-guide/user-guide-periodics.yaml
github/ci/prow/files/jobs/kubevirt/user-guide/user-guide-presubmits.yaml

Another pull req to fix venv path.  Hopefully we can write to /tmp

user-guide: Fix venv path

---

github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
github/ci/prow/files/orgs.yaml

Add initial configuration for review and periodic job that will update the configuration in GitHub. In another step we will enable this by updating to `--confirm=true`
See #812
/cc @fgimenez @rmohr @fabiand

Add peribolos configuration and job

---

github/ci/prow/files/config.yaml

[HCO] Require Sanity Checks on PR to master

---

github/ci/prow/files/orgs.yaml

Remove org admin

---

github/ci/prow/files/labels.yaml

Following labels were missing:
- release-note-action-required
- do-not-merge/work-in-progress
- lgtm
- approved
- needs-ok-to-test

Add some other missing labels to default section

---

github/ci/prow/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml

Add separate CDI destructive lane for destructive tests

---

github/ci/prow/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml

Accidentally copied a line I shouldn't have, this fixes it

Remove duplicate kubevirt/containerized-data-importer

---

github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml

Work around strange push issues with docker.io.

Release bootstrap image on quay.io

---

github/ci/prow/files/labels.yaml

Fix labels by removing the duplicates

---

github/ci/prow/files/jobs/kubevirt/common-templates/common-templates-periodics.yaml

Periodically Check for a new Fedora version and create a new Containerdiskimage for it in the registry

Periodically Check for a new Fedora version and create a new CDI

---

github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml

The proxy has issues with uploading big layers.

Don't use proxy for the bootstrap job for now

---

github/ci/prow/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml

CDI make the destructive lane required and always run

---

github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
github/ci/prow/files/orgs.yaml

Enable mutations for org members, teams, team members and team permissions on repos.
/hold

Enable org mutations

---

github/ci/prow/files/labels.yaml

Also test presubmit job.
/hold
/cc @dhiller

Move ok-to-test to default section

---

github/ci/prow/files/orgs.yaml

Signed-off-by: alonsadan <alonsadan1@gmail.com>

Add alonsadan as a member to kubevirt org

---

github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.38.yaml

Release configs for kubevirt/kubevirt release branch release-0.38

---

github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml

Add missing curly braces around BASE_REPOID var

---

github/ci/prow/files/orgs.yaml

She has been sending lots of useful patches, and I trust her patches
to not require additional human verification (/ok-to-test).

Add alicefr to kubevirt members.

---

github/ci/prow/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-periodics.yaml
github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
github/ci/prow/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-periodics.yaml
robots/flakefinder/BUILD.bazel
robots/flakefinder/Makefile
robots/flakefinder/push.sh
robots/flakefinder/report.go
robots/flakefinder/report_test.go

Add list of jobs

---

github/ci/prow/files/orgs.yaml

I'm a new software engineer in the CNV storage team

Add shellyka13 to org members

---

github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
github/ci/services/prometheus-stack/manifests/grafana.yaml
github/ci/services/prometheus-stack/manifests/ingress.yaml

c&p error, i noticed that the service was not accessible from https://grafana.ci.kubevirt.io/

Several grafana fixes

---

github/ci/prometheus/templates/dashboards.yaml
github/ci/services/prometheus-stack/manifests/grafana.yaml

Add the [e2e jobs overview dashboard](https://grafana-kubevirt-prow.apps.ovirt.org/d/Cz6zgEEGz/e2e-jobs-overview?var-job_name=.*-kubevirt-e2e-.*) to the setup.
/cc @fgimenez

Add e2e jobs overview dashboard

---

github/ci/prometheus/templates/dashboards.yaml
github/ci/services/prometheus-stack/README.md
github/ci/services/prometheus-stack/manifests/grafana.yaml

Shows historical information about https://github.com/fgimenez/ci-health/, looks like https://grafana.ci.kubevirt.io/d/WZU1-LPGz/merge-queue?orgId=1

Persist merge-queue dashboard

---

github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
hack/manage-secrets.sh

Follow up of https://github.com/kubevirt/project-infra/pull/946#pullrequestreview-591107237 
/cc @dhiller 

Refactor secret management scripts to separate file

---

github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml

Adds the job to upload testing manifests for KubeVirt release 0.38.
/cc @fgimenez

Add job to upload testing manifests

---

github/ci/prow/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml

Use docker-proxy in CDI jobs

---

github/ci/prow/files/jobs/kubevirt/csi-driver/csi-driver-presubmits.yaml

Add presubmits that invokes tests, functional tests, and goveralls.

csi-driver presubmits

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
github/ci/services/prometheus-stack/e2e/e2e_test.go
github/ci/services/prometheus-stack/hack/deploy.sh
github/ci/services/prometheus-stack/manifests/node-exporter.yaml

This will give us hardware and OS metrics, details here https://github.com/prometheus/node_exporter
/cc @dhiller

prometheus-stack: add node-exporter

---

releng/release-tool/Dockerfile.release-tool-base
releng/release-tool/release-tool.go
releng/release-tool/release-tool_test.go

pr creator during our release process failed. The pr creator was updated recently and a parameter "match-title" was removed. This caused our automation to fail.

handle new pr creator

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.39.yaml

Release configs for kubevirt/kubevirt release branch release-0.39

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.39.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml

This new version correctly picks up the in-cluster docker configuration.
Follow up of #987

Bump to new bootsrap image

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presets.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.39.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
images/bootstrap/runner.sh

Our docker setup uses a http proxy. The http proxy is picked up via environment variables. Use a subshell to contain the proxy settings to the docker startup.

New bootstrap with nested shell for http proxies

---

config
github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
jobs

Set real paths on config_updater settings and update symlinks

---

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml

Add CDI basic tests performed by travis.

---

github/ci/prow-deploy/files/orgs.yaml

Add fgimenez to org admins

---

github/ci/prow-deploy/files/orgs.yaml

Add monitoring repository and team

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml

Use fedora-based bootstrap image in e2e periodics

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Disable quarantine lanes

---

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml

revert the changes that prevent HCO test to run in minor changes; it didn't work

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Re-enavbling ceph due to mailing list feedback.

Revert disabling rook-ceph

---

.bazelrc
external-plugins/rehearse/Dockerfile
external-plugins/rehearse/plugin/BUILD.bazel
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
hack/print-workspace-status.sh

Will fix failures like https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/publish-rehearse-image/1368982337546620929
/cc @dhiller

Use bazel to build rehearse image

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml

Reverting #1021
This reverts commit 9acac5d25c78225dfb6be5384ec4e32e32e1da78.

Revert "Add kubevirt/kubevirt job to kubevirtci (#1021)"

---

github/ci/prow-deploy/kustom/base/manifests/local/prow-rehearse-deployment.yaml
github/ci/prow/tasks/main.yml

Already live in prow's control plane.
/cc @dhiller 

Bump rehearse image

---

github/ci/prow-deploy/files/orgs.yaml

See kubevirt/kubevirt#5226
/cc @fgimenez

Enable GitHub projects for repo kubevirt/kubevirt

---

github/ci/prow-deploy/files/jobs/kubevirt/common-templates/common-templates-periodics.yaml

Modify the job to move the logic into a script in common-templates.

Modify the job to move the logic into a script in common-templates

---

github/ci/prometheus/templates/dashboards.yaml
github/ci/services/prometheus-stack/manifests/grafana.yaml

Lates version available at https://grafana-kubevirt-prow.apps.ovirt.org/d/Cz6zgEEGz/e2e-jobs-overview?orgId=1&refresh=2h
/cc @dhiller 

Update grafana dashboards

---

github/ci/prow-deploy/files/orgs.yaml

Hi all, I am a software engineer in the CNV Virt team and contributing to KubeVirt.

Add acardace to org members

---

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml

Whoops!  not initializing selinux on all nodes for rook.

rollback to prev ceph

---

plugins/cmd/uploader/uploader.go
plugins/mirror/bazel.go
plugins/mirror/bazel_test.go

Remove dead links from WORKSPACE artifacts

---

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-postsubmits.yaml

Add post submit jobs for CDI to do releases.

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml

Add login to image registry in job script

---

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-postsubmits.yaml

I confused tags and branches in ProwJob, this should trigger on right branch

Fixed CDI triggering on branch instead of tag

---

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml

LEt's make sure things actually work this time

test lane for new rook ceph

---

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-postsubmits.yaml

Fix regex to match the correct branch

---

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-postsubmits.yaml

Stop using docker proxy when pushing CDI images

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml

I've also taken the opportunity to specify the execution time of the sig periodics so that we don't DoS ourselves triggering all of them at once.
/cc @dhiller @vatsalparekh 

Add sig-compute periodic

---

releng/release-tool/release-tool.go

For some reason, the issue filters by label don't appear to work in the github api request. I don't have an explanation for this and it breaks our ability to make releases now because it looks like all issues are a blocker.
To fix this, I filter on our end by the blocker label after retrieving the issues. I think this is compensating for a github api regression because this definitely worked properly at one point.

Fix issue with github api not returning consistent label filtered results

---

images/yaspeller/.yaspeller.json

@phoracek  Small fix to the dictionary file

Update to yaspeller dictionary

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.40.yaml

Release configs for kubevirt/kubevirt release branch release-0.40

---

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml

Add new k8s 1.19 and 1.20 lanes to CDI

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Get rid of test lane and have ceph lane use new provider.

move to always use new rook/ceph after trying it out

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml

This should make the job trigger whenever a tag is pushed. Also we handle in the job script that it will only run for versions >= 0.40.
/cc @fgimenez @rmohr 
FYI @davidvossel

Use semver regex to trigger job on tag pushes

---

images/kubevirt-kubevirt.github.io/Gemfile
images/kubevirt-kubevirt.github.io/Rakefile
images/kubevirt-kubevirt.github.io/_config.yml
images/kubevirt-kubevirt.github.io/check_selectors.js
images/kubevirt-kubevirt.github.io/kubevirt_dev_t.te
images/markdownlint/markdownlint.yaml

issues/1139...Consolidate kubevirt.github.io files for disk img builds

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml

Do not yet include it for publishing.

Add provision jobs for k8s-1.21

---

github/ci/prow-deploy/files/jobs/kubevirt/common-templates/common-templates-periodics.yaml

Add a periodic job to build the latest CentOS container disk image

Add a periodic job to build the latest CentOS container disk image

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml

Add presubmit job to test plugins

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
robots/cmd/flake-issue-creator/cluster_failure_test.go
robots/cmd/flake-issue-creator/flake_issue_test.go
robots/cmd/flake-issue-creator/issue_test.go

Remove env variable from sig-compute lane here because they're being moved [#5464](https://github.com/kubevirt/kubevirt/pull/5464)

Remove env variable from sig-compute lane

---

github/ci/prow-deploy/files/jobs/nmstate/nmstate/OWNERS

Add jobs/nmstate/nmstate OWNERS

---

github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-periodics.yaml
github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml
github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits-0.15.yaml
github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits-0.31.yaml
github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits-0.35.yaml
github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits-0.37.yaml
github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits.yaml
github/ci/prow-deploy/files/jobs/nmstate/nmstate/nmstate-presubmits.yaml

Declare cluster for nmstate presubmit

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml

As the forcepush happens every day this search will not yield anything
for 24h.

Set 12h for autoapprove

---

github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml

Should be the last config change, sorry I overlooked this one.
/cc @dhiller 

Fix wrong URL in Prow config

---

github/ci/prow-deploy/files/jobs/kubevirt/common-templates/common-templates-periodics.yaml

Modify CentOS Job to specify the exact stable CentOS version

---

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.4.yaml
github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml

HCO: add new release-1.4 branch

---

github/ci/prow-deploy/files/jobs/kubevirt/common-templates/common-templates-periodics.yaml

Update the branch for the common-templates project

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Add additional jobs to run non-root implementation
/hold
Needs https://github.com/kubevirt/kubevirt/pull/5540 to be merged.

Add aditional jobs to run non-root implementation

---

github/ci/prow-deploy/files/jobs/kubevirt/libguestfs-appliance/libguestfs-appliance-presubmits.yaml

Create presubmit prow job for the respository [libguestfs-appliance](https://github.com/kubevirt/libguestfs-appliance)

Create presubmit job for kubevirt/libguestfs-appliance

---

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-periodics.yaml
github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml

HCO: change the default branch to main

---

github/ci/prow-deploy/files/jobs/kubevirt/community/community-presubmits.yaml

Adds a presubmit that validates the sigs.yaml whenever it changes.

Add validation presubmit for sigs.yaml

---

github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.53.yaml

This PR adds lanes for the new stable branch release-0.53 at CNAO

cnao, Add lanes for new stable branch release-0.53

---

github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits-v0.26.yaml
github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits.yaml

This PR adds lanes for the new stable branch release-v0.26 at KMP

kubemacpool, Add lanes for new stable branch release-v0.26

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.41.yaml

Release configs for kubevirt/kubevirt release branch release-0.41

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
robots/cmd/kubevirtci-presubmit-creator/BUILD.bazel
robots/cmd/kubevirtci-presubmit-creator/main.go
robots/cmd/kubevirtci-presubmit-creator/main_test.go

Creates a new prow presubmit in case a new kubernetes release does not yet have a corresponding presubmit for kubevirtci.

Create prow job for new kubernetes release

---

github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits-v0.21.yaml

This PR Adds lanes for new stable branch release-v0.21

kubemacpool, Add lanes for new stable branch release-v0.21

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Reenable reporting to GitHub for kubevirt goveralls

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml

Also remove autoapprove job that doesn't work anyway.
/cc @rmohr

Add periodics to kubevirt flakefinder weeklies

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
hack/git-pr.sh

Use new image from kubevirt/kubevirt#5640 with updated PR creator that supports --labels flag.
Add support for labels flag -L to git-pr.sh. Update job to add labels when creating or updating PR.

Add labels to uploader PR

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Enable goveralls to always run for kubevirt

---

github/ci/prow-deploy/files/jobs/kubevirt/libguestfs-appliance/libguestfs-appliance-periodics.yaml

Add periodic job to build libguestfs appliance

Create periodic job for kubevirt/libguestfs-appliance

---

images/yaspeller/.yaspeller.json

Update dictionary file

---

github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml

Enable DCO plugin on OVS CNI project

---

images/kubevirt-kubevirt.github.io/Dockerfile
images/yaspeller/.yaspeller.json

Dockerfile for website
```
$ podman image ls | grep kubevirt.github.io
localhost/kubevirt-kubevirt.github.io  latest  6c3d5350fc07  About a minute ago  842 MB
```
Image is parred down to 840MiB.  It could probably be parred down further if we break dnf and systemd

Dockerfile for website

---

github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml
github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml

Use new kubernetes-nmstate default branch "main"

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml

Result: https://coveralls.io/jobs/80359336
needs changes of kubevirt/kubevirt#5659
/hold

Add postsubmit to calculate kubevirt coverage on master branch

---

github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml

Rebased Marcin Franczyks changes from kubevirt/project-infra#229  on latest master 
/cc @mfranczy

add restcoverage lens

---

github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits-v0.20.yaml

This PR add lanes on kubemacpool repo to stable branch release-v0.20

kubemacpool, Add lanes to stable branch release-v0.20

---

images/kubevirt-userguide/Dockerfile

Build img consolidation and streamline. We now build a single img containing mkdocs, yaspeller, htmlproofer packed in.

Build img consolidation and streamline

---

github/ci/prow-deploy/files/orgs.yaml

I'm an Engineer in the CNV Storage team.

Add akalenyu to kubevirt members

---

github/ci/prow-deploy/files/jobs/kubevirt/terraform-provider-kubevirt/terraform-provider-kubevirt-presubmits.yaml

Signed-off-by: Nir Argaman <nargaman@redhat.com>

terraform-provider-kubevirt: Add presubmits file

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.40.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.41.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Reduce memory requests for e2e jobs

---

github/ci/prow-deploy/kustom/overlays/workloads-production/kustomization.yaml
github/ci/prow-deploy/tasks/secrets.yml
github/ci/prow-deploy/vars/kubevirtci-testing/secrets.yml

Requires https://github.com/kubevirt/secrets/pull/22
/cc @dhiller 

Deploy secret for Windows Sysprep testing

---

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml

Add new k8s-1.20-hpp-istio (Istio deployed) lane to CDI

---

github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml

knmstate: Branch protection for release-0.37

---

github/ci/prow-deploy/files/jobs/kubevirt/libguestfs-appliance/libguestfs-appliance-periodics.yaml

The latest-version.txt contains the latest version of the appliance
tarball.

publish latest-version.txt

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Added presubmit to check for unassigned tests

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml

Move kubevirtci jobs to prow-workloads

---

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-postsubmits.yaml

Add push to latest on post submit of main for CDI

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
github/ci/prow-workloads/bootstrap.yml
github/ci/prow-workloads/hack/bootstrap.sh
github/ci/prow-workloads/hack/common.sh
github/ci/prow-workloads/hack/deploy.sh
github/ci/prow-workloads/roles/bootstrap/tasks/main.yml

Adds an ansible role with all the customizations required to setup e2e worker nodes. Also creates a prow job to run the job on tag push.
/cc @dhiller @rmohr

Prow workloads bootstrap automation

---

github/ci/services/prometheus-stack/manifests/stack/production-e2e-workloads/metrics-ingress.yaml

Add prow-workloads metrics ingress

---

github/ci/prow-deploy/kustom/overlays/workloads-production/kustomization.yaml

Add required secrets to prow-workloads cluster

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml

Also taken the opportunity to remove an old lane that executed the whole suite.
/cc @dhiller 

Prevent slack reports on periodic lanes that run quarantined tests

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml

SR-IOV machines in prow-workloads are not yet ready to run SR-IOV jobs.

Run SR-IOV job on phx-prow

---

OWNERS

asking to be added to approvers list

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml

See https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirtci-bump-kubevirt/1403265422832177152

Fix image for job that bumps kubevirtci on kubevirt

---

github/ci/prow-deploy/files/jobs/kubevirt/kubectl-virt-plugin/kubectl-virt-plugin-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubectl-virt-plugin/kubectl-virt-plugin-postsubmits.yaml
github/ci/prow-deploy/files/orgs.yaml

/cc @fgimenez 
https://github.com/kubevirt/kubectl-virt-plugin/pull/31 needs to go in afterwards.

Set default branch to main

---

github/ci/prow-deploy/files/jobs/kubevirt/common-templates/common-templates-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
github/ci/prow-deploy/files/orgs.yaml
github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml

/cc @fgimenez @rmohr 
/hold
We can unhold after the default branch has been renamed

Set default branch for kubevirtci to main

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml

Deploy Prow components on merges to master instead of tag push.
/cc @dhiller 

Continuous Deployment of Prow components

---

github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml

The master branch was changed to main.

Update OVS CNI branch to main

---

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml

Remove Istio focus from k8s-1.20-hpp-istio CDI lane

---

github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits-0.47.yaml

knmstate-jobs-release-0.47

---

github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits-0.47.yaml

knmstate-0.47-fix-branches

---

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml

HCO: add lane for 1.20

---

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml

Fix wrong image for HCO 1.20 lane

---

github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-postsubmits.yaml

added postsubmits to replace local travis [script](https://github.com/k8snetworkplumbingwg/kubemacpool/blob/main/.travis.yml).

kubemacpool, Add kubemacpool postsubmits

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml

Disable check provision lane for 1.17

---

github/ci/prow-deploy/files/jobs/kubevirt/bridge-marker/bridge-marker-postsubmits.yaml

added postsubmits to replace local travis [script](https://github.com/kubevirt/bridge-marker/blob/main/.travis.yml).

bridge-marker, Add postsubmits

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml

Fix branch for kubevirtci postsubmit

---

github/ci/prow-deploy/files/jobs/kubevirt/bridge-marker/bridge-marker-postsubmits.yaml

This PR fixes a small typo in the script

bridge-marker, postsubmits, Fix typo

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.42.yaml

Test lanes created using test-infra releng/config-forker
/cc @rmohr @fgimenez 
FYI  @xpivarc @enp0s3

Add lanes for kubevirt release 0.42 branch

---

external-plugins/release-blocker/server.go
releng/release-tool/release-tool.go

Updates release tool to use main as default branch

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml

See https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirtci-cluster-minorversion-updater/1407363207349145600

Point baseref for kubevirtci minorversion-updater to main

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.42.yaml

The script does not exist in 0.42

Remove check-unassigned-tests lane for 0.42

---

github/ci/prow-deploy/files/jobs/kubevirt/bridge-marker/bridge-marker-presubmits-0.6.yaml

Register presubmit for bridge-marker 0.6

---

github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/ovs-cni/ovs-cni-presubmits-0.19.yaml

Add presubmit job for stable OVS CNI 0.19

---

github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml

Signed-off-by: Nir Argaman <nargaman@redhat.com>

terraform-provider-kubevirt: Add the repo to queries section in prow config

---

github/ci/prow-deploy/files/orgs.yaml

I am going to contribute to kubevirt.

Add dominikholler to org members

---

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml

Set k8s-1.20-hpp-istio CDI lane to always_run=true

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
github/ci/services/prometheus-stack/manifests/stack/common/kube-prometheus-stack.yaml

Includes fixes to run the services tests in the prow-workloads cluster.
/cc @dhiller 

Increase Prometheus persistent volume size

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt.github.io/kubevirt-github-io-postsubmits.yaml
images/ruby/Dockerfile

Based on @mazzystr s PR #1387. This one adds ruby prow image based on kubevirtci/bootstrap and uses it in the job. It also enables the docker mirror on the job.
/cc @mazzystr @fgimenez

Website ci

---

github/ci/services/ci-search/patches/statefulset.yaml

Update Prow urls in ci-search flags

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml

Will enable to run all test suites (parallel and serial) even if a test
fails. See https://github.com/kubevirt/kubevirt/pull/5927
/hold

Set KUBEVIRT_E2E_RUN_ALL_SUITES on periodic sig kubevirt jobs

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
github/ci/prow-deploy/kustom/overlays/ibmcloud-production/kustomization.yaml
github/ci/prow-deploy/kustom/overlays/workloads-production/kustomization.yaml
github/ci/prow-deploy/tasks/secrets.yml
github/ci/prow-deploy/vars/kubevirtci-testing/secrets.yml

Creates the presubmit that for now is manually triggerable, also it creates a postsubmit.
See https://github.com/kubevirt/kubevirt/pull/5731

Add fossa analysis presubmit manual and postsubmit

---

github/ci/services/prometheus-stack/manifests/stack/production-control-plane/thanos.yaml

Reduce Thanos retention

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml

Run uploader for project-infra

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml

Add periodic nightly release job for ARM64

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Make fossa presubmit run always

---

images/yaspeller/.yaspeller.json

Signed-off-by: Chris Callegari <mazzystr@gmail.com>

Update yaspeller dictionary file

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.43.yaml

add presubmit job for branch release-0.43

---

github/ci/prow-deploy/files/orgs.yaml

@jobbler
[x] I have reviewed the community code of conduct (https://github.com/kubevirt/kubevirt/blob/master/CODE_OF_CONDUCT.md)<br>
[x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)<br>
[x] I have subscribed to the kubevirt-dev e-mail list (https://groups.google.com/forum/#!forum/kubevirt-dev)<br>
[x] I am actively contributing to KubeVirt<br>
[x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines<br>
[x] I have spoken to my sponsors ahead of this application and they have agreed to sponsor my application<br>
[x] I have publicly introduced myself to the community through one of the community communication channels<br>
* @mazzystr
* @dhiller
* PRs reviewed …

Added joherr/jobbler to members

---

github/ci/prow-deploy/files/orgs.yaml

Add KubeVirt Velero plugin repository and team

---

github/ci/README.md
robots/cmd/flake-issue-creator/main.go
robots/cmd/flakefinder/report.go

Update deck links

---

github/ci/prow-deploy/files/orgs.yaml

Matthew has done work on libnbd Go bindings and CDI.

Add Matthew Arnold to kubevirt members.

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-velero-plugin/kubevirt-velero-plugin-presubmits.yaml
github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml

KubeVirt Velero Plugin needs its own CI run on each PR.

Project and CI configuration for KubeVirt Velero plugin

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Require compute and operator for non-root

---

github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml

Add RedHatQE/openshift-python-wrapper to project to use prow plugins.

Add RedHatQE/openshift-python-wrapper to project

---

github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml

Signed-off-by: Meni Yakove <myakove@redhat.com>

Indent lines under plugins section

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Make 1.20-sig-compute required

---

github/ci/prow-deploy/kustom/base/manifests/local/cherrypicker_deployment.yaml

This will prevent issues with the new HMAC secret format.
/cc @enp0s3 

Bump cherrypicker image

---

external-plugins/release-blocker/BUILD.bazel
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
github/ci/prow-deploy/kustom/base/manifests/local/release-blocker_deployment.yaml

Add jobs to test and push relase-blocker image

---

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml

Start build at 3:02 nightly, where kubevirt is at 1:02.

Add CDI ARM build periodic

---

OWNERS_ALIASES
docs/membership-policy.md

Add CI maintainer membership doc

---

github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner/hostpath-provisioner-presubmits.yaml

Add sanity and k8s external storage e2e test lane for hostpath provisioner CSI plugin

---

github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner/hostpath-provisioner-presubmits.yaml

Fix path to script in hpp k8s e2e storage job

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.44.yaml

Release configs for kubevirt/kubevirt release branch release-0.44

---

docs/how-to-add-a-prow-cluster.md

Add document on how to add CI build clusters

---

README.md
docs/infra-layout.svg
docs/infrastructure-components.md

Also updates the main readme.
/cc @enp0s3 @rmohr @dhiller 

Add infrastructure overview doc

---

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml

HCO: add 1.21 lane

---

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.5.yaml

HCO: Add tests for the new release-1.5 branch

---

github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.58.yaml

This PR adds a stable CNAO lane to test PRs on release-0.58 branch

cnao, Add stable lane release-0.58

---

github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits-v0.31.yaml

This PR adds a stable KMP lane to test PRs on release-v0.31 branch

kubemacpool, Add stable lane release-v0.31

---

github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner/hostpath-provisioner-presubmits.yaml

Make hpp sanity and k8s-storage lane mandatory and gating

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Signed-off-by: Vladik Romanovsky <vromanso@redhat.com>

Make the vGPU lane mandatory

---

github/ci/prow-deploy/files/orgs.yaml

Add brybacki to maintainers of KubeVirt Velero plugin

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
hack/git-pr.sh

Add support of commit description command,
this way, the created PR can have an informative
commit message and PR description.
Use this new feature in order to add what changed info to automatic bumps
Depends on https://github.com/kubevirt/kubevirt/pull/6306

periodic-kubevirtci-bump-kubevirt, Add what changed info to automatic bumps

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

Skip `MediatedDevices` tests asd include `sig-operator`.

Update skip-list for cgroupv2 presubmit job

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml

Adds cgroupsv2 periodic now that the fix for the recurring error has been merged here https://github.com/kubevirt/kubevirt/pull/6335
/cc @vasiliy-ul @dhiller 

Re-add cgroupsv2 periodic

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
hack/git-pr.sh

Test-drives the new image from https://github.com/kubevirt/project-infra/pull/1536 , uses it to simplify job script. If that works, in a next step, I'd change the other jobs (kubevirtci-minor-bump etc.) to using this image.
/cc @fgimenez

Switch using pr-creator image

---

images/bootstrap/Dockerfile

/cc @dhiller @rmohr
Signed-off-by: Federico Gimenez <federico.gimenez@gmail.com>

Prepull bazel 4.2.1 in bootstrap image

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

This will allow us to run specific tests
to verify we are testing nonroot

Add nonroot keyword to target

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml

Bump to latest image with prepulled bazel built here https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/publish-bootstrap-image/1434867946034827264
/cc @dhiller 

Bump bootstrap image

---

github/ci/prow-deploy/files/orgs.yaml

@xphyr
------
[x] I have reviewed the community code of conduct (https://github.com/kubevirt/kubevirt/blob/master/CODE_OF_CONDUCT.md)
[x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
[x] I have subscribed to the kubevirt-dev e-mail list (https://groups.google.com/forum/#!forum/kubevirt-dev)
[x] I am actively contributing to KubeVirt
[x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
[x] I have spoken to my sponsors ahead of this application and they have agreed to sponsor my application
[x] I have publicly introduced myself to the community through one of the community communication channels
------
@vladikr 
@dhiller
-----
PRs reviewed and/or authored
[List of kubevirt PRs by …

requesting community membership for kubevirt org

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.45.yaml

Release configs for kubevirt/kubevirt release branch release-0.45 

---

github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml

It can be used in test.sh to focus nonroot tests

Add new variable NONROOT

---

github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-periodics.yaml

Bump flakefinder jobs

---

github/ci/prow-deploy/files/jobs/kubevirt/vm-import-operator/OWNERS
github/ci/prow-deploy/files/jobs/kubevirt/vm-import-operator/vm-import-operator-presubmits.yaml

@dhiller 
Signed-off-by: Sam Lucidi <slucidi@redhat.com>

Use k8s-1.20 for vm-import-operator job

---

github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits.yaml

Update kubernetes-nmstate jobs

---

github/ci/prow-deploy/files/orgs.yaml

Also update ssp-maintainers team
/cc @fabiand @ksimon1 @dominikholler

Create ssp-admin team to give access for travis leak

---

github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml

Add quay login before image push

---

github/ci/services/prometheus-stack/manifests/rules/production-control-plane/ci-kpi.yaml

Mention that the value is a weekly average for all the alerts and show the actual value.
/cc @enp0s3 

Make CI health alert messages more meaningful

---

github/ci/prow-deploy/kustom/base/manifests/local/prow-rehearse-deployment.yaml
github/ci/prow-deploy/kustom/components/docker-mirror-proxy/base/resources/deployment.yaml
github/ci/prow-deploy/kustom/overlays/kubevirtci-testing/resources/bootstrap.yaml
github/ci/prow-deploy/kustom/overlays/kubevirtci-testing/resources/ingress-nginx-controller.yaml
github/ci/prow-deploy/kustom/overlays/workloads-production/resources/multus-cni.yaml

I've mirrored the missing images to quay and made the new repositories public, all is accessible now.
/cc @dhiller 

Use images from Quay

---

github/ci/prow-deploy/files/jobs/kubevirt/community/community-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-tutorial/kubevirt-tutorial-periodics.yaml

Signed-off-by: Chris Callegari <mazzystr@gmail.com>
Fixes https://github.com/kubevirt/kubevirt-tutorial/issues/123

Update branch to respectful name

---

github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-periodics.yaml
github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
github/ci/testgrid/gen-config.yaml

Signed-off-by: Erkan Erol <eerol@redhat.com>

Add HCO jobs into testgrid

---

github/ci/testgrid/README.md

Updates in workflow to reflect our integration with testgrid's config merger.
/cc @erkanerol @dhiller 

Update testgrid docs

---

github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner/hostpath-provisioner-presubmits.yaml

Switch hostpath provisioner unit test running to golang container

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml

This also fixed one issue we had when execution of job failed here: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirtci-cluster-minorversion-updater/1442407897769185280
Successful execution here: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirtci-cluster-minorversion-updater/1442451469407096832
/cc @fgimenez

Use pr-creator image for kubevirtci minor version updater

---

github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner/hostpath-provisioner-presubmits.yaml

Switch hpp presubmit that builds containers to golang container runner

---

github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner-operator/hostpath-provisioner-operator-postsubmits.yaml
github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner/hostpath-provisioner-postsubmits.yaml

Switch DOCKER_PREFIX to DOCKER_REPO which is used in hpp and operator

---

github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml

Stop using shorthand flag version as this is undefined.
/cc @fgimenez

Fix kubevirt robot job args
