kubevirt/project-infra

- github/ci/Vagrantfile
- github/ci/ci.yaml
- github/ci/jenkins-master/templates/04-jobs.groovy
Use JobDSL configure block, to configure the not natively supported
Publish-Over-Ssh build wrapper, which publishes independent of the job
status.
> Make sure, that we always publish logs

- github/ci/jenkins-master/templates/01-plugins.groovy
- github/ci/jenkins-master/templates/04-jobs.groovy
In the last two weeks we had repeatedly broken code, which caused some
pods to never start succeeding. To avoid hanging jobs, set a timeout of
120 minutes.
> Add timeout of 120 minutes to builds

- github/ci/README.md
- github/ci/jenkins-master/templates/04-jobs.groovy
- github/ci/jenkins-master/templates/05-github.groovy
Add matrix build support. The automation script can check the $TARGET environment variable to determine what it should deploy and test.
> Prepare matrix build for release testing

- github/ci/jenkins-master/templates/04-jobs.groovy
Especially to avoid re-deploying non-tracked manifests, make sure that
we only have the git content in the repo.
> Remove all untracked content after git checkout

- github/ci/jenkins-master/templates/04-jobs.groovy
Allows him to trigger 'retest this please' and 'ok to test' for external
contributions.
> Make artyom a CI admin

- github/ci/beaker/tasks/main.yaml
- github/ci/ci.yaml
- github/ci/jenkins-deps/tasks/main.yml
- github/ci/jenkins-master/tasks/main.yml
- github/ci/jenkins-slave/tasks/main.yml
* Assume Centos 7.4 as slave base, now that we only need docker
* Make sure that nested virtualization is enabled
* Make sure that the docker store is located at /home/docker where most
free space is available
> Prepare for docker-only usage

- github/ci/jenkins-master/templates/04-jobs.groovy
- github/ci/jenkins-slave/defaults/main.yml
* Windows Job is now called "windows2016". We did not update the labeling regarding to that
* The preferred workdir for clients is "/var/lib/warm" and not "/var/lib/jenkins" anymore. That is already reflected on the host but the change is not merged in the repo
> Fix two outdated entries in ansible

- CODE_OWNERS
Signed-off-by: Fabian Deutsch <fabiand@fedoraproject.org>
> Add code owners

- github/ci/README.md
- github/ci/ci.yaml
- github/ci/prow/files/config.yaml
- github/ci/prow/files/labels.yaml
- github/ci/prow/files/plugins.yaml
- github/ci/prow/tasks/main.yml
- github/ci/prow/templates/config.yaml
- github/ci/prow/templates/hook-service.yaml
- github/ci/prow/templates/hook.yaml
- github/ci/prow/templates/label-sync.yaml
- github/ci/prow/templates/labels.yaml
- github/ci/prow/templates/plugins.yaml
- github/ci/prow/templates/route-hook.yaml
* Only deploy the minimum prow setup which allows using github bots
* plugins.yaml will at the end contain the plugins for all repos which want to use prow-bots
Plugins which would be enabled:
* assigner (allows people to self-assign tasks: /assign)
* size (estimate PR size and add labels)
* labels (/king bug|improvment, /area virtctl, ...)
* releasenote needs to be specified or `NONE` needs to be give in a `release-note` codeblock. Labels are managed according to that
* blunderbuss (assign reviewers and approvers automatically based on the file  history out of an OWNER file)
* Adds a label configmap which can synchronize github labels, including renames, color changes, setting descriptions, ...
TODO:
* Give maintainers access to prow (can be done via role binding in os/ansible)
* Improve …
> Add prow role which provides useful github bots

- github/ci/prow/files/plugins.yaml
- github/ci/prow/tasks/main.yml
- github/ci/prow/templates/hook-rbac-role-binding.yaml
- github/ci/prow/templates/hook-rbac.yaml
- github/ci/prow/templates/hook-service-account.yaml
- github/ci/prow/templates/hook.yaml
Instead of running ansible everytime when prow configs change, let's run
the config-updater plugin which will update the configs whenever a PR
gets merged which changes these files. In order to achieve this, this PR contains the following:
- enable config-updater plugin for kubevirt/project-infra
- add a service account for hook which allows it to modify the configs
- `openshift_raw` has some issues with some resource types (fixed in ansible 2.6) which required to run oc directly.
> Automatically update configs if the are merged to master

- github/ci/jenkins-slave/defaults/main.yml
- github/ci/jenkins-slave/templates/swarm.service
Allow setting "exclusive" for labeled nodes to improve build speed. Use "normal" as default.
> Allow setting normal and exclusive mode for swarm plugin

- github/ci/prow/files/labels.yaml
- github/ci/prow/files/plugins.yaml
* owner-label sets labels specified in OWNERS files if specific files
have changed
* verify-owners ensures that changed OWNERS files are valid
> Enable verify-owners and owners-label plugin for kubevirt

- github/ci/prow/files/labels.yaml
network, security, storage and virtualization topics are relevant to most, if not all of our repositories. Let us promote them to default ones.
> make 4 of the topic labels default

- github/ci/prow/templates/label-sync.yaml
The label sync binary does not like archived repos. Use a forked build until a rebuild with kubernetes/test-infra#10407 included happens.
> Skip new archived repos in label-sync

- github/ci/prow/tasks/main.yml
- github/ci/prow/templates/ghproxy.yaml
ghproxy is needed to not waste API token requests on github.
/hold
need a PV first.
> Add ghproxy

- github/ci/prow/templates/hook-rbac.yaml
The automatic config-updater needs read permissions for config-maps. Saw in the `hook` logs that it failed accessing them because of our rbac rules. The change is already rolled out and worked for #72.
> The config-updater needs read permissions for config maps

- github/ci/prow/files/jobs/project-infra/project-infra-periodics.yaml
We now decorate periodic jobs, like we should, but that also means that
the command must be explicitly specified, since the decorators override
the entrypoint.
> We now decorate periodic jobs, specify the command explicitly

- github/ci/prow/files/config.yaml
- github/ci/prow/tasks/main.yml
- github/ci/prow/templates/ghproxy.yaml
- github/ci/prow/templates/greenhouse-service.yaml
- github/ci/prow/templates/pushgateway.yaml
Add the pushgateway and configure all prow components to push metrics to it. Greenhouse is the only component which wants to be scraped (under `/prometheus`) and does not want to push metrics.
This PR does not include prometheus itself or a graphana dashboard. It only prepares the ground.
> Pushgateway

- github/ci/prow/tasks/main.yml
- github/ci/prow/templates/cherrypicker_deployment.yaml
- github/ci/prow/templates/deck-deployment.yaml
- github/ci/prow/templates/ghproxy.yaml
- github/ci/prow/templates/greenhouse-deployment.yaml
- github/ci/prow/templates/hook.yaml
- github/ci/prow/templates/horologium-deployment.yaml
- github/ci/prow/templates/label-sync.yaml
- github/ci/prow/templates/memory-defaults.yaml
- github/ci/prow/templates/needs-rebase_deployment.yaml
- github/ci/prow/templates/plank-deployment.yaml
- github/ci/prow/templates/pushgateway.yaml
- github/ci/prow/templates/sinker-deployment.yaml
- github/ci/prow/templates/statusreconciler-deployment.yaml
- github/ci/prow/templates/tide-deployment.yaml
To ensure that different components are not being evicted at runtime, we
should have memory requests and limits set on every deployed container.
Currently, added default req and lim for all the containers and set it
to 510Mi. For components that are expected to consume more memory
(currently greenhouse and deck), we overwrite the defaults.
Also, added pod anti-affinity rules for components with more than one
replica.
> Add memory limits to Prow deployment

- github/ci/prow/files/config.yaml
- github/ci/prow/tasks/main.yml
- github/ci/prow/templates/accounts.yaml
- github/ci/prow/templates/deck-rbac.yaml
- github/ci/prow/templates/hook-rbac.yaml
- github/ci/prow/templates/horologium-rbac.yaml
- github/ci/prow/templates/memory-job-defaults.yaml
- github/ci/prow/templates/plank-rbac.yaml
- github/ci/prow/templates/sinker-rbac.yaml
- github/ci/prow/templates/statusreconciler-rbac.yaml
- github/ci/prow/templates/tide-rbac.yaml
Move Jobs and Pods into a separate namespace, so that jobs are isolated from the prow components and that we can have for instance distinct memory limits.
> Separate namespace

- github/ci/prow/files/config.yaml
- github/ci/prow/files/docker-daemon-mirror.conf
- github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
- github/ci/prow/files/jobs/kubevirtci/kubevirtci-presets.yaml
- github/ci/prow/files/mirror.yaml
- github/ci/prow/files/plugins.yaml
- github/ci/prow/tasks/main.yml
- github/ci/prow/templates/docker-daemon-mirror-config.yaml
- github/ci/prow/templates/memory-job-defaults.yaml
- github/ci/prow/templates/mirror-config.yaml
- github/ci/prow/templates/mirror-service.yaml
- github/ci/prow/templates/mirror.yaml
* Add a docker mirror which can be referenced via `preset-docker-mirror: "true"`
* Add a preset which mounts the shared images directory from stdci via `preset-shared-images: "true"`
* Add e2e kubevirt jobs for all jobs which exist in stdci
> Add demo jobs for kubevirt

- github/ci/prow/files/plugins.yaml
The config updater looks by default into the namespace of the prowjobs.
We have the prowjobs now in a different namespace than the prow
components. Setting the namespace therefore now explicitly for all
config maps. Fixes #88
> Set correct config-map namepspace for config-updater

- github/ci/prow/templates/plank-rbac.yaml
"get" was missing and led to situations where plank can not properly
update prowjobs.
> Give plank "get" access to prowjobs

- github/ci/prometheus/templates/grafana.yaml
- github/ci/prometheus/templates/prometheus.yaml
- github/ci/prometheus/templates/token-counter.yaml
- github/ci/prow/files/jobs/project-infra/project-infra-periodics.yaml
- github/ci/prow/files/jobs/project-infra/project-infra-presubmits.yaml
- github/ci/prow/templates/hook.yaml
The infra zone consist of VMs that can migrate, thus we use
it for running Jenkins instances in order to achieve high availability
(we can't run replicas of Jenkins because they can't share the same
storage).
We prefer not to have other services on the nodes that runs the Jenkins
instances, in order to make it more stable.
> Run Prow services on the CI zone

- github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
- github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml
https://github.com/kubernetes/test-infra/pull/12655 is merged which brings a newer docker version. This docker version is not affected by https://github.com/moby/moby/issues/37581. This allows us to prepare containerized clusters which create containers bigger than 8GB.
> Use newer boostrap image with newer docker

- github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
/hold
Can only be merged after the following preconditions:
* #91 needs to be merged
* https://github.com/kubevirt/kubevirt/pull/2199 needs to be merged
* The stdci webhook needs to be disabled for kubevirt/kubevirt
In case something goes wrong, the tests can be disabled again and the stdci webhook re-enabled.
This does not enable `tide`. It only let's the prow jobs run.
> Always run kubevirt e2e with prow instead of stdci

- github/ci/prow/files/config.yaml
Modified it to `DirectoryOrCreate` instead of `Directory`.
> kubevirt-presubmits: create shared-iso mount type if needed

- github/ci/prow/files/config.yaml
* The new gcs account uses a `kubevirt-prow` bucket
* This will make all old build logs inaccessible
* Since we already loose old logs, we can change the deck urls from `https://deck-kubevirt-prow.apps.ovirt.org` to `https://prow.apps.ovirt.org`
> Prepare switch to official gce account

- github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Reduce number of parallel builds per node to reduce disk pressure. Will reduce the errors where docker daemon needs too long to come up.
> Set memory requests higher to reduce parallel runs per node

- github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
With max_concurrency set to 5, we're taking
all the available resources of the cluster
and other projects end up waiting for too
long time before they get a some compute
resources.
> Reduce max_concurrency of presubmits to 3

- github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Renamed okd-4.1.0-rc.0 to okd-4.1.0, which aligns it with what we have in kubevirtci in the meanwhile
> Removed rc0 postfix of okd4 job

- github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml
Packet nodes use a MTU of 1450. Our DIND setup defaults to 1500 in the kubevirtci jobs. Inject the correct docker config.
> Set right docker MTU also for kubevirtci jobs

- github/ci/prow/files/config.yaml
- github/ci/prow/files/labels.yaml
- github/ci/prow/files/plugins.yaml
**Added Kubevirt-Tutorial repo to Prow CI/CD**
- Added Config to manage AutoMerges on Kubevirt-Tutorial repo
- Added Plugins:
- approve
- lgtm
- owners-label
- config-updater
- skip
- override
- trigger
- Added Labels for this concrete repo:
- kind/lab-updates
- kind/lab-deployment
- kind/new-lab
> Feat: Adding Kubevirt-Tutorial to Prow config allowing repo management

- github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
The long running build lanes have a big backlog while we have resources
free.
> Double allowed concurrent builds for all kubevirt prow jobs

- github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml
Let's keep the same naming pattern for each job.
> change push job name for k8s-multus-1.13.3

- github/ci/prow/files/jobs/project-infra/project-infra-periodics.yaml
- github/ci/prow/files/plugins.yaml
Trigger /retest on one PR per hour at most which is approved.  This does
not enable tide. It should only help maintainers to not have to go back
to PRs and type retest there.
> Add automatic retest capability for kubevirt/kubevirt

- github/ci/prow/templates/accounts.yaml
- github/ci/prow/templates/greenhouse-deployment.yaml
- github/ci/prow/templates/mirror.yaml
The caches write to hostPaths, give them their own service account which
is allowed to use hostPaths.
@slintes already rolled out. Was necessary to let the containers start.
> Give caches their own serviceaccount

- github/ci/prow/files/config.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Tide is now enabled for kubevirt and will treat travis and coveralls as external required tests.
Further the test-run configuration looks now like this:
All e2e test are required, but don't run all of them until the PR is
approved.
The following tests will always run:
* pull-kubevirt-e2e-k8s-1.13.3
* pull-kubevirt-e2e-k8s-multus-1.13.3
* pull-kubevirt-e2e-os-3.11.0-crio
The following tests will only be run when a PR is in the merge pool:
* pull-kubevirt-e2e-k8s-1.11.0
* pull-kubevirt-e2e-k8s-genie-1.11.1
* pull-kubevirt-e2e-os-3.11.0-multus
* pull-kubevirt-e2e-windows2016
Tests which by default only run in the merge-pool can still be triggered
via `/test <name>` or `/test all` and will be rerun if `/retest` is done
afterwards.
> Tide for kubevirt/kubevirt

- github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Now we only run a subset of jobs when PRs are opened. They can now run
more often, since the other tests don't run by default that often
anymore. They only run when the PR is in the mergepool or if they are
manually triggered. This should help to bring PR faster into the merge
pool.
> Allow jobs which run always to run more often

- github/ci/prow/files/jobs/project-infra/project-infra-periodics.yaml
- github/ci/prow/tasks/main.yml
Prow ignores `/retest` from itself. Therefore we need an extra commenter bot account.
> Add commenter bot token

- github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
We don't want to block jobs which need to run with max parallel builds,
if resources are available, but we also don't want to run too many jobs
in general on a node. More adjustments may follow. This is the reaction of seeing more jobs, which have issues to start DIND properly.
> Use more memory to reduce the amount of parallel jobs

- github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
This PR configures a new job for running kubevirt tests that need a sriov device.
> Add job for sriov ci

- github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
https://github.com/kubevirt/project-infra/pull/138 added a job for sriov ci but the pod antiaffinity section is wrong, so multiple pods are running at the same time causing tests to fail.
> Fix the pod antiaffinity spec under affinity

- github/ci/prow/files/config.yaml
- github/ci/prow/tasks/main.yml
- github/ci/prow/templates/gcsweb-deployment.yaml
- github/ci/prow/templates/gcsweb-service.yaml
- github/ci/prow/templates/routes.yaml
Add a gcsweb viewer which allows browsing test artifacts.  With this
config, an `Artifacts` button is visible in spyglass which points to all
artifacts uploaded by the job into gcs.
> Deploy gcsweb viewer

- github/ci/prow/files/jobs/kubevirt-tutorial/kubevirt-tutorial-periodics.yaml
- github/ci/prow/files/jobs/kubevirt-tutorial/kubevirt-tutorial-presubmits.yaml
- github/ci/prow/files/jobs/kubevirt.github.io/kubevirt-github-io-periodics.yaml
- Added Periodic job to test laboratories every 96h
- Added Presubmit job to test labs on every PR
- Both, periodics and presubmits jobs uploads log files for every lab tested, also the log from the Job (more info at https://github.com/kubevirt/kubevirt-tutorial/pull/105 PR)
- Refactored kubevirt.io link-checker job using extra-refs instead of a raw git clone
WIP: Still waiting on https://github.com/kubevirt/kubevirt-tutorial/pull/105 to be merged before continue with this one.
> Feat: Added Kubevirt-Tutorial related jobs for lab testing

- github/ci/README.md
- github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits-0.17.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
* Lock master jobs to non-release branches 
* Ensure that we have a sane and locked set of CI jobs for 0.17 release.
The jobs were generated with the config-forker from test-infra. Related to #121. We are still at a very dark spot for our longterm 0.13 release branch.
> Release 0.17 jobs

- github/ci/prow/files/jobs/virtblocks/virtblocks/virtblocks-periodics.yaml
While technically the `pull-virtblocks-vet` and `pull-virtblocks-fmt` jobs don't need `libtool` to run, it makes sense that all jobs for the projects would use the same container image.
> Use same container image for all Virt Blocks jobs

- github/ci/prow/files/jobs/virtblocks/virtblocks/virtblocks-periodics.yaml
This is necessary as of https://github.com/virtblocks/virtblocks/commit/42b2615357c41780abcc973cd2224e945da9f528.
> virtblocks: Set VIRTBLOCKS_LANGUAGE=golang

- github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
relevant PR in kubevirt is not merged yet
> reverted k8s-1.11.0 / k8s-1.15.1-ceph change

- github/ci/prow/files/jobs/virtblocks/virtblocks/virtblocks-periodics.yaml
Build the Rust code along with the Go code; in addition to building, run the test suite and the example programs too.
Doing this requires using a custom container image that includes a Rust compiler.
> Virt Blocks update

- github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Once https://github.com/kubevirt/kubevirtci/pull/134 and https://github.com/kubevirt/kubevirt/pull/2628 are merged, the dependency with pciutils is not needed anymore since the setup is done via the openshift sriov operator, but the operator needs envsubst in order to work so we are installing it before running the tests.
> Remove pci-utils, install gettext in for sriov lane (switch to sriov-operator)

- github/ci/prow/files/labels.yaml
Will be used via OWNER file in kubevirt/kubevirt repo in order to raise awareness for build changes
> Added build-change label

- github/ci/prow/files/labels.yaml
added missing color and target for area/virtctl
> Fixed label config of area/virtctl

- github/ci/prow/files/jobs/kubevirt/kubevirt-periodics.yaml
- robots/flakefinder/index.go
- robots/flakefinder/main.go
- robots/flakefinder/report.go
- robots/flakefinder/report_test.go
Sort tests descending by severity, so that worst (red) test cells are shown at the top of the report.
Furthermore add `--preview` flag to not meddle with existing reports, i.e. old reports are not overwritten any more if flag is used, if flag is used reports are written to `.../preview` subdirectory instead.
[Report preview available here.](https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/preview/flakefinder-2019-09-05-024h.html)
**Note: this is a quick shot, sorting is not really descending, it rather is grouped as not the number of failed tests has been used but the severity instead. However, the effect is good...**
/cc @fedepaol 
/cc @fabiand 
Closes #186
> Sort report data descending by severity

- github/ci/prow/files/jobs/kubevirt/kubevirt-periodics.yaml
- robots/flakefinder/BUILD.bazel
- robots/flakefinder/index_test.go
- robots/flakefinder/report.go
- robots/flakefinder/report_test.go
- vendor/github.com/onsi/ginkgo/extensions/table/BUILD.bazel
- vendor/github.com/onsi/ginkgo/extensions/table/table.go
- vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go
- vendor/modules.txt
Test sorting has been revised so that the sorting of tests now accurately reflects the total test severity over all lanes. If severity of test lanes are equal they are sorted lexically.
Previews:
- [4 weekly](https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/preview/flakefinder-2019-09-19-672h.html)
- [weekly](https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/preview/flakefinder-2019-09-19-168h.html)
- [daily](https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/preview/flakefinder-2019-09-19-024h.html)
> Improve flakefinder test sorting

- github/ci/prow/files/config.yaml
- github/ci/prow/files/plugins.yaml
In order to avoid tide automatically merging PRs having this label
we later on can enable the dco plugin per repo or for the whole org
to enforce commit signoff.
We might think about making the dco check mandatory by branch-protection
to avoid being able to manually merge PRs failing the dco check.
/cc @rmohr
> Add dco-signoff:no to missingLabels for tide

- github/ci/prow/files/jobs/kubevirt/kubevirt-periodics.yaml
- robots/flakefinder/downloader.go
- robots/flakefinder/main.go
Checks file creation date of `finished.json` to be after report start date, if that's not the case, test results are skipped.
/cc @fedepaol @rmohr
> Filter test results before start of report

- github/ci/prow/files/plugins.yaml
Enable the DCO plugin for the virtblocks org.
> Enable DCO plugin for virtblocks org

- robots/flakefinder/flakefinder_suite_test.go
- robots/flakefinder/index_test.go
- robots/flakefinder/report_test.go
In regards to the discussion [here](https://github.com/kubevirt/project-infra/pull/196#discussion_r327004586) I moved the boolean flag into a command line parameter.
**Note to reviewer:** I was forced to use `BeforeEach` and checking a conditional as the `flag.Parse()` is executed **after** the declarations on `When` level. I find this a little ugly and am open for suggestions. I tried with `BeforeSuite` but this is allowed only once and I wanted to keep the initialization of the variables in scope.
see #196 for details.
> Convert boolean logging flag into command line flag

- github/ci/prow/files/jobs/virtblocks/virtblocks/virtblocks-presubmits.yaml
Add an e2e job which runs on machines with /dev/kvm and update to the new builder image which contains golang and qemu.
> Add e2e job for virtblocks

- github/ci/prow/files/jobs/kubevirt/kubevirt-periodics.yaml
- robots/flakefinder/BUILD.bazel
- robots/flakefinder/main.go
- robots/flakefinder/main_test.go
Two new configurations are now available
--pr_base_branch=master
This parameter marks the base branch on which PRs are filtered now, i.e. only PRs that are merged into `master` in this case.
--report_output_child_path=master
This parameter adds a further path for where the reports are written, i.e. in this case it will write to `reports/flakefinder/master`
These should help us to diversify the reports as needed.
Preview reports available [here](http://storage.googleapis.com/kubevirt-prow/reports/flakefinder/preview/master/index.html).
Closes #200.
> Filter PRs on base branch, add output path config

- github/ci/prow/files/config.yaml
- github/ci/prow/files/jobs/project-infra/project-infra-periodics.yaml
[Branchprotector](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/branchprotector) is a tool to configure [GitHub branch protection](https://help.github.com/articles/about-protected-branches/). This i.e. enables to require status checks to succeed on PRs, so that these only then can get merged.
The job executing Branchprotector regularly enforces the configured rules on several levels, i.e. branch, repo, org or even over multiple orgs.
This gives us the opportunity to centralize the configuration of required status checks in one place, in the Prow plugin configuration that is located in `project-infra`.
All repository maintainers of the kubevirt org having repo admin rights, please reply with a list of required status checks and the branches you would like to protect. In the …
> Add automatic branch protection via prow job for kubevirt org and possibly virtblocks org 

- github/ci/prow/files/config.yaml
- github/ci/prow/tasks/main.yml
- github/ci/prow/templates/branch-protector.yaml
Branch protection config:
- For minimal set of repositories enable dco check as required on master
- For kubevirt additionally enable dco check on all branches
Added job to execute branch protector.
> Add branch protection to kubevirt org

- github/ci/prow/files/jobs/kubevirt/kubevirt-periodics.yaml
- robots/flakefinder/index.go
- robots/flakefinder/index_test.go
- robots/flakefinder/main.go
- robots/flakefinder/report.go
- robots/flakefinder/report_test.go
Adds command line parameters for GitHub `org` and `repo`, so that the report generation is no longer hardcoded on kubevirt/kubevirt but can instead be done for any project that stores it's test run results in a similar location on our prow instance. Test format must be same as used for kubevirt/kubevirt, though.
Based on this PR we can add additional job specs for cdi.
/cc @rmohr @awels
> Add command line options org and repo for report generation.

- github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Docker is extensively tested on the k8s lanes. Now with release-0.22 we can stop testing the os-3.11 and docker combination on master.
> Remove openshift-docker testlane for master

- github/ci/prow/files/jobs/containerized-data-importer/containerized-data-importer-periodics.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt-periodics.yaml
Add daily, weekly and monthly job for cdi, adjust output path
for kubevirt.
New report urls will be
* http://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/containerized-data-importer/index.html
* https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/index.html
/cc @awels @rmohr 
> Add flakefinder report generation for cdi

- github/ci/prow/files/labels.yaml
Fixes an issue where openshifts prow instance wants to set that label.
It is a no-op for us right now to unblock openshift CI.
> Add label for openshift CI

- github/ci/prow/files/config.yaml
- github/ci/prow/files/jobs/containerized-data-importer/containerized-data-importer-presubmits.yaml
coveralls is not configured properly and the results are never reported so the branch protection is not helping.
Disable automatic running of OKD lane to reduce load on system.
> Disable automatic running of OKD and remove coveralls branch protection.

- github/ci/prow/files/jobs/kubevirt/kubevirt-periodics.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits-0.13.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits-0.17.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits-0.20.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
- github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml
- Add okd-4.1 periodic job
- Make all os-3.11 lanes optional (from 0.17+)
- Remove provision and push for OKD 4.2
> Cleanup okd lanes

- github/ci/prow/files/config.yaml
> Remove travis protection from hostpath provisioner and operator.

- github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits-0.22.yaml
Removed remaining okd-4.2 lane.
/cc @rmohr @slintes 
> Remove okd-4.2

- github/ci/prow/files/jobs/containerized-data-importer/containerized-data-importer-presubmits.yaml
> Make k8s 1.15 and OS 3.11 lanes required in CDI

- github/ci/prow/files/jobs/kubevirt/kubevirt-periodics.yaml
- robots/flakefinder/main.go
- robots/flakefinder/report.go
- robots/flakefinder/report_test.go
Use the PR Ids before filtering instead of collecting them while
checking report results. Also now link the numbers to the PRs from
github.com .
> Use source PR IDs instead of report PRs

- github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
As the k8s-1.16 provider has been merged we should enable it.
/cc @rmohr
> Always run k8s-1.16 test lane

- github/ci/README.md
When creating an ssh key via `ssh-keygen` the key is stored in OpenSSH format by default, as opposed to being stored in PEM earlier on. For the new key format the ./decrypt.sh will not work any more. Added a description of how to fix this in the README.md. 
/cc @rmohr @cynepco3hahue
> Add solution for id_rsa not in PEM format

- github/ci/prow/files/jobs/project-infra/project-infra-postsubmits.yaml
- github/ci/prow/files/jobs/project-infra/project-infra-presets.yaml
In order to publish the container to our org in dockerhub,
we need to have the credentials mounted.
> Add presets with kubevirtci secret

- github/ci/prow/files/jobs/containerized-data-importer/containerized-data-importer-periodics.yaml
- robots/flakefinder/update-jobs-with-latest-flakefinder-image.sh
Updated the image shas for cdi to use latest flakefinder version.
Fixed the update script. The script only updated the shas for kubevirt/kubevirt,
this fix now updates any *-periodics.yaml below github/ci/prow/files/jobs containing 
flakefinder image references.
> Fix script that updates flakefinder image shas in periodics

- github/ci/prow/files/plugins.yaml
Instead of operating on the entire org, we want just to
enable this check for a single project.
> Enable needs-rebase for kubernetes-nmstate only

- images/kubevirt-infra-bootstrap/Dockerfile
Update slave image with packages which are required for
ansible-kubevirt-modules.
> Update slave image

- images/kubevirt-infra-bootstrap/Dockerfile
Required for ansible-kubevirt-modules
> Add pip to the slave image

- github/ci/prow/files/jobs/ansible-kubevirt-modules/ansible-kubevirt-modules-presubmits.yaml
- The job of this projects requires pip, which was installed
in the slave image that was added in this commit.
- Fix the job's name.
> Fix ansible-kubevirt-module job

- github/ci/prow/files/jobs/nmstate/kubernetes-nmstate-postsubmits.yaml
kubernetes-nmstate need more than 1gb of memory to build.
> Remove limits from knmstate publish job

- github/ci/prow/files/jobs/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
* drop OKD CI lane since it is broken, it will be replaced by OCP in a follow up
* fix names of workflow lanes
> Fix cnao name and drop okd

- github/ci/prow/files/jobs/nmstate/kubernetes-nmstate-presubmits.yaml
We want to test against D/S too. The underlying system and the
NetworkManager version there may be different. Also, OCP lane seems
to be more stable than OKD.
This also mark the OKD lane as optional since it is consistently
*not* working.
> add OCP job to knmstate

- github/ci/prow/files/jobs/common-templates/common-templates-presubmits.yaml
This PR enables win 2019 test. This job is optional, because i need to verify if win2019 can boot in prow.
//cc @dhiller 
Signed-off-by: Karel Šimon <ksimon@redhat.com>
> enable windows 2019 test for common templates

- github/ci/prow/files/docker-daemon-mirror.conf
To run ipv6 jobs we need docker daemon to be properly configured as stated here  kubevirt/kubevirtci#241.
> Add ipv6 config for docker daemon

- github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml
Running kind at dind depends on [1]
[1] https://github.com/kubernetes-sigs/kind/issues/303
> Mount /lib/modules and /sys/fs/cgroup for kind ipv6 job

- github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml
We are creating a k8s provider based of fedora [1], for that we need a pair of jobs to to build the base images for those, same we have for centos nodes.
[1] https://github.com/kubevirt/kubevirtci/pull/246
> Add fedora base image jobs

- github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
This reverts commit 38bcee49bf59b54f15c5c40cc853317771230e43.
https://github.com/kubevirt/kubevirt/pull/3026 should have fixed the issues
with the lane.
> Revert "Disable auto-run for the sr-iov lane (#297)"

- github/ci/prow/files/jobs/project-infra/project-infra-periodics.yaml
The commenter bot is only updated at `gcr.io/k8s-prow/commenter` for some time now. Some jobs still point to the old location. These jobs are now broken because I updated to a newer tag. Fixing this.
> Use new location for commenter images

- github/ci/prow/files/config.yaml
- github/ci/prow/files/jobs/macvtap-cni/OWNERS
- github/ci/prow/files/jobs/macvtap-cni/macvtap-cni-postsubmits.yaml
- github/ci/prow/files/jobs/macvtap-cni/macvtap-cni-presubmits.yaml
- github/ci/prow/files/plugins.yaml
> add macvtap-cni jobs

- github/ci/prow/files/config.yaml
- github/ci/prow/tasks/main.yml
- github/ci/prow/templates/crier-deployment.yaml
- github/ci/prow/templates/crier-rbac.yaml
We report periodics, batch and postsubmits when they fail, since it is
hard to track that they are failing otherwise.
> Enable crier to report failing tests on slack

- github/ci/prow/templates/sinker-rbac.yaml
sinker now requires access to a new config-map and it needs to be able
to get and list prowjobs
> Update sinker role

- github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Adjust the kubevirt jobs to use the new provision layout in kubevirtci.
Once #358 is merged, this one can go in.
> Adjust kubevirt jobs to the simplified provision layout

- github/ci/prow/files/config.yaml
Fails on k8snetworkplumbingwg dues to permission issues, so we're removing it for now.
> Remove k8snetworkplumbingwg branch protection

- github/ci/prow/files/jobs/containerized-data-importer/containerized-data-importer-periodics.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt-periodics.yaml
- github/ci/prow/files/jobs/nmstate/kubernetes-nmstate-periodics.yaml
- robots/flakefinder/main.go
- robots/flakefinder/report.go
- robots/flakefinder/update-jobs-with-latest-flakefinder-image.sh
In order to avoid triggering the kubevirtprow bot (who thinks there is
an error in the logs and sounds an alarm then) we introduce a flag to
enable switching stdout printing of report (default is off).
References:
* [slack message](https://coreos.slack.com/archives/CTFN306KC/p1582048325001900)
* [log output](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-publish-kubevirt-flakefinder-weekly-report/1229810288421769216)
> Add stdout flag to flakefinder, default is false

- github/ci/prow/files/config.yaml
This adds the branch protection settings for k8snetworkplumbingwg/kubemacpool again.
This reverts commit 5f93466cde82e08edf74b1dd77a12881ed8a6366.
/cc @phoracek @qinqon
> Revert "Remove k8snetworkplumbingwg branch protection (#370)"

- images/kubevirt-infra-bootstrap/Dockerfile
[kustomize](https://kustomize.io/) is a tool used to customize application configuration files. 
Currently [kubemacpool project](https://github.com/k8snetworkplumbingwg/kubemacpool) uses this tool during the ci tests, and so there is a need to add it to the Bootstrap Docker file (currently failing due to this). 
> adding kustomize tool to bootstrap Docker file

- github/ci/prow/files/jobs/k8snetworkplumbingwg/kubemacpool-presubmits.yaml
Following the insertion of prow tests to [kubemacpool project](https://github.com/k8snetworkplumbingwg/kubemacpool/), PRs are failing because kustomize tool is [needed](https://github.com/k8snetworkplumbingwg/kubemacpool/blob/b69c56e0ef0d080b5391aef151273e2746b0bb25/Makefile#L39). 
After updating the project-infra Dockerfile in an already merged [PR](https://github.com/kubevirt/project-infra/pull/373), changing the kubemacpool base image tag should solve the failing PRs.
> update kubemacpool base image for prow tests

- images/kubevirt-infra-bootstrap/Dockerfile
Since dash is commonly used in project infra, in order to allow access to kustomize for containers using the Dockerfile base image, we need to move kustomize to /usr/bin folder.
The former copying to .bashrc is relevent only for /bin/bash applications. copying to this path will work for both shells.
> changing kustomize path to /usr/bin

- github/ci/prow/files/jobs/k8snetworkplumbingwg/kubemacpool-presubmits.yaml
Following the [PR #375](https://github.com/kubevirt/project-infra/pull/375) where a sym link was added to make kustomize ready for dash shell, we update the [kubemacpool](https://github.com/k8snetworkplumbingwg/kubemacpool) image for prow tests.
> updating the base image so that kustomize will be accessible to dash

- github/ci/prow/files/jobs/cluster-network-addons-operator/cluster-network-addons-operator-postsubmits.yaml
Building of the images is still done via Travis. That will be resolved in
a follow-up PR.
CNAO automation PR: https://github.com/kubevirt/cluster-network-addons-operator/pull/330
> add CNAO GitHub release automation

- github/ci/prow/files/config.yaml
There is no simple way to rerun a postsubmit job in Prow in the current state.
With this patch, we are adding a support for kubevirt's "prow-job-taskforce"
members to retrigger a run of a build through the Deck UI.
> allow rerun of builds through UI

- github/ci/prow/files/jobs/ovs-cni/ovs-cni-presubmits.yaml
Needed for: https://github.com/kubevirt/ovs-cni/pull/115
> rename ovs-cni e2e tests target

- github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
With regard to kubevirt/kubevirt#3053 we still need to enable the check so that it runs on changes.
> Enable flaky tests check

- github/ci/prow/files/jobs/containerized-data-importer/containerized-data-importer-presubmits.yaml
Wasn't properly exporting environment variables for ember lane and they were not being picked up. This fixes the exports.
> Export snapshot/block sc properly in ember lane.

- github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
It generates a lot of noise in CI. Let's drop it.
> sriov: silence tar extracting

- github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Prow checks out the base branch and merges the pr branch
on top of it, so the last merge commit is ofcourse the
current HEAD. This leads to "no files changed" when trying to
fetch changed files after last merge commit (which is done
by default in the script.
Therefore we explicitly set TARGET_COMMIT to the base branch
sha.
> Set TARGET_COMMIT to base sha

- github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Support for Genie is being dropped from kubevirt together with its test-lane.
* kubevirt: https://github.com/kubevirt/kubevirt/pull/3206
* kubevirtci: https://github.com/kubevirt/kubevirtci/pull/325
> remove Genie test lane from kubevirt

- github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Has being already tested multiple times.
Testing PR with kubevirt automation change: https://github.com/kubevirt/kubevirt/pull/3131
Prow job https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3131/pull-kubevirt-e2e-k8s-cnao-1.17/1242422026359017472
> Replace kubevirt multus lane with k8s-cnao-1.17

- github/ci/prow/files/config.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt-periodics.yaml
- github/ci/prow/files/jobs/kubevirtci/kubevirtci-presets.yaml
In order to consume the build from openshift ci (see openshift/release#8123) we push the images to docker registry beforehand.
> Create job to build and push kubevirt nightly to docker

- github/ci/prow/files/jobs/kubevirt/kubevirt-periodics.yaml
Set current schedule more close to midnight.
> Start periodic job for KubeVirt nightly build shortly after 1 AM

- github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Let's reduce the CI load while this lane can't succeed. The Job will now report to github, but it will only be run if you explicitly do
```
/test pull-kubevirt-e2e-k8s-1.17
```
> Make k8s-1.17 job report, but don't run it always

- github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Ipv6 support was introduced to kubevirt in
PR https://github.com/kubevirt/kubevirt/pull/3112
kind-k8s-1.17.0-ipv6 was green prior merging the PR.
To avoid regressions, the lane is changed to be always run.
However, since currently there are some flaky tests, the lane will
still be optional and skip reports until it stays green.
> Always run kind-k8s-1.17.0-ipv6

- github/ci/prow/files/jobs/common-templates/common-templates-presubmits.yaml
Change the memory requests for common-templates to match kubevirt's and to solve
"cannot allocate memory" issues that frequently happen when running test lanes
Signed-off-by: Omer Yahud <oyahud@redhat.com>
> Change the memory requests for common-templates

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The test suite should now pass with SELinux enabled (enforced), since https://github.com/kubevirt/kubevirt/pull/3371.
Making the 1.17 lane always run and block PRs will ensure we don't introduce new denials.
> Make k8s-1.17 job run always but still optional for now

- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
The current job is failing on commit. By adding the GIT_AUTHOR environment variables and adding the GIT_ASKPASS step I got so far as it can create the commit, push to the fork, but now it fails when trying to create the PR against kubevirt/project-infra:
```
...
time="2020-05-08T12:49:30Z" level=info msg="GetFile(virtblocks, virtblocks, OWNERS, )" client=github                           
time="2020-05-08T12:49:36Z" level=info msg="GetFile(virtblocks, virtblocks, OWNERS_ALIASES, )" client=github                                                                                                                                                  
time="2020-05-08T12:49:43Z" level=warning msg="Ignoring the repo with no OWNERS file in the upstream repo." orgRepo=virtblocks/virtblocks …
```
> Fix autoowners job failing to commit by adding GIT_AUTHOR variables

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Since ipv6 was introduced to kubevirt few PRs broke the lane.
To avoid this situation in the future, the lane should be required.
> Since ipv6 lane is green - make it required

- github/ci/prow/files/jobs/kubevirt/vm-import-operator/vm-import-operator-presubmits.yaml
This PR changes vm-import-operator post-submit job to pre-submit.
> Change vm-import-operator job from post to pre

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
SR-IOV deployments are broken more often than not, and that is
easily explained since it does not vote in CI, and does not even
run.
This is a step in that direction; run it, but don't have it voting.
We intend to actively debug the sriov lane, and nurture it back to
a healthy state, then have it voting in CI.
Signed-off-by: Miguel Duarte Barroso <mdbarroso@redhat.com>
> sriov: run lane on each PR

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
This lane is unstable. We want to collect logs, so it runs on the
background, but it should not add noise to PRs.
> sriov: don't show results on PRs

- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
- robots/flakefinder/report.go
New code we merged into vendor requires go 1.13 already.
> Go 1.13 for flakefinder

- github/ci/prow/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-2.4.yaml
- github/ci/prow/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
hco: move to OCP 4.4 and k8s 1.17.0 and add a new config for release-2.4 branch
> hco: move to OCP 4.4 and k8s 1.17.0 and add a new config for release-2.4 branch

- github/ci/prow/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-2.4.yaml
- github/ci/prow/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
kubevirt-ci lane for k8s-1.17 is named "k8s-1.17", and not "k8s-1.17.0".
This PR updates the ${TARGET} var to be corresponding with the actual name of the kubevirt-ci provider.
https://github.com/kubevirt/kubevirtci/tree/master/cluster-up/cluster/k8s-1.17
> fix k8s-1.17 lane name

- github/ci/prow/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-2.4.yaml
- github/ci/prow/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
Temporary disable OCP 4.4 lanes on HCO repo
because is still not stable enough to be
used on development tests.
> Temporary disable OCP 4.4 lanes on HCO repo

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Improves upon the nightly build creation job by uploading the kubevirt-operator manifest and cr to the gcs bucket `kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/${build_date}`. Furthermore it uploads the commit id into the file `commit` and puts a file `latest` containing the build date in YYYYMMDD format into the parent folder.
Example uploads: 
* https://storage.googleapis.com/kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/20200609/commit
* https://storage.googleapis.com/kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/20200609/kubevirt-operator.yaml
* https://storage.googleapis.com/kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/20200609/kubevirt-cr.yaml
* https://storage.googleapis.com/kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/latest
> Upload operator manifest, upload commit id

- github/ci/prow/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-presubmits.yaml
CI script in nmo have been adjusted to use upstream CI, now we can run
openshift 4.3 with every build.
> Enable the 4.3 job for NMO and make it blocking

- github/ci/prometheus/templates/prometheus.yaml
The pod was constantly being OOM killed.
Note: this is a temporary solution. Until we set up a more
serious Prometheus deployment.
> Increase memory requirements for Prometheus pod

- github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
This PR removes `kind-k8s-sriov-1.14.2` check up job following https://github.com/kubevirt/kubevirtci/pull/384.
and add a job for the newer provider `kind-k8s-sriov-1.17.0`.
The job name changed to `check-up-kind-1.17-sriov`, as preparation to changing provider name:
from: `kind-k8s-sriov-1.17.0`
to:     `kind-1.17-sriov`
> Update SRIOV provider check-up job

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
This PR set the sriov-lane job to not run on every PR change,
until those PR are merged 
https://github.com/kubevirt/kubevirtci/pull/378
https://github.com/kubevirt/kubevirt/pull/3509
This PR also rename the job name to `pull-kubevirt-e2e-kind-1.17-sriov`, as preparation to changing provider name:
from: kind-k8s-sriov-1.17.0
to: kind-1.17-sriov
> Disable sriov lane until provider is stabilized

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
We bump the ceph lane to use k8s-1.16 and to avoid friction we make the lane optional.
> Bump ceph lane to use 1.16 provider , make it optional

- github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
This PR fixes `check-up-kind-1.17-sriov` job by adding missing `export` to `KUBEVIRT_PROVIDER`
and exports `KUBEVIRT_NUM_NODES=2`.
> Fix sriov check-up job

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The recently bumped lane has issues, therefore we disable status
reporting to not cause more friction.
Relates to kubevirt/kubevirt#3622
> Skip reporting of status to GitHub for 1.16 ceph lane

- github/ci/prow/files/labels.yaml
In order to assign the label one can write `/triage build-officer`.
> Build officer label which can be used with the label plugin

- github/ci/prow/templates/label-sync.yaml
The kubevirt-bot only has access to one repo within the nmstate org and
the nmstate org maintainers would like to keep it that way, so we split
the job into two, one per org, where the nmstate job only updates one
repo.
Fixes #477
> Split label-sync job into one per org

- github/ci/prow/files/labels.yaml
It is replaced with triage/build-officer, so that people can use the
label plugin for assigning it.
> Remove the old build-officer label

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
For ease of use we add the test infra manifests to make them more easily consumable by the nightly build.
> Add test infra manifests to nightly release

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.30.yaml
This is following PR for https://github.com/kubevirt/project-infra/pull/483
kubevirt-bot running the wrong sriov-lane jobs on PRs from kubevirt `release-0.30` branch
https://prow.apps.ovirt.org/?job=pull-kubevirt-e2e-kind-k8s-sriov-1.17.0
This PR disable sriov lane job also on kubevirt `release-0.30` branch until https://github.com/kubevirt/kubevirt/pull/3509 is merged to master and to `release-0.30` branch.
This PR also rename the job name to `pull-kubevirt-e2e-kind-1.17-sriov` in order to align with the sriov lane prow  job configuration on kubevirt master branch.
> Disable sriov lane until provider is stabilized on release-0.30 branch

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Cluster up of it is broken, it uses resources,
and alter prow statistics with its failures.
Since it fails all the time, we dont need the statistics.
See 
https://github.com/kubevirt/kubevirt/issues/3622
> Disable pull-kubevirt-e2e-k8s-1.16-ceph auto run

- github/ci/prow/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits-1.13.yaml
This is based on an older version of the test file.
This is done as the KUBEVIRT_PROVIDER lanes do not exist in those names on the release-v1.13 branch.
> Add testing for CDI release-v1.13 branch.

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
This is the first step of migrating all our CI workloads to Prow. Our
worker nodes have more juice than what Travis gives us and it will allow
us to make a pipeline out of this job in the future.
> Run Travis test script on Prow

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
This PR enable sriov lane to run on every change, report and decrease timeout.
This should be merged only after https://github.com/kubevirt/kubevirtci/pull/378 and 
https://github.com/kubevirt/kubevirt/pull/3509 are merged.
> Enable sriov lane back on master branch

- github/ci/prow/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Soon to replace k8s-1.16 lanes, we'd like to keep up to date with the latest k8s releases.
This is copy-pasted from the k8s-1.16 lanes with the version swapped and changing optional to true.
Would quickly error out until https://github.com/kubevirt/containerized-data-importer/pull/1252 is merged.
> Add optional k8s-1.18 lanes to CDI.

- github/ci/prow/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-periodics.yaml
- github/ci/prow/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-periodics.yaml
- robots/flakefinder/index.go
- robots/flakefinder/index_test.go
- robots/flakefinder/main.go
- robots/flakefinder/main_test.go
- robots/flakefinder/report.go
- robots/flakefinder/report_test.go
Setting `--today=true` will now lead to a report with data range from start of day until report start.
Furthermore report start _and_ end dates are now normalized to avoid overlapping of fetched PRs. Report end will now be  normalized to the end of the previous day when report generation has been triggered.
I.e. 024h report was triggered on 2020-06-30T03:04:00Z, then
report data will contain PRs
from 2020-06-29T00:00:00Z
till 2020-06-29T23:59:59.999Z
Added `--dry-run` in the process, so that we won't overwrite files on gcp any more, thus making local testing easier. If `--dry-run` is used, the generated reports and index page are written to standard out instead.
Report examples entry link is here, what you will see is three examples of the new reports, top line (30-06) contains an example …
> flakefinder: add rolling window report

- github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
This is inspired by looking at [flakefinder reports for CNAO](https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/cluster-network-addons-operator/index.html)
They seem to point at kubevirt/kubevirt rather than kubevirt/cluster-network-addons-operator, I was blindly searching for what could've caused it.
> Specify repo, so we don't default to "kubevirt"

- github/ci/prow/tasks/main.yml
Without explicitly specifying the context, the module uses the default
systems KUBECONFIG. We want to use the KUBECONFIG from the vars to
ensure that we have enough permissions to deploy all the components.
> Add missing K8s context to the playbook

- github/ci/prow/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-periodics.yaml
- github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
- github/ci/prow/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-periodics.yaml
As of latest changes to flakefinder the report data coverage interval
is normalized against start of resp. end of day to avoid overlapping PRs
in two adjacent reports. Now the flakefinder weekly reports are run
somewhere during the day using `interval` which may lead to them running
late in the day and therefore not being available.
We use cron and let them run somewhere after midnight (also adding some
variance) to have them available at the start of the day for when the
build officer starts working.
> Change weekly flakefinder report to run as cron

- robots/flakefinder/report.go
Move popup to the bottom below the cell so that it is displayed always. Also remove the arrow pointing to the bottom.
Example report: https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/preview/kubevirt/kubevirt/flakefinder-2020-07-01-168h.html
> Fix popup bug

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
It is failing 100 % of the time. Let's just use it to gather some data
in the background for now.
There is no value in showing always-failing lane on all PRs.
> hide results of SR-IOV lane

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Should be stable enough, and we need it as a guard.
> Update pull-kubevirt-e2e-k8s-1.18 to be mandatory

- Makefile
- github/ci/prow/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-periodics.yaml
- github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
- github/ci/prow/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
- github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-periodics.yaml
- robots/flakefinder/BUILD.bazel
- robots/flakefinder/downloader.go
- robots/flakefinder/index.go
- robots/flakefinder/main.go
- robots/flakefinder/main_test.go
- robots/flakefinder/report.go
- robots/flakefinder/report_test.go
- robots/indexpagecreator/BUILD.bazel
- robots/indexpagecreator/Makefile
- robots/indexpagecreator/main.go
- robots/indexpagecreator/update-jobs-with-latest-indexpagecreator-image.sh
- robots/pkg/flakefinder/BUILD.bazel
- robots/pkg/flakefinder/flakefinder.go
This PR introduces automation for updating the [flakefinder project overview page](https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/index.html), which is serving as global entry page for all projects covered by flakefinder reports.
There are two parts:
- the page creation tool that is contained within a container image
- the job executing the tool on a 24h schedule
Furthermore:
- the code that could be reused has been moved into the flakefinder package
- the bazel files have been updated to enable building tool binary and container image with it
- another script to update the images on all jobs after push has been added
> Automate the master index page creation for the flakefinder entry page

- github/ci/prow/files/config.yaml
- github/ci/prow/files/plugins.yaml
In order to avoid that people mention other people or close issues via
github autoclose commands in commits, let's ensure that we don't merge
them.
Both have unwanted side-effects whan e.g. backporting or closing such repos on github.
> Enable invalidcommitmsg plugin for kubevirt org

- github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Recently the pods on 1.16 ran into timeout when running the sonobuoy
conformance tests at the end. We increase the timeout values for the
jobs to 3 hours in order to give the tests enough time to finish.
Example: https://prow.apps.ovirt.org/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/407/check-provision-k8s-1.16/1283650167454568448
> Increase pod timeout for k8s check provision and push

- github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
Fix the job config for the flakefinder jobs.
> Add dry-run flag for cnao jobs

- github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
Change to cron, as the job should run daily after midnight UTC to make
the data available for the next build officer.
/cc @vatsalparekh @qinqon
> Change cnao flakefinder daily to cron

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
The current git command doesn't supress the git diff and it can cause a
recursive variable references itself error from make.
> Fix git commit reference in nightly publish job

- hack/git-askpass.sh
In order to savely provide github credentials to git, let's use
GIT_ASKPASS and a small helper binary which will print the github token
provided to stdout.
Unblocks work on #352 which needs this script.
> Add a script to provide github credentials to git

- github/ci/prow/files/plugins.yaml
Now that the ssp-operator is under the kubevirt org, our CI should be similar to the rest of the org.
Signed-off-by: Omer Yahud <oyahud@redhat.com>
> Enable kubevirt-bot for ssp-components

- github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
This PR Adds new job in order to test KubeMacPool functests on
latest CNAO builds.
This is necessary in order to catch bugs and prevent more issues that 
related to how KubeMacPool integrates with CNAO, 
especially on CNAO releases and KubeMacPool bumps.
This PR is need for https://github.com/kubevirt/cluster-network-addons-operator/pull/408
> Add Kubemacpool functests on CNAO job

- github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
This PR enables Kubemacpool tests on CNAO lane and it will report back.
This lane is optional.
> Enable Kubemacpool tests on CNAO lane

- github/ci/prow/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
The CDI tests now require libdevmapper.so to run. The base image all the
lanes are running from does not include it, but a latest version does.
This PR adds an optional lane to verify that a/ the tests run
correctly and b/ the CI works with the updated image.
> Add an optional lane with a newer version of base image.

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Move the "generate" step off of travis to reduce the runtime there.
> Make kubevirts generate prowjob required

- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Let's only retrigger jobs all three hours for now and see if it is a
good compromise.
> If things look bad in CI, the one hour retest is an issue

- github/ci/prow/templates/hook-rbac.yaml
This permission is needed in order to track running jobs on a remote
cluster.
> Add permissions for hook to list ProwJobs

- github/ci/prow/files/plugins.yaml
The prow version we use has a bug where
the link for the list of bot commands is
broken if not explicitely set.
Setting it to its "default" value.
Fixed upstream by:
https://github.com/kubernetes/test-infra/pull/18097
> Fix the bot command list link

- github/ci/prow/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Functional tests need libdevmapper to be present and available in the
test image. This PR updates the image and creates a link to the
required version of the library.
> Update base image for testing.

- github/ci/prow/templates/greenhouse-deployment.yaml
- github/ci/prow/templates/mirror.yaml
The label is set on the caching node only and the caching node has the
specified taint applied too.
> Schedule our caches on a dedicated node.

- github/ci/prow/templates/statusreconciler-deployment.yaml
Status reconciler recreates required jobs in the ibm cluster over and over.
> Disable statusreconciler

- github/ci/prow/files/labels.yaml
The label plugin supports labeling using a command only specific types
and "topic" is not one of them.
"sig" is a supported type and is equivalent in meaning to the "topic"
one.
With this change, one can label a PR or issue using the
`/sig network` comment.
> labels: Rename topic/network to sig/network

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Kind clusters have huge requirements on cluster resources, eat way too
many watches and threads which then renders their host catastrophically
slow and lead into other lanes failing.
With this patch, we introduce an anti-affinity, making sure that we run
only a single kind test run per host at the time.
> Run only one kind lane per node at the time

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Make use of the two new nodes which got added.
> Allow more executions in parallel of the core kubevirt/kubevirt lanes

- github/ci/prow/files/config.yaml
Get rid of
```
{"component":"unset","file":"prow/config/config.go:1234","func":"k8s.io/test-infra/prow/config.(*Config).validateComponentConfig","level":"warning","msg":"rerun_auth_config will be deprecated in July 2020, and it will be replaced with rerun_auth_configs['*'].","severity":"warning","time":"2020-08-26T08:35:32Z"}
```
> Update rerun_auth_config to the not deprecated form

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.31.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.32.yaml
Making `pull-kubevirt-generate` required on master, but not on release
branche confuses status-reconciler. As a quick solution unblock it by
removing the unused jobs from the release-branches.
Status-reconciler sees the job the once as optional and once as required
in the current job list and fails to distinguish them. When it compares
the last known state with the current state it can't distinguish them
and thinks that the second optional job for the release branch is now
required and retriggers the jobs in an endless loop.
Note that this is only a quick-fix. We need to prevent this in the future somehow.
> Unblock status reconciler by removing pull-kubevirt-generate from release branches

- github/ci/prow/files/config.yaml
coveralls does not report back right now with our custom prow job. Making the coveralls report optional to not block merges on kubevirt.
> Make coveralls non-required until it is fixed

- github/ci/prow/templates/statusreconciler-deployment.yaml
Newer status reconcilers can save the state and better calculate differences. This PR does not re-enable the statusreconciler, since tests showed that it still fails with the same issue like before.
> Re-enable statusreconciler and store the state on GCS

- github/ci/prow/files/plugins.yaml
Right now users need to be github org admins to be able to override
a job since [1] merged at prow users at OWNERS file can override
them if configured, this commit activate that feature.
[1] https://github.com/kubernetes/test-infra/pull/14538
> Allow non org admins but project owners to override jobs

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
When tide does try to batch merge do not run the coverage job. It seems as if it overrides the coverage on the PR which then seems to get lost somehow.
> Ignore pull-kubevirt-goveralls for batch jobs

- github/ci/prow/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-periodics.yaml
- github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
- github/ci/prow/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-periodics.yaml
- robots/flakefinder/downloader.go
- robots/flakefinder/main.go
By default flakefinder omits test results on PRs that happened earlier
than the start of the report interval, which makes daily and weekly
reports incomparable.
Add a switch that can turn this off.
Disable omitting test failures for existing job configurations by
switch.
Fixes #596
> flakefinder: Create switch skip_results_before_start_of_report

- github/ci/prow/files/jobs/kubevirt/kubevirt.github.io/kubevirt-github-io-periodics.yaml
Looks like the main branch on kubevirt.github.io has been changed to `source`. Updated the job configuration to update to that.
> Changed kubevirt.github.io link checker branch to source

- github/ci/kubernetes_crud/README.md
- github/ci/kubernetes_crud/molecule/default/cleanup.yml
- github/ci/kubernetes_crud/molecule/default/converge.yml
- github/ci/kubernetes_crud/molecule/default/destroy.yml
- github/ci/kubernetes_crud/molecule/default/molecule.yml
- github/ci/kubernetes_crud/molecule/default/prepare.yml
- github/ci/kubernetes_crud/molecule/default/verify.yml
- github/ci/kubernetes_crud/molecule/files/manifests/test-plain.yaml
- github/ci/kubernetes_crud/molecule/files/manifests/test-template.yml.j2
- github/ci/kubernetes_crud/molecule/files/manifests/test-url.yaml
- github/ci/kubernetes_crud/tasks/_manifest_source.yaml
- github/ci/kubernetes_crud/tasks/apply_manifest.yaml
- github/ci/kubernetes_crud/tasks/create_namespace.yaml
- github/ci/kubernetes_crud/tasks/main.yaml
- github/ci/kubernetes_crud/tasks/remove_manifest.yaml
- github/ci/kubernetes_crud/tasks/remove_namespace.yaml
- github/ci/kubernetes_crud/vars/main.yaml
- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
- images/kubevirt-ci-testenv/Dockerfile
this role a is a generic interface between ansible and batch deployments
of kuberneted manifests.
It allows to write steps in a declarative way avoiding duplication of
common parameters such as kubeconfig or context.
This role will be used by the upcoming rewrite of role to deploy prow
and its dependencies.
Signed-off-by: Gabriele Cerami <gcerami@redhat.com>
> Add kubernetes_crud role

- github/ci/prow/files/labels.yaml
The label `good first issue` , is not triggred by the bot when
asked. Changing it's name to `good-first-issue` should solve it.
Signed-off-by: alonSadan <asadan@redhat.com>
> labels: change good first issue label name

- github/ci/prow/files/labels.yaml
Forgot to add `previously` to rename existing label as of #617.
> Fix rename by adding previously

- github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-postsubmits.yaml
Currently, prow's postsubmits script is set to run
if the file name in field 'run_if_changed' is changed.
However, this field is actually a [regex](https://github.com/kubernetes/test-infra/blob/8c49c0c2b8fce773ea5c254971e98c867314a63d/prow/config/jobs.go#L308)
and as such, it follows a greedy approach where any file with that name
changes - regardless of it's preceding  path - the postsubmits will be initiated.
In order to make sure the regex picks up only the file we want - we anchor the field value.
> add ^ anchor to run_if_changed in cnao postsubmits

- github/ci/prow/files/jobs/kubevirt/macvtap-cni/macvtap-cni-postsubmits.yaml
Currently, prow's postsubmits script is set to run
if the file name in field 'run_if_changed' is changed.
However, this field is actually a [regex](https://github.com/kubernetes/test-infra/blob/8c49c0c2b8fce773ea5c254971e98c867314a63d/prow/config/jobs.go#L308)
and as such, it follows a greedy approach where any file with that name
changes - regardless of it's preceding  path - the postsubmits will be initiated.
In order to make sure the regex picks up only the file we want - we anchor the field value.
> add ^ anchor to run_if_changed in macvtap-cni postsubmits

- github/ci/prow/files/labels.yaml
Renaming according the rebrand.
> Rename build-officer to build-watcher

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Add lane for new k8s provider (see kubevirt/kubevirtci#434). At first
this lane will not report, not be required and not run always.
> Add k8s-1.19 lane

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presets.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Create a set of jobs to replace the Travis job that runs on PRs. At first these jobs are not reporting their status to GitHub. We will let them run besides the Travis and when we are confident, enable reporting.
Also refactor the env variables configuring the bazel cache into a preset.
> Create a set of jobs to replace the Travis job that runs on PRs

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Want to always test snapshot/restore.
This has been running on demand successfully for me for awhile.
> make rook ceph lane mandatory

- releng/release-tool/release-tool.go
- releng/release-tool/release-tool_test.go
- Adds `#` character to PRs in release notes so they appear as links. 
- Fixes issue with branch cache. We need to clear
branch cache and re-generate in the event a new branch
is created
- Fixes issue with branching prow configs. Only attempt
to pull the latest branch code for the prow config if
the branch already exists.
> Release tool improvments

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Let the new k8s-1.19 lane run always (not reporting though). If it looks stable enough we are going to make it report.
> Make k8s-1.19 lane always run

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
In the current conformance tests periodic, we've never fetched KubeVirt
sources. This patch should fix it.
The nightly fails now: https://storage.googleapis.com/kubevirt-prow/logs/periodic-kubevirt-push-nightly-conformance/1307145148014006272/build-log.txt
> Checkout kubevirt sources for conformance tests

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Enables the presubmits for kubevirt/kubevirt
* pull-kubevirt-apidocs
* pull-kubevirt-client-python
* pull-kubevirt-manifests
* pull-kubevirt-prom-rules-verify
to run on every PR push.
/cc @danielBelenky
> Set kubevirt presubmit checks to always run

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
After having pulled some data for stability we disable 1.19 always_run again.
/cc @rmohr @danielBelenky
> Disable always run for 1.19 again

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Enable reporting to GitHub for the following jobs:
* [pull-kubevirt-apidocs](https://prow.apps.ovirt.org/?job=pull-kubevirt-apidocs)
* [pull-kubevirt-client-python](https://prow.apps.ovirt.org/?job=pull-kubevirt-client-python)
* [pull-kubevirt-manifests](https://prow.apps.ovirt.org/?job=pull-kubevirt-manifests)
* [pull-kubevirt-prom-rules-verify](https://prow.apps.ovirt.org/?job=pull-kubevirt-prom-rules-verify)
/cc @danielBelenky
> Enable reporting to GitHub for new kubevirt jobs

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
In order to enable gating for KubeVirt we make the following jobs required:
* pull-kubevirt-apidocs
* pull-kubevirt-client-python
* pull-kubevirt-manifests
* pull-kubevirt-prom-rules-verify
Next step will be the removal of the Travis CI run on every PR.
/cc @rmohr
> Make kubevirt prow checks required

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
In order to retrieve more data about the stability of the lane, we enable it to run on every PR.
/cc @rmohr @danielBelenky
> Reenable k8s-1.19 to run always

- github/ci/prow/files/config.yaml
In order to be able to remove Travis CI, we first need to make it non required.
/cc @rmohr @danielBelenky
> Make travis ci non required

- github/ci/prow/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-periodics.yaml
We are vendoring a specific version of kubevirt/client-go, but the
nightly job need to pull in the latest kubevirt/client-go, so make sure
the toplevel kubevirt directory is clean before cloning.
> HCO: clean kubevirt directory before cloning

- github/ci/prow/files/config.yaml
This elaborates on commit 8c56d2f, where travis ci run was made non required for any branch.
As we still need to run Travis on the release branches we add rules for
the last ten release branches.
/cc @rmohr
> Make travis ci run required for the last ten release branches 

- github/ci/prow/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-periodics.yaml
The nightly build will fail to compile if kubevirt/client-go is up to
date.
> Use go mod vendor after updating client-go

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The windows job runs way under one hour, reduce the maximum execution
time to 2 hours.
If something is wrong in the test scripts, it aborts earlier than right now: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4292/pull-kubevirt-e2e-windows2016/1312060536942235648. The issue there will get a fix in kubevirt/kubevirt too.
> Reduce the max job execution time for windows jobs

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.31.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.32.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.33.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.34.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
It is important to see this job, in order to see if `make` detected
uncommited code-changes, similare to the generate job.
> Make pull-kubevirt-build required

- github/ci/README.md
In case the config-updater doesn't run after merging a PR into
project-infra we need to update the complete prow configuration
manually. Add paragraph in README to show how that is done.
/cc @rmohr @danielBelenky @gabrielecerami
> Add section for updating prow configuration manually

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
At the moment it seems that the goveralls check can't be run as it
consumes too much memory on the node. Disable reporting and make it
optional to be able to investigate the problem.
> Disable goveralls prow job

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
In order to be able to completely avoid building anything required for 
running the tests on OpenShift CI (and anywhere else) we need to add the tests
binary as it is coupled with the state of the code from which the
nightly is built.
As the binary is quite big we also add a job to remove nightlies older than 4 weeks.
> Add tests binary to nightly

- github/ci/prometheus/templates/grafana.yaml
Adding a PVC and mounting it to grafana so that the grafana database survives restarts of the pod.
Mounting the PVC volume to /var/lib/grafana, where the database is located.
> Adding persistent storage volume for Grafana data

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Enable the reporting for k8s-1.19 lane, as [it seems stable enough](https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2020-10-22-168h.html). We don't make it mandatory yet for now.
/cc @rmohr
> Enable reporting for k8s-1.19

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.30.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.31.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.32.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.33.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.34.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Enable SRIOV lane back
Also:
- Increase job timeout.
- Set golang download silent to reduce noise in the job log.
This PR should be merged only after https://github.com/kubevirt/kubevirt/pull/4424
> enable sriov lane

- github/ci/prow/files/config.yaml
This commit updates the merge strategy of the macvtap repo.
> macvtap: update repo merge strategy

- external-plugins/rehearse/plugin/go.mod
- external-plugins/rehearse/plugin/handler/handler.go
First rebase PRs on the latest state of the target branch to reliably
get the real diff to master. This is needed to avoid a situation where
jobs are still present on the base ref on a PR and not on the target
branch anymore.
> [rehearsal] Rebase PRs on target branch

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
In recent times the push to docker hub started to fail with just a short
error like this:
```
Error pushing image to ...: unable to push image to ...: Put
https://index.docker.io/v2/kubevirtnightlybuilds/...: EOF
```
Locally this could be reproduced once, on second and third try it
succeeded. Therefore we change the container restartPolicy to OnFailure
to retry the push.
> Mitigate docker hub push fails on EOF with RestartPolicy=OnFailure

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.34.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Also, change the job name for the forked release branch job to avoid
triggering the status reconciler bug.
> Make k8s-1.19 lane mandatory

- hack/git-pr.sh
- plugins/cmd/uploader/uploader.go
The script tries to generalize functionality present in https://github.com/kubevirt/kubevirt/blob/master/hack/autobump-generic.sh or https://github.com/kubevirt/kubevirt/blob/master/hack/autobump-kubevirt.sh. It uses getopts to define the options, there are default values for most of them, the only required is the command to execute.
It allows defining the path where the command should be executed (with `-m`) and the path of the target repo, there are cases when they need to be different (for instance, when using the uploader plugin https://github.com/kubevirt/project-infra/tree/master/plugins/cmd/uploader).
Signed-off-by: Federico Gimenez <federico.gimenez@gmail.com>
> Added generic script to modify arbitrary repos and create PRs

- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
When running in the actual prow deployment `$HOME` is `/` leading to this error:
```
mkdir: cannot create directory '//bazel': Permission denied
```
in this execution for instance https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-mirror-uploader/1326420887624224768 With these changes bazelisk is downloaded to a temp dir.
Also adds a security context to execute commands as root so that there are no issues creating the default bazel directories.
> install bazelisk in temp dir for mirror uploader periodic job

- github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml
This is a special branch to point to the project's webpage content.
Closes https://github.com/nmstate/kubernetes-nmstate/issues/628
> knmstate: Skip gh-pages branch at publish job

- github/ci/prow/files/jobs/kubevirt/kubectl-virt-plugin/kubectl-virt-plugin-presubmits.yaml
Adds two presubmit jobs for kubectl-virt-plugin:
* create_release in dry-run and
* shellcheck (optional)
> Add presubmit jobs for kubectl-virt-plugin

- github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Lane was removed from both kubevirtci and kubevirt already.
> Remove kubevirtci kind ipv6 lane

- github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml
One of the publish step is to push into the `gh-pages` branch, for that we need the github token for kubevirt-bot user, best way to pass this to git is using the special [GIT_ASKPASS](https://git-scm.com/docs/gitcredentials#_requesting_credentials) that points to a script that dumps the token to git.
> knmstate, publish: Use GIT_ASKPASS

- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
- images/bootstrap/Dockerfile
- images/bootstrap/runner.sh
The image is based on `gcr.io/k8s-testimages/bootstrap:v20201106-b01d6e7` and includes a wrapper around `/usr/local/bin/runner.sh` that:
* verifies if there are env vars defined for setting up HTTP proxy, renaming them as needed. The docker daemon process requires `HTTP_PROXY` and `HTTPS_PROXY` env vars to be defined, we plan to use the more specific `DOCKER_HTTP_PROXY` and `DOCKER_HTTPS_PROXY` in presets.
* optionally adds a CA certificate to the system-wide trusted root authority, this will allow connecting the docker daemon with the mirror proxy using TLS.
> Add bootstrap image with docker mirror proxy support

- github/ci/prow/files/config.yaml
- github/ci/prow/tasks/main.yml
- github/ci/prow/templates/mirror-proxy-config.yaml
- github/ci/prow/templates/mirror-proxy-service.yaml
- github/ci/prow/templates/mirror-proxy.yaml
Creates the mirror manifests, the secret for the proxy CA cert and the job presets. Currently using the image `fgimenez/docker-mirror-proxy:v0.1.0` built from https://github.com/fgimenez/docker-registry-proxy
> Add docker mirror proxy

- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Adds ghproxy to avoid suspicious termination, see https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-project-infra-autoowners/1301829245277835264
Also uses the new askpass script and `extra_refs` instead of git clone.
> Add ghproxy to autoowners job

- github/ci/README.md
- github/ci/prow.yaml
- github/ci/remote-cluster.yaml
- github/ci/requirements.txt
It includes doc to create a virtual env and install the requirements (including ansible) on it. Also sets the `ansible_python_interpreter` var to the right value so that the interpreter in the virtual env and the libraries installed there are used.
> Add requirements file for ansible roles

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Sriov lane uses [KIND](https://github.com/kubernetes-sigs/kind) infrastructure.
Unlike QEMU VM's based kubevirtci providers where the nodes are VM's and isolated in terms of access to host resources
it is enough to let the prow job pod terminate to cleanup all the resources, using KIND requires 
"gracefully" teardown using `kind` binary to prevent resurrects leak as suggested at https://github.com/kubernetes-sigs/kind/issues/759.
At the current sate if for any reasoner sriov lane is interrupted or failed there will be no cluster deletion using `kind`
This PR ensures that sriov lane job will teardown the KIND cluster that was created inside the prow job pod
gracefully using `kind` binary in any case.
> SRIOV lane, Prevent Resources Leak

- github/ci/README.md
- github/ci/kubernetes_crud/README.md
- github/ci/kubernetes_crud/requirements.txt
- github/ci/requirements.txt
Instead of relying on virtual environments created with `--system-site-packages` (and depending on what is installed in the host) declare all the needed packages in requirements.txt.
cc/ @dhiller 
> Include all the required modules in ansible requirements

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
The openshift-ci periodics require the testing manifests to be uploaded
to gcs so that they can get deployed from there during the nightly smoke
test preparations. This job uploads them automatically for the
0.34 and 0.35 release.
Fixes kubevirt/kubevirt#4562
/cc @fgimenez @oshoval
> Add job to upload testing manifests for releases

- github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits.yaml
Add a new lane used for testing parallel nncp rollout
at nmstate repo.
> Add lane for nmstate with parallel nncp rollout

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Also replace git clone with extra_refs, and simplify copying of files to
gcs a bit.
Test job run: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-push-nightly-build-master/1331538968650452994
/cc @fgimenez
> Use docker proxy for kubevirt nightly

- github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.42.yaml
With the latest release at 0.42 branch we are hitting 3h limit [1],
let's increment that and also the grace period.
[1] https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/667/pull-e2e-cluster-network-addons-operator-lifecycle-k8s/1329739606412759040
> cnao, 0.42: Increase lifecycle test timeouts

- github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
We must not merge PRs that breaks sriov provider.
> Make srivo kind up lane mandatory

- github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml
To keep kubevirtbot email at project-infra this change pass it as env
var so publish.sh can consume it.
> knmstate, publish: Use env var for github email

- github/ci/prow/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-periodics.yaml
build-manifests no longer supports passing images through environment
variables, we need to update the image files, and use update_images to
fetch the correct digests
> Adapt nightly HCO to new build-manifests

- github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-postsubmits.yaml
As part of moving out from Travis we need to be logged in to push
to quay.io from automation/release.sh
> cnao: Add quay.io loging to release job

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
`sh` shell does not support catching ERR interrupts
with 'trap' due to that we get `trap: ERR: bad trap` errors:
- check-up-kind-1.17-sriov
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/492/check-up-kind-1.17-sriov/1331963388397359104#1:build-log.txt%3A84
-  pull-kubevirt-e2e-kind-1.17-sriov
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4581/pull-kubevirt-e2e-kind-1.17-sriov/1331948919290073090#1:build-log.txt%3A84
This PR changes SRIOV  lanes jobs to use `bash` instead
> SRIOV lane jobs: use bash

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Adds a scripted retry to the push of the KubeVirt nightly images built,
as since a couple days the push is failing with a simple EOF. Suspicion
is that the rate limit is somehow responsible for this to occur.
/cc @fgimenez
> Add retry to push of kubevirt nightly

- github/ci/prow/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-periodics.yaml
/bin/sh points to /bin/dash and doesn't support the <<< redirection.
Switch to bash.
> Use bash for running the nightly script

- cni-plugins/sriov-passthrough-cni/Dockerfile
- cni-plugins/sriov-passthrough-cni/README.md
- cni-plugins/sriov-passthrough-cni/deploy/multus-cni.yaml
- cni-plugins/sriov-passthrough-cni/install-plugin
- cni-plugins/sriov-passthrough-cni/plugin/90-sriov-passthrough-cni.conf
- cni-plugins/sriov-passthrough-cni/plugin/sriov-passthrough-cni
We use this plugin to test KubeVirt with SR-IOV hardware. Up until now,
this plugin was stored in a separate repo outside of the KubeVirt org
without any good reason. Moving it here will increase it's visibility.
> Move SR-IOV passthrough CNI to this repo

- images/kubevirt-infra-bootstrap/Dockerfile
This will allow us to migrate the jobs based on the kubevirt-infra-bootstrap image to use the docker proxy. Also the packages to be installed are now alphabetically ordered.
> Build kubevirt-infra-bootstrap image on top of kubevirtci/bootstrap

- github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
following #730, we increase the lifecycle lane of CNAO during release
> cnao, increase lifecycle lane timeout on master

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
These postsubmit jobs are equivalent to these travis jobs https://github.com/kubevirt/kubevirt/blob/master/.travis.yml#L22-L42 but pushing to quay.io instead of dockerhub. Both prow and travis jobs can run in parallel for a while, as soon as we verify that all is ok we can switch kubevirt code to use the quay images and remove the jobs from travis. 
The repositories have been added to quay.io/kubevirt with a description to distinguish them "Part of kubevirt/kubevirt artifacts", some image names like `conformance` or `tests` can be ambiguous. kubevirtbot user has write access on all of them. 
Successful executions:
push-latest-kubevirt-images: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/push-latest-kubevirt-images/1334400323929772032
push-latest-functest-images: …
> Publish kubevirt images to quay.io

- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
In the current state, we often forget to close flakey issue report after
the problem gets resolved. Due to this we end up with irrelevant Issues
rotting around for months.
With this change, we will close all issues triaged by the build watcher
after a week of inactivity. If an issue reoccurs, it should be mentioned
on the Issue.
> Close build watcher issues after 14 days

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Kubevrit SRIOV lane should be mandatory and block a given PR if it fails.
Now that SRIOV lane is stabilized and all flaky tests are resolved it is possible to set 
it mandatory.
Please share if there are any problems we should fix first before merging this PR.
> Set Kubevirt SRIOV lane mandatory

- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
- images/kubekins-e2e/Dockerfile
- images/kubekins-e2e/runner.sh
There are a few jobs that use `gcr.io/k8s-testimages/kubekins-e2e`, this PR creates an image based on it that includes a modified runner to include our proxy CA certificate in the trusted root, same as we did in #704. The repository is already created on quay.io. 
cc/ @dhiller
> Add docker proxy compatible kubekins-e2e image

- releng/release-tool/Dockerfile.release-tool-base
The new referenced commit contains https://github.com/kubernetes/test-infra/pull/19009 which should make us more resilient to statusreconciler issues. Note that this PR got reverted later on due to some context expectations  in k8s release scripts in the later pipeline stages.
> Bump to a config-forker which creates unique job-names

- OWNERS
Remove some reviewer suggestions from people which are not or only
sporadically working on kubevirt at this point in time and move two
approvers to the emeritus section for the same reason.
This is needed to get more meaningful reviewers and approvers assigned.
> Cleanup owners file

- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
One periodic updates the current latest three k8s releases to the latest
patch version, the other periodic checks if there is a new minor
version, copies the scripts over to the new minor version provider.
> Periodically update kubevirtci cluster major and minor versions

- github/ci/prow-deploy/kustom/overlays/ibmcloud-production/yq_scripts/config.yaml
Set the right prod URLs in two additional configuration paths.
> Add missing prow configuration patches

- plugins/mirror/bazel.go
- plugins/mirror/bazel_test.go
Mirror `rpm` bazel artifacts to our GCS store.
A preparation for https://github.com/kubevirt/kubevirt/pull/4703.
> Support `rpm` workspace artifacts in the mirror plugin

- plugins/cmd/uploader/uploader.go
- plugins/mirror/bazel.go
- plugins/mirror/bazel_test.go
* Check if we have to do an upload before opening a connection to the
source.
* Try to connect to the source with all available artifact urls and not
just with the first one.
> Improve mirror download behaviour

- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Ensure that every kubevirtci bump job has its own unique branch in
kubevirt-bot/kubevirti.
> Give kubevirtci bumpers explicit bump branch names

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
This jobs verifies that every RPM referenced in the WORKSPACE file is
signed by known GPG keys.
Once https://github.com/kubevirt/kubevirt/pull/4703 is merged, this job will be made required.
> Add job which verifies RPMs in kubevirt/kubevirt

- github/ci/prow/templates/plank-deployment.yaml
Plank was OOMKilled regularly and thus in CrashLoopBackoff, therefore we increase mem request and limit to 1Gi.
/cc @rmohr
> Increase mem request and limit to 1Gi for plank

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Add lane for k8s-1.20 provider, at first don't report to github, and only run manually.
> Add kubevirt test lane for 1.20

- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
We want the presubmit check also to run whenever anything has changed in
or below robots folder, not only when there had been changes in
robots/flakefinder.
/cc @fgimenez
> Change flakefinder presubmit to robots presubmit

- github/ci/prow-deploy/kustom/overlays/ibmcloud-production/kustomization.yaml
- github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/plank_deployment.yaml
- github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/StrategicMerge/plank_deployment_replicas.yaml
- github/ci/prow-deploy/kustom/overlays/kubevirtci-testing/kustomization.yaml
- github/ci/prow-deploy/kustom/overlays/kubevirtci-testing/patches/JsonRFC6902/plank_deployment.yaml
- github/ci/prow-deploy/kustom/overlays/kubevirtci-testing/patches/StrategicMerge/plank_deployment_replicas.yaml
Applies the same changes as in #799 to increase plank resources. 
Also includes patches to set plank deployment replicas to 1, defaults to 0 here https://github.com/kubevirt/project-infra/blob/master/github/ci/prow-deploy/kustom/base/manifests/test_infra/e88598c4a7f86e0564a2d8b46ce5f729247791e6/plank_deployment.yaml#L26 looks like prow-controller-manager is preferred upstream, in the latest versions plank has been completely removed.
cc/ @dhiller @rmohr 
> Bump plank resources in automated Prow deploy.

- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
`nodeSelector` was declared in the wrong place for `prow-deploy-test` and `cert-manager-deploy-test` jobs, causing connectivity errors like https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/794/prow-deploy-test/1346377627543277568 when the job was not scheduled on a bare metal node
> Fix nodeSelector declaration for presubmit jobs

- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Same nodeSelector fix as in #806 but for ci-search-deploy-test. It also includes changes to trigger presubmit tests for cert-manager and ci-search deploy on changes of its own code, the common services library and vendor.
> Fix ci-search-deploy-test job

- github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.44.yaml
Adding CNAO ci lanes for the new stable [branch](https://github.com/kubevirt/cluster-network-addons-operator/tree/release-0.44).
> cnao, Add lanes for new branch release-0.44

- github/ci/prow-deploy/molecule/default/collect_resource.yml
- github/ci/prow-deploy/molecule/default/vars/kubevirtci-testing.yml
This will prevent errors like:
```
"./cluster-up/up.sh", "unknown flag: --run-etcd-on-memory
```
here https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/811/prow-deploy-test/1346802302165454848
> prow-deploy: bump kubevirtci tag

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
We need to clear the folder before uploading as there might be older
manifests already present, which lead to duplicate object creation.
Also we move kubevirt testing manifest creation from 0.35 to 0.36,
as we will not need the 0.35 manifests for continuous testing approach.
/cc @fgimenez
> Remove release folder before updating

- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
- github/ci/services/ci-search/README.md
Besides $subject it tweaks the ci-search and cert-manager deployment and test jobs:
* tests are triggered on `WORKSPACE` changes too
* no need to extract kind config in tests, rely on the default config file.
* for deployments, use config file instead of env var.
> Add ci-search readme

- github/ci/prow/files/config.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Spyglass config pointing to https://testgrid.k8s.io/ instance and basic annotations for kubevirt/kubevirt presubmits.
> Add testgrid configuration

- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
Bugzilla token was not being properly created and the main pod was not able to be created.
> Fix ci-search deployment

- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
- images/autoowners/Dockerfile
Also compile statically linked binary and remove superfluous env vars from job.
[Test run](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-project-infra-autoowners/1348704465342959616)
/cc @fgimenez
> Use k8s-prow git image as base

- images/bootstrap/Dockerfile
Ensure that bazelisk is present in the binary and that  the most
commonly used bazel version is precached. Finally create a symlink to
from bazelisk to bazel, which makes it easier for scripts to work with
plain bazel or bazelisk.
> Add bazelisk to the bootstrap image

- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
- github/ci/services/ci-search/patches/statefulset.yaml
The pods were crashlooping:
```
$ kubectl logs search-0 -n ci-search
I0112 12:29:59.483273       1 reaper_linux.go:59] Launching periodic reaper
I0112 12:29:59.483460       1 reaper_linux.go:69] Reaped: []
F0112 12:29:59.483357       1 main.go:57] error: unable to create directory for artifact: mkdir /var/lib/ci-search/bugs: permission denied
```
> ci-search: set fs group for mounted volumes

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Also added new periodics that run the main provider lanes 3 times per day.
They will be added to the 'periodics' dashboard, which includes the
conformance results too.
> Removed testgrid annotations from non-compatible jobs.

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.20.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.23.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.24.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.26.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.29.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.30.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.31.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.32.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.33.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.34.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.35.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.36.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
There is an effort of creating a multi sriov POC.
It will allow running multi sriov lane on the same node, simultaneously.
In order to be able to run it on CI, with minimal interference
to the official jobs, this commit suggests adding a new
`podAntiAffinity`, so official jobs won't be run when the POC
is running (manually triggered only for now), and vice versa.
For example, It will allow us to easily investigate the blocker of the POC,
which appears to be a real issue unrelated to sriov
https://github.com/kubevirt/kubevirt/issues/3886.
Running multi jobs at the same time, allows to simulate
this issue easier, so the investigation should be easier.
> sriov lanes, Add podAntiAffinity of sriov-pod-multi

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Commands were wrong, this will fix errors like https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-latest/1349838947831779328 
> Fix kubevirt e2e periodics

- github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
The required repositories are already created with the right permissions in quay.io
> Publish kubevirtci images to quay

- github/ci/services/ci-search/patches/statefulset.yaml
This will make the links in https://search.ci.kubevirt.io/ results point to https://prow.apps.ovirt.org/view/gcs
> ci-search: add job-uri-prefix

- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
Will fix errors like https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/post-project-infra-upload-testgrid-config/1351551792164376576
> Add missing gh token to testgrid config upload job

- cni-plugins/sriov-passthrough-cni/deploy/multus-cni.yaml
Prow jobs use network multus-cni-ns/sriov-passthrough-cni. 
CI has the NAD deployed in multus-cni-ns as the jobs expect [1],
but the NAD manifest doesnt state which namespace to use, 
so the NAD will be created in the default cluster namespace,
and will be unreachable by the jobs.
[1]
```
NAMESPACE           NAME                          AGE
multus-cni-ns       sriov-passthrough-cni         1y
```
> sriov cni, Add NetworkAttachmentDefinition missing namespace

- WORKSPACE
- releng/release-tool/Dockerfile.release-tool-base
One commit landed which pulled in the right config-forker library to a
dockerfile, but this base image was then never for the build.
Follow up of #777.
> Use a base image with the right config-forker

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.37.yaml
In order to run the multi sriov POC side by side
with the official sriov jobs, a new podAntiAffinity
was introduced.
Add it also to the new release job 0.37
see #843
> sriov release 0.37, Add sriov-poc-multi podAntiAffinity

- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
The upload jobs were failing like here https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/post-project-infra-upload-testgrid-config/1351931293503328256 
The problem is that the gh token we use is associated with a user that doesn't have a public email set, this causes that the email is shown as empty here https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/post-project-infra-upload-testgrid-config/1351931293503328256#1:build-log.txt%3A2 and finally causes an error in this line of the transfigure.sh script https://github.com/kubernetes/test-infra/blob/master/testgrid/cmd/transfigure/transfigure.sh#L171
Tested locally and worked successfully, this PR was generated with these changes https://github.com/kubernetes/test-infra/pull/20554
Signed-off-by: Federico Gimenez …
> Add missing options to transfigure upload call

- github/ci/prow/files/jobs/kubevirt/user-guide/user-guide-periodics.yaml
- github/ci/prow/files/jobs/kubevirt/user-guide/user-guide-presubmits.yaml
The userguide jobs weren't working due to path permission issues, these are fixed now:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_user-guide/372/user-guide-presubmit-build/1352287010806566912
/cc @mazzystr 
see kubevirt/user-guide#372
> Fix user-guide jobs

- github/ci/prometheus/templates/dashboards.yaml
Persist a minimalistic tide dashboard which looks like this:
> Minimalistic tide dashboard

- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
We've had two successful runs: https://prow.apps.ovirt.org/?job=periodic-kubevirt-org-github-config-updater
Let's enable updating.
> Make peribolos job update org configuration

- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
The presubmit is intended to run peribolos over the new configuration in
order to catch configuration errors before they are getting committed.
> Create presubmit for kubevirt orgs config changes

- images/bootstrap/Dockerfile
Include first bazel LTS version in bootstrap's bazelisk cache, details about the release here https://blog.bazel.build/2021/01/19/bazel-4-0.html
> Cache bazel 4.0 in bootstrap image

- github/ci/prow/files/labels.yaml
The definitions were missing, so the labels didn't have a color. In order to make existence of those labels more prominent as it's required for merging, we add these.
> Add label definition for dco-signoff

- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Last night due to an invalid label update the label-sync jobs stopped working:
* https://shift.ovirt.org:8443/console/project/kubevirt-prow/browse/pods/label-sync-kubevirt-1611789420-hrbg7
* https://shift.ovirt.org:8443/console/project/kubevirt-prow/browse/pods/label-sync-nmstate-1611789420-h724l
This was caused due to a duplicate label. This PR introduces a presubmit that runs label_sync against the new configuration. 
Example run here: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/888/pull-prow-labels-update-precheck/1354758422972600320
> Add presubmit to check labels.yaml

- images/bootstrap/runner.sh
Help docker a little to find docker-init and docker-proxy binaries.
Fixes the following issue with docker in docker:
```
15:10:07: docker: Error response from daemon: driver failed programming external connectivity on endpoint dazzling_hugle (0ce88d806c12357c12b16dc78102518e2b3b3f2286fca99538a655d7080951cf): exec: "docker-proxy": executable file not found in $PATH.
```
> Configure docker userland binary paths

- images/bootstrap/Dockerfile
- images/bootstrap/create_bazel_cache_rcs.sh
* Remove version dependent bazel configuration. We don't know the version upfront and all extra handling is for ancient bazel versions wich are not relevant for us
* Install sysctl and modprobe, which is needed for the ipv6-enabled docker startup
> Fix minor bootstrap issues

- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
- images/prow-deploy/Dockerfile
- images/prow-deploy/requirements.txt
Towards #859 
Besides downloading dependencies, it builds test-infra's config-bootstrapper so that we don't need to build it on tests/deployment, only this will reduce the job times in ~8min.
> Add prow deploy test image

- cni-plugins/sriov-passthrough-cni/Dockerfile
- cni-plugins/sriov-passthrough-cni/README.md
- cni-plugins/sriov-passthrough-cni/deploy/multus-cni.yaml
- cni-plugins/sriov-passthrough-cni/install-plugin
- cni-plugins/sriov-passthrough-cni/plugin/90-sriov-passthrough-cni.conf
- cni-plugins/sriov-passthrough-cni/plugin/sriov-passthrough-cni
In order to allow running multi sriov clusters simultaneously,
allocate only one sriov PF per CNI call.
In case no PFs exist, exit with an error, so the job won't
start without PF.
It may occur in case the container was forcely deleted,
and then it takes a few minutes for the PF
to reappear in `/sys/class/net`.
The CNI will exit, delete the old NS, and a new container will
be created and retrigger CNI that would try again, until
the PF reappears.
This update makes the CNI re-entrant as well,
by detecting possible collisions in case two jobs try to take the same PF
at the same time.
One of them will succeed, and the other will advance to the next available PF.
Prow will schedule jobs according the number of PFs on the node (will be done on other PR).
This way we are guaranteed to be safe. …
> sriov CNI, Allocate only one sriov PF

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
In case the folder does not exist, when trying to delete it the job fails like this: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-update-release-0.36-testing-manifests/1356040996617457664
Therefore we check whether it exists before trying to delete it.
/cc @fgimenez 
FYI @vatsalparekh
> periodic-kubevirt-update-release-0.36-testing-manifests: Check whether folder exists before trying to delete it

- github/ci/prow/files/orgs.yaml
I am currently contributing to kubevirt/common-templates and others as part of Red Hat's SSP team.
Signed-off-by: Nelson Mimura Gonzalez <nelson@ibm.com>
> Add nelsonspbr to org members

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
There was an error in the way we calculated the target for the previous and previous-previous supported k8s versions, because of that all the kubevirt periodic master e2e were executed against the latest k8s version. 
> Fix target calculation for kubevirt periodic master e2e

- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
- github/ci/prow/files/orgs.yaml
There were tests failing on the PR which prohibited the automatic merge.
In order to make sure we catch issues with the autoowners job
let's assign it to this group to get notified in case something goes
wrong.
> Assign to prow-job-taskforce

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Now that we have the issues fixed, we want to run the 1.20 lane always.
/cc @qinqon @fgimenez
> Make k8s 1.20 lane run always

- github/ci/prow-deploy/kustom/base/kustomization.yaml
- github/ci/prow-deploy/kustom/base/manifests/local/docker-mirror-proxy_deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/local/docker-mirror-proxy_pvc.yaml
- github/ci/prow/templates/mirror-proxy.yaml
- github/ci/remote-cluster/templates/mirror-proxy.yaml
These changes will prevent errors like https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/publish-bootstrap-image/1354780192060477440 when pushing big layers through our proxy. 
I've also taken the opportunity to switch to the upstream docker-registry-proxy image now that https://github.com/rpardini/docker-registry-proxy/issues/70 is fixed and our previous upstream PRs have already landed.
Finally, I've added the proxy deployment to the automated prow-deploy, was missing there. 
> use upstream docker-registry-proxy and set proxy-connect timeouts

- images/bootstrap/Dockerfile
> Add libvirt-devel to bootstrap image

- cni-plugins/sriov-passthrough-cni/README.md
- hack/patch_node.sh
The script is meant to create/remove/update extended resources
named `prow/sriov`, in order to control how many
jobs each sriov node can run simultaneously
according how many sriov PFs it has.
After creating the resources, they would appear as allocatable,
after around 30 seconds.
Verified that It survives node reboot.
> Introduce sriov patch nodes script

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Now that we have verified that the periodic e2e lanes are working as expected let's increase the frequency to execute them twice a day, we have still margin thanks to the 7h timeout. 
Besides getting more feedback from them executing on working hours would run them on real conditions, the executions when no one else is using the cluster might give good results because of low resource usage. 
> Execute periodic e2e from master twice a day

- github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
Aiming to fix failures like https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/publish-kubevirtci/1357277772417863680
> Increase timeout for publish-kubevirtci

- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
- github/ci/services/common/k8s/pkg/wait/wait.go
- github/ci/services/sippy/BUILD.bazel
- github/ci/services/sippy/README.md
- github/ci/services/sippy/e2e/e2e_test.go
- github/ci/services/sippy/hack/deploy.sh
- github/ci/services/sippy/manifests/full.yaml
- github/ci/services/sippy/manifests/ingress.yaml
- github/ci/services/sippy/overlays/testing/cluster-issuer.yaml
I've read here https://groups.google.com/g/kubernetes-sig-testing/c/BxnXXipU42M/m/XAV53pyBAwAJ that upstream kubernetes will start using sippy https://github.com/openshift/sippy as part of their efforts for increasing CI reliability. I think it can help us as well to analyze test results from testgrid, it has a lot of nice features. Some of the links still point to openshift-related services (like openshift's ci-search) but I expect this will be changed soon. 
I've also taken the opportunity to introduce a timeout in the wait functions under `github/ci/services/common`, let me know wdyt.
/cc @dhiller @rmohr  
> Add sippy deployment

- github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
Add periodic job that downloads repositories for installing
cri-o version 1.20 and rsyncs the downloaded repository with gcs.
Since we can expect other versions to be needed later,
I'm adding `sync_crio_repo_for_version` so we can iterate
over a list of multiple versions when needed.
> Add periodic job that syncs OpenSuse Crio repo

- github/ci/prometheus/templates/prometheus-config.yaml
ci-health now publishes a metrics file in Prometheus format as part of the artifacts http://fgimenez.github.io/ci-health/output/metrics with these changes this file will be scraped by prometheus and we will be able to see the evolution of the metrics over time in grafana dashboards.
> Add ci-health to prometheus scrape targets

- github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
bootstrap image doesn't have reposync, let's
fix that by installing it.
> Fix missing reposync in kubevirtci crio sync periodic

- github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
$BUCKET_DIR is missing the `$`
> Fix missing $ sign

- github/ci/prometheus/templates/dashboards.yaml
- github/ci/services/prometheus-stack/manifests/grafana.yaml
Add dashboard for job load and failed jobs.
* [Prow Jobs](https://grafana-kubevirt-prow.apps.ovirt.org/d/wc9rspPGk/prow-jobs?orgId=1&refresh=1h)
> Add job failures 4h grafana dashboard

- github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
The reposync version from debian yum-utils package
doesn't download metadata even when `--download-metadata`
parameter is specified.
Switching to fedora image instead and using dnf-utils.
> Use fedora image instead of debian and download metadata for crio mirror

- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
- github/ci/services/ci-search/e2e/BUILD.bazel
- github/ci/services/ci-search/e2e/e2e_test.go
- github/ci/services/common/k8s/pkg/check/BUILD.bazel
- github/ci/services/common/k8s/pkg/check/check.go
- github/ci/services/kuberhealthy/BUILD.bazel
- github/ci/services/kuberhealthy/README.md
- github/ci/services/kuberhealthy/crds/kuberhealthy.yaml
- github/ci/services/kuberhealthy/e2e/BUILD.bazel
- github/ci/services/kuberhealthy/e2e/e2e_test.go
- github/ci/services/kuberhealthy/hack/deploy.sh
- github/ci/services/kuberhealthy/manifests/ingress.yaml
- github/ci/services/kuberhealthy/manifests/kuberhealthy.yaml
- github/ci/services/kuberhealthy/manifests/namespace.yaml
- github/ci/services/kuberhealthy/overlays/testing/cluster-issuer.yaml
- github/ci/services/prometheus-stack/e2e/BUILD.bazel
- github/ci/services/prometheus-stack/e2e/e2e_test.go
- github/ci/services/sippy/e2e/BUILD.bazel
- github/ci/services/sippy/e2e/e2e_test.go
Test and deployment code for a basic [Kuberhealthy](https://github.com/Comcast/kuberhealthy) installation. Includes 3 preconfigured synthetic checks for damonset, deployment and dns status. Includes ingress for accessing the status page at https://status.ci.kubevirt.io
I've taken the opportunity to refactor the HTTP service checks in the `github/ci/services` deployments e2e tests.
> Add kuberhealthy deployment

- github/ci/prow-deploy/molecule/default/prepare.yml
- github/ci/prow-deploy/molecule/default/smoke_tests.yml
- github/ci/prow-deploy/molecule/default/vars/kubevirtci-testing.yml
- github/ci/prow-deploy/tasks/deploy.yml
- github/ci/prow-deploy/vars/ibmcloud-production/main.yml
prow-deploy task for patching SRIOV nodes using the `hack/patch_node.sh` script, includes check in smoke tests.  
For now it only defines SRIOV node entries in the testing configuration, when we use the deployment code in the new control plane we need to add the actual node names and capacities in the prod config.
/cc @oshoval @dhiller  
> prow-deploy: add SRIOV node patch action

- github/ci/prow/files/labels.yaml
These labels are taken from Kubernetes:
https://github.com/kubernetes/test-infra/blob/2efad71f085991710643e572dbde606377a807b1/label_sync/labels.yaml
They should be used to clasify state of Issues and make our bug scubbing
more effective.
> Add triage labels

- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
containerized-data-importer repo has recently changed its default branch from master to main, without these changes we get this error in the periodic:
```
$ git fetch https://github.com/kubevirt/containerized-data-importer.git master
fatal: Couldn't find remote ref master
```
For instance here https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-mirror-uploader/1361934958288965632#1:build-log.txt%3A125
/cc @dhiller 
> use main branch for containerized-data-importer

- github/ci/prow/files/jobs/kubevirt/user-guide/user-guide-postsubmits.yaml
Initially job [failed on configuring git user name and email](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/push-user-guide-master-build-and-push-to-gh-pages/1362113887071113217), we now
configure only on the checked out repo. Also to avoid other permission
issues when building the site with mkdocs we change runasuser.
/cc @mazzystr @codificat
> Fix user-guide postsubmit permission issues

- github/ci/prometheus/templates/dashboards.yaml
- github/ci/services/prometheus-stack/manifests/grafana.yaml
The lines for avg + std and avg - std are shown and the area between them (60% of the total of samples) is filled. Also the Y axis of the average time to merge shows units now. Already in use here https://grafana.ci.kubevirt.io/d/WZU1-LPGz/merge-queue?orgId=1
> Update cihealth dashboard to show standard deviation

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presets.yaml
- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Change all main presubmits and postsubmits for kubevirt to the new fedora based bootstrap image. This new image allows running the e2e tests without nesting.
> Run kubevirt e2e tests without the buider image to make them more lightweight

- plugins/cmd/uploader/uploader.go
- plugins/mirror/bazel.go
* Check if we get a good HTTP return code
* Check if the artifact from the mirror has the expected shasum
* Add a command to verify that all mirrored dependencies have the expected shasum
Here the output after running the new verify command:
```
$ ./uploader -verify -workspace /home/rmohr/go/src/kubevirt.io/kubevirt/WORKSPACE 
true
2021/02/22 12:35:24 failed to upload llvm-libs-0__10.0.1-4.fc32.x86_64 to https://storage.googleapis.com/builddeps/2553c52dfcf5b6b8edabb89bfd3af8c4a7cecb81169a48cd7af9460ea20e108f: artifact llvm-libs-0__10.0.1-4.fc32.x86_64: expected shasum 2553c52dfcf5b6b8edabb89bfd3af8c4a7cecb81169a48cd7af9460ea20e108f, got 3bf95b81d86575587ba92ece56c9a53410b3c1da529e5d66917b460c7ba263af
2021/02/22 12:35:39 failed to upload procps-ng-0__3.3.16-2.fc32.x86_64 to …
```
> Make the dependency mirror tool more fault  tolerant

- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
- github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
With this our jobs will use the transfigure image built with the changes from https://github.com/kubernetes/test-infra/pull/20902, which will fix the links from the dashboards in https://testgrid.k8s.io/kubevirt to our prow instance.
> testgrid: set transfigure image tag

- github/ci/prow-deploy/molecule/default/prepare.yml
- github/ci/prow-deploy/molecule/default/vars/kubevirtci-testing.yml
This will prevent errors like https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/854/pull-project-infra-prow-deploy-test/1363409299254022145
/cc @dhiller @oshoval 
> prow-deploy: use quay image for kind test cluster

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The `ip` command is missing in the fedora image, which breaks it:
```
home/prow/go/src/github.com/kubevirt/kubevirt/cluster-up//cluster/kind-k8s-sriov-1.17.0/config_sriov.sh: line 243: ip: command not found
```
> Revert for sriov lane to debian based bootstrap image

- images/bootstrap/Dockerfile
SRIOV lane installs `gettext` via `apt` and it fails on the bootstrap image due to the missing `ip` binary which is part of `iproute`.
> Add sriov lane requirements

- github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
In case the push does not succeed after the maximum number of retries
check the retval to be non zero and exit in that case.
Occurred on [periodic-kubevirt-push-nightly-build-master job run](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-push-nightly-build-master/1364742725022257152).
Cause of the failure was a nonexisting image repository on quay, although I found the 429 error code slightly misleading :)
I have created the missing repo and have started a job instance of said job manually: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-push-nightly-build-master/1364879739231145984
/cc @fgimenez @thetechnick @davidvossel
> kubevirt push nightly: fix error handling

- plugins/cmd/uploader/BUILD.bazel
Failing job: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-mirror-uploader/1366283426084163584
> Fix periodic-kubevirt-mirror-uploader: add missing dependency

- images/bootstrap/Dockerfile
- images/bootstrap/runner.sh
These mixin entrypoints allow layered containers to bring in additional setup and teardown code, avoiding the need to wrap the `runner.sh` script.
One example is for instance a layered golang container:
```
FROM quay.io/kubevirtci/bootstrap:latest
RUN curl -sL -o /bin/gimme https://raw.githubusercontent.com/travis-ci/gimme/master/gimme && chmod +x /bin/gimme
RUN gimme 1.15.8
RUN echo 'eval $(gimme 1.15.8)' > /etc/setup.mixin.d/golang.sh
```
Similar things can very often be achived by putting code into profile files or similar places, but they very often depend on the execution shell or other assumptions on how one enters a container. This way injection can be done in a well-defined way.
> Allow mixins for layering funcitonality on top of the bootstrap image

- images/bootstrap/runner.sh
The default debian location is not by default picked up on fedora.
Changing that by explicitly sourcing it and taking DOCKER_OPTS into
account.
> Pick up docker setup from CI

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Limit the amount of parallel runs per node a little bit more. We have too much pressure on the nodes. Limit the amount on parallel jobs runs per node slightly by requesting more memory.
> Request more memory on e2e jobs

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Publish conformance yaml to allow for instance for kubevirtci during cluster provision running latest conformance tests from kubevirt.
> Publish conformance yaml on developer builds of kubevirt

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Due to a bug peribolos seems to fail on creation of a team in dry-run mode. Therefore we disable the fix-teams switches for the presubmit.
See #990 
See https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/990/pull-kubevirt-org-github-config-updater/1366785736094781440
/cc @fgimenez
> Disable peribolos team fixes for presubmit

- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
travis-ci.org no longer exists so the branch protection is no longer valid. The
tests performed by travis will be replaced with matching PROW jobs.
> Remove travis branch protection from CDI

- robots/pkg/kubevirtci/kubevirtci.go
- robots/pkg/kubevirtci/kubevirtci_test.go
Ensure that we properly detect if the latest k8s version provider
already exists, and in that case only bump to the latest minor version
if necessary, instead of copying the n-1th release into a subdirectory
of the latest existing provider.
Fixes a wrong copy operation like in this PR: https://github.com/kubevirt/kubevirtci/pull/547
> Fix adding the latest kubevirtci provider

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Adds quarantine lanes for 1.19, 1.18, 1.17, cnao-1.19 and kind-1.17-sriov to run the tests marked with the `QUARANTINE` label. Relies on the `automation/run-quarantined-tests.sh` script added here https://github.com/kubevirt/kubevirt/pull/5156 to only spin up the test cluster when there are quarantined tests for the specific provider.
> Add quarantine lanes

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The following lanes are affected:
* k8s-1.17-rook is now set to optional and not always_run
* k8s-1.17 is now set to optional and not always_run
* k8s-1.20 is now set to not always_run
Most notably the following two main lanes stay enabled (together with
other smaller lanes):
* k8s-1.18
* k8s-1.19
This step should be revised and/or reverted within one week (Mar 15th).
> Reduce the amount of required jobs as emergency measure

- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Trying to use the exact same text as apears in the lane:
`Sanity Checks / Sanity Checks (pull_request)`
> Trying again to require HCO sanity test on push to master

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presets.yaml
- images/bootstrap/Dockerfile
- images/bootstrap/runner.sh
Ensure that we know which directory bazel will use as a cache
directories, independent of the user used on the prow job.
Further mounting an emptyDir at this well known location if jobs decide
to run bazel unnested.
This way bazel will not write massively into the container overlay,
which can fill up the container space pretty fast and which can also
perform bad.
> Set the bazel output base directory to a well known location

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
This PR adds a new job `pull-kubevirt-e2e-k8s-1.19-sig-network` 
The purpose of this job is to allow running a more
focused group of tests, in isolation from the other tests,
owned by the sig-network.
It will run only the tests that are marked with sig-network,
including MacVtap and Multus (which require CNAO).
At the end of the effort, this new lane `pull-kubevirt-e2e-k8s-1.19-sig-network`
would always run, but won't be a gating.
The differences between this new lane and the official k8s-1.19
```
always_run: false
optional: true
```
The TARGET has suffix `-sig-network`
After testing we will make it `always_run` true,
since there is no rehearsal on k8s-1.19 we need this lane first merged.
Kubevirt counterpart https://github.com/kubevirt/kubevirt/pull/5167
Signed-off-by: Or Shoval …
> kubevirt-presubmits: Add sig-network k8s 1.19 job

- images/bootstrap/Dockerfile
Some dependencies either changed in the bootstrap image or something
changed in fedora.
This ensures that we always have the python binary present.
Without this explicit `/usr/bin/python` binary present, bazel can not detect python and fails with something like this:
```
ERROR: no such package '@pip_deps//': pip_import failed:  (src/main/tools/process-wrapper-legacy.cc:75: "execvp(python, ...)": No such file or directory
```
> Pull in the unversioned python binary explicitly

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Is very difficult to test kubevirtci PRs at kubevirt, this change add a
job for k8s-1.18 to test kubevirt at a kubevirtci PR.
From PR https://github.com/kubevirt/kubevirtci/pull/565 tested at job https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/565/check-kubevirt-e2e-k8s-1.18/1370022818195968000 
> Add kubevirt/kubevirt job to kubevirtci

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
Currently the push-release-master runs into a timeout more than half of
the runs.
/cc @fgimenez
> Increase timeouts for release jobs

- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.39.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Last time bazel was writing into the container overlay, which cause unexpected disk pressure on nodes.
This time bazel writes to a well define emptyDir which is mounted via the bazel preset.
> Reenable unnested bazel builds for e2e tests in kubevirt

- github/ci/prow-deploy/files/jobs/kubevirt/ovs-cni/ovs-cni-presubmits.yaml
In order to use the latest image cache proxy,
update the bootstrap image.
This change also update the bootstrap image itself
to point on quay instead of docker.io.
`preset-docker-mirror-proxy: "true"` already exists in this job.
> ovs-cni presubmit job, Update the bootstrap image

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
- images/golang/Dockerfile
- images/publish_image.sh
The image wraps `gimme`. By default 1.15.8 will be used, but
`GIMME_GO_VERSION` can be overwritten at runtime to fetch any other
golang version. 1.15.8 is also pre-cached.
It will be published together with a new bootrap build in a postsubmit.
Follow up of #985
> Publish a golang image together with the bootstrap image

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Switch from kubekins to our own bootstrap images based on fedora with
golang.
> Bump kubevirtci jobs to quay.io/kubevirtci/golang

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Reverts the change introduced here https://github.com/kubevirt/project-infra/pull/1027 that causes errors like https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/1004/pull-project-infra-test-rehearse/1370413514463645697
/cc @dhiller 
> Revert image used for rehearse job

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
The `-latest` periodic is running on 1.20 now, even though we are not using this provider its directory is under `cluster-up/cluster`, and the code to determine the target in these jobs is blindly picking it. 
With these changes we will have fixed targets for each e2e periodic that need to be updated when we include a new provider. The job names keep the same so that we don't need to update testgrid config
> Fixed providers for e2e periodics

- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Merge this after https://github.com/kubevirt/containerized-data-importer/pull/1703 completes to enable new embedded rook/ceph
> use embedded rook/ceph

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
The bootstrap image this job uses is fedora based and
does not have 'apt' package manager.
The job report is finished successfully, but it actually had an error that the trap didn't catch 
causing the job to deploy the default cluster k8s-1.18 instead.
https://prow.apps.ovirt.org/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/559/check-up-kind-1.17-sriov/1372225414985945088
This PR removes the usage of apt and adjust the trap to catch such errors.
Also make use of `GIMME_GO_VERSION` env var to get golang binaries
> Remove apt command usage from SRIOV check-up job

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The purpose of this job is to allow running a more
focused group of tests, in isolation from the other tests,
owned by the sig-storage.
This lane would always run, but won't be a gating.
It will run only the tests that are marked with sig-network
The differences between this new lane and the official k8s-1.19
```
always_run: false
optional: true
```
The TARGET has suffix `-sig-storage`
After testing we will make it always_run true,
since there is no rehearsal on k8s-1.19 we need this lane first merged.
Corresponding Kubevirt PR https://github.com/kubevirt/kubevirt/pull/5212
I have based my work on https://github.com/kubevirt/project-infra/pull/1007 (including text for commit and PR)
> kubevirt-presubmits: Add sig-storage k8s 1.19 job

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
- hack/git-pr.sh
Let the CDI artifact mirror job create PRs against the right main
branch, which is `main` now, and not `master`.
> The artifact mirror job should use the right CDI main branch

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Use the same container image as other lanes. 
The version was lost after rebase.
> correct container image for sig-storage

- github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
K8s-1.19 is more stable, hence use it once kubevirtci
is bumped in HCO.
Depends on https://github.com/kubevirt/hyperconverged-cluster-operator/pull/1195
> hco, Use k8s-1.19 for pull-hyperconverged-cluster-operator-e2e-k8s

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Use the new KV test feature to pass the `KUBEVIRT_E2E_FOCUS` and the `KUBEVIRT_E2E_SKIP` variables in order to create a new lane for the KV operator test as an isolated test.
> Add new lane for the 'Operator' test

- github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-postsubmits.yaml
In order to fix docker.io rate limit, migrate to quay.io when publishing hco test image
See https://github.com/kubevirt/hyperconverged-cluster-operator/pull/1194
> hco, Update publish job to use quay.io

- cni-plugins/sriov-passthrough-cni/README.md
There is another method to call the undercloud sriov cni
multiple times.
Update docs accordingly.
> sriov cni, docs, Add an alternative method to call cni multiple times

- github/ci/prow-deploy/files/jobs/kubevirt/bridge-marker/bridge-marker-presubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/controller-lifecycle-operator-sdk/controller-lifecycle-operator-sdk-presubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-presubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubectl-virt-plugin/kubectl-virt-plugin-presubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/macvtap-cni/macvtap-cni-presubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-presubmits-master.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
- github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits.yaml
Since this change need to be tested on CI,
and its resource extensive, we are doing it in batches.
Update bootstrap image from `kubevirtci/bootstrap:v20201119-a5880e0`
to `quay.io/kubevirtci/bootstrap:v20210311-09ebaa2`
(Part of those, since there are many)
> infra, Replace bootstrap image

- github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/macvtap-cni/macvtap-cni-presubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-presubmits-master.yaml
Since this change need to be tested on CI,
and its resource extensive, we are doing it in batches.
Update bootstrap image from `kubevirtci/bootstrap:v20201119-a5880e0`
to `quay.io/kubevirtci/bootstrap:v20210311-09ebaa2`
(Part of those, since there are many)
> infra, Replace bootstrap image part 2

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Currently sriov-passthrough-cni allocates single PF to
the prow job pod.
In order to test Kubevirt SRIOV Live Migration it requires
a setup with two workers where each worker has SRIOV PF
in its netns.
https://github.com/kubevirt/kubevirt/pull/5238
This commit sets sriov-passthrough-cni to allocate two SRIOV PF's
> Increase SRIOV PF to allocate for kubevirt SRIOV lane

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
I missed on my review that the job was not `required`. The operator job needs to be required. Otherwise we would not run them at all.
> Make operator job required

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
As part of the effort to migrate project-infra images
from `docker.io` to `quay.io`,
update the bootstrap image of kubevirt sriov presubmit job
to use a newer one, which is hosted on `quay.io`.
Use a quay.io/kubevirtci/golang
in order to align kubevirt job to kubevirtci job,
and to have golang easier.
Since the new image doesn't have apt, but already has
`gettext-base`, update the job run command accordingly.
Remove `KUBEVIRT_PROVIDER` because `TARGET` is enough,
`KUBEVIRT_PROVIDER` will be set accordingly
by automation/test.s according to `TARGET`.
Add `set -e` in order to fail fast in case the job command
has an error, and not mask those errors.
> sriov, presubmits, kubevirt, Update bootstrap image

- github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-postsubmits.yaml
Since current proxy version cause problems
when pushing big layers to quay.io,
remove it for the time being.
> hco, Remove preset-docker-mirror-proxy

- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
I noticed that flakefinder hasn't reported anything for CDI in a while, including any merged PRs.
I assume this is due to the branch rename, and blindly performed this change, hopefully it's the right one.
> Point CDI flakefinder jobs at the "main" branch

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
In order to test sig-storage job, create a periodic
lane that will run each 8h (similar to sig-network).
We will run it for a week, and if its stable,
we will consider making the sig-network job run on each PR.
> sig-storage, Create a periodic job

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
- github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits.yaml
This commit updates few more boostrap images
that are hosted on docker.io to point to quay.io
It also updates their version.
Images that were updated
`kubevirtci/bootstrap:v20210112-b29dfd7`
`kubevirtci/bootstrap:v20201119-a5880e0`
updated to
`quay.io/kubevirtci/bootstrap:v20210311-09ebaa2`
> Update bootstrap images to point to quay

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Set always_run -> false, optional -> true so it can be triggered manually when needed.
Needed for testing cgroups v2 support in kubevirt:
https://github.com/kubevirt/kubevirt/pull/4907
https://github.com/kubevirt/kubevirtci/pull/567
> Add k8s-1.20-cgroupsv2 check-provision job

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Aligns the kubevirt e2e periodic definitions to the presubmits:
* Adds `KUBEVIRT_E2E_SKIP` for the main provider periodics
* Updates SRIOV periodic to the latest changes, aiming to fix the failures we get https://testgrid.k8s.io/kubevirt-periodics#periodic-kubevirt-e2e-k8s-prev-prev-sriov&width=20
/cc @dhiller 
> Update kubevirt e2e periodics

- github/ci/prow-deploy/files/jobs/nmstate/nmstate/nmstate-presubmits.yaml
Prow by default run on all branches, that's good enoough also this is
maybe preventing running PRs.
> Remove branch section from nmstate job

- github/ci/prow-deploy/files/jobs/kubevirt/common-templates/common-templates-periodics.yaml
Increase the worker node in the cluster to accommodate all common-templates automation tests.
The old kubevirt cluster had a master node and a worker node. This cluster also creates 10 pvs in each of the nodes. The common-templates automation test for linux has 12 test cases for the different VM flavors and sizes. Each of these tests need a pv. There was a recent addition in common-templates code that specifies that the high-performance VMs only need to be placed on worker nodes. If the worker node PVs get used up before the last few high-performance VM tests are run(the PVs are bound, even after the test finishes), then there is a VM scheduling error for the last few tests. Increasing the worker node, provides another 10 PVs, that allow the tests to pass.
Signed-off-by: Shweta Padubidri …
> Increase the worker node in the cluster to accommodate all common-templates automation tests.

- github/ci/prow-deploy/files/orgs.yaml
Signed-off-by: Hao Yu <yuh@us.ibm.com>
This is Hao Yu from IBM T. J. Watson Research Laboratory and currently working with Red Hat teams on KubeVirt and OpenShift Virtualization.
> Request to be added into kubevirt.org

- github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-periodics.yaml
In order to fix docker.io rate limit,
switch to use quay.io
Depends on 
https://github.com/kubevirt/hyperconverged-cluster-operator/pull/1206
> hco, periodic, Update nightly build to use quay.io

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
In order to fix docker.io rate limit,
update builder jobs to use quay.io instead.
> infra, presubmit, Update build jobs to use quay.io

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
In order to fix docker.io rate limit,
the push of kubevirt-infra-bootstrap updated to point to quay.
More changes:
1. Use yaml literal that preserves new lines.
2. Add `-e` to the bash, so in case one command fails,
it will fail the whole job command, instead having
the commands anded together in one long command.
3. Update job bootstrap image to point to quay.
> infra, postsubmit, Update kubevirt-infra-bootstrap to push to quay

- github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits.yaml
Since we're running the handler e2e tests by default in
parallel on 50% nodes, we don't need the parallel lane anymore.
This commit removes the parallel lane.
Depends on https://github.com/nmstate/kubernetes-nmstate/pull/717
> Remove k8s-handler-parallel lane

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The job is needed for the PR https://github.com/kubevirt/kubevirt/pull/4907
It is supposed to run e2e tests on k8s 1.20 cluster with cgroupv2 enabled on the nodes. Set always_run -> `false`, optional -> `true` so it can be triggered manually when needed.
> Add pull-kubevirt-e2e-k8s-1.20-cgroupsv2 job

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
In case we don't need it, lets remove it.
> infra, Remove docker.io preset from kubernetes-crud-ci-role

- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-postsubmits.yaml
Right now the command fails if the tag is not found. This reverses
the logic so that the second part of the || is not executed but
the result is success instead.
> Don't error CDI job if no tag is found.

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The job is supposed to run e2e tests on k8s 1.20 cluster with cgroupv2 enabled on the nodes.
Copied from `periodic-kubevirt-e2e-k8s-1.19-sig-network` with the following changes:
- job name, command to run, env
- timeout: 4h -> 7h
- `cron: "15 7,15,23 * * *"`
Additionally the PR enables status report for cgroupv2 presubmit job.
Needed for https://github.com/kubevirt/kubevirt/pull/4907
> Add periodic-kubevirt-e2e-k8s-1.20-cgroupsv2 job

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
`KUBEVIRT_STORAGE=rook-ceph-default`
Once this verified works, will remove/update existing rook/ceph lane.
> new optional lane to test new rook/ceph

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Kubevirt `automation/test.sh` already has a trap
to cluster-down the kind sriov cluster,
it is enough to run it once, and the signal
will propagate first to the script.
Hence remove it from the job command.
> sriov, presubmit, Remove redundant trap

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Kubevirt automation/test.sh already has a trap
to cluster-down the kind sriov cluster,
it is enough to run it once, and the signal
will propogate first to the script.
Hence remove it from the job command.
As done on https://github.com/kubevirt/project-infra/pull/1084 for the presubmit.
> sriov, periodics, Remove redundant trap

- github/ci/prow-deploy/files/jobs/kubevirt/common-templates/common-templates-periodics.yaml
Change the periodic job to point to the master branch of common-templates project
> Change the periodic job to point to the master branch of common-templates project

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
We suspect disk pressure might be causing apiserver panics in the
test runs: https://github.com/kubevirt/kubevirt/issues/5353
And this will reduce the disk pressure a bit.
Tunable mentioned in https://github.com/kubevirt/kubevirtci/pull/568
> Run some quarantined tests with in-memory etcd

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
This PR makes the `sig-network` job mandatory and always run.
It also removes sig-network tests from
`pull-kubevirt-e2e-k8s-1.19` job,
and from k8s-1.19 periodic job (note its name is `periodic-kubevirt-e2e-k8s-latest`).
It removes CNAO jobs, since `sig-network` runs all the tests that are needed now anyway,
see https://github.com/kubevirt/kubevirt/pull/5354 which moved the `VMIlifecycle` networking tests
to `sig-network`.
No test run duplication needed, and it will ease running
`sig-network` group isolated.
The job was tested periodically for a week, each 8 hours [1],
23 runs, all passed, beside two which are not due to the `sig-network`
tests problems [2] [3].
It's stable enough for this change.
Reduce timeout from 7h to 4h for `pull-kubevirt-e2e-k8s-1.19-sig-network`.
[1] …
> sig-network, Make sig-network job mandatory and always run

- github/ci/services/ci-search/patches/statefulset.yaml
We were getting errors like https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/1082/pull-project-infra-ci-search-deploy-test/1380153133111447552 Trying to pull ci-search image locally I get:
```
$ docker pull registry.svc.ci.openshift.org/ci/ci-search:latest
Error response from daemon: received unexpected HTTP status: 503 Service Unavailable
```
According to Ben Parees:
```
i think registry.svc.ci.openshift.org is dead.
use registry.ci.openshift.org/ci/ci-search:latest
```
> update ci-search image

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The sig-storage lane should be actually run on all PRs so we can compare it's behavior to other lanes (with all tests). 
In the near future we want to remove sig-storage tests from main 1.19 lane and from periodic job. 
It takes about 30 minutes to finish on average. 
No failure (not counting single image fetch problem) since creating a periodic job with this lane: https://prow.apps.ovirt.org/job-history/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.19-sig-storage
> sig-storage, enable to always run

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Update job to use the Env section, instead exporting
the needed TARGET as part of the command.
It is nicer and aligned to the recommended style.
> sig-network, presubmit, Update env var style

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
This PR fixes the login to quay before running the tag release script.
/cc @davidvossel
> Fix push-release-kubevirt-tag quay login

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
This PR adds a job that will checkout kubevirt master, call `make bump-kubevirtci` and create a PR against kubevirt.
/cc @rmohr @fgimenez @EdDev
> Add job to bump kubevirtci on kubevirt after new release

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
This is part of checking k8s 1.20 lanes status and try to graduate to
github reporting.
It also add counterpart presubmit jobs with `always_run: false` to run them manually at `cluster: prow-workloads`
> Create k6t periodic lanes for k8s-1.20 

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
In order to stay in sync with RPM updates which e.g. fix CVEs which we do not even know about, let's update all our RPM dependencies on a weekly base.
> Update kubevirt RPM dependencies once a week

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
The original background was a blind attempt at reducing I/O
load, we now have a better theory for the problem, and we
want to understand why this lane has more failures than the
-prev lane by reducing differences.
> Revert running etcd in-memory

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Optional cross-compile presubmit for arm64.  A prerequisite to start publishing arm release artifacts at some point.
> Add optional arm crosscompile build presubmit

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
- github/ci/prow-deploy/hack/deploy.sh
- github/ci/prow-deploy/kustom/overlays/ibmcloud-production/kustomization.yaml
- github/ci/prow-deploy/kustom/overlays/kubevirtci-testing/kustomization.yaml
- github/ci/prow-deploy/kustom/overlays/workloads-production/.gitignore
- github/ci/prow-deploy/kustom/overlays/workloads-production/kustomization.yaml
- github/ci/prow-deploy/kustom/overlays/workloads-production/patches/JsonRFC6902/prow-jobs-namespace.yaml
- github/ci/prow-deploy/kustom/overlays/workloads-production/patches/JsonRFC6902/prow-namespace.yaml
- github/ci/prow-deploy/kustom/overlays/workloads-production/resources/bootstrap.yaml
- github/ci/prow-deploy/tasks/deploy.yml
- github/ci/prow-deploy/tasks/main.yml
- github/ci/prow-deploy/tasks/secrets.yml
- github/ci/prow-deploy/vars/ibmcloud-production/main.yml
- github/ci/prow-deploy/vars/kubevirtci-testing/secrets.yml
- github/ci/prow-deploy/vars/workloads-production/main.yml
Modifies prow-deploy to be able to deploy the new cluster components. It also adds a postsubmit to run the actual deployment on tag push.
It also includes these fixes that affect the deployment on ibm-prow:
* Fixed gcs secret file name
* Fixed project-infra root path (fgimenez -> kubevirt)
* Added kubeconfig path to Kustomize command
* Updated to use GIT_ASKPASS instead of GITHUB_TOKEN
> Added prow-workloads overlay and deployment job

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
With https://github.com/kubevirt/kubevirt/pull/5456 merged we can start running the crosscompile check on every PR. Still keeping it optional for the next 2-3 days.
> Make the arm cross compile job always run

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
This bot automatically approves kubevirt-bot "uploader" PRs if its test lanes have succeeded but who have not been reviewed within the last 24 hours.
> Add autoapprove for  kubevirt-bot "uploader" PRs

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Looks like the periodic jobs for kubevirt sig-network k8s-1.20 are fine
[1], let's promote the presubmit so it's always run but not voting and
not reporting to github.
[1] https://grafana-kubevirt-prow.apps.ovirt.org/d/Cz6zgEEGz/e2e-jobs-overview?orgId=1&refresh=2h&from=now-5d&to=now&var-job_name=periodic-kubevirt-e2e-k8s-1.20-sig-network
> Promote k6t 1.20 sig-net presubmit lane

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
Since some of the images are still on docker.io
publish may fail due to docker.io rate limit.
Add the docker proxy to the job.
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/publish-kubevirtci/1384131974548951040
```
v15: Pulling from ceph/ceph
toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```
> kubevirtci, postsubmit, Add docker proxy

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The job history speaks for itself: https://prow.apps.ovirt.org/job-history/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-build-arm64. Pretty much always green and failed lanes are not related to the cross-compilation.
> Make arm64 crosscompile presubmit required

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Once it is enabled we need to watch for 24h the number of pending jobs in https://grafana-kubevirt-prow.apps.ovirt.org/d/Cz6zgEEGz/e2e-jobs-overview?orgId=1&refresh=2h to check if they increase too much. 
/cc @brybacki 
/cc @dhiller 
> Enable 1.20-sig-sorage presubmit

- plugins/cmd/uploader/uploader.go
- plugins/mirror/bazel.go
- plugins/mirror/bazel_test.go
Basic problem was missing handling of elements who only have a `url` element, but where `urls` element is missing. In that case we replace the `url` element with a `urls` element.
Also we remove http client variable for mocking, instead introduce a function parameter.
Fixes https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-mirror-uploader/1384765400746561536
/cc @rmohr @fgimenez @awels
> Fix rule attr nil dereference

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Will prevent errors like https://testgrid.k8s.io/kubevirt-periodics#periodic-kubevirt-e2e-k8s-1.19-sig-compute&width=20&show-stale-tests= when declaring `cluster` for all the jobs I took the opportunity to start migrating some of them to prow-workloads, but I didn't realize that we still don't have docker proxy there.
/cc @brybacki @dhiller 
> Temporarily disable docker proxy for prow-workloads lanes

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
kubevirt/kubevirt's 1.19-sig-compute presubmit was missing, this PR adds it as required.
/cc @vatsalparekh 
/cc @dhiller
> Add 1.19-sig-compute presubmit

- github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-periodics.yaml
- robots/cmd/flakefinder/main.go
- robots/cmd/flakefinder/report.go
- robots/pkg/flakefinder/downloader.go
- robots/pkg/flakefinder/flakefinder.go
Adds periodic job data to flakefinder report. Is controlled by setting the option `periodic_job_dir_regex`. Example:
`--periodic_job_dir_regex=periodic-kubevirt-e2e-.*`
Result: 
/cc @rmohr @fgimenez 
Fixes #1076
> Add periodics to report

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
This happens due to tide leaving this in pending for
overall status, which prohibits the search to find it.
> Remove status filter as PR never reaches success

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
No improvements were seen in the test suite stability, reverting the memory request to its previous value.
/cc @rmohr @dhiller
> Revert memory increase for e2e periodic

- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
- github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/deck_deployment.yaml
* Deck: actually removes deprecated `--redirect-http-to=` instead of `--oauth-url`
* Plank: defines `pod_unscheduled_timeout`, after the change introduced here https://github.com/kubernetes/test-infra/pull/20582/files#diff-88e6b42a331a7aa9260f9a830961e3ba3c77e0e6d781465378b510d7abc1517cR1633 job pods were killed after 5min if they were not already scheduled, like here https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5428/pull-kubevirt-e2e-k8s-1.20-sig-network/1386672796477689856
> Several Prow deployment fixes

- github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-periodics.yaml
- robots/pkg/flakefinder/downloader.go
- robots/pkg/flakefinder/flakefinder.go
We never want to include job data that is outside the time window of
the report.
This differs from the PR based data retrieval where we
want to include all job data from a PR, even if it is before the time
window, to have the complete picture of all failures.
> Flakefinder periodics:  Skip job data outside report window for periodics

- github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
- github/ci/prow-deploy/kustom/base/manifests/local/prow-rehearse-deployment.yaml
- github/ci/prow-deploy/kustom/base/manifests/local/prow-rehearse-rbac.yaml
- github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/prow-rehearse-deployment.yaml
Required by rehearse plugin, without it the rehearse replicaset complains with:
```
Error creating: pods "rehearse-5cc657d6f6-" is forbidden: error looking up service account kubevirt-prow/prow-rehearse: serviceaccount "prow-rehearse" not found
```
> Fix rehearse deployment

- github/ci/prow-deploy/kustom/base/manifests/local/docker-mirror-proxy_deployment.yaml
- github/ci/prow/templates/mirror-proxy.yaml
With the previous timeout values we were getting errors on layer push.
> Increase docker proxy timeouts

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
The ceph lane seems like it uses an old version of kubernetes, let's add an optional lane to check if it's stable, and later switch.
> Add optional k8s-1.20 ceph lane

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
We need to run the quarantined tests in the SIG e2e periodics to know when they are stable enough to go back to the SIG e2e presubmit lanes. We were doing it for the main e2e periodic lanes (1.19 and 1.18) but not for the SIG e2e periodics.
I've also taken the opportunity to remove the 1.17 e2e periodic.
/cc @EdDev @brybacki @enp0s3 @tiraboschi @dhiller 
> Run quarantined tests in SIG e2e periodic lanes

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
This is a part of an effort to put 1.20 lane as mandatory.
we would like to observe the stability of the lane
and as part of it we will enable the reporting and make
it always run.
> Set K8s 1.20 sig-compute lane to run always

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
- robots/cmd/kubevirtci-bumper/main.go
- robots/pkg/kubevirtci/kubevirtci.go
- robots/pkg/kubevirtci/kubevirtci_test.go
The current bump will never succeed on `check-cluster-up.sh` as that tries running `make cluster-up` without the cluster-up folder for the new provider being present. This PR adds the copying of that folder and also adds the new parameter to the job definition.
/cc @rmohr
> Also copy cluster-up directory when adding new provider in kubevirtci bump

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.40.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Instead of filtering based on the `Operator` string now we can use `[sig-operator]` instead.
> Manage operator tests using its dedicated SIG label

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Job periodic-kubevirtci-cluster-minorversion-updater has a superfluous
double quote that makes the job fail. Removed.
/cc @fgimenez
> Fix superfluous double quote

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Job failed here: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-update-flakefinder-indexpage/1389963950665240576
This PR updates the job to use the correct binary.
> Fix binary name

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Presubmits are reporting to GitHub but need to get triggered manually.
FYI @EdDev
/cc @rmohr @fgimenez @qinqon
> Add periodics and presubmits for k8s-1.21

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Given that the migration of bare metals from `phx-prow` cluster to `prow-workloads` hasn't started yet I've taken the opportunity to configure the job to run on `phx-prow` to prevent increasing the pressure on `prow-workloads`.
We don't have manual executions of the presubmit but do have the periodic results that execute the same set of tests plus the quarantined ones, these are the latest runs:
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.20-operator/1389606132045058048
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.20-operator/1389726759133384704
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.20-operator/1389847562520891392 …
> Enable 1.20-operator presubmit to run on PRs

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
1.19-sig-compute is being executed https://prow.ci.kubevirt.io/?job=periodic-kubevirt-e2e-k8s-1.19-sig-compute but the results are not being reported.
/cc @vatsalparekh @enp0s3 @dhiller 
> Include 1.19-sig-compute in reports

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
- hack/bump-prow.sh
Sets a periodic to bump Prow every Friday. Loosely based on https://github.com/kubernetes/test-infra/blob/master/prow/bump.sh, no queries to GCloud for the tags (obtained from the manifests), no manual selection of tag to apply. 
Copies fresh manifests from test-infra, extracts the image tag from them, and updates the utility images with it. Then it creates a PR like this one https://github.com/kubevirt/project-infra/pull/1204 (without the changes that add the job and the bump script) to trigger the deployment tests on it and review. 
This is how the execution of the periodic job looks like https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-project-infra-prow-bump/1390729643409018880 
> Automated prow bump

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
We are still executing sig-compute tests on 1.19 lane, IIRC they were already removed but somehow they are back.
/cc @vatsalparekh @enp0s3 @dhiller 
> Filter sig-compute on 1.19 lane

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
586 tests passing, the remaining 156 skipped. Some important
networking and some important disk hotplug tests are part
of the skipped ones, so no 100% guarentee that we have
full cgroupsv2 support now.
This PR:
- Stops current cgroupsv2 lane from skipping sig-operate tests
- Adds another cgroupsv2-rook-ceph lane
> Run all remaining storage and networking tests with cgroupv2

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
With the recent changes in `hack/git-pr.sh` we require to use the latest builder version that ships pr-creator with labels support, if not we get errors like in this build https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-project-infra-prow-bump/1393086418238050304
```
Creating PR to merge kubevirt-bot:prow-autobump into master...
+ pr-creator --github-token-path=/etc/github/oauth --org=kubevirt --repo=project-infra --branch=master '--title=Run hack/bump-prow.sh' '--match-title=Run hack/bump-prow.sh' '--body=Automatic run of "hack/bump-prow.sh". Please review' --source=kubevirt-bot:prow-autobump --labels= --confirm
flag provided but not defined: -labels
```
/cc @dhiller 
> Bump builder tag to prevent pr-creator errors

- github/ci/prow-deploy/files/jobs/kubevirt/libguestfs-appliance/libguestfs-appliance-periodics.yaml
Add extra_refs to fetch the libguestfs-appliance repository.
> fix libguestfs appliance periodic job

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
- github/ci/testgrid/hack/check.sh
- github/ci/testgrid/hack/common.sh
- github/ci/testgrid/hack/update.sh
- github/ci/testgrid/hack/upload.sh
Updates to use Config Merger instead of transfigure for TestGrid config management. 
Until now with transfigure every time we merged changes in our jobs config, the new testgrid config was generated and PR was issued in k8s/test-infra with the relevant changes. With Config Merger, we first instruct TestGrid to read our config from a GCS bucket and then we can manage that config without requiring merging changes in k8s/test-infra. Config Merger configuration on test-infra side is described here https://github.com/GoogleCloudPlatform/testgrid/tree/master/cmd/config_merger and this is an example of the steps required to migrate to use Config Merger https://github.com/GoogleCloudPlatform/oss-test-infra/issues/832
These changes remove the old transfigure jobs and add 3 new jobs:
* testgrid …
> Adapt TestGrid config managment to Config Merger

- github/ci/testgrid/hack/common.sh
This will prevent errors like https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/1224/pull-project-infra-check-testgrid-config/1394252628979879936
/cc @dhiller
> Fix test-infra repo path.

- github/ci/testgrid/hack/common.sh
Fixes project-infra paths in the script used by `pull-project-infra-check-testgrid-config` to prevent errors like https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/1224/pull-project-infra-check-testgrid-config/1394261998304235520 
> Fix project-infra paths in pull-project-infra-check-testgrid-config

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
`podinfo.json` is written as part of the job report here https://github.com/kubernetes/test-infra/blob/f7e21a3c18f4f4bbc7ee170675ed53e4544a0632/prow/crier/reporters/gcs/kubernetes/reporter.go#L208 when report is disabled (`skip_report: true`) `podinfo.json` is not written and we see errors in testgrid like https://testgrid.k8s.io/kubevirt-presubmits#pull-kubevirt-e2e-k8s-1.20-sig-storage&width=90. For instance, in https://testgrid.k8s.io/kubevirt-presubmits#pull-kubevirt-e2e-k8s-1.19-sig-compute&width=5 it is clear in the `pod` row how 1.19-sig-compute was reporting a podinfo.json missing error until it `skip_report` was set to false.
These changes enable reporting of 1.20-sig-storage. I've also taken the opportunity to move environment variable definition of 1.19-sig-storage to the `env` …
> Enable report of 1.20-sig-storage

- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Since OVS CNI was moved under NPWG GitHub organization, its branch
protection configuration must be adjusted.
Fixes: https://github.com/kubevirt/project-infra/issues/1234
> Fix OVS CNI branch protection configuration

- github/ci/prow-deploy/files/jobs/kubevirt/macvtap-cni/macvtap-cni-postsubmits.yaml
- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
The `macvtap-cni` repo has been renamed from `master` to `main`.
> macvtap-cni: rename the main branch

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
* Adding the unnested label will run bazel directly, resulting in not
downloading the builder image.
* /etc/bazelrc files will now be automatically be picked up, since in
the unnested build they are now at a well known place for bazel to
look at.
* Stop request docker-in-docker to be started
> Run unit tests for kubevirt unnested

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
- github/ci/testgrid/hack/check.sh
- github/ci/testgrid/hack/common.sh
- github/ci/testgrid/hack/update.sh
- github/ci/testgrid/hack/upload.sh
- hack/create_bazel_cache_rcs.sh
Changes in this PR:
* Use bazel cache, reduces execution time from 33m here https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/post-project-infra-update-testgrid-config/1395311825699999744 to 3m here https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/post-project-infra-update-testgrid-config/1395331223252897792
* Include missing kubernetes/test-infra extra_ref
* Use `GIT_ASKPASS` instead of plain token
* Reduce verbosity of scripts
* A couple of fixes related to the GitHub username
Successful execution here https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/post-project-infra-update-testgrid-config/1395331223252897792 
/cc @dhiller @rmohr
> Fix testgrid update job

- github/ci/prow-deploy/files/orgs.yaml
Add Victor as he's an active member of the community and he's willing to help me maintaining the [libguestfs-appliance repo](https://github.com/kubevirt/libguestfs-appliance)
> Add victortoso to kubevirt members

- github/ci/prow-deploy/kustom/overlays/ibmcloud-production/kustomization.yaml
- github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/ghproxy_deployment.yaml
- github/ci/prow-deploy/kustom/overlays/kubevirtci-testing/resources/bootstrap.yaml
These changes remove the restriction to run ghproxy on a specific node that comes from upstream prow manifests here https://github.com/kubernetes/test-infra/blob/master/config/prow/cluster/ghproxy.yaml#L71-L78 (note the `run on our dedicated node` comment).
According to the doc https://github.com/kubernetes/test-infra/tree/master/ghproxy there's no specific requirement to run ghproxy in isolation and we now run prow control plane on a cluster with proper dynamic PV provisioning.
> Allow ghproxy to run on any node

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.41.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Now that greenhouse and docker-mirror-proxy are running on `prow-workloads` we can enable both on all the jobs running on that cluster.
> Enable docker proxy and bazel cache on prow-workloads cluster

- github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml
After massive changing knmstate jobs to use main branch one of the
options got renamed incorrectly. This changes address that pointing
project-infra to master.
Closes https://github.com/nmstate/kubernetes-nmstate/issues/758
> knmstate: Use correct project-infra branch

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
Adding 1.21 version to be synced with GCP.
> Sync cri-o version 1.21

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
New CI cluster is now ready for k8s-1.19 sig-network.
The missing ipv6 docker gateway was added.
> sig-network, k8s-1.19, Move presubmit job to new CI cluster

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
- github/ci/testgrid/hack/common.sh
- github/ci/testgrid/hack/update.sh
* Refactor to use `hack/git-pr.sh` for creating the PRs with modified testgrid configs.
* Fix in the config creation, do not overwrite the base config at `github/ci/testgrid/gen-config.yaml`
PR successfully created here https://github.com/kubevirt/project-infra/pull/1260 the diff includes the changes in this PR too besides the new testgrid config, will be fixed once this PR is merged. 
/cc @dhiller  
> Use git-pr script in TestGrid update job

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
The minor version bump should always execute this now that this lane is part of kubevirt.
/cc @fgimenez
> Always run 1.21 provision check

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
- github/ci/testgrid/hack/common.sh
Includes a couple of fixes too:
* Run testgrid config checks when `github/ci/testgrid/gen-config.yaml` (the root config) is changed.
* Do not initialize `TEST_INFRA_ROOT` env var when test-infra repo is present.
Successful execution of `post-project-infra-upload-testgrid-config` with these changes here https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/post-project-infra-upload-testgrid-config/1399387941830135808
/cc @dhiller 
> Authenticate to gcloud to perform testgrid config upload

- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits-1.28.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
- Make 1.19 / 1.20 lanes required.
- Remove 1.17 / 1.18 lanes.
- Make ceph lane actually test k8s 1.20, not 1.17.
- Keep the lanes for release-v1.28, which isn't expected to support k8s-1.19 / 1.20 lanes
> Switch CDI to k8s 1.19/1.20

- github/ci/prow-deploy/files/jobs/kubevirt/libguestfs-appliance/libguestfs-appliance-periodics.yaml
- github/ci/testgrid/gen-config.yaml
It'll send an email if the job fails or it stales for an hour.
Note that the last successful job took less than 10 minutes.
Signed-off-by: Victor Toso <victortoso@redhat.com>
> libguestfs-appliance: periodic: notify by email on failure

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
This PR is to test https://github.com/kubevirt/project-infra/pull/1244 before merging it.
After it is merged, we can revert this PR.
> Add a temporary lane to test regex for ignoring documentation changes

- github/ci/prow-deploy/vars/workloads-production/main.yml
Probably a leftover of local testing, it will prevent errors like https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/post-project-infra-prow-workloads-cluster-deployment/1400104330970796032
/cc @dhiller 
> Fix project_infra_root for workloads-production overlay

- github/ci/prow-deploy/files/jobs/kubevirt/libguestfs-appliance/libguestfs-appliance-periodics.yaml
The new appliance is built weekly. However, if the kernel, os and appliance are the same as the previous build, we overwrite the old appliance with a new sha. The builds that refer the old sha start failing.
Fixes: https://github.com/kubevirt/libguestfs-appliance/issues/10
> publish libguestfs appliance only on new versions

- github/ci/prow-deploy/kustom/overlays/workloads-production/kustomization.yaml
- github/ci/prow-deploy/kustom/overlays/workloads-production/resources/ingress-controller.yaml
Required for accessing services in the prow-workloads cluster. 
The manifests come from upstream verbatim except for a change in the service type, from `LoadBalancer` to `NodePort` (with 30080 and 30443 as the `nodePorts` for HTTP and HTTPS respectively). This is needed for being able to receive incoming requests in the self-managed cluster.
/cc @rmohr 
> Add ingress controller to prow-workloads

- github/ci/prow-deploy/kustom/overlays/ibmcloud-production/kustomization.yaml
- github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/pushgateway_deployment.yaml
We were losing some prow-related metrics during periods of high load, pushwateway was requesting more CPU than available and was evicted in some cases.
These changes set resources for pushgateway above the highest usage it had during the last 2 days https://grafana.ci.kubevirt.io/d/GlXkUBGiz/kubernetes-pod-overview?orgId=1&refresh=10s&var-namespace=kubevirt-prow&var-pod=pushgateway-64f6547bb7-gx9tv&var-container=All&from=now-2d&to=now It also fixes the QoS to Guaranteed (same memory and CPU requests and limits) to mitigate further issues.
/cc @dhiller 
> Set pushgateway resources

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Now that all the tests are assigned to a SIG after https://github.com/kubevirt/kubevirt/pull/5741 has been merged we can remove the now empty 1.19 lane. Recent execution (all tests skipped) here https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4922/pull-kubevirt-e2e-k8s-1.19/1400808312303259648
/cc @dhiller 
> Remove pull-kubevirt-e2e-k8s-1.19 lane

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
Fix an issue in the kubevirtci bump periodic: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirtci-bump-kubevirt/1402902817156370432.
It needs a newer build image to have a `pr-creator` available with the new `-label` flag.
> Bump builder image in kubevirtci bump job for new pr-creator

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
- hack/git-pr.sh
- robots/cmd/kubevirt-presubmit-requirer/BUILD.bazel
- robots/cmd/kubevirt-presubmit-requirer/main.go
- robots/cmd/kubevirt-presubmit-requirer/main_test.go
Adds a job that converges the kubevirt e2e lanes for latest
provider into being required for merge.
Phase 1: make the lane run always (fix skip_report: false to make it
report)
Phase 2: make the lane required (by setting optional to false)
The job runs at the 1st of every month. This should have the
effect of making the new lanes run always after around three weeks
and be required after two months (in case the PRs get merged in
time).
Example of the file changes here (**Note: you need to load the diff manually, as the serialization has reordered the fields**): https://github.com/kubevirt/project-infra/pull/1297/files#diff-26f7cd0389085c1da47f919a02c4dbeca5ddd96ca00d8e49c0862f698475aaf9R3
> Add kubevirt e2e presubmit requirer

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
- images/autoowners/Dockerfile
In order for autoowners to support the [`--pr-base-branch argument`](https://github.com/openshift/ci-tools/pull/2056) we
update the image to the latest version. This is a change required ahead
of renaming the default branch for project-infra.
Also we create jobs to automate autoowners image build and push.
> Update autoowners to latest version

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
The test started failing after set to execute on `prow-workloads`, moving it back to `phx-prow` to unblock PRs while investigating the root cause. Also reduced the requested memory, leftover from when the test used kubevirtci. 
/cc @dhiller 
> Execute prow-deploy-test in phx-prow

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Following kubevirt/kubevirtci#621, we need to test it on CI environment 
as kind-1.19-sriov going to be new provider for SRIOV lanes.
This PR adds new kubvirtci-check-up and kubvirt-pull-e2e jobs for it.
> Create new jobs for kind-1.19-sriov provider

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
- github/ci/prow-deploy/files/orgs.yaml
see also https://github.com/kubevirt/kubevirt/pull/5823
Can only go in after the default branch in `kubevirt/kubevirt` has been renamed.
/hold
> Set default branch for kubevirt/kubevirt to main

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
This PR chance 1.19 sriov jobs to **not** always run in order to prevent extra pressure on CI.
We will change it back once we set 1.19 sriov jobs as voting lanes.
> kind-1.19-sriov jobs: Cancel always_run

- cni-plugins/sriov-passthrough-cni/README.md
- github/ci/prow-deploy/files/jobs/kubevirt/community/community-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubectl-virt-plugin/kubectl-virt-plugin-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/user-guide/user-guide-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml
- github/ci/prow-deploy/files/orgs.yaml
- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
- github/ci/prow-deploy/molecule/default/vars/kubevirtci-testing.yml
- github/ci/testgrid/README.md
/hold
Can go in after:
- https://github.com/kubevirt/project-infra/pull/1330 has been merged (for support `--pr-base-branch` of `autoowners`)
- after the default branch of project-infra has been renamed
Eventually we need to run the config updater manually after the merge: https://github.com/kubevirt/project-infra/blob/97713878997f9f31ff029dbfb08ae11a540f1c73/github/ci/README.md#updating-prow-configuration-manually
> Set default branch for project-infra to main

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
- github/ci/prow-deploy/molecule/default/cleanup.yml
- github/ci/prow-deploy/molecule/default/collect.yml
- github/ci/prow-deploy/molecule/default/molecule.yml
- github/ci/prow-deploy/molecule/default/prepare.yml
- github/ci/prow-deploy/molecule/default/vars/kubevirtci-testing.yml
Changes to prevent errors when running in `prow-workloads` cluster include:
* Use a more recent kubevirtci/prow-deploy image with kind v0.11.1 as suggested here https://github.com/kubernetes-sigs/kind/issues/2316#issuecomment-864182778, built with the changes in #1350 
* Bump kindest/node image used by kind (pointing to our quay mirror).
* Collect kind logs in case of cluster creation failure.
Additionally, all the executions with the new kind have taken less than 7min, previously it was taking ~10min.
Successful execution here https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/1341/rehearsal-pull-project-infra-prow-deploy-test/1405963755489071104 
/cc @dhiller 
> Fix prow-deploy test

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
We want to deprecate the 1.17 lane from kubevirtci, so let's make sure there are no remaining uses.
> kubevirt: Avoid using k8s-1.17 lanes for ceph, make 1.20 ceph lane mandatory

- github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/ovs-cni/ovs-cni-postsubmits.yaml
This commit adds 2 jobs:
- release-ovs-cni: image-push of tags to qauy
- main-ovs-cni: image-push of main branch to quay, using virtual-
tags as the image tag.
> ovs-cni, Add postsubmits

- github/ci/prow-workloads/roles/bootstrap/tasks/additional_kernel_modules.yml
- github/ci/prow-workloads/roles/bootstrap/tasks/main.yml
After moving jobs to prow-workloads OVS CNI test fail due to a missing openvswitch kernel module.
/cc @phoracek @dhiller 
> Include openvswitch kernel module in prow-workloads node bootstrap

- images/prow-deploy/Dockerfile
Suggested in https://github.com/kubernetes-sigs/kind/issues/2316#issuecomment-864182778 to prevent errors like https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/1341/rehearsal-pull-project-infra-prow-deploy-test/1405885064394313728
/cc @dhiller 
> Bump kind in prow-deploy file

- github/ci/prow-deploy/files/jobs/kubevirt/community/community-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
In order to align the builder version for all jobs that occasionally
fail due to "flag provided but not defined: -labels" when using
`git-pr.sh` we align those images to use one tagged version.
See i.e.: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirtci-bump-kubevirt/1407252471889268736
/cc @fgimenez
> Set kubevirt builder image to tagged version

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
The jobs skipped reporting to the configured channels, so we missed notifications about their failures.
/cc @davidvossel @rmohr @fgimenez
> Enable reporting for kubevirt release jobs

- github/ci/prow-deploy/kustom/components/docker-mirror-proxy/base/resources/deployment.yaml
- github/ci/prow-deploy/kustom/components/docker-mirror-proxy/hostpath/patches/JsonRFC6902/deployment.yaml
We are getting connectivity errors in ibm-prow-workloads cluster to quay: `Get https://quay.io/v2/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)`. Quay status page looks fine and we are able to connect to it without problems from other clusters. The issue seems related to docker-mirror-proxy in ibm-prow-jobs, looking at the resource usage seems like it hasn't been able to report the `up` metric around times when there was a spike in cpu usage. These changes set the cpu requests and limits a bit above the highest usage value we have recorded in the last 7 days:
/hold
Changes are already deployed, will check for a while if the errors are gone before proposing this PR for review.
> Set cpu requests for docker-mirror-proxy

- releng/release-tool/Dockerfile.release-tool-base
- releng/release-tool/release-tool.go
Automatically approve forked ci configs when doing a kubevirt release.
> Add lgtm,approved labels on release tool config forks

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
As we are now testing rook-ceph in the sig-storage lanes we do not need
those separate jobs any more.
Examples:
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5914/pull-kubevirt-e2e-k8s-1.20-sig-storage/1407998908197507072
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.21-sig-storage/1407939144176373760
> Drop separate rook-ceph lanes

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Remove lanes, see https://github.com/kubevirt/kubevirtci/pull/627
> Drop check-provision lanes for k8s 1.18 and lower

- github/ci/prow-deploy/molecule/default/vars/kubevirtci-testing.yml
- github/ci/prow-deploy/tasks/deploy.yml
- github/ci/prow-deploy/vars/ibmcloud-production/main.yml
- github/ci/prow-deploy/vars/workloads-production/main.yml
prow-deploy image already ships kubernetes and openshift modules, but installed with the python3 interpreter. We needed to install them again in the test execution because the interpreter used was python2.7. Now this python version is deprecated and the pip installation during the test started failing like here https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/1380/pull-project-infra-prow-deploy-test/1408335642642878464
With these changes we make sure that python3 is used both for testing and deployment. The pip installation during testing is no longer needed, we use the modules installed in the image.
/cc @dhiller 
> Make sure to use Python3 in prow-deploy

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Will prevent errors bc of missing cluster provider, like here https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-prev-prev-sriov/1408069905177120768#1:build-log.txt%3A30
/cc @dhiller 
> Update SR-IOV periodic

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Change required after the change of the default project-infra branch to main, will prevent errors like https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-project-infra-prow-bump/1408306601693024256#1:build-log.txt%3A333 Successful execution with the change in this PR here https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-project-infra-prow-bump/1408325247156883456
/cc @dhiller 
> Target prow-autobump PR to main branch

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt.github.io/kubevirt-github-io-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt.github.io/kubevirt-github-io-presubmits.yaml
- github/ci/prow-deploy/files/orgs.yaml
Due to the default branch change the repo config needs to get adjusted, otherwise the peribolos job fails. See: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-org-github-config-updater/1409764248128589824#1:build-log.txt%3A150
Also we move the existing jobs away from phx-prow.
/cc @fgimenez 
FYI @mazzystr
> Update branch for repo config, move jobs to ibm cluster

- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Fixes #1383
Now that the default branch has changed in these repos we need to update branch-protector config.
/cc @dhiller @awels 
> Fix branch-protector for CDI and CNAO

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
This lane was part of the efforts to not trigger jobs when only docs change. The verified that the approach we were taking won't work without changes in Prow, this lane is no longer required.
/cc @dhiller 
> Remove experimental lane

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
In order to allow more than one PR test the mandatory lanes,
increase max_concurrency to 2.
> kubevirtci k8s-x.yy presubmits, Increase max_concurrency to 2

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Currently the image specified for cgroup v2 lanes is incorrect. Update to the proper one. Needed for https://github.com/kubevirt/kubevirtci/pull/638
> Update the image for cgroupsv2 jobs

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Hi @fgimenez @rmohr 
I add a periodic task for ARM, please take a look when you have time.
There are two additional requests to make this job work.
1. The kubeconfig of ARM server needs to be upload and sorted.
2. I am not sure if it is appropriate to use quay.io/kubevirt to store test images. If not which repository we can use to store test images.
> [DRAFT] add periodics cluster sync test for ARM

- github/ci/prow-deploy/kustom/overlays/ibmcloud-production/kustomization.yaml
- github/ci/prow-deploy/kustom/overlays/workloads-production/kustomization.yaml
FOSSA token was created in kubevirt-prow namespace, jobs run in kubevirt-prow-jobs ns.
/cc @fgimenez
> Add namespace for fossa token

- github/ci/prow-deploy/kustom/overlays/ibmcloud-production/kustomization.yaml
As the secrets for jobs in ibm-prow-jobs context need to get created
in kubevirt-prow-jobs ns we add the namespace explicitly to those.
We set the default for secrets without namespace declaration to go to
kubevirt-prow now.
Related to #1404 whose fix only works for context prow-workloads
Tested locally with kustomize, partial result:
```
....
---
apiVersion: v1
data:
token: ""
kind: Secret
metadata:
name: slack-token
namespace: kubevirt-prow
type: Opaque
...
---
apiVersion: v1
data:
honk.txt: ""
kind: Secret
metadata:
name: unsplash-api-key
namespace: kubevirt-prow
type: Opaque
---
...
---
apiVersion: v1
data:
token: ""
kind: Secret
metadata:
name: kubevirtci-fossa-token
namespace: kubevirt-prow-jobs
type: Opaque
(END)
```
> Fix namespaces for secrets in kustomize

- github/ci/prow-deploy/vars/workloads-production/main.yml
The nodes have 4 PFs instead of 2.
> Bump PFs of SR-IOV nodes to 4

- github/ci/services/prometheus-stack/manifests/stack/common/kube-prometheus-stack.yaml
- github/ci/services/prometheus-stack/patches/production-control-plane/prometheus.yaml
We are ingesting more metrics now, Prometheus pod was being OOMKilled with the old settings. Also, now that Thanos is in place we don't need that much local retention (we also had issues with the PV being filled).
/cc @dhiller 
> Update Prometheus settings

- github/ci/prow-deploy/files/orgs.yaml
[x] I have reviewed the community code of conduct (https://github.com/kubevirt/kubevirt/blob/master/CODE_OF_CONDUCT.md)
[x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
[x] I have subscribed to the kubevirt-dev e-mail list (https://groups.google.com/forum/#!forum/kubevirt-dev)
[x] I am actively contributing to KubeVirt
[x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
[x] I have spoken to my sponsors ahead of this application and they have agreed to sponsor my application
[x] I have publicly introduced myself to the community through one of the community communication channels
- @mazzystr
- @dhiller
- [List of kubevirt PRs by @cwilkers](https://github.com/pulls?q=is%3Apr+author%3Acwilkers+kubevirt)
- …
> Add cwilkers to members of KubeVirt org

- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Change the `merge_method` of the SSP operator project to `merge`.
> ssp-operator: change merge_method to 'merge'

- github/ci/services/prometheus-stack/manifests/stack/production-control-plane/grafana.yaml
Adds the JSON code for the CI utilization dashboard available here https://grafana.ci.kubevirt.io/d/qFDyvVinx/ci-infrastructure-utilization?orgId=1
/cc @dhiller 
> Added CI utilization dashboard

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
The PR fixes the periodic and presubmit cgroupsv2 jobs considering the approach from https://github.com/kubevirt/kubevirtci/pull/638
**NOTE**: Also (if no objections) it will mark the presubmit jobs in kubevirtci as mandatory.
> Fix cgroupv2 jobs

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
This job will trigger on vendor folder changes or if any `go.sum` or `go.mod` file was changed in a PR in kubevirt.
Requires https://github.com/kubevirt/kubevirt/pull/5808 to be merged first.
> Job to verify that go.mod, go.sum and vendor folders are in sync

- github/ci/prow-deploy/kustom/components/greenhouse/hostpath/kustomization.yaml
- github/ci/prow-deploy/kustom/components/greenhouse/hostpath/patches/JsonRFC6902/deployment.yaml
After setting a hostPath PV I've verified the available space in greenhouse container `/data` mount point and it didn't actually change:
```
$ kubectl exec -ti -n kubevirt-prow greenhouse-657d5bbc47-tgmfl -- /bin/sh
/app # df
Filesystem           1K-blocks      Used Available Use% Mounted on
[...............]
/dev/sda4            1872337680 208913800 1663423880  11% /data
[...............]
```
Still the whole 1.8Tb available to be filled. According to https://kubernetes.io/docs/concepts/storage/volumes/#resources `There is no limit on how much space an emptyDir or hostPath volume can consume, and no isolation between containers or between pods.` This is expected to work at some point by requesting a certain amount of space using a resource specification, but not yet in place.
For the time …
> Tune greenhouse to not occupy the whole disk

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
According to https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md#protecting-status-contexts conditionally-run jobs may or may not post a status context to GitHub, and as such, they cannot be required through the branch protection mechanism. This prevents us from not executing required jobs depending on some condition, but we can still stop running the non-required ones. This PR changes the job definition of kubevirt/kubevirt presubmits to not trigger them on docs changes.
/cc @dhiller 
> Do not run optional lanes on doc changes

- github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/ci-usage-exporter-deployment.yaml
- robots/pkg/ci-usage-exporter/metrics/metrics_test.go
- robots/pkg/ci-usage-exporter/metrics/resources.go
This will allow us to estimate the resource utilization per full execution on each PR (taking into account only presubmit jobs that have `always_run: true` and discarding release presubmits through the brancher.branches and brancher.skip_branches settings).
/cc @dhiller 
> Expose job's always_run and brancher settings

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Adding a lane to run periodic nightly windows-sysprep test.
The test is added in: https://github.com/kubevirt/kubevirt/pull/5757
Signed-off-by: borod108 <boris.od@gmail.com>
> Add windows-sysprep lane

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Reverts kubevirt/project-infra#1433
Sinker and other pods are crashlooping with errors like `job pull-kubevirt-e2e-k8s-1.21-sig-network is set to always run but also declares skip_if_only_changed targets, which are mutually exclusive`
/cc @dhiller
> Revert "Do not run optional lanes on doc changes"

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Some of our commenter jobs have started to fail with an error from
GitHub API where it complains like this:
```
... "resource":"Search","field":"q","code":"invalid"}
```
This seems to be caused by the newlines in the query field. Removing
those has fixed the problem.
Example: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-test-infra-close-build-watcher-triage/1415482583101214720
> Fix commenter jobs suddenly failing with q invalid

- github/ci/prow-deploy/files/jobs/RHsyseng/rhcos-slb/rhcos-slb-presubmits.yaml
- github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Following the [added](https://github.com/RHsyseng/rhcos-slb/pull/24) ci test script on [rhcos-slb repo](https://github.com/RHsyseng/rhcos-slb), we would like to add am optional prow lane for it
> rhcos-slb, Adding presubmits lane for main branch

- images/prow-deploy/Dockerfile
Required for reconciliation of the GitHub webhooks, see here: https://github.com/kubernetes/test-infra/blob/master/prow/cmd/hmac/README.md
/cc @fgimenez
> Add hmac tool to prow deploy image

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
We are currently redeploying prow on each merge to main, these changes restrict deployment to changes on `github/ci/prow/deploy/.*`. Also fix a redundant regexp for triggering prow-deploy tests.
/cc @dhiller 
> Only deploy Prow on relevant changes

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Corrects the setting for the base branch for repos where the default branch has been renamed.
Fixes kubevirt/kubevirt#6043
> Set base branch to main for flakefinder jobs

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
- github/ci/prow-deploy/molecule/default/molecule.yml
- github/ci/prow-deploy/tasks/deploy.yml
- github/ci/prow-deploy/vars/ibmcloud-production/main.yml
- github/ci/prow-deploy/vars/kubevirtci-testing/secrets.yml
- github/ci/prow-deploy/vars/workloads-production/main.yml
Add configuration in configs.yaml to onboard the existing orgs. Add hmac
tool execution to deploy.yaml, only being executed on the real
deployment.
> Add configuration for GitHub webhooks reconciliation

- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
`pull-cdi-unit-test` has started failing recently, like here https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1863/pull-cdi-unit-test/1415713420736466944 These changes aim to stabilize the execution by giving the job more memory and moving it to the workloads cluster. Given that the tests are executed with `go test` the bazel cache preset is also removed.
Successful execution here https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1863/pull-cdi-unit-test/1416013362738761728, execution time goes down from ~7m to 1m25s.
/cc @awels @dhiller 
> Update pull-cdi-unit-test job

- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
This is the configuration to add the remaining repositories that are onboarded to KubeVirt CI to also have managed their GitHub webhook by KubeVirt Prow instance. 
/cc @phoracek @stu-gott @fgimenez
> Add remaining repos to managed webhooks configuration

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Retester haven't been creating comments for a while, removing the new lines in the query fixes the issue. Job executed with the old query https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-project-infra-retester/1416057716270436352 and with the new one right after https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-project-infra-retester/1416064652709728256
/cc @dhiller 
> Remove new lines in retester query

- github/ci/services/prometheus-stack/patches/production-control-plane/prometheus.yaml
Prometheus pod is still being OOMKilled in ibm-prow-jobs cluster, this leads to these gaps in metrics:
These changes give it resources according to the recorded resource utilization:
/cc @dhiller 
> Increase Prometheus CPU resources in control plane

- robots/pkg/kubevirtci/kubevirtci.go
- robots/pkg/kubevirtci/kubevirtci_test.go
If a provider already exists for a kubernetes version, but it has a
different revision number, we don't want to update the revision as this
does the same what ensureLatestThreeMinor does.
See https://github.com/kubevirt/kubevirtci/pull/643 as an example.
> EnsureProviderExists should not touch existing

- github/ci/prow-deploy/kustom/components/greenhouse/base/resources/deployment.yaml
Sets the limits above the highest recent recorded utilization:
> Define greenhouse CPU resources

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
- hack/update-jobs-with-latest-image.sh
A recent release has introduced a fix for commenter newline issue with
GitHub
https://github.com/kubernetes/test-infra/blame/5548472063500a93b8a1e269abea4d5dc74fdfc5/robots/commenter/main.go#L119
We bump the commenter images to use that one and reinstate the old more
readable queries for the jobs.
Also added support for using labels on image bump script
hack/update-jobs-with-latest-image.sh
/cc @fgimenez
> Bump test-infra commenter image to restore queries

- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
This will configure gh webhook on RedHatQE/openshift-python-wrapper repo, kubevirt-bot is already admin there.
/cc @rmohr 
> Add RedHatQE/openshift-python-wrapper to managed webhooks

- github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
openshift-python-wrapper remove release-note plugin
> openshift-python-wrapper remove release-note plugin

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Add a Prow job that runs 3 times a day a density test creating 100 VMs.
This prow job results will be used as the baseline performance of KubeVirt to evaluate possible performance regression.
Additionally, this job runs in the `prow-workloads` but will be modified in the future to run a the `prow-performance` cluster.
This PR Depends on kubevirt/kubevirt/pull/6139
> Add daily job to run performance density test

- BUILD.bazel
- WORKSPACE
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
Properly defines the Python toolchain to be used by Bazel when there are two of them available as described here https://github.com/bazelbuild/rules_python/blob/main/docs/python.md#py_runtime_pair  
Fixes errors like https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/publish-release-blocker-image/1420410039285321728 and allows us to use recent fedora-based bootstrap images for jobs that require a python toolchain, like those using rules_docker. Example of successful execution with `quay.io/kubevirtci/bootstrap:v20210715-d0c2b78` https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/publish-release-blocker-image/1425368122788941824
> Fix python toolchain definition for Bazel.

- github/ci/prow-deploy/kustom/overlays/ibmcloud-production/kustomization.yaml
- github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/sinker_deployment.yaml
- github/ci/services/prometheus-stack/manifests/stack/production-control-plane/thanos.yaml
- github/ci/services/prometheus-stack/patches/production-control-plane/prometheus.yaml
Resources adjusted according to reported usage from https://grafana.ci.kubevirt.io/d/GlXkUBGiz/kubernetes-pod-overview?orgId=1&refresh=10s
The resources are defined with matching limits and requests to:
* Force Guaranteed QoS
* Have predictable resource utilization, we won't see utilization spikes on these pods.
* The pods with these limits have the resources available, the rest of pods will need to fight for the remaining resources with the risk of being throttled on CPU and even evicted first if they use too much memory. 
/cc @rmohr 
> Adjust resources for several components

- github/ci/prow-deploy/kustom/base/manifests/local/cherrypicker_deployment.yaml
- hack/bump-prow.sh
This will update images for branchprotector, label_sync, and cherrypicker. Also removed TODO comment about this issue already closed https://github.com/kubernetes/test-infra/pull/18077
/cc @rmohr 
> Include local manifests in bump-prow script

- github/ci/prow-workloads/roles/bootstrap/tasks/main.yml
We have had an issue in one of the nodes, the boot partition is only 256MB and yum was configured to keep files for 3 versions of the same package. This led to a situation in which a `dnf update` that introduced a new kernel was not able to put the new kernel files in place. The grub entry had been already updated and the node was not able to reboot.
These changes add tasks to set the number of packages kept by yum to 2 and also remove all the old packages leaving only the two most recent versions.
/cc @rmohr 
> Set the number of kept packages to 2 in workloads cluster nodes

- github/ci/prow-deploy/kustom/overlays/ibmcloud-production/kustomization.yaml
- github/ci/prow-deploy/kustom/overlays/kubevirtci-testing/resources/hmac.yaml
- github/ci/prow-deploy/molecule/default/prepare.yml
- github/ci/prow-deploy/tasks/secrets.yml
Now that we are using the [hmac tool](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/hmac/README.md) to handle the HMAC setup we no longer need to create the k8s secret ourselves with a plain random string, the secret is created by the tool and the contents are updated every time we reexecute it. 
The changes includes code to initialize the hmac secret on the integration testing env, where we don't call the hmac tool.
> Do not create HMAC secret

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
We are receiving eventually error messages from presubmit jobs as batch like this one https://coreos.slack.com/archives/CTFN306KC/p1627981181003300, I've also added changes to prevent slack notifications of batch jobs by default.
/cc @rmohr @dhiller
> Do not send slack notifications for batch jobs

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
- robots/cmd/kubevirtci-presubmit-creator/main.go
The phx-prow can not be used for the provision check any more. This changes the latest job to use prow-workloads, also it changes the automation code that creates new jobs to use prow-workloads.
/cc @enp0s3
> Change check-provision job and automation to use prow-workloads

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
That job is still reporting to #kubevirt-ci-monitoring slack channel, which it shouldn't any more IMHO.
/cc @enp0s3
> Remove slack reporting for kubevirt cgroupsv2 periodic

- github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
- github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-periodics.yaml
- hack/update-jobs-with-latest-image.sh
This updates the flakefinder jobs to use the latest version (which contains the fix to the new prow.ci.kubevirt.io). Also fixes the job directory path in the update image script.
Fixes #1516
/cc @jean-edouard
> Update flakefinder to latest version

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-velero-plugin/kubevirt-velero-plugin-presubmits.yaml
This PR fixes configuration of KubeVirt Velero Plugin's CI.
There are two fixes:
- pull-kvp-unit-test needs to be run in priviledged mode, because it
runs the tests inside Docker container
- pull-kvp-functional-test calls a script to setup a cluster and run
the tests rather than call Make target directly.
Signed-off-by: Tomasz Baranski tbaransk@redhat.com
> Configuration fixes of KubeVirt Velero Plugin's CI.

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
These have flakiness, and we have the more stable 1.21 lane
required already, which should avoid introducing flakes.
> Make the kubevirt sig-storage 1.19 and 1.20 lanes optional

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
We can re-add it after https://github.com/kubevirt/kubevirt/pull/6042 is merged and we properly support cgroupsv2.
/cc @iholder-redhat @EdDev  @dhiller 
> Remove cgroupsv2 periodic

- .gitignore
With these changes these files will be ignored by git:
* Any `group_vars/all/main.yml` file under  `github/ci` dir, no matter where.
* Specific secret files for the `ibmcloud-production` and `workloads-production` environments used by the prow deployment jobs.
> Update ignored files to make harder to leak secrets

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-velero-plugin/kubevirt-velero-plugin-presubmits.yaml
In order to use KVM virtualization, the tests need to be run on a bare metal node, which is not available in ibm-prow-jobs cluster. The PR adds the nodeSelector and changes cluster to prow-workloads.
> Fixing configuration of the functional tests cluster

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
- robots/cmd/kubevirt-job-copier/BUILD.bazel
- robots/cmd/kubevirt-job-copier/main.go
- robots/cmd/kubevirt-job-copier/main_test.go
kubevirt-job-copier creates new periodic and presubmit jobs in case a
new kubernetes provider gets released. It does that by copying the
existing jobs that use the currently latest kubevirt provider.
Periodics cron expressions are advanced to spread the load, presubmits
are created as optional and always_run: false. This way they are not
failing when the new provider has not landed in the kubevirt codebase
yet, but can be triggered manually when it has landed.
/cc @fgimenez
> Add periodic job, code and simple test for kubevirt-job-copier

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
- hack/git-pr.sh
We are getting errors in periodic-kubevirtci-cluster-minorversion-updater, for instance https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirtci-cluster-minorversion-updater/1432736830964371456. The job doesn't find an existing PR to update and later fails to create it bc it is already there.
Looks like GH query is failing with the truncated title here https://github.com/kubevirt/kubevirtci/pulls?q=is%3Aopen+is%3Apr+archived%3Afalse+repo%3Akubevirt%2Fkubevirtci+author%3Akubevirt-bot+in%3Atitle+Run+bazelisk+run+%2F%2Frobots%2Fcmd%2Fkubevirtci-bumper%3Akubevirtci-bumper+--+-ensure-latest+--k8s-provider-dir+%2Fhome%2Fprow%2Fgo%2Fsrc%2Fgithub.com%2Fkubevirt%2Fproject-i but not if we get a bit more of the title https://github.com/kubevirt/kubevirtci/pulls?q=is%3Aopen+is%3Apr+a …
> Add headBranch support to git-pr.sh

- README.md
- robots/cmd/kubevirt-job-copier/main.go
- robots/cmd/kubevirt-job-copier/main_test.go
Fixes the edge case where a cron expression has the value of
"0 7,15,23 ..." which needs to result in "... 0,8,16 ..."
Also adds entry to README.md for job-copier.
/cc @fgimenez @enp0s3
> Fixes cron expression advancement edge case

- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
Sets the job schedule with cron instead of interval, which depends on the time when the job was executed for the last time.
> Set periodic-kubevirtci-bump-kubevirt to run every 12h

- README.md
- github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
- robots/cmd/labels-checker/BUILD.bazel
- robots/cmd/labels-checker/main.go
- robots/cmd/labels-checker/main_test.go
Adds some code that checks whether certain labels are missing and fails
with non zero exit code if they are not.
Changes the bump-kubevirtci job to use that code to ensure lgtm
label is missing on PR.
Example why this is needed: See also kubevirt/kubevirt#6238
There we can see that the existing PR is force pushed again and again and therefore fails to get merged.
/cc @enp0s3 @fgimenez
> Add check that lgtm label is missing before bumping kubevirtci

- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
- github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
- images/pr-creator/Dockerfile
Adds an image as base for jobs using git-pr.sh. This is intended to
replace the kubevirt builder image where that image is not required to
be used.
This image is based on kubevirtci/bootstrap so it has bazel built in, which most of the jobs require.
It also has git-pr.sh and git-askpass.sh built in so we can remove the env var declaration and remove the path from the script call. 
/cc @fgimenez
> Create pr-creator image
